### ISSUE TITLE
FOP - Problem with uBo redirect option

### ISSUE THREAD

**Issue by realodix** [easylist/ruadlist#10]
FOP v3.918

**Step to reproduce**
1. Write ||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js^$script,redirect-rule=googlesyndication_adsbygoogle.js,domain=example.com
2. Run FOP v3.918

**Expected**
`/adsbygoogle.^$script,redirect-rule=googlesyndication_adsbygoogle.js,domain=example.com`

**Actual**
`/adsbygoogle.^$script,redirect-rule=googlesyndication-adsbygoogle.js,domain=example.com`

I suppose bugged here: 
https://github.com/easylist/ruadlist/blob/a5737b25c70edc3059f00aca10d4f5ee96f5e5de/fop.py#L297

**Comment by lainverse** [comment]
Should work now.
