### ISSUE TITLE
stopgame.ru

### ISSUE THREAD

**Issue by dotterian** [easylist/ruadlist#100]
Привет, это снова разработчик StopGame.ru и снова недоволен тем, как работает блокировщик:

Вот этот фильтр убирает в том числе и абсолютно корректные списки, не содержащие рекламных ссылок:
```
stopgame.ru#?#section > div[class^="_content-wrapper_"]:-abp-has(> div > a[href^="/watch"]) ~ div[class^="_content"] [class^="_list_"]
```

Убедиться можно на этих страницах:
https://stopgame.ru/show/131336/cistemki_the_callisto_protocol_paket_yarovoy_dlya_igr_uhod_ea_iz_rossii_kitaycy_perestali_igrat
https://stopgame.ru/show/131355/ischem_horoshie_igry

Я бы, как минимум, добавил к нему проверку на то, что `href` начинается с `/to?` (эта часть автоматически подставляется ко всем внешним ссылкам в тексте) и резал не весь список, а конкретные `li`, содержащие эти ссылки. Не очень знаком с синтаксисом селекторов блоклиста, но, судя по всему, такая техническая возможность есть.

_(Во избежание оффтопика в комментариях: я не бунтую против блокировки рекламы на сайте, я не доволен тем, что фильтр режет не только рекламу. Пожалуйста, оставьте обсуждение того, кто, чем и сколько зарабатывает за пределами комментариев этого ишью)_

**Comment by dimisa-RUAdList** [comment]
Дубликат. Такое уже есть: https://github.com/easylist/ruadlist/issues/61
