### ISSUE TITLE
amedia.online

### ISSUE THREAD

**Issue by iG8R** [easylist/ruadlist#101]
Например: `https://amedia.online/212-put-vyborov/episode/1/seriya-onlayn.html`

Невозможно переключиться на вкладку "С выбором озвучки", чтобы была возможность выбрать озвучку от других дабберов. Вкладка нажимается, но не происходит смена внешнего вида плеера, где как раз и осуществляется выбор озвучки.

Экспериментальным путём определено, что участвуют в этом следующие фильтры, но при их отключении в "My filters" вновь лезет реклама из всех щелей:
```
amedia.online#@#+js(abort-on-property-read, Date.prototype.toUTCString)
amedia.online#@#+js(abort-on-property-read, Object.prototype.initDeps)
amedia.online#@#+js(cookie-remover, amedia_is_online)
```

<details><summary>Screenshot</summary>

![amedia online-2022-11-29_160655](https://user-images.githubusercontent.com/11407417/204552268-88b746ec-63f3-41a0-8f65-fa65e671cd7b.jpg)

</details>

**Comment by dimisa-RUAdList** [comment]
Что-то не повторяется. Впрочем, вы никак не указываете конфигурацию, и проверка выполнялась в произвольной.

Отключите в браузере все расширения (а также системные средства vpn), оставив только uBlock Origin. Если это не решит проблему, укажите точный номер версии браузера и геолокацию, определяемую на [2ip](https://2ip.ru/).

@dportvine 
Есть возможность посмотреть?

**Comment by dportvine** [comment]
У меня `"С выбором озвучки"`тоже не работает, только если я добавлю в исключения:
```adb
amedia.online#@#+js(abort-on-property-read, Date.prototype.toUTCString)
amedia.online#@#+js(cookie-remover, amedia_is_online)
```

**Comment by dimisa-RUAdList** [comment]
А там этот фрейм вообще есть? Он появляется, если "прибить его гвоздями"? ~>
```
amedia.online##.players-section > [class^="tabs"]:has(> li:first-child + .current) + .box + .box:style(display: block !important)
amedia.online##.players-section > [class^="tabs"]:has(> li:first-child + .current) + .box:style(display: none !important)
```

**Comment by dportvine** [comment]
Фрейм есть, помогают только исключения.
<details>
<summary>Screen</summary>

![2022-11-29_220836](https://user-images.githubusercontent.com/111344219/204637581-c98d3c55-e7eb-49fd-846b-62d16e26650f.png)
</details>

**Comment by dimisa-RUAdList** [comment]
Хорошо. Если убрать исключения для скриплетов, добавить пару стилей из поста выше, и обновить страницу, удерживая шифт - переключение работает?

**Comment by dimisa-RUAdList** [comment]
Ага, то есть поломался именно функционал самой страницы. Он завязан на яндекс, может быть для нероссийских ip его глючит. Если открыть в консоли вкладку сеть, там у запросов не проскакивает статус 404, 503 и подобные?

**Comment by dportvine** [comment]
Есть такое:
<details>
<summary>Screen</summary>

![2022-11-29_220836](https://user-images.githubusercontent.com/111344219/204639455-c52a077d-3437-4c59-8daa-f8cae1ce54cd.png)
![2022-11-29_221944](https://user-images.githubusercontent.com/111344219/204639463-a1f3b0a7-0d33-41d9-b926-899f138005ed.png)
</details>

**Comment by dimisa-RUAdList** [comment]
С российским ip, через vpn, это повторяется? Хотелось бы понять, это аппаратная проблема на маршруте, или они специально сделали ограничение для определённых геолокаций.

**Comment by dportvine** [comment]
Яндекс в Украине заблокирован и не только он. Через VPN, Яндекс работает.
<details>
<summary>Screen</summary>

![2022-11-29_222905](https://user-images.githubusercontent.com/111344219/204641043-9a8abc68-cf93-42d0-a87a-e6a0564644fb.png)
![2022-11-29_222812](https://user-images.githubusercontent.com/111344219/204641054-fac11ef8-2b93-4182-8bd7-3aae21614e6c.png)
</details>

Стили решают проблему. [Gif](https://imgur.com/uUH8SVq)

**Comment by dimisa-RUAdList** [comment]
Всё понял, спасибо.

В Фоксе стили работают безобразно, как и весь сайт, впрочем.

Поправил с учётом этого несчастья: https://github.com/easylist/ruadlist/commit/78bb48991bb96e7256f331c32436fda1ac272495

**Comment by dimisa-RUAdList** [comment]
@dportvine 
А если вместо стилей принудительно убрать геоловушку? ~>
`||amedia.online/templates/Animedia/js/libs.js$script,removeparam=|`

**Comment by iG8R** [comment]
@dimisa-RUAdList 
При убранной принудительно ловушке всё нормально работает, т.е. переключается на вкладку с выбором озвучки.
Спасибо за такое оперативное решение проблемы.

**Comment by dimisa-RUAdList** [comment]
Ок. Убрал стили, сделал скриплеты опять общими, добавил редирект для геоловушки: https://github.com/easylist/ruadlist/commit/41aa1210d55b35b1f6a525cc592abda23ca46113

**Comment by dportvine** [comment]
> А если вместо стилей принудительно убрать геоловушку? ~> `||amedia.online/templates/Animedia/js/libs.js$script,removeparam=|`

В данный момент, могу проверить только с мобильного. **Removeparam** решает проблему.
<details>
<summary>Screen</summary>

![Screenshot_20221130-210905](https://user-images.githubusercontent.com/111344219/204887893-ab786edf-6669-4529-a830-79d832f91e42.png)
![Screenshot_20221130-210830](https://user-images.githubusercontent.com/111344219/204887988-115c8041-7b82-4754-af06-062489d04af7.png)
</details>
