### ISSUE TITLE
kovi.ru

### ISSUE THREAD

**Issue by eporubin** [easylist/ruadlist#104]
Hi @dimisa-RUAdList 
Could you please have a look at [this website ](https://kovi.ru/) we got complains about ads from mobile. 
For reference on [this page ](https://kovi.ru/luchshie-svadby-v-kino/) they have more banners with this  unrelated clothes ads from Klert which redirects: 

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/33602691/206184917-fca35bcc-24e0-4021-afa8-d9255d873bad.png)

</details>

This filter would help hiding them `kovi.ru#?#div:-abp-has(>a[href*="https://keltr.ru/"])`

I have done it pseudo specific because for example in another [sport related article ](https://kovi.ru/video-vseh-boev-ufc-281/) they are also recommending the same clothes website but  its at leats related, and if the filter would target only the link would affect that section.
<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/33602691/206208851-1d7d906b-a1f3-4980-8ec6-d2ca52ef8004.png)

</details>

I personally consider them all as ads, but up to you to decide what best for the list. 

Regards

**Comment by dimisa-RUAdList** [comment]
Ok: https://github.com/easylist/ruadlist/commit/0423ca82420432d5fda16b16fc7808b7ff1db452

**Comment by eporubin** [comment]
Thanks a lot
