### ISSUE TITLE
livejournal.com

### ISSUE THREAD

**Issue by eporubin** [easylist/ruadlist#109]
Hi, could you please add this filter `trim-c.livejournal.com##.image-banner-place` to hide the empty space left for the ads. its taking too much space especially on mobile. (check the video to see what i mean) 
https://imgur.com/a/0TeGrwy
Thank you in advance.

**Comment by dimisa-RUAdList** [comment]
I couldn't find any mention of the `image-banner-place` class using a search in the developer tools. The only way to get it to appear is to use a European ip. But the vast majority of visitors to `livejournal.com` have a Russian ip and a completely different layout (and a different list of network requests), so adding the rule `trim-c.livejournal.com##.image-banner-place` won't help them at all.

The `trim-c.livejournal.com` subdomain is one of thousands of similar `livejournal.com` subdomains, and all of them belong to the Rambler group, which has long and consistently fought against ad blockers. I've added universal hiding rules that will work regardless of ip, but I don't think they will work for more than a few days.

**Comment by eporubin** [comment]
Thanks a lot @dimisa-RUAdList  for looking into it and adjusting it accordingly.
