### ISSUE TITLE
FOP - Problems with filter options beginning with a star

### ISSUE THREAD

**Issue by realodix** [easylist/ruadlist#11]
FOP v3.918

**Step to reproduce**
1. Write `*$popunder,domain=example.com`

[uBlockOrigin/uAssets/filters/filters.txt#L6400](https://github.com/uBlockOrigin/uAssets/blob/d547b014bd8d106ff12b15572c8f43b0df25441d/filters/filters.txt#L6400)

2. Run FOP v3.918

**Expected**
`*$popunder,domain=example.com`

**Actual**
`$popunder,domain=example.com`

**Comment by lainverse** [comment]
That's expected behaviour.
`*$opts` is equal to `$ops` and should work the same both in ABP and uBO.
The only exceptions are rules with redirect/rewrite options.

**Comment by lainverse** [comment]
Ok, according to @dimisa-RUAdList  it's mandatory for `popunder` rules.
Fixed in commit b7c7c9e9feff4b9f4bb79829eef2a0e1685b2a14
