### ISSUE TITLE
.pw: vk-apps.com vk.com

### ISSUE THREAD

**Issue by VzdutieJivota** [easylist/ruadlist#110]
Мои приложения на платформе VK Mini Apps отправляют XHR запросы на сайт *.pw, строка `||pw^$third-party,script,xmlhttprequest,domain=....` блокирует эти запросы. Прошу добавить `~vk.com|~vk-apps.com` в разрешенные домены (для .xyz они добавлены: https://github.com/easylist/ruadlist/commit/ae846f2e4ea2f25ee4565a8fe716a184b62bee31)

**Comment by dimisa-RUAdList** [comment]
Вы забыли указать ссылку на страницу, где данная блокировка приводит к проблемам у пользователей.

**Comment by VzdutieJivota** [comment]
> Вы забыли указать ссылку на страницу, где данная блокировка приводит к проблемам у пользователей.

https://vk.com/app7915515
https://vk.com/app51421246
https://vk.com/app7489511
На всех страницах проблема одна, так как все приложения обращаются к одному домену

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/3324c0f45e87e150e32895d080a75440aebee2d5
