### ISSUE TITLE
burninghut.ru

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#113]
`https://burninghut.ru/ogorod-na-podokonnike/`

<details>
<summary>Screen</summary>

![2023-01-03_100252](https://user-images.githubusercontent.com/111344219/210319573-333b21f3-d731-47a0-a507-b23ac10761a9.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/c855ef92a71c131cfa5df4f3c9ab5b1baebc2fd1
