### ISSUE TITLE
ya.ru

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#114]
```adb
http://ya.ru/images/search?text=%D0%B4%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D0%B8%D0%B5%20%D0%B6%D0%B8%D0%B2%D0%BE%D1%82%D0%BD%D1%8B%D0%B5&lr=213
```

<details>
<summary>Screen</summary>

![2023-01-03_100252](https://user-images.githubusercontent.com/111344219/210320016-9086983e-a087-41fe-a474-61d574c5e997.png)
</details>

Европейский ip.

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/bfdcae058a14b35fb1ba2a04eee006a2207722fc
