### ISSUE TITLE
rbc.ru

### ISSUE THREAD

**Issue by apuzikova** [easylist/ruadlist#115]
Dear Sir/Madam,

My name is Alena Puzikova, I am a project manager, responsible for the web-site `rbc.ru`. We have found out that in the showcase on the main page `rbc.ru` (swiper-wrapper) the content block of our subproject pro.rbc.ru (swiper-slide) is no longer displayed when Adblock is enabled.

For our part, we have checked our block for the existence of blocking factors. Content output was blocked on December 22, 2022 https://github.com/easylist/ruadlist/commit/7078d34e1f59a94ef59ff4becb708a1d7cbf8a78 on the grounds of the presence of utm-tag `utm_campaign` in the material links. However, we use this tag to track the performance of particular materials of the project under our domain, i.e. our subproject `pro.rbc.ru`. In this case, all content in the showcase has the same tag `utm_campaign=vitrina_main` in order to indicate that the `pro.rbc.ru` showcase with its materials is placed on the main page for more accurate tracking of our traffic source.

Could you please reconsider your decision regarding the presence of this showcase in EasyList, as it does not contain blocking factors for output on the site under Adblock.

Thank you in advance!

**Comment by dimisa-RUAdList** [comment]
Правильно ли я понимаю, что знакомиться с материалами на pro.rbc.ru могут только те пользователи, которые оплатили подписку?

**Comment by apuzikova** [comment]
Не совсем так: 

Блоки показываются как платным, так и бесплатным пользователям. При открытии материалов пользователям без подписки его переводит на страницу материала с небольшим текстом, где для дальнейшего прочтения нужно купить подписку. В случае с платными пользователями – для них это просто подборка интересных материалов, с которыми они могут ознакомиться уже полностью. 

 

Эти блоки попадают под Adblock и никто даже не может посмотреть что за материалы там находятся, в том числе и люди, у которых уже есть подписка и они могут это читать. При этом, pro.rbc.ru – это наш подпроект. 

 

От: dimisa ***@***.***>
Обратный адрес: easylist/ruadlist ***@***.***>
Дата: вторник, 10 января 2023 г. в 16:51
Кому: easylist/ruadlist ***@***.***>
Копия: apuzikova ***@***.***>, Author ***@***.***>
Тема: Re: [easylist/ruadlist] rbc.ru (Issue #115)

 

Правильно ли я понимаю, что знакомиться с материалами на pro.rbc.ru могут только те пользователи, которые оплатили подписку?

**Comment by dimisa-RUAdList** [comment]
Ок, смотрите что получается. У вас на странице в левой колонке и так уже есть три огромных баннера, ведущих на сторонний платный ресурс, которые по идее должны подпадать под блокировку, поскольку ресурс платный, а не публичный. А анонсы слайдеров это уже не баннеры. Ещё не мошенничество, но где-то близко. Их заголовки вводят в заблуждение пользователей, которые справедливо полагают, что анонсируемые материалы доступны для них, однако это не так, и для ознакомления они должны оплатить подписку. Смысл анонса становится ничтожным, превращаясь в рекламу платного ресурса. Но если по баннеру пользователь изначально может принять решение, кликать или нет, то про-анонсы никакой информации, позволяющей такое решение принять, не предоставляют.

Уже продолжительное время я регулярно получаю жалобы на этот счёт. При этом ни одного обращения по ложной блокировке не поступало. Вы первый и единственный, кто это сделал. Хотя, вы не пользователь, а представитель ресурса, который пытается этими анонсами ввести пользователей в заблуждение.

По хорошему, все анонсы платного контента на публичном домене должны быть заблокированы. Навигация и интерфейс про-домена позволяют платным пользователям осуществлять веб-сёрфинг без каких-либо ограничений. Обычным же пользователям эти анонсы вообще ни к чему.

**Comment by apuzikova** [comment]
Спасибо за ответ, я вас услышала. 

 

Тогда что нам делать с нашими платными пользователями, которые жалуются на отсутствие материалов, за которые они заплатили? Сейчас есть для них просто пустые заголовки, а Adblock может быть включен по дефолту в браузере. 

 

Возможно ли вернуть показ блока под Adblock платным пользователям? 

От: dimisa ***@***.***>
Обратный адрес: easylist/ruadlist ***@***.***>
Дата: вторник, 10 января 2023 г. в 17:34
Кому: easylist/ruadlist ***@***.***>
Копия: apuzikova ***@***.***>, Author ***@***.***>
Тема: Re: [easylist/ruadlist] rbc.ru (Issue #115)

 

Ок, смотрите что получается. У вас на странице в левой колонке и так уже есть три огромных баннера, ведущих на сторонний платный ресурс, которые по идее должны подпадать под блокировку, поскольку ресурс платный, а не публичный. А анонсы слайдеров это уже не баннеры. Ещё не мошенничество, но где-то близко. Их заголовки вводят в заблуждение пользователей, которые справедливо полагают, что анонсируемые материалы доступны для них, однако это не так, и для ознакомления они должны оплатить подписку. Смысл анонса становится ничтожным, превращаясь в рекламу платного ресурса. Но если по баннеру пользователь изначально может принять решение, кликать или нет, то про-анонсы никакой информации, позволяющей такое решение принять, не предоставляют.

Уже продолжительное время я регулярно получаю жалобы на этот счёт. При этом ни одного обращения по ложной блокировке не поступало. Вы первый и единственный, кто это сделал. Хотя, вы не пользователь, а представитель ресурса, который пытается этими анонсами ввести пользователей в заблуждение.

По хорошему, все анонсы платного контента на публичном домене должны быть заблокированы. Навигация и интерфейс про-домена позволяют платным пользователям осуществлять веб-сёрфинг без каких-либо ограничений. Обычным же пользователям эти анонсы вообще ни к чему.

**Comment by dimisa-RUAdList** [comment]
Ещё раз повторюсь, я не получал ни одной жалобы от пользователей с платной подпиской. И заголовки вовсе не пустые, первая строка, с жирным шрифтом, присутствует. То есть, возможность перейти в целевой раздел сохранена. При этом само пожелание иметь на публичном сайте все ссылки и навигацию по стороннему платному ресурсу невыполнимо в принципе. Размещая про-анонсы, вы даёте ссылки лишь на малую часть того, что доступно пользователю непосредственно при посещении самого про-домена. Единственное решение, при котором пользователь может получить все возможные ссылки и навигацию, это полностью скопировать всё содержимое про на основной домен. Это нереализуемо и абсурдно.

Тем не менее, в вашем сообщение прослеживается намерение предоставить платным пользователям возможность видеть про-анонсы на основном домене. В то же время мне необходимо сделать так, чтобы блокировщики (с подключенным фильтром RU AdList) выполняли ту работу, которую пользователи от них ожидают.

Совместными действиями мы может сделать так, чтобы обе цели были достигнуты не в ущерб друг другу. Для этого обе стороны должны сделать небольшие правки. Если вы сделаете у платных пользователей в макете у `body` класс `pay`, а у обычных класс `free`, то я переделаю правила скрытия таким образом, чтобы они якорились на эти классы и срабатывали только при условии их наличия.

P.S. Кстати, сейчас открыл ваш сайт на большом экране, и обнаружил, что и в правой колонке также присутствуют баннеры, ведущие на сторонний платный ресурс.

**Comment by apuzikova** [comment]
Хорошо, спасибо 
Предложу данное решение руководству на обсуждение. 



Отправлено из мобильной Почты Mail.ru


вторник, 10 января 2023 г. в 18:38 +0300 от ***@***.***  ***@***.***>:

**Comment by AnnaErmakova25** [comment]
@dimisa-RUAdList Добрый день 
Внесли правки на проде.

**Comment by dimisa-RUAdList** [comment]
@AnnaErmakova25 
Здравствуйте. Вы ещё работаете в компании?

**Comment by AnnaErmakova25** [comment]
@dimisa-RUAdList Добрый день 
Мы поправили классы на новой версии сайта РБК.

**Comment by AnnaErmakova25** [comment]
@dimisa-RUAdList 

Добрый день 

> Мы никогда не поддерживали работу фильтров в рекламных браузерах, и не планируем этого в будущем.

Это печально, потому что уже довольно большая часть аудитории пользуется Яндекс Браузером. 

Также хотелось бы вернуться к вопросу блокировки нашего редакционного контента для неавторизованных пользователей.

Ресурс https://pro.rbc.ru/ - это проект РБК, подписной продукт с эксклюзивными редакционными материалами. Мы используем стандартную для медиа модель: пользователь может ознакомиться с частью материала, а полный доступ предоставляется по подписке. 

В текущей конфигурации блокировка фактически ограничивает доступ к редакционному контенту и мешает работе платной модели СМИ, что затрагивает не рекламные механики, а саму возможность распространения нашего редакционного продукта.

Просим пересмотреть добавление данного ресурса в фильтры или уточнить критерии, чтобы мы могли внести соответствующие правки.

**Comment by AnnaErmakova25** [comment]
@dimisa-RUAdList 

Добрый день 

Обратила внимание, что вы пишете о "стороннем платном контенте", размещенном на pro.rbc.ru. 

Видимо, здесь есть недопонимание. На ресурсах РБК не продвигается сторонний контент, речь идет о доступности и продвижении собственного контента РБК, который доступен как в бесплатном, так и платном вариантах.

Проект на домене pro.rbc.ru - это один из продуктов РБК, такой же, как, например, Инвестиции (https://www.rbc.ru/quote) и Недвижимость (https://realty.rbc.ru/).

Размещение дополнительного платного контента за пейволом является общепринятым стандартом, которым пользуются крупнейшие мировые СМИ. Достаточно зайти например на основную страницу The Wall Street Journal и там будут блоки, ведущие на страницы с ограниченным текстом и предложением оплатить подписку для доступа. Аналогичными механизмы используются и российскими медиа, когда на главной странице есть подзамочный контент, который также ведет на отдельные страницы с пейволом. 

Однако в отличие от вышеприведенных примеров, где AdBlock не влияет на функциональность отображения, на сайте РБК имеются проблемы с доступом к собственному платному контенту, так как adblock расценивает его как рекламу сторонних материалов.

Вы пишете о неких изменениях, укажите, пожалуйста, что именно мы можем поменять, чтобы не подпадать под фильтры. Мы готовы внести нужные изменения.

**Comment by AnnaErmakova25** [comment]
@dimisa-RUAdList 

Добрый день,

спасибо за разъяснение вашей позиции.

Мы понимаем ваш подход, при котором контент на разных доменах может рассматриваться как сторонний. Однако в данном случае это приводит к ложному срабатыванию (false positive), которое затрагивает базовую функциональность сайта.

Даже если рассматривать http://pro.rbc.ru/ как отдельный домен, блокируемый элемент не является рекламой в обычном смысле:

- он не содержит сторонней рекламы, трекеров или спонсорского контента
- не продвигает внешние продукты или сервисы
- является частью механизма доступа к редакционному контенту (paywall)

Проблема в том, что текущее правило не просто скрывает промо-элементы, а вмешивается в пользовательский сценарий доступа к материалам. В ряде случаев это влияет на нормальное взаимодействие со страницей, а не только на отображение отдельных блоков.

На наш взгляд, это выходит за рамки задачи блокировки рекламы и затрагивает функциональность сайта, чего обычно стараются избегать даже при строгих фильтрах.

Мы с уважением относимся к вашему подходу и целям фильтрации. Однако в данном случае правило, вероятно, является слишком широким и затрагивает легитимный механизм доступа к контенту.

Могли бы вы, пожалуйста, рассмотреть возможность скорректировать правило таким образом, чтобы оно не влияло на функциональность, сохраняя при этом свою основную задачу?

При необходимости готовы предоставить конкретные примеры страниц.

Спасибо.

**Comment by dimisa-RUAdList** [comment]
Из вашего пространного сообщения я понял, что вы обнаружили какую-то поломку функционала. Приведите пожалуйста детали того, что именно поломано и опишите шаги, которые необходимо выполнить для воспроизведения проблемы.

**Comment by NatalyRBC** [comment]
Добрый день!

Возвращаемся к вопросу о блокировке анонсов материалов РБК с подпиской.

В предыдущем обсуждении вы поясняли, что причиной блокировки являлось размещение материалов с подпиской на pro.rbc.ru: при показе их анонсов на rbc.ru такой контент, согласно вашей логике фильтрации, рассматривался как сторонний.

С тех пор архитектура продукта изменилась: Подписка на РБК полностью переехала с pro.rbc.ru на основной домен rbc.ru. Сейчас и сами редакционные материалы, и их анонсы размещаются в рамках одного домена — rbc.ru.

После переезда некоторое время анонсы материалов с подпиской корректно отображались и при включённом AdBlock. Сейчас мы видим, что у неавторизованных пользователей эти анонсы снова блокируются.

Хотели бы разобраться, с чем связано текущее срабатывание фильтров. Причина, которую мы обсуждали ранее — размещение анонса и самого материала на разных доменах, — в текущей реализации отсутствует.

При этом речь идёт об анонсах собственного редакционного контента РБК на rbc.ru. Они не являются сторонней рекламой и не ведут на внешний ресурс: пользователь переходит с одной страницы rbc.ru на другую страницу rbc.ru, где размещён соответствующий редакционный материал.

Подскажите, пожалуйста, какое именно правило сейчас приводит к блокировке этих анонсов и по какому критерию они классифицируются как элементы, подлежащие блокировке?

Готовы предоставить конкретные URL и примеры страниц, на которых воспроизводится проблема.

Спасибо!

**Comment by dimisa-RUAdList** [comment]
Приведите пожалуйста конкретный пример.

**Comment by NatalyRBC** [comment]
<details>
<summary>Так выглядит например блок Главное с включенным Adblock</summary>

<img width="556" height="325" alt="Image" src="https://github.com/user-attachments/assets/1e175107-624c-44a3-91dd-8743677fa756" />

</details>

<details>
<summary>А так с выключенным </summary>

<img width="548" height="492" alt="Image" src="https://github.com/user-attachments/assets/6a2652dc-e831-41b1-9e43-cc653fb5101e" />

</details>

**Comment by dimisa-RUAdList** [comment]
Причина скрытия про-анонсов подробно изложена в первом же моём ответе по существу: https://github.com/easylist/ruadlist/issues/115#issuecomment-1377371358

С тех пор ничего не изменилось. И как и было условлено ранее, скрываются они не у всех, обладатели подписки Pro их видят. 

Определение "сторонние" касалось исключительно баннеров. То, что вы перенесли платные материалы на основной домен, ни на что не влияет. Вы по-прежнему продолжаете намеренно вводить пользователей в заблуждение, оформляя про-анонсы как публично доступные материалы.

**Comment by NatalyRBC** [comment]
Спасибо за пояснение. Понимаем, что анонсы блокируются не из-за доменной структуры, а потому, что вы считаете анонсирование материалов, доступных по подписке, вводящим пользователя в заблуждение.

Однако все такие материалы РБК маркируются специальным значком непосредственно в анонсе, рядом с заголовком. Пользователь ещё до перехода видит, что материал имеет ограниченный доступ, поэтому нам непонятно, на каком основании это квалифицируется как намеренное введение пользователя в заблуждение.

При этом речь идёт не о рекламе подписки, а об анонсах собственных редакционных материалов РБК, включая, например эксклюзивы, на rbc.ru. То, что полный доступ к части редакционного контента предоставляется по подписке, само по себе, на наш взгляд, не превращает его анонс в рекламу.

Кроме того, насколько мы понимаем политику EasyList, self-promotion, включая подписки, не должен становиться непосредственной целью блокировки. Поэтому просим пояснить, на основании какого конкретного правила RU AdList анонсы платных редакционных материалов РБК подлежат блокировке.

И отдельно хотелось бы понять, применяется ли этот критерий одинаково ко всем СМИ с paywall. Мы видим российские и зарубежные издания с аналогичной моделью, у которых анонсы платных материалов не блокируются. В чём принципиальное отличие нашего случая?

С учётом явной маркировки платных материалов просим пересмотреть блокировку либо пояснить конкретный критерий, на основании которого она применяется.

**Comment by dimisa-RUAdList** [comment]
Ваш специальный значок имеет нулевую информативность, и оттого вся аргументация, построенная на утверждении об обратном, теряет какой-либо смысл. 

Я не имею прямого отношения к EasyList, а EasyList, в свою очередь, не имеет прямого отношения к AdBlock. То, что блокирующие рекламу расширения и программы используют публичные фильтры, не объединяет нас в одну структуру с общей политикой. Часть расширений и программ даже не относит себя к блокировщикам рекламы, кто-то имеет собственные белые списки, кто-то практикует комбинирование фильтров (EasyList+RU AdList, например). На политику RU AdList и выбор способов борьбы с рекламой и нежелательным контентом всё это никак не влияет.

Критерий нежелательности применяется одинаково, исходя из принципа разумности. Зарубежные издания не относятся к сфере RU AdList. Если у вас есть аналогичный российский пример, приведите его для сравнения.

**Comment by NatalyRBC** [comment]
Спасибо за пояснение. Тогда хотели бы понять, какие именно критерии вы используете для оценки информативности маркировки.

Если используемый нами значок, с вашей точки зрения, недостаточно информативен, какая маркировка позволила бы пользователю однозначно понять, что материал доступен по подписке?

При этом блокируются и анонсы, где под заголовком прямо указано «Подписка на РБК». Почему в таком случае этот формат также считается недостаточно информативным и подпадает под блокировку? 


<details>
<summary>Screenshot(s)</summary>

<img width="706" height="143" alt="Image" src="https://github.com/user-attachments/assets/2cccd782-f412-4b5f-8c31-23eedd08a728" />

</details>

**Comment by dimisa-RUAdList** [comment]
Вся эта привязка к информативности специального значка - часть ваших собственных рассуждений. Несмотря на то, что ни перечёркнутый наискосок квадрат, ни маркировка "Подписка на РБК" совершенно ничего объясняют, про-анонсы, будь то строчные новости в разделе "Главное", слайдеры или врезки, блокируются вовсе не поэтому. 

О причине я уже писал ранее. Речь идёт о намеренной недобросовестности. Вы специально вводите пользователей в заблуждение, чтобы продвинуть платную подписку. Никаких материалов, доступных для ознакомления, в ссылках про-анонсов нет. И вы это прекрасно знаете. И если врезки и слайдеры - это просто обман, то помещение про-анонсов в раздел "Главное" - это уже обман циничный.
