### ISSUE TITLE
Яндекс Директ

### ISSUE THREAD

**Issue by CATIOR** [easylist/ruadlist#116]
Я просто скину этот кошмар картинкой. 

- Режим встраивания мгновенный в TamperMonkey (версия 4.18.1 2022-11-13)
- Используется Ublock 1.46.0
- Внутри Ublock активен список ruadlist
- Версия скрипта ruadlist 20221120.0 для TamperMonkey
- Последняя версия Google Chrome

<details>
<summary>Screenshot(s)</summary>

![фу](https://user-images.githubusercontent.com/37276986/212355850-c8f2178b-ace3-4a66-874d-f4a753c94e58.png)
![япогода](https://user-images.githubusercontent.com/37276986/212356351-b5302c3b-8436-4d07-813d-0411c1a318f1.png)

</details>

Уважаемый автор! Спасибо за Вашу работу. Возможно ли что-то с этим Яндексом сделать?

**Comment by dimisa-RUAdList** [comment]
Укажите пожалуйста точные ссылки на страницы, где были сделаны скриншоты. Также нужен точный номер версии браузера.

**Comment by CATIOR** [comment]
https://yandex.ru/pogoda/ - тут сразу в правом блоке. Я так понимаю, с ним давно борьба идёт, ибо он то появлялся, то исчезал с обновлениями скрипта :)
https://yandex.ru/images/search?text=cyberpunk%202077%20art&lr=49&rpt=image - тут не сразу появляется, по ощущениям нужно сделать несколько поисковых запросов на одной и той же странице, пооткрывать картиночки и полистать страницу вниз. С первого раза на Яндекс Картинках не появляется огромный баннер.

Версия Google Chrome 109.0.5414.75

**Comment by CATIOR** [comment]
Ааа! mail.yandex.ru - в почте тоже пробудилось древнее зло, которое до этого спало

![фу](https://user-images.githubusercontent.com/37276986/212359729-c440e10c-c722-4e34-8bd9-b704e0bc055b.png)

**Comment by CATIOR** [comment]
Прошу прощения. Я переустановил скрипт и всё исправилось. Ерунда какая-то.

**Comment by dimisa-RUAdList** [comment]
Дело в том, что для пользователей uBlock Origin скрипт RU AdList JS Fixes не нужен уже года два. Это функции выполняются при подключении фильтра Counters: https://github.com/easylist/ruadlist/wiki/RU-Adlist-links

Полностью рекомендации для uBlock Origin описаны в [топике поддержки RU AdList на руборде](http://forum.ru-board.com/topic.cgi?forum=5&topic=50761&start=0&limit=1&m=3#1).

**Comment by CATIOR** [comment]
Спасибо.

Оно всё же появилось. https://afisha.yandex.ru/moscow/cinema
Проверьте, пожалуйста.

![фу](https://user-images.githubusercontent.com/37276986/212377778-ce36d5f2-862e-43b5-8962-5e779b49bcdd.png)

**Comment by dimisa-RUAdList** [comment]
Counters подключен?

**Comment by CATIOR** [comment]
Спасибо. Теперь всё точно хорошо.
