### ISSUE TITLE
37.1.205.159

### ISSUE THREAD

**Issue by PhoenixIndigo** [easylist/ruadlist#117]
`123torrent.ru,37.1.201.32,37.1.203.156,37.1.204.182,37.1.204.76,37.1.205.159,37.1.205.47,37.1.206.121,37.1.206.95,37.1.207.130,37.1.207.65,37.1.216.106,37.1.216.119,37.1.217.105,37.1.217.113,5.45.65.153,5.45.66.118,5.45.70.162,5.45.86.39,5.45.87.85,berutor.site,blackrutor.site,extrutor.org,extrutor.site,fastrutor.site,herutor.org,listrutor.org,new-rutor.org,pipitor.org,pronpic.org,prutor.site,r-tor.ru,rutor-live.tk,rutor-search.info,rutor1.site,tracker-rutor.tk,xrutor.org##:not(obhod-adblocka)`
Это правило скрывает сайт.

**Comment by dimisa-RUAdList** [comment]
Всё верно.

**Comment by PhoenixIndigo** [comment]
Так в чём смысл блокировки зеркал, если новые работают отлично, так зачем блокировать старые. Firefox+uBO

**Comment by PhoenixIndigo** [comment]
Просто неясно, к чему правило если надо исключение.

**Comment by dimisa-RUAdList** [comment]
Фейковые ресурсы, продвигающие вредоносное ПО и мошеннические сайты - блокируются намеренно. Конкретно 37.1.205.159 является фейковым зеркалом рутора, к тому же ещё и практикующим обход адблока.

**Comment by PhoenixIndigo** [comment]
А как этот: `http://37.1.206.118/torrent/905344/avatar-put-vody_avatar-the-way-of-water-2022-ts-d/`

**Comment by PhoenixIndigo** [comment]
Понятно фейк, удалю исключение.

**Comment by dimisa-RUAdList** [comment]
Заблокировал: https://github.com/easylist/ruadlist/commit/b6ce3ceec6a11c3e16f81e575358b894024dd711

**Comment by PhoenixIndigo** [comment]
Гугл только фейк новый и находит. Компромисс бы был.

**Comment by dimisa-RUAdList** [comment]
Какой ещё компромисс? Фейк, продвигающий мошеннические сайты, практикующий кликандеры и загружающий вредоносное ПО вместо торренов - не может быть компромиссом, это исключено.
