### ISSUE TITLE
vsesdal.com

### ISSUE THREAD

**Issue by felippesantos46** [easylist/ruadlist#118]
`https://vsesdal.com/kursovaya-rabota`

Links hidden by `##a[href*="://vsesdal.com/promo/"]` affects the domain functionality.

<details>
<summary>Screenshot(s)</summary>

<img width="1440" alt="Google Chrome AdBlock is off" src="https://user-images.githubusercontent.com/65717387/213687961-17e368d3-9a96-451e-94cc-fb9162801326.png">
<img width="1432" alt="Google Chrome AdBlock is on" src="https://user-images.githubusercontent.com/65717387/213687967-ea3a7b2a-f4d2-4641-b9ab-cf376a2887af.png">

</details>

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/db4bd3fcfc39ce8fe730756b447166fca13a1b00
