### ISSUE TITLE
tag.aticdn.net

### ISSUE THREAD

**Issue by smed79** [easylist/ruadlist#119]
Hi,

blocking `tag.aticdn.net` break the video player at `information.tv5monde.com`

e.g. `https://information.tv5monde.com/video/etats-unis-bataille-politique-autour-de-l-immigration`

Thank you.

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/64e0582b63bdc0c0580f83a4fe58ae90efd273bd
