### ISSUE TITLE
FOP: Unrecognised uBo option

### ISSUE THREAD

**Issue by realodix** [easylist/ruadlist#12]
According uBo static filter syntax documentation, I found some options that are not recognized by FOP.

**1p**
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#1p

**3p**
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#3p

**css**
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#css

**cname**
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#cname

**denyallow**
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#denyallow

**ehide**
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#elemhide

**ghide**
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#generichide

**inline-font**
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#inline-font

**frame**
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#frame

**specifichide, shide**
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#specifichide

**strict1p**
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#strict1p

**strict3p**
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#strict3p

**removeparam**
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#removeparam

**Comment by dimisa-RUAdList** [comment]
They and shouldn't be recognized. Most of the listed options are pseudonyms that are used in uBO when working internally with the classic syntax.

1p = `~third-party`
3p = `third-party`
css = `stylesheet`
etc...

By the way, not pseudonyms are displayed in the uBO logger, but classic rules.

FOP was created to work with the filter RU AdList and fully meets the current needs. It is not planned to add support for uBO-specific options in addition to the existing universal analogs. At least until a real need arises.

**Comment by realodix** [comment]
Thank you
