### ISSUE TITLE
irecommend.ru

### ISSUE THREAD

**Issue by zpttchk** [easylist/ruadlist#120]
Добрый день!
Обфускацию РСЯ убрали как обсуждалось здесь https://github.com/easylist/ruadlist/issues/108
Прошу откатить правила, ломающие сайт для юзеров с адблоком:
https://github.com/easylist/ruadlist/blob/d96d84c/advblock/specific_special.txt#L8
https://github.com/easylist/ruadlist/blob/d96d84c/advblock/specific_special.txt#L25
https://github.com/easylist/ruadlist/blob/74672ec/js-fixes-experimental.txt#L66
https://github.com/easylist/ruadlist/blob/74672ec/js-fixes-experimental.txt#L80
https://github.com/easylist/ruadlist/blob/74672ec/js-fixes-experimental.txt#L186
https://github.com/easylist/ruadlist/blob/74672ec/js-fixes-experimental.txt#L253

**Comment by dimisa-RUAdList** [comment]
Дубль, обсуждение этого домена уже есть.
