### ISSUE TITLE
metaratings.ru

### ISSUE THREAD

**Issue by r10t** [easylist/ruadlist#121]
Добрый день. Можно ли из фильтров удалить правило "metaratings.ru##a[href^="/promo1xstavka"]" ? Мы ничего не имеем против блокировки рекламы на нашем сайте, но конкретно это правило ломает нам корректную работу сайта. Данная промо-ссылка не используется в баннерах, всплывающих окнах и кетфишах, не является навязчивой рекламой, не нарушает опыт взаимодействия пользователя с сайтом. И, если у пользователя скрывается ссылка с таким href - пункт рейтинга вырезается.
<details>
<summary>Screenshot(s)</summary>

![1675257025432](https://user-images.githubusercontent.com/1777684/216052681-bc8f2e7f-42b8-420b-a90e-2aa4f7a564ea.jpg)

</details>

**Comment by dimisa-RUAdList** [comment]
Вы не указываете, где именно наблюдается проблема, но на самом деле, эту проблему в одностороннем порядке не решить. Те элементы, ссылки с которых ведут на ресурсы букмекеров, подлежат блокировке. Если же они несут какую-то информативную составляющую, она оказывается утрачена. В текущем виде сайт заведомо несовместим с блокировщиком. Единственное, что тут можно поправить с нашей стороны, это скрыть те элементы, показ которых без рекламных ссылок потерял смысл. Но наилучшим решением было бы не использовать рекламные ссылки в качестве информационных данных.

**Comment by r10t** [comment]
Прощу прощения, не прикрепил скрин с заблокированной промо-ссылкой. Данные промо-ссылки не являются рекламой БК в классическом понимании, у нас сайт представляет из себя рейтинг букмекерских контор, где люди (которые изначально пользуются услугами БК) могут почитать отзывы о них, сравнить рейтинги надёжности и, в случае заинтересованности, перейти на сайт. Т.е. данное правило не убирает рекламу у пользователя, а не даёт ему (пользователю) в должной мере пользоваться сервисом.
![1675317762680](https://user-images.githubusercontent.com/1777684/216244552-e199ae71-9e6b-4d6f-8c2f-d8d791f8b7a1.jpg)

**Comment by dimisa-RUAdList** [comment]
Вы опять прикладываете скрин без указания ссылки на страницу, где он был сделан. Чтобы обсуждение было предметным, нужен конкретный линк.

**Comment by r10t** [comment]
[На главной сайта](https://metaratings.ru)

**Comment by dimisa-RUAdList** [comment]
Спасибо, теперь понятно. Судя по всему, у вас не совсем верное понимание того, что является рекламой и подлежит блокировке. Общая идея описана в [EasyList Policy](https://easylist.to/pages/policy.html). Если кратко, то режутся любые сторонние ссылки, за исключением ссылок из поисковой выдачи и социалки, да и то не всей.

С виджетами типа "рейтинг букмекеров" за годы поддержки фильтра RU AdList я сталкивался бесчисленное количество раз, и не было ни одного случая, чтобы такой виджет был информационным. Это всегда инструмент плохо замаскированной монетизации и он является целевым для блокировщика.

Чтобы такой виджет работал под адблоком, взаимодействие с ним не должно приводить к переходу на сторонние ресурсы.

Поэтому если вы хотите сделать виджет совместимым с блокировщиком, подумайте о том, чтобы после блокировки рекламных ссылок с него, его вид имел хоть какую-нибудь полезную составляющую.
