### ISSUE TITLE
rg.ru

### ISSUE THREAD

**Issue by ddantondden** [easylist/ruadlist#122]
Добрый день.
На сайте rg.ru с блокировщиком AdblockPlus не работают переходы на статьи.

Как повторить:
Перейти на главную страницу https://rg.ru и перейти на любую статью в колонке слева. После этого Возникнет сообщение об ошибке. При повторной попытке перехода сайт зависнет и останется только белый экран.

**Comment by dimisa-RUAdList** [comment]
На сайте используется агрессивный метод обхода адблока с помощью обфускации РСЯ. Этот метод несовместим с адблоком, сайт будет ломаться, реклама же при этом всё равно показана не будет. Проблема может быть решена только на стороне ресурса.

**Comment by dimisa-RUAdList** [comment]
Вы представляете rg.ru или РСЯ?

**Comment by ddantondden** [comment]
Я никого не представляю. Но, если надо, могу связать вас с представителями РСЯ.

**Comment by ddantondden** [comment]
Сайт, кажется, заработал. Спасибо.

**Comment by dimisa-RUAdList** [comment]
Представители РСЯ прекрасно знают, как со мной связаться. Но насколько мне известно, им запрещено общение с авторами фильтров и разработчиками блокировщиков.

Что касается починки сайта, то никаких действий с моей стороны не предпринималось.

**Comment by ddantondden** [comment]
Все такие иногда проблема повторяется. Не знаю от чего это зависит. Можно посмотреть?

**Comment by dimisa-RUAdList** [comment]
Вместо того, чтобы повторно кликать по несработавшей ссылке, попробуйте просто обновить страницу.

**Comment by ddantondden** [comment]
Не работают не только повторные клики, а любые переходы. То есть после каждого перехода по ссылке мне нужно нажимать F5 или сайт ломается. Это не очень удобно.

**Comment by dimisa-RUAdList** [comment]
Что-то не повторяется. Ни один из нескольких десятков переходов не привёл к ошибке.

**Comment by dimisa-RUAdList** [comment]
Что бы вы предложили в качестве решения?

**Comment by ddantondden** [comment]
Хм. Я не специалист в этом, но кажется проблемы появились после внесенных вами изменений. Почему бы не попробовать как то исправить правила чтобы так не случалось?
