### ISSUE TITLE
amedia.online

### ISSUE THREAD

**Issue by ddantondden** [easylist/ruadlist#123]
Добрый день.
На сайте https://amedia.online/ c AdblockPlus не работает куча функций.

Не работает переключение темы, не работают кнопки с помощью которых можно листать списки. Не работает поиск, не работают комментарии и авторизация. Может что-то еще сломано о чем я не знаю.

**Comment by dimisa-RUAdList** [comment]
На сайте используется агрессивный метод обхода адблока с помощью обфускации РСЯ. Этот метод несовместим с адблоком, сайт будет ломаться, реклама же при этом всё равно показана не будет. Проблема может быть решена только на стороне ресурса.

**Comment by ddantondden** [comment]
Ну то есть я правильно понимаю что сайт сломан специально с вашей стороны, чтобы заставить авторов перестать обходить блокировку рекламы?

**Comment by dimisa-RUAdList** [comment]
Вы поняли неправильно. Попытки починить сайт предпринимались неоднократно, но добавленные для этого исключения были использованы РСЯ для встраивания рекламы и их пришлось удалить. С этого момента обфускация РСЯ стала квалифицироваться как несовместимая с адблоком, ведь любой сетевой запрос при её использовании теперь потенциально может приводить к загрузке рекламы. Фактически, РСЯ стала рекламным террористом.

Действующие в настоящий момент правила нацелены на блокировку РСЯ, часть функционала не работает вынуждено, это единственный способ избежать встраивания рекламы.

Текущий процесс веб-сёрфинга сейчас напоминает слалом вслепую. Какой-то сайт нормально не грузится из-за действий РКН, при этом дело не в блокировке сайта как таковой, достаточно наличия скрипта фейсбука или логотипа канала во фрейме youtube. Другие сайты не работают ввиду прямой блокировки из-за санкций с обеих сторон. Что-то не работает из-за слишком строгих дефолтных настроек безопасности актуальных браузеров, где-то нужен сертификат минцифры, где-то нужно очистить куки. Недоступность сервисов вк, дзена и яндекса, имевшая место в последние дни, стала совершенно рядовым явлением, о которой сообщили далеко не во всех новостях.

В результате пользователь должен преодолеть все препоны: включением-отключением впн, смены в нём локации, обновлением страниц, корректировкой настроек браузера, включением-отключением блокировщика или обновлением его фильтров и т.д. Или вообще, зайти на интересующий сайт позже.

В этом свете что-то неработающее уже выглядит совершенно обыденным, тем, с чем пользователь сталкивается многократно в течении дня.

И это ещё не вступил в действие гугловский MV3. Как только это произойдёт, обновление части правил в блокировщиках потеряет оперативность и станет возможным только при публикации новой версии расширения в магазине. Учитывая, что где-то шестая часть ежедневно актуализируемых правил преследует цель не заблокировать рекламу, а предотвратить ложные срабатывания, нас ждёт ситуация, при которой будут на постоянной основе ломаться сотни сайтов. Гугл в курсе этой перспективы, однако считает что безопасность, придущая вместе с MV3, важнее.

Ещё год назад обфускация РСЯ была средством встраивания рекламы в обход адблока, превращая сайт в такой вид, будто блокировщик не работает вовсе. Ведь неработающий функционал был уникальным явлением. Сейчас не работает слишком много всего, поэтому создание прецедента, когда обфускация РСЯ не приводит к показу рекламы, и лишь порождает риск поломки части функционала, уместно как никогда.

**Comment by ddantondden** [comment]
Под попытками "починить сайт" вы имеете ввиду попытки удалить рекламу без поломки сайта?
Вы говорите что я что-то неправильно понял, но буквально пишете в первом и в последнем абзаце, что специально сломали сайт, а остальная часть сообщения - это мотивация, котороя сводится к "все так делают".

Предположим даже я соглашусь с фактом, что все что вы описали насчет РКН, санкций итд приводят к тому, что серфинг в интернете стал похож на минное поле. Но из этого совершенно не следует, что теперь всё дозволено и каждый плагин имеет право усугублять ситуацию.

**Comment by dimisa-RUAdList** [comment]
Поскольку вы не делаете никаких предложений, да и вообще, отказываетесь признавать принадлежность к встраиванию рекламы, дальнейший диалог теряет смысл. У меня попросту нет времени на подобные дискуссии.

**Comment by ddantondden** [comment]
Я не понимаю какие предложения могут быть с нашей стороны. Мой интерес тут был в том чтобы понять логику по которой ломается сайт. И, к сожалению, я никак не могу повлиять на встраивание рекламы.

Как я писал выше если вам интересно обсудить что-либо с представителями РСЯ - я могу донести это желание.

За снятие правил ломающих сайт спасибо.
