### ISSUE TITLE
myauto.ge

### ISSUE THREAD

**Issue by 836874** [easylist/ruadlist#127]
Не могу открыть страницы при включенном ruadlist

<details>
<summary>Screenshot(s)</summary>

![Capture](https://user-images.githubusercontent.com/124845740/222915603-66baa928-5b9c-4b30-b8fd-3f125fe2047f.PNG)

</details>

**Comment by dimisa-RUAdList** [comment]
Ваша сообщение не содержит ссылки на страницу, где наблюдается проблема. На главной никаких поломок нет.

**Comment by 836874** [comment]
> Ваша сообщение не содержит ссылки на страницу, где наблюдается проблема. На главной никаких поломок нет.

https://www.myauto.ge/ru/pr/85106299/iyideba-manqanebi-jipi-toyota-highlander-2018-benzini-tbilisi?offerType=superVip
Например здесь
Да, главная страница работает
/js/banners.js нашел в правилах, может в этом проблема

**Comment by 836874** [comment]
> Не фиксирую срабатываний этого правила. Возможно, есть какая-то геозависимость, или проблема повторяется только в каком-то определённом браузере. Укажите пожалуйста точный номер версии браузера и геолокацию. Если используется vpn, то название этого расширения и какая страна выбрана в его настройках.

Google Chrome 110.0.5481.178
страна Грузия
нет впн
это фильтры
![Capture](https://user-images.githubusercontent.com/124845740/222922630-91401e68-4483-47c5-b0d5-ca1338894ff3.PNG)

**Comment by dimisa-RUAdList** [comment]
Ок, попробуйте добавить в "Мои фильтры" ~> `/js/banners.js$badfilter,domain=~apteka9800000.ru`

**Comment by 836874** [comment]
> Ок, попробуйте добавить в "Мои фильтры" ~> `/js/banners.js$badfilter,domain=~apteka9800000.ru`

Теперь работает, спасибо

**Comment by dimisa-RUAdList** [comment]
Добавил исключение для этого домена: https://github.com/easylist/ruadlist/commit/bb70f8f0ae8b7c68865454d123201d8f27aca9e6

Минут через 15 исправление вступит в силу и станет доступно при обновлении фильтров [вручную](http://forum.ru-board.com/topic.cgi?forum=5&topic=50761&start=0&limit=1&m=5#1). После этого правило из "Моих фильтров" можно будет удалить.

**Comment by dportvine** [comment]
```adb
https://www.myauto.ge/ru/pr/85106299/iyideba-manqanebi-jipi-toyota-highlander-2018-benzini-tbilisi?offerType=superVip
```

<details>
<summary>Screen</summary>

![2023-03-05_101030](https://user-images.githubusercontent.com/111344219/222949409-0ea371a6-ffd8-4d84-87be-e91f03ce7102.png)
</details>

**Comment by dimisa-RUAdList** [comment]
Не уверен, что это нужно делать. За последние 8 лет в ABP-дайджест репортов ни один домен ge не попал ни разу. Я вообще не знаю, куда они улетают. Из стран СНГ русскоязычной контент сохранили Украина, Белорусь, Казахстан, страны Прибалтики... А вот Армения и Грузия русский язык практически предали забвению. Наличие исправлений, предотвращающих поломки, в RU AdList смотрятся адекватно, а что будет с частными блокирующими правилами, когда они начнут что-то ломать - неизвестно. Лучше не трогать.
