### ISSUE TITLE
probiv.in, probiv.one

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#128]
`https://ru.probiv.in/`, `https://rus.probiv.in/`
<details>
<summary>Screen</summary>

![2023-03-05_100133](https://user-images.githubusercontent.com/111344219/222949147-bc9cacb3-b3c1-4cc0-ad38-a952822e6a34.png)
![2023-03-05_100237](https://user-images.githubusercontent.com/111344219/222949152-c816f842-8b5a-4a4d-b24c-f31bde06be30.png)
</details>

`https://probiv.one/`
<details>
<summary>Screen</summary>

![2023-03-05_100205](https://user-images.githubusercontent.com/111344219/222949175-d8019456-2917-4460-9bb0-361e6f34cfba.png)
</details>

**Comment by dimisa-RUAdList** [comment]
Да, возможно именно это [имел ввиду](http://forum.ru-board.com/topic.cgi?forum=5&topic=50761&start=3840#13) **LION8GN**. По крайней мере, имеет место аналогия с уже скрываемым анонсом "рекламные места на форуме".

Добавил в BitBlock: https://github.com/easylist/ruadlist/commit/cc74154fe7f220c72f1b2cb5a4b8c31b606171b0
