### ISSUE TITLE
FOP: "Warning: Incorrect filter" on a valid filter

### ISSUE THREAD

**Issue by realodix** [easylist/ruadlist#13]
**Valid Syntax**
`||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js^$script,redirect-rule=googlesyndication_adsbygoogle.js,domain=example.com`

Can also be written like this, but FOP gives a warning "Incorrect filter"

`/adsbygoogle.$script,redirect-rule=googlesyndication_adsbygoogle.js,domain=example.com`

I did an experiment on this page by blocking https://github.githubassets.com/assets/environment-f0adafbf.js

`/environment-$script,redirect=noop.js,domain=github.com`

The results are as expected

<details>
  <summary>Screenshot</summary>
  
  ![cats](https://user-images.githubusercontent.com/1314456/109565619-4cec0d00-7b15-11eb-9427-f8ed5765807d.jpg)
</details>

**Comment by dimisa-RUAdList** [comment]
Use asterix: `*`

Example:
*/adsbygoogle.$script,redirect-rule=googlesyndication_adsbygoogle.js,domain=example.com
*/environment-$script,redirect=noop.js,domain=github.com

**Comment by realodix** [comment]
The uBlo logger are displayed as `/environment-$script,redirect=noop.js,domain=github.com`, which you call classic rules. Why must starting with `*` ?

**Comment by dimisa-RUAdList** [comment]
I don't understand your comment. If you want to use FOP without an error message, add an asterisk in front of your rules, as in the example above.

**Comment by realodix** [comment]
Thank you

**Comment by lainverse** [comment]
Technically redirect-rule filters were supposed to either always start with || or apply to all links (and asterisk was mandatory even though it's optional at start or when it's the only symbol in the pattern). This rule definitely apply to rewrite filters (at least according to APB documentation).
