### ISSUE TITLE
kufar.by

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#131]
`https://www.kufar.by/`

<details>
<summary>Screen</summary>

![2023-03-15_174845](https://user-images.githubusercontent.com/111344219/225365102-2e48159a-c02d-4604-87c8-ba3e7c4cef85.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/c640ef9adce11250ad1f7a494fc3153729c0dc3d
