### ISSUE TITLE
itc.ua

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#132]
```adb
https://itc.ua/ua/articles/oglyad-msi-clutch-gm51-ta-gm51-wireless-igrovi-myshi-z-chudovoyu-ergonomikoyu-rgb-pidsvichuvannyam-i-maksymalnoyu-rozdilnoyu-zdatnistyu-26-000-dpi/
```

<details>
<summary>Screen</summary>

![2023-03-15_174845](https://user-images.githubusercontent.com/111344219/225366157-50967712-c170-4996-83df-935f789ae268.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/c1e9db41ab0caee30dd3ba6e1b224fa8ca63101f

**Comment by dportvine** [comment]
`https://itc.ua/ua/novini/samsung-anonsuvala-galaxy-a54-za-19-999-galaxy-s23-dlya-narodu/`

<details>
<summary>Screen</summary>

![2023-03-15_210659](https://user-images.githubusercontent.com/111344219/225416979-6a75bbd6-4225-4bb5-b6b5-c07bccabaab9.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/2b4ead7b96ec187001afb7559610cf34b0e56536

**Comment by dportvine** [comment]
`https://itc.ua/ua/novini/fedorov-abo-ty-rozbereshsya-zi-shtuchnym-intelektom-abo-vin-zaminyt-tebe/`

<details>
<summary>Screen</summary>

![2023-04-23_183744](https://user-images.githubusercontent.com/111344219/233849607-98297eb9-75c0-41a2-98db-71db51f5af65.png)
</details>

**Comment by dportvine** [comment]
```
https://itc.ua/ua/articles/oglyad-aser-aspire-c24-1300-ekonomnyj-zruchnyj-ergonomichnyj-komp-yuter-dlya-domu-ta-ofisu/
```

<details>
<summary>Screen</summary>

![2023-10-24_173046](https://github.com/easylist/ruadlist/assets/111344219/8fb9995e-946b-4880-9e16-a30a2bc5804b)
![2023-10-24_173017](https://github.com/easylist/ruadlist/assets/111344219/a7034942-dcc1-468c-829b-d190e26ff1ba)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/4eb4647d7401a348922dc39a40e1235b27b7f622
