### ISSUE TITLE
kolo.news

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#133]
`https://kolo.news/category/suspilstvo/34370`

<details>
<summary>Screen</summary>

![2023-03-18_203736](https://user-images.githubusercontent.com/111344219/226129558-61baff01-c872-4e86-a9fa-e7fde741d0e5.png)
![2023-03-18_203759](https://user-images.githubusercontent.com/111344219/226129563-d9e322f3-78ad-4d79-8443-a69a0b3f4a6a.png)
![2023-03-18_203821](https://user-images.githubusercontent.com/111344219/226129569-803d484e-7b4b-4b1d-aedb-e828217c81bc.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/c54ae51f1d780eeac901576bd8b515fddc378b50

**Comment by dportvine** [comment]
`https://kolo.news/category/suspilstvo/34370`

<details>
<summary>Screen</summary>

![2023-06-16_111918](https://github.com/easylist/ruadlist/assets/111344219/2763a848-7d23-4574-9e47-9e7a355d6dce)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/2fb9e0cb4e8a929cf5f208e23aa2859a421484de
