### ISSUE TITLE
gagadget.com

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#134]
```adb
https://gagadget.com/uk/226742-anons-blizko-xiaomi-pochala-tizeriti-vikhid-smartfona-redmi-note-12-turbo-z-chipom-snapdragon-7-gen-2/
```

<details>
<summary>Screen</summary>

![2023-03-20_091243](https://user-images.githubusercontent.com/111344219/226271431-6ea808f4-d12a-477f-b0a0-0eb1c0ffc2af.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/85b2944bb477b8b779e7d247bdbc73457b468ccc
