### ISSUE TITLE
kinovasek.org

### ISSUE THREAD

**Issue by eporubin** [easylist/ruadlist#135]
Hi, could you please block this ads on `https://mp4.kinovasek.org/`
This filters hides it: 
`##div[style*="padding: unset"]`
<details>
<summary>Screen</summary>

![image](https://user-images.githubusercontent.com/33602691/226598180-8aafa0b6-d893-4266-8b0a-e07907354b9c.png)

</details>

I am using ABP Chrome extension.

**Comment by dimisa-RUAdList** [comment]
I don't see any ads on this site, even with Adblock Plus disabled.

Perhaps this ad appears only when using a certain geolocation. Or, the condition for the appearance of advertising is the presence of some markers in the address bar.

Please indicate the geolocation and the exact link of the page.

**Comment by eporubin** [comment]
I was with USA VPN then I have checked it yesterday, yet today I tried to reproduce and could not as well. Maybe it was removed. 
Thanks for looking into it @dimisa-RUAdList.
