### ISSUE TITLE
rau.ua

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#136]
`https://rau.ua/personalii/miroslava-trandash-talentor/`

<details>
<summary>Screen</summary>

![2023-03-21_173658](https://user-images.githubusercontent.com/111344219/226659660-ce3b2900-35f5-4b7c-859c-65b13c64eb98.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/f4eee904ca15cb32d445048899f9e04d0022aefc

**Comment by dportvine** [comment]
`https://rau.ua/`

<details>
<summary>Screen</summary>

![2023-06-16_111918](https://github.com/easylist/ruadlist/assets/111344219/0fa21803-0f3c-4b97-8165-fd7aefad6622)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/8f6216f4055301cf888c378912779b9a0eea720b
