### ISSUE TITLE
pikabu.ru

### ISSUE THREAD

**Issue by Vektor-537** [easylist/ruadlist#138]
pikabu.ru#?#.sidebar-block:-abp-has(> [id] > [id] [id]:empty)
 цей рядок зносить інтерфейс сайту замість панелі з рекламою

<details>
<summary>Screen</summary>

![image](https://user-images.githubusercontent.com/108080424/228182352-08c69bdc-965a-4933-aa1c-5b9e687ca2c4.png)

</details>

без нього

<details>
<summary>Screen</summary>

![image](https://user-images.githubusercontent.com/108080424/228182558-e8044f18-e4cf-4bf6-9367-37583f3def7c.png)

</details>

з ним
також не блокується місце для реклами

<details>
<summary>Screen</summary>

![image](https://user-images.githubusercontent.com/108080424/228183360-84e56e34-a177-46e2-9c1e-ce3365e92ee9.png)

</details>

**Comment by dportvine** [comment]
@Vektor-537 
Обновите фильтры вручную, [исправлено](https://github.com/easylist/ruadlist/commit/abd3da4776880f995f140743e314f50fc0fcd22e#diff-4678692434e861bd0921111ae2d0afe0b9df10888aefd920427539f68d3da868L4380) 12 часов назад

**Comment by dimisa-RUAdList** [comment]
Как это сделать, описано [здесь](https://forums.lanik.us/viewtopic.php?f=102&t=22786).
