### ISSUE TITLE
amedia.online

### ISSUE THREAD

**Issue by ddantondden** [easylist/ruadlist#139]
Вместо сайта черный экран.

**Comment by dimisa-RUAdList** [comment]
Это домен-рецидивист. [Дубль](https://github.com/easylist/ruadlist/issues/123). Ввиду отсутствия на гитхабе [регламента](https://forums.lanik.us/viewtopic.php?t=24280) для подобных обсуждений, рассмотрение этого случая возможно только на официальном [форуме RU AdList](https://forums.lanik.us/viewforum.php?f=102-ru-adlist).
