### ISSUE TITLE
Blocked suggestions

### ISSUE THREAD

**Issue by GOGEN** [easylist/ruadlist#14]
### List the website(s) where you encounter issues with ruadlist filters

* https://yandex.ru/search/?text=gmail&lr=213
* https://yandex.ru/

### Define the problem 

When I enable uBlock Origin with ABP filters enabled (from https://github.com/easylist/ruadlist/blob/master/ruadlist-fixes.user.css#L4615) the site is broken and navigation suggests is blocked. It came with this [commit](https://github.com/easylist/ruadlist/commit/4e13a9674ad341c2b8d6c75ed3404521044b1bf0)

### Screenshot(s) 
Without filters

[file](https://user-images.githubusercontent.com/5768578/112519623-9bef3000-8dab-11eb-9308-602438ad9146.mp4)

With filters

[file](https://user-images.githubusercontent.com/5768578/112519455-72360900-8dab-11eb-8c86-9eefa42293f7.mp4)

**Comment by dimisa-RUAdList** [comment]
Ок, исправлено: https://github.com/easylist/ruadlist/commit/3e9fba6ac09f9a59a763a2f749a030c4a39fe29c
