### ISSUE TITLE
chrome.install-now.com

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#140]
Фейковый сайт, [virustotal](https://www.virustotal.com/gui/file/45ddbfe6877b5cd4376dcfa78b575c6084fe396ae9b8a982c041259e7fa41b46/detection). Сам `install-now.com` похож на пустышку.

`https://www.comss.ru/disqus3/page.php?id=261`
<details>
<summary>Screen</summary>

![IMG_20230328_203510](https://user-images.githubusercontent.com/111344219/228322330-c0446cc3-46e6-419f-8f49-0e77912c2421.png)
</details>

Сюда `https://safebrowsing.google.com/safebrowsing/report_phish/` сообщил.

**Comment by dimisa-RUAdList** [comment]
Ok: https://github.com/easylist/ruadlist/commit/a6857df60f3b649c4cfbdc7c9581287a81ea14a9
