### ISSUE TITLE
uatv.ua

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#141]
`https://uatv.ua/`

<details>
<summary>Screen</summary>

![2023-03-29_145103](https://user-images.githubusercontent.com/111344219/228527043-136600e0-5aea-4839-a3f8-1905df6b3db2.png)
![2023-03-29_145126](https://user-images.githubusercontent.com/111344219/228527057-bec2c6f3-6b45-4b06-989f-bab08ab484fb.png)
![2023-03-29_145143](https://user-images.githubusercontent.com/111344219/228527079-1b64ac5e-9cf9-401a-9589-3146bb48d393.png)
![2023-03-29_145157](https://user-images.githubusercontent.com/111344219/228527100-49e341ea-1210-4cbb-b463-062a13aec028.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/34559c80b2f64cb8eb9199501ba2b4c6db252ad5
