### ISSUE TITLE
starhit.ru

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#143]
`https://www.starhit.ru/story/`

<details>
<summary>Screen</summary>

![2023-04-03_113000](https://user-images.githubusercontent.com/111344219/229455938-91a6c11a-770f-4415-8903-1e355dae339e.png)
![2023-04-03_113023](https://user-images.githubusercontent.com/111344219/229455960-0d45a0e1-8682-4efb-8038-1004ce3be64b.png)
![2023-04-03_113101](https://user-images.githubusercontent.com/111344219/229455973-3e02b55f-790c-4c2e-bcf4-293edc6eb5fd.png)
</details>

А также: `https://mydecor.ru/`, `https://thegirl.ru/`

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/2bbf05a81a189bd9267b36319a8e929679590077

https://github.com/easylist/ruadlist/commit/5647798d22f36e27541d6a8a835d6aab4edd4efa

https://github.com/easylist/ruadlist/commit/13b498454a5ae5fee6ba49e51e4d1725e09e15ba
