### ISSUE TITLE
ebooks.skin

### ISSUE THREAD

**Issue by felippesantos46** [easylist/ruadlist#144]
`https://e.ebooks.skin/`

<details>
<summary>Screen</summary>

<img width="1192" alt="Screenshot 2023-04-04 at 11 26 19" src="https://user-images.githubusercontent.com/65717387/229750691-7a8f23cf-5106-4f89-bf49-92b35288c834.png">
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/f56650f93d4306f37767e8089a16a0ae177b4e57
