### ISSUE TITLE
fakty.com.ua

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#146]
`https://fakty.com.ua/ua/`

Можно убрать автоплей?
<details>
<summary>Screen</summary>

![2023-04-21_113213](https://user-images.githubusercontent.com/111344219/233587541-694c395e-e7d3-46be-8047-bf4d2d8ede36.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/a96694c8485b6b1802446c5c685532c9ca5be5f0
