### ISSUE TITLE
yandex.ru

### ISSUE THREAD

**Issue by Felix14-v2** [easylist/ruadlist#147]
_Ранее сообщалось [здесь](https://github.com/uBlockOrigin/uAssets/issues/17512), отчёт перенаправлен сюда._

### Описание
При попытке скопировать ссылку из результатов поиска или перейти по ней, ссылка моментально заменяется на длиннючий редирект. Крайне неудобное поведение, так как теперь, чтобы скопировать ссылку, приходится обязательно открывать сайт, а само его открытие теперь занимает больше времени:

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/75726196/230768840-fe4c5914-7479-4cac-a140-42ec4d153448.mp4

</details>

При блокировке JavaScript проблема уходит, но это явно не то решение, которым удобно пользоваться.

### Дополнительно
Пример запроса: https://yandex.ru/search/?text=тестовый+запрос
- [X] Проверено без других расширений в чистом профиле браузера

**Comment by dimisa-RUAdList** [comment]
Что это за браузер?

**Comment by Felix14-v2** [comment]
Яндексовский

**Comment by dimisa-RUAdList** [comment]
Мы не тестируем работу блокировки в рекламных браузерах, и это не планируется в будущем. Когда браузер добавляет рекламу на страницы посещаемых сайтов в дополнение к той, что имеется там изначально, предотвращает запуск расширений для блокировки рекламы на своих и партнёрских доменах, осуществляет отслеживание собственными средствами с целью таргетирования рекламы, пытаться противодействовать этому с помощью расширений попросту бесполезно и бессмысленно.

Если проблема повторяется в Google Chrome, то её можно изучить и попробовать исправить. Яндекс ведёт непримиримую борьбу с блокировщиками рекламы и помимо детектирования и последующей обфускации с целью показа рекламы, ещё и мелко гадит. Например, намеренно ломает контекстное меню, вызываемое кликом по трём точкам в правом верхнем углу блоков поисковой выдачи. Так что будет совсем не удивительно, если окажется, что они в своём рекламном браузере при обнаружении блокировщика подменяют прямые ссылки на редирект.

**Comment by Felix14-v2** [comment]
> будет совсем не удивительно, если окажется, что они в своём рекламном браузере при обнаружении блокировщика подменяют прямые ссылки на редирект

Похоже, на этот раз обошлось :)
Хром той же болезнью страдает:
![image](https://user-images.githubusercontent.com/75726196/233700537-c346ee4e-66ee-4d31-b520-9fd673cd6167.png)

**Comment by dimisa-RUAdList** [comment]
В Хроме эта проблема решается при использовании [рекомендуемых настроек uBO](https://forum.ru-board.com/topic.cgi?forum=5&topic=51141&start=0&limit=1&m=3#1). Попробуйте быструю настройку с помощью готового файла конфигурации. Но чтобы всё это взлетело, потребуется отключить все сторонние средства блокировки, анонимизации, приватности, и пр.

Одновременное использование нескольких блокировщиков приводит к тому, что не работает ни один из них. Либо они ломают сайты. Используйте только один блокировщик и согласованные  с ним средства. На вашем скрине видно, что вместе с uBlock Origin также работает AdGuard. Это 100% конфликт.

Для рекламного браузера яндекса стабильного решения нет, но вы можете попробовать минимизировать вред, наносимый этим браузером, установкой [dev-версии uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii) вместо обычной версии и так же использовав готовый файл конфигурации. Судя по отзывам, это единственное известное расширение для блокировки рекламы, способное работать в браузере яндекса более-менее адекватно.

**Comment by Felix14-v2** [comment]
> проблема решается при использовании [рекомендуемых настроек uBO](https://forum.ru-board.com/topic.cgi?forum=5&topic=51141&start=0&limit=1&m=3#1)

Разве это решение? Если есть какой-то ломающий фильтр, то его нужно отловить и исправить. Спасибо за инструкцию, но всё же это обходной путь.

> Но чтобы всё это взлетело, потребуется отключить все сторонние средства блокировки, анонимизации, приватности, и пр

Да нет, спокойно всё завелось :)

> Используйте только один блокировщик и согласованные с ним средства. На вашем скрине видно, что вместе с uBlock Origin также работает AdGuard. Это 100% конфликт.

Я только один и использую, AdGuard полностью отключён. С него я потихоньку свои фильтры перетаскиваю, у меня там их много накопилось.
<details>
 <summary>А на скриншоте иконка SponsorBlock была</summary>

![image](https://user-images.githubusercontent.com/75726196/233737685-408a7e35-82a8-4c09-ba26-849095b33ff3.png)

</details>

> Для рекламного браузера яндекса стабильного решения нет ...
> ... установкой [dev-версии uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii) вместо обычной версии

Да я уже понял, что ябраузер вы всей душой ненавидите, можете не утруждать себя лишними эпитетами. dev-билд у меня и стоит, им и пользуюсь. Да и в данном случае вряд ли браузер виноват – хоть в плане рекламы они действуют очень некрасиво, но раз уж проблема проявилась и в Chrome, то источник её либо в расширении, либо в самом Chromium (в чём я сомневаюсь).

В любом случае, спасибо за наводку, в свободное время ещё посижу, попробую локализовать причину.

**Comment by dimisa-RUAdList** [comment]
Причина не в браузере и не в расширении. И не в каких-то ломающих правилах. Сайт детектирует блокировщик и подменяет прямые ссылки на редирект. Есть всего два пути - отказаться от блокировки рекламы (предотвратив срабатывание детектора), как это делает AdGuard, и получить прямые ссылки, либо заблокировать её рекомендованным решением.

Проблема рекламы на сайтах яндекса появилась не вчера. Её изучению и противодействию команды uBlock Origin, AdGuard, RU AdList - посвятили не один год и в конце концов все пришли к выводу, что для стабильно работающей блокировки следует использовать опциональный способ. В итоге ни один блокировщик с дефолтными настройками не блокирует рекламу на сайтах яндекса без обходного пути, поскольку на дефолтные правила блокировки и их изменения веб-мастера яндекса реагирует молниеносно, делая их бесполезными. Поэтому для любого блокировщика на сайтах яндекса требуется дополнительный костыль в виде ещё одного расширения. Как правило, это менеджер скриптов + загружаемый в него целевой скрипт.

Для Adblock Plus или AdBlock - Tampermonkey + RU AdList JS Fixes, для AdGuard - Tampermonkey + AdGuard Extra, и т.д. Для uBlock Origin я создал возможность обойтись без дополнительных расширений, дабы он выполнял эту задачу собственными силами, нужно лишь подключить дополнительный фильтр, содержащий правила для решения. Это самый простой путь в настоящий момент, пусть и обходной.

Рекомендации наших команд в настоящий момент выглядят так:
[AdBlock](https://helpcenter.getadblock.com/hc/en-us/articles/9738537518483-I-m-seeing-ads-on-Russian-and-Ukrainian-websites)
[AdGuard](https://github.com/AdguardTeam/AdguardFilters/issues/136545#issuecomment-1340655934)
[RU AdList](https://forums.lanik.us/viewtopic.php?f=102&t=23650)
[uBlock Origin](https://github.com/uBlockOrigin/uAssets/issues/16741#issuecomment-1429203870)

К рекламному браузеру яндекса я отношусь абсолютно ровно, но поскольку его технические особенности и фактическое поведение преследуют совершенно очевидную цель, не учитывать это невозможно. 

Что касается вашего скриншота, то я имел ввиду конечно же не иконку в правом верхнем углу, а соответствующую строку в контекстном меню.
<details>
<summary>Screenshot(s)</summary>

![233700537-c346ee4e-66ee-4d31-b520-9fd673cd6167](https://user-images.githubusercontent.com/20126984/233745294-ab2128c0-5861-4564-ac98-3352c944b7c8.png)

</details>

Полагаю, вопрос можно считать освещённым исчерпывающе и если в ближайшие дни не поступит нового фидбека, тикет будет закрыт.
