### ISSUE TITLE
eucargologistic.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/ruadlist#148]
`https://www.eucargologistic.com/video-rastet-grud-i-padaet-libido-10-produktov-kotorye-nelzya-est-muzhchinam/`

The ad placeholder can be hidden with `eucargologistic.com##center:has(ins.adsbygoogle)`. Maybe `eucargologistic.com##center` could work as well, because I don't think anything else gets hidden on the site.

<details>
<summary>Screenshot(s)</summary>

![Screenshot from 2023-04-22 12-54-36](https://user-images.githubusercontent.com/89158249/233797148-bf109435-2521-49be-afae-1d3e6114b7ee.png)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/4c2c160cb59b5015a17f6e072f1a92d89e23c2af
