### ISSUE TITLE
ua-vestnik.com

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#149]
`https://ua-vestnik.com/zdorovya/kardiolog-nazvav-neochevidni-simptomi-porushenogo-krovoobigu.html`

<details>
<summary>Screen</summary>

![2023-04-22_222515](https://user-images.githubusercontent.com/111344219/233802980-844bf3aa-3677-4e1b-9fe0-2f036f04ae41.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/888781685ed9121a5b050c4dec083074b2ec41e8
