### ISSUE TITLE
nnews.com.ua

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#150]
`https://nnews.com.ua/meteorytnyj-doshh-lirydy-zasliplyuye-nichne-nebo.html`

<details>
<summary>Screen</summary>

![2023-04-22_222515](https://user-images.githubusercontent.com/111344219/233803257-bcd2e68c-433a-40c2-8b83-648d20d40e37.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/91b71fdcf68a0475fbd903a9ec6ab6abfda7f447
