### ISSUE TITLE
empireg.ru

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#151]
`https://empireg.ru/news-and-updates/5442-the-last-stand-aftermath-2021-pc-repack-ot-rg-gogfan.html`

<details>
<summary>Screen</summary>

![2023-04-24_084800](https://user-images.githubusercontent.com/111344219/233947057-f73ca640-d44f-4ba9-addd-e3a3fbca154d.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/e7aff5f62a975bcfe8334180b2bd345572e9df3a
