### ISSUE TITLE
musiklip.ru

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#152]
`http://musiklip.ru/video/vip/66392/indonezijskie/veni_nur_mau_nangis_lupa_nadanya`

<details>
<summary>Screen</summary>

![2023-04-24_084800](https://user-images.githubusercontent.com/111344219/233948176-0be5accb-92de-4276-a946-5fd0b678d3f2.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/f178a29f82c784ea816b5538a0acada9588effc6

**Comment by dportvine** [comment]
У меня не работает.

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/9e09bc419be76ed9e8defb4cec64ca608c4935b1
