### ISSUE TITLE
oxy.st

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#155]
`https://download.oxy.st/d/ZEHg/2/700f518a4eb250362d49368d44e81c73`

`##.tlg` ~> **BitBlock**

<details>
<summary>Screen</summary>

![2023-04-25_183747](https://user-images.githubusercontent.com/111344219/234329810-54dcfc8c-59f6-4a33-b495-0c11e5073cc8.png)
![2023-04-25_183804](https://user-images.githubusercontent.com/111344219/234329822-4d9a1b58-4ec7-4bd7-addc-3c9ac7a68ddb.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/fdd3930864608806c5553c4bae27283f13b02203
