### ISSUE TITLE
root-nation.com

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#156]
`https://root-nation.com/ua/gadgets-ua/wearables-ua/ua-huawei-watch-ultimate-review/`

<details>
<summary>Screen</summary>

![2023-04-25_191406](https://user-images.githubusercontent.com/111344219/234343565-91d08fab-58be-4167-ae3b-28539e3a0565.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/a4ef84b775033a2728eb5f3f7b9b18a76926a4aa

**Comment by dportvine** [comment]
`https://root-nation.com/ua/news-ua/it-news-ua/ua-qual-snapdragon-8-gen-3/`

<details>
<summary>Screen</summary>

![2023-08-02_195720](https://github.com/easylist/ruadlist/assets/111344219/48e563b1-88cf-49cc-ab20-81218836da73)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/c92c7aeaabefa4e151e613724e75c8f630b847dd

**Comment by dportvine** [comment]
`https://root-nation.com/ua/`

<details>
<summary>Screen</summary>

![2023-08-26_084453](https://github.com/easylist/ruadlist/assets/111344219/e84bcef5-529a-4198-af30-cb83f907dc33)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/b8d41bcdd61ad047d204090aab8bdc509dfc065d

**Comment by dportvine** [comment]
Это правило скрывает лишнее. `root-nation.com##.tdi_89`

`https://root-nation.com/ua/news-ua/it-news-ua/ua-apple-developing-system-iphones-latest-software/`

<details>
<summary>Screen</summary>

![2023-10-17_093026](https://github.com/easylist/ruadlist/assets/111344219/602446fc-3af0-4bf8-bf32-c1b875d67310)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/6acfab8463fddeaeedb72db485cd30de82f1fd8b

**Comment by dportvine** [comment]
Правило скрывает лишнее. `root-nation.com##.td-stretch-content`

`https://root-nation.com/ua/other-ua/tv-ua/ua-samsung-neo-qled-2023-all-about/`

<details>
<summary>Screen</summary>

![2023-10-18_091423](https://github.com/easylist/ruadlist/assets/111344219/62060f3c-2fc0-44b4-9c00-b392e1cdf900)
![2023-10-18_091503](https://github.com/easylist/ruadlist/assets/111344219/39624ae5-8ea5-4484-9738-2d5dcb51765b)
</details>

**Comment by dportvine** [comment]
Правило скрывает лишнее:  `##body.home #tdi_89`

`https://root-nation.com/`

<details>
<summary>Screen</summary>

![2023-10-22_163859](https://github.com/easylist/ruadlist/assets/111344219/1da647a5-2aa5-40ef-a6e5-c4f49fcfc118)
</details>

Огрызок.

`https://root-nation.com/ua/articles-ua/windows-ua/ua-password-protect-folder-windows-11/`

<details>
<summary>Screen</summary>

![2023-10-22_163948](https://github.com/easylist/ruadlist/assets/111344219/eebbb5bb-0754-42a6-a67c-179140d12872)
</details>


Правило скрывает фрейм ютуба: `root-nation.com##+js(remove-node-text, style, /body[\s]{1}{[\s][\t][\t]*background-color:|body{background-color:/)`

<details>
<summary>Screen</summary>

![2023-10-22_164526](https://github.com/easylist/ruadlist/assets/111344219/1fb2fd28-6cc0-472b-a2b3-49e3fcfa6a2c)
</details>

**Comment by dimisa-RUAdList** [comment]
Ложное скрытие и пустое место - ок:
https://github.com/easylist/ruadlist/commit/7e18721e8b35b6ac05fde72f04585deb9bdbce36
https://github.com/easylist/ruadlist/commit/8ebc69d2fb69cf9b8b2455423870998191451c4b

А `remove-node-text` ещё требуется? Вроде и без него всё нормально работает. Удалил пока:
https://github.com/easylist/ruadlist/commit/64730a6fa08bf5561b004b2bc90bb1990b3b5839

**Comment by dportvine** [comment]
>А remove-node-text ещё требуется? Вроде и без него всё нормально работает.

Проблему которую он решал, может наблюдаться только в **Firefox**. Вот пускай **Mozilla** и решает свои проблемы.

**Comment by dimisa-RUAdList** [comment]
Да, я помню. И проверял именно в Firefox. Но то ли поправили в самом браузере, то ли  что-то поменялось в инжектировании стилей в uBO, но того мелькания фона, которое наблюдалось ранее, я не заметил.

**Comment by dportvine** [comment]
Пустое место от рекламы.

`https://root-nation.com/ua/soft-ua/web-services-ua/ua-midjourney-images-ai-review/`

<details>
<summary>Screen</summary>

![2023-10-24_165520](https://github.com/easylist/ruadlist/assets/111344219/df32351f-b6ab-4929-a77c-29a82d009f1b)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/d664b813c256dd86a1b6eb4c8f689c0042d36472
