### ISSUE TITLE
ukrfootball.ua

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#159]
`https://ukrfootball.ua/category/natsyonalna/`

<details>
<summary>Screen</summary>

![2023-04-25_191406](https://user-images.githubusercontent.com/111344219/234349142-c83e07e0-704d-45d3-8172-a6098f755798.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/58c9ba4bf5861703558142e4358ab9c496bed00d
