### ISSUE TITLE
ukranews.com

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#160]
`https://ukranews.com/`

<details>
<summary>Screen</summary>

![2023-04-27_113200](https://user-images.githubusercontent.com/111344219/234806072-fb64c6e7-c857-4900-9a65-29f9e986a654.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/f9834806c82ad1d2b70649aaacb78b9a685780cd
