### ISSUE TITLE
ostro.org

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#161]
`https://www.ostro.org/news/unaslidok-vybuhu-v-melitopoli-pomer-politsejskyj-kolaborant-mishhenko-i416187`

<details>
<summary>Screen</summary>

![2023-04-27_113200](https://user-images.githubusercontent.com/111344219/234807691-c6bf27c0-733a-4daa-a066-d76e95d2677b.png)
![2023-04-27_113851](https://user-images.githubusercontent.com/111344219/234807724-c8588aee-9200-48cc-b2cc-501b8237056a.png)
![2023-04-27_113810](https://user-images.githubusercontent.com/111344219/234807758-85ee683a-4984-4d89-b24f-958653e3a35a.png)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/b7af183c80c9ca3bd6fb802df0a4044c366388ef
