### ISSUE TITLE
Ложноположительный блок страницы на stopgame.ru

### ISSUE THREAD

**Issue by dotterian** [easylist/ruadlist#163]
**Ссылка:**
https://stopgame.ru/newsdata/58024/tizer_trailer_seriala_po_twisted_metal

**Что происходит:**
При переходе с включенным RuAdList запрос блокируется.
При переходе без RuAdList — новость открывается.

Ничего особенного в url не вижу, такой же, как и все остальные url всех остальных новостей.

**Comment by dimisa-RUAdList** [comment]
Проблемы этого домена обсуждаются здесь: https://github.com/easylist/ruadlist/issues/61

P.S. Из сообщения непонятно, как воспроизвести проблему.
