### ISSUE TITLE
yandex.ru/games

### ISSUE THREAD

**Issue by PhoenixIndigo** [easylist/ruadlist#166]
`https://yandex.ru/games/app/208377`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://user-images.githubusercontent.com/107413021/235371873-2f78097c-29ad-454e-ac85-978e07bec511.png)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/55d6aba0e093ec9292fca7ef9990c0d4ac442b9a
