### ISSUE TITLE
small-games.info

### ISSUE THREAD

**Issue by VladislavMaksimov** [easylist/ruadlist#167]
Добрый день.

Недавно сайт был внесён за [рецидив](https://forums.lanik.us/viewtopic.php?t=48087-small-games-info) в список блокировок. Администрация сайта уже знает об этом, и надеюсь, что она уберёт кнопки и свяжется с вами. Но как пользователь, давно знакомый с сайтом, я бы хотел немного поадвокатствовать, потому что не считаю случившееся рецидивом.

Вы пишете, что предупреждали администрацию SGi о кнопках, которые продвигают вредоносное ПО, в 2018 году, т.е. 5 лет назад:
![image](https://user-images.githubusercontent.com/46715602/235455437-97e216b0-bb1e-4573-944c-542b2cf2d4cf.png)

Скорее всего, это предупреждение получали не те люди, которые сейчас админят сайт, потому что активные администраторы с годами менялись. Создатель сайта им и вовсе давно не занимается.

Те, кто администрирует сайт сейчас, явно не имеют доступа к кодовой базе или не умеют с ней работать. Они практически ничего не добавляют и не меняют на сайте. При этом там нет множества важнейших функций, вроде смены пароля или удаления аккаунта. Часть разделов вовсе недоступна: например, если попробовать перейти на форум, то появится ошибка, потому что форума много лет уже нет; если зайти в [FAQ / Общение](https://small-games.info/?go=faq) и нажать на ссылку "Быстрый переход: [к коментариям пользователей](https://small-games.info/?go=faq#comment_list)" - ничего не откроется. Я сам тестил апиху для [пет-проекта](https://github.com/VladislavMaksimov/sgi-hacker-tools), и по итогам этого админы не закрывали найденные мной уязвимости и не убирали последствия тестов, хотя это делается простейшим SQL-запросом. По-видимому, если нужно что-то простое добавить или срочно пофиксить - дёргают создателя сайта.

Я почекал по [веб-архиву](http://web.archive.org/web/20150715000000*/http://small-games.info/?go=game&c=42&i=8754) кнопки, на которые была жалоба на форуме. Они появились примерно в конце 2014 - начале 2015 года и оставались с тех времён по сегодняшний день, при этом в разных снапшотах урл, на который перебрасывают кнопки, разный. Они подтягиваются вместе с остальным контентом страницы с домена small-games, но это вообще характерно для сайта: там очень умеренный AJAX, основная часть контента собирается пыхой на бэке (всё-таки SGi создавался в 2008 году как пет-проект одного чувака). Видимо, бэк просто подтягивает со стороннего сервиса эти кнопки и добавляет в структуру веб-страницы, которую отдаёт юзеру. А именно сторонний сервис постоянно меняет урлы на новые зеркала, чтобы обходить блокировки. В то, что создатель сайта постоянно вручную меняет урлы, почти не изменяя ничего другого на сайте, мне не верится.

Согласен с тем, что кнопки нужно удалить, но не согласен с тем, что это "рецидив", поскольку речь здесь явно не о злом умысле, а о проблемах поддержки древнего сайта. Да, 8 лет назад не стоило эти кнопки добавлять, но считаю, что сейчас было бы правильнее договориться с администрацией об их удалении, а не блокировать сайт сразу. Тем более, что SGi важен не только с точки зрения доступа к играм: у него есть устоявшееся сообщество и значимость с т.з. цифровой презервации (там много описаний / скринов / видео игр, которых сейчас нигде не найти + комменты к ним).

**Comment by VladislavMaksimov** [comment]
> Отсутствие каких-то необычайных навыков не требуется, когда нужно изменить один символ в имени класса, чтобы он перестал попадать под блокировку. Именно это они и сделали, и мотив этого действия прозрачен и очевиден - вывод из-под блокировки вредоносного ПО. Ротации адсерверов оффера зафиксировано не было, так что ответственность за обход блокировщика полностью на стороне ресурса.

Хмм, не знал, что по классам блокируется. Думал, какой-нибудь регуляркой, которая матчит урл.

Но, в общем, понятно, спасибо 😕

**Comment by VladislavMaksimov** [comment]
Администрация в итоге поменяла кнопки на баннер: вот [страница](https://small-games.info/?go=game&c=13&i=21324) для примера. Хотели через форум Адблока связаться, но там какая-то верификация аккаунта пока идёт, поэтому попросили меня написать.

![image](https://github.com/easylist/ruadlist/assets/46715602/b7170dc0-f3b2-493a-8c70-f608b04bcbf7)

**Comment by dimisa-RUAdList** [comment]
Сообщение на форуме благополучно было ими размещено, как и ответ на него: https://forums.lanik.us/viewtopic.php?t=48087-small-games-info
