### ISSUE TITLE
24h.tv

### ISSUE THREAD

**Issue by PhoenixIndigo** [easylist/ruadlist#168]
`https://24h.tv/channels/1hd`
Просмотр разрешён в россии
<details>
<summary>Screenshot(s)</summary>

![](https://user-images.githubusercontent.com/107413021/235521454-e86a8699-1f7a-434c-a466-a2d2085d5444.png)

</details>

**Comment by PhoenixIndigo** [comment]
Другие проблемы
`https://24h.freshdesk.com/support/tickets/public/551b564931bff21907e46350a9458bde7b2f641f110dab96056891d908915f7e`

**Comment by dimisa-RUAdList** [comment]
В чём суть других проблем? Приложенный к обращению в тех.поддержку скрин без аккаунта недоступен.

**Comment by PhoenixIndigo** [comment]
Как описано так и есть, там полный экран с панелями

**Comment by dimisa-RUAdList** [comment]
Где там? Что за панели?

**Comment by PhoenixIndigo** [comment]
Там это где описано, панели управления, канал, и возрастное ограничение торчат постоянно в фуллскрине.

**Comment by PhoenixIndigo** [comment]
Там это где фуллскрин, панели управления, канал, и возрастное ограничение, торчат постоянно в фуллскрине.

**Comment by PhoenixIndigo** [comment]
![изображение](https://user-images.githubusercontent.com/107413021/235533158-1d8cf750-de6f-44cb-bc02-05ad1e005b56.png)

**Comment by dimisa-RUAdList** [comment]
Без аккаунта я вижу там только миниатюру 16+ в левом верхнем углу, которая пропадает через несколько секунд после старта плеера, и крестик от поломанного оверлейного промо, на которое вы жаловались изначально. С аккаунтом там ещё какие-то панели?

**Comment by PhoenixIndigo** [comment]
На картинке в полноэкранном режиме же всё остаётся не убираясь, как видно на снимке, всё же понятно. Аккаунта нет, там по номеру аккаунты.
<details>
<summary>Screenshot(s)</summary>

![изображение](https://user-images.githubusercontent.com/107413021/235533158-1d8cf750-de6f-44cb-bc02-05ad1e005b56.png)

</details>

**Comment by PhoenixIndigo** [comment]
Попробуйте ещё перемотать, переходит на страницу `https://24h.tv/channels/1hd#packets`

**Comment by PhoenixIndigo** [comment]
И крестик не от поломанного оверлейного промо, вероятно он мог бы закрывать канал

**Comment by dimisa-RUAdList** [comment]
Перемотка там является платной пакетной функцией, о чём они явным образом сообщают при попытке ей воспользоваться. В актуальных стабильных версиях хрома и фокса миниатюра 16+ в полноэкранном режиме у меня пропадает. Честно говоря, я вижу там слишком много отсылок на функции, завязанные на наличие аккаунта, а также функций, которые поломаны. Поэтому попытки убрать оверлейное промо или прибить гвоздями то, что сейчас не работает, могут дать ложные блокировки после того, как поломки устранят. Думаю, лучше не трогать, пока они не наведут там порядок.

**Comment by PhoenixIndigo** [comment]
А у меня в лисе не пропадает даже без блока, попробую чистый профиль

**Comment by PhoenixIndigo** [comment]
Проблема только в лисе

**Comment by PhoenixIndigo** [comment]
Миниатюра и у меня исчезает в окне. А что там с фуллскрином в лисе?

**Comment by dimisa-RUAdList** [comment]
К сожалению, этот браузер из-за своей [малой распространённости](https://www.similarweb.com/ru/browsers/worldwide/desktop/) не пользуется популярностью у веб-мастеров при отладке. Я довольно часто встречаю косяки разработчиков, связанные именно с этим. Попробуйте в полноэкранном режиме опустить курсор в самый низ левого или правого угла, должно получиться.

**Comment by PhoenixIndigo** [comment]
Спасибо! А стартовую всплывашку в бит не сунете?

**Comment by dimisa-RUAdList** [comment]
Блин, у этих notify слишком много отсылок на функции авторизированных юзеров, можно запросто поломать там что-то. По идее, после того как веб-мастер починит функционал оверлея, у него должна появиться кнопка закрытия, а сам факт закрытия должен сохраняться в куки. Поэтому я бы не трогал до исправлений.

**Comment by PhoenixIndigo** [comment]
Там закрывает ссылка Не сейчас

**Comment by PhoenixIndigo** [comment]
? - ##.notify-enter-done.is_freshdesk.notify_may_optimal.notify

**Comment by PhoenixIndigo** [comment]
Так кукушки удаляются, а исключать каждый сайт тогда зачем?

**Comment by dimisa-RUAdList** [comment]
Не, нужно ждать фиксов. Они вполне могут сопровождаться блокировкой прокрутки и кликов, и тогда юзеры тупо получат статичную картинку без возможности сделать на ней хоть что-то.

**Comment by PhoenixIndigo** [comment]
Да с чего такое мнение как на снимке всё работает с блокировкой. https://github.com/AdguardTeam/AdguardFilters/issues/149891

**Comment by PhoenixIndigo** [comment]
А Esc переводит на заднюю страницу.

**Comment by dimisa-RUAdList** [comment]
Функционал сайта явно поломан и очевидно будет чиниться. Риск поломать сиюминутными правилами тот вариант, который будет реализован после исправлений, весьма высок. Поэтому правила, если это потребуется, будут добавлены только после исправлений.

**Comment by PhoenixIndigo** [comment]
Тогда ждёмс

**Comment by PhoenixIndigo** [comment]
А крестик работает, только переводит на заднюю страницу

**Comment by dimisa-RUAdList** [comment]
Ваша заявка в тех.поддержку имеет статус "Обрабатывается". Когда действия по ней закончатся, при неизменности макета безопасно можно использовать `24h.tv##.notify_may_optimal`.

**Comment by PhoenixIndigo** [comment]
Так это для маёв только сгодится. Тогда всё ясно.

**Comment by PhoenixIndigo** [comment]
Так это для маёв только сгодится. Надо обобщить.

**Comment by PhoenixIndigo** [comment]
Это глупая затея, уж лучше куками закрыть, чем выскакивающее при обновлении окно! Тема закрыта!

**Comment by PhoenixIndigo** [comment]
С другой стороны такие окна должно закрывать расширение как это планируется в [лисе](https://www.opennet.ru/opennews/art.shtml?num=58999) и сделано в https://addons.mozilla.org/ru/firefox/addon/youtube-nonstop/

**Comment by PhoenixIndigo** [comment]
С другой стороны такие окна должно закрывать расширение, как это планируется в [лисе](https://www.opennet.ru/opennews/art.shtml?num=58999) и сделано в [ytns](https://addons.mozilla.org/ru/firefox/addon/youtube-nonstop/)!
<details><summary>Details</summary>
<p>

[Отобранные](https://addons.mozilla.org/ru/firefox/collections/17366156/My-extensions/?page=1&collection_sort=name) с [Окном](https://user-images.githubusercontent.com/107413021/235808159-72d29537-f43f-4047-b29c-43a9caebf0f0.png)

</p>
</details>

**Comment by PhoenixIndigo** [comment]
> @Alex-302
> Заменил немелькающим.
> В куки фигурирует месяц, так что не особо подходит этот способ.
> Вротой простой вариант - автоклик по кнопке. Мигнёт только при первом посещении.
https://github.com/AdguardTeam/AdguardFilters/commit/ec9bb375d29ff64dfe861394ee95df34055b8958

**Comment by dimisa-RUAdList** [comment]
Я правильно понимаю, что вопрос можно закрывать?
