### ISSUE TITLE
wp.pl - blocked video

### ISSUE THREAD

**Issue by seba2282** [easylist/ruadlist#17]
All videos are blocked on wp.pl.

Possible fixes:
`@@||wideo.wp.pl^$script,domain=wideo.wp.pl`  or write as `domain=~wp.pl`

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/29dac1dcfb52e4b25e768a4583b3bb549aa83dd3
