### ISSUE TITLE
aviasales.ua

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#170]
`https://www.aviasales.ua/`

При поиске билета, происходит редирект в предыдущей вкладке. Галочка малозаметная и в результате, человек получает рекаму. Результат зависит от запроса. [Gif](https://imgur.com/a/hWnY0Jr) 

<details>
<summary>Screen</summary>

![2023-05-05_101219](https://user-images.githubusercontent.com/111344219/236398642-5ba77455-3ea6-4d0f-83a2-51f21069006d.png)
![2023-05-05_103442](https://user-images.githubusercontent.com/111344219/236401010-9888dda9-36f6-44d3-96d9-ee20f8ec20fc.png)
</details>

**Comment by dimisa-RUAdList** [comment]
Это вроде как сервис. Они предоставляют поиск как билетов, так и отелей. Чтобы пользователю не искать дважды, первый запрос дублируется по обоим базам. Далее галочка снимается автоматически. Вероятно, можно найти способ снять её изначально, но риск поломать при этом что-то достаточно велик, лучше не трогать.

Для скрытия анонсов отелей в поиске билетов нужна ссылка поискового запроса.

Кстати, плашка куки: https://github.com/easylist/easylist/pull/15159/commits/d9fb07feb65047b1afd47a11157aedbf09e46214#diff-4e630449ee8c285ce1e1a54e699dbbd85e3e3466f3c6afebb87699cd01a51d07R2403 там имеет рандомное имя.

Её можно скрыть по положению: `www.aviasales.ru,www.aviasales.kg,www.aviasales.uz,www.aviasales.kz,www.aviasales.ua,www.aviasales.by##body > .footer ~ [src^="https://pay.google.com/"] + div[class]`

**Comment by dportvine** [comment]
Сообщил `https://github.com/easylist/easylist/issues/15851`
