### ISSUE TITLE
drive2.ru

### ISSUE THREAD

**Issue by eporubin** [easylist/ruadlist#171]
Hi, could you please check out `https://www.drive2.ru/`
There are lots of ads on the page:

- on this [page ](https://www.drive2.ru/l/3216103/?)the top banner with ads can be removed with the filter `drive2.ru##.dv-post-header`

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/33602691/236792920-b6796970-11aa-478e-be4d-b2c676d0386b.png)

</details>

- there are also other ads on the page at the bottom which seems like circumvention  to me so I haven’t been able to find a good filter for it. 

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/33602691/236794378-3c2d7ff7-b00f-4a24-b606-99e7ef170c44.png)
![image](https://user-images.githubusercontent.com/33602691/236794432-1f43abbb-f68c-4091-a15e-cdb3c53853d9.png)

</details>

Using ABP version 3.17 with ABP filters, Easy List, RuAdList +Easy List on Chrome. 
Thank you in advance for checking this out.

**Comment by dimisa-RUAdList** [comment]
This site belongs to the problematic category.
Solution here: https://greasyfork.org/en/scripts/19993-ru-adlist-js-fixes
