### ISSUE TITLE
drive2.ru

### ISSUE THREAD

**Issue by KS1VA** [easylist/ruadlist#172]
Лента на `https://www.drive2.ru/` при включённом фильтре "RU AdList" не отображается.
<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/easylist/ruadlist/assets/11857748/b26a198f-0dc8-4626-81fc-cfec7b6f1543)

</details>

Блокировщик: uBlock Origin 1.49.2
Браузер: Google Chrome Версия 113.0.5672.93

**Comment by dimisa-RUAdList** [comment]
Исправлено: https://github.com/easylist/ruadlist/commit/6cfa6859b30ae676477949b4f0d6ccaf35b3ba33
