### ISSUE TITLE
nrj.ua

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#174]
`https://nrj.ua/`

<details>
<summary>Screen</summary>

![2023-05-23_102226](https://github.com/easylist/ruadlist/assets/111344219/31158705-390e-4d43-99de-7c860692b13d)
</details>

В **ABP** слайдер не работает.

**Comment by dimisa-RUAdList** [comment]
Вообще убрал его: https://github.com/easylist/ruadlist/commit/1406059494c413320bb234cc993e29358e4d8b9d

В нём дубликаты анонсов, перемешанные с рекламой.
