### ISSUE TITLE
yandex.com

### ISSUE THREAD

**Issue by Daxy7** [easylist/ruadlist#178]
Firefox Version 113.0.2 (64-bit), United Kingdom

`https://yandex.com/images/`

Test: 

```
https://avatars.mds.yandex.net/i?id=e67c20f98bdc512c5d3bc20c140f8fac-5719595-images-taas-consumers&n=27&h=384&w=480
```

Using the reverse image search to test, got one-time ads[[1](https://github-production-user-asset-6210df.s3.amazonaws.com/91396482/243166258-2b262833-15cd-48bd-9a5c-272bd3b51ad3.png)][[2](https://github-production-user-asset-6210df.s3.amazonaws.com/91396482/243166186-53cd00a6-2696-40e1-bdaa-170f5de09932.png)] through clicking on the gallery of images or browsing the page and scrolling down.
[Below image, sidebar, inline]

Video:
https://github-production-user-asset-6210df.s3.amazonaws.com/91396482/243165195-24129d5f-ca25-48c3-940a-d37393130d8d.mp4

**Comment by dimisa-RUAdList** [comment]
What blocker are you using?

**Comment by Daxy7** [comment]
uBlock Origin 1.49.2

**Comment by dimisa-RUAdList** [comment]
The rules for this site are contained in [RUS: RU AdList](https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/easylist/ruadlist/master/RuAdList-uBO.txt&title=RU%20AdList%20for%20uBO%20only) and [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters) (left-click to subscribe).

**Comment by Daxy7** [comment]
Ok. `RU AdList: Counters` works
