### ISSUE TITLE
doska.fi

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/ruadlist#18]
Banner near the top, banners on the bottom, and the top menu being shown incorrectly. Example page: `http://www.doska.fi/`. I propose:
```
doska.fi,russian.fi###container + center
doska.fi,russian.fi###centered2
doska.fi,russian.fi###centered_right
doska.fi,russian.fi###centered_left
||russian.fi/include/banners.php^
```

![image](https://user-images.githubusercontent.com/22780683/119782389-6e6a5400-becc-11eb-9081-a6ef0610b57d.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/119783190-47f8e880-becd-11eb-9507-732da8166c54.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.77 x64
- Adblock Extension/version: uBO 1.35.3b5 + I Don't Care About Cookies 3.3.0

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/2688fb22662fdce71fac33bcedc28f337af51078
