### ISSUE TITLE
info-app.ru

### ISSUE THREAD

**Issue by b13f** [easylist/ruadlist#183]
Could you remove this domain from blocklist here https://github.com/easylist/ruadlist/blob/master/advblock/adservers.txt#L2731 ? this is actually not an adserver, but the domain which we are using for partners

**Comment by dimisa-RUAdList** [comment]
Укажите пожалуйста ссылку на страницу с примером, где указанное правило блокирует лишнее.

**Comment by b13f** [comment]
> Укажите пожалуйста ссылку на страницу с примером, где указанное правило блокирует лишнее.

https://zakonguru.com/ вот страница партнёра с виджетом внизу, виджет не работает (телефон для обратного звонка не отправить), потому что использует этот домен

**Comment by dimisa-RUAdList** [comment]
Ваш виджет и не должен работать под блокировщиком. Всё, написанное в отношении [lexprofit](https://forums.lanik.us/viewtopic.php?t=37479), в той же мере касается и вас.
