### ISSUE TITLE
zv.zp.ua

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#185]
`https://zv.zp.ua/fahivci-poperedili-pro-novu-zagrozu-dlja-smartfoniv/`

<details>
<summary>Screen</summary>

![2023-07-02_221212](https://github.com/easylist/ruadlist/assets/111344219/119db54f-83f6-4f4f-bc5e-b1d3e24bbfac)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/522f947660be7c5ab6d75ceb0529d422be0b2321
