### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#186]
`https://www.filmweb.pl/films` 

`/counters^` блокирует лишнее `https://www.filmweb.pl/api/v1/film/527837/counters/locales`

<details>
<summary>Screen</summary>

![2023-07-04_070650](https://github.com/easylist/ruadlist/assets/111344219/dfca06dd-f904-417b-b68a-7ed754e7b191)
![2023-07-04_070747](https://github.com/easylist/ruadlist/assets/111344219/dcb0f993-d26f-4d0f-b88a-73a733ae44cf)
![2023-07-04_070804](https://github.com/easylist/ruadlist/assets/111344219/698df2a9-55cc-4b1a-9580-563bead8bc96)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/673e7f067f42b07a4a920b6ec8b6ac0251fe804b
