### ISSUE TITLE
pohoronnoe-byuro.com

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#187]
`http://pohoronnoe-byuro.com/` `https://ucoz.getinstant.website/?ze=hbrdinjsgy5ha3ddf42dkojs`

<details>
<summary>Screen</summary>

![2023-07-05_093806](https://github.com/easylist/ruadlist/assets/111344219/fd634ba7-14d4-424b-ace3-39ccda9a3d00)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/237ab7d0ae2a238a3b9c865db53f874d3d64bc44
