### ISSUE TITLE
Блокировка скрипта AB-тестов - exp.js

### ISSUE THREAD

**Issue by Firnis** [easylist/ruadlist#188]
Привет!
Вы заблокировали abt.s3.yandex.net/expjs/latest/exp.js (https://github.com/easylist/ruadlist/commit/a9cb43c5a88ede4c76f6812430c5145b3c9212d0#diff-b388d33807295d76f10e02af371df6a13ce1b1218682728c4083964d83a52149R235)

Этот скрипт не является трекером и не отслеживает действия пользователя.
Он применяет A/B эксперименты к странице.

Его блокировка ломает поведение сайтов, которые запускают эксперименты.

Скрипт отправляет один сетевой зарос к uaas.yandex.ru. Передаёт адрес страницы и идентификатор выборки эксперимента, в которую попал пользователь.
Адрес страницы нужен, так как клиент может в эксперименте настроить фильтр по страницам.

Подробнее про эксперименты можно почитать тут https://yandex.ru/support/varioqub/index.html

Если этой информации недостаточно для удаления его из списка, то дайте, пожалуйста, знать чего не хватает.

**Comment by dimisa-RUAdList** [comment]
Укажите пожалуйста ссылку на конкретную страницу, где наблюдается поломка.

**Comment by Firnis** [comment]
https://myfitkit.ru/
Отображается 2 меню в шапке.
На этом сайте, в зависимости от выборки, скрывается одно из меню. Из-за блокировки expjs этого не происходит.

**Comment by dimisa-RUAdList** [comment]
Похоже на частный случай. Есть другие примеры? Этот скрипт блокируется не только экпериментальным фильтром Counters, который подключается исключительно вручную, и которым пользуются единицы, но и любым регулярным антитрекинговым фильтром, вроде [AdGuard Tracking Protection filter](https://filters.adtidy.org/extension/chromium/filters/3.txt), которыми пользуются миллионы, и для их активации которых достаточно просто поставить галочку в блокировщике. Кстати, `uaas.yandex.ru` там блокируется тоже. Так что эта проблема не решится, даже если убрать блокировку скрипта.

**Comment by dimisa-RUAdList** [comment]
Проблема перестала повторяться.
