### ISSUE TITLE
yandex.com

### ISSUE THREAD

**Issue by fromanywhere** [easylist/ruadlist#189]
Добрый день, в https://easylist-downloads.adblockplus.org/cntblock.txt прилетело правило `yandex.com##.serp-list .Root[id]`

Режутся врезки, например, по запросу `https://yandex.com/search/?text=rrhfcyjt+gkfnmt&lr=0`

<details>
<summary>Screenshot(s)</summary>

<img width="1929" alt="image" src="https://github.com/easylist/ruadlist/assets/1042969/fd0554e1-143e-403e-97ac-b97a9675451a">

Вырезанное 
![telegram-cloud-photo-size-2-5314646129423534974-y](https://github.com/easylist/ruadlist/assets/1042969/db86a1bb-2d1f-4d01-8288-f31a45496a50)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/f95b83012f455f60dc21033651887858d785a8aa
