### ISSUE TITLE
ufchgu.ru

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#190]
`https://ufchgu.ru/blog/kak-proverit-hesh-summu-fajla-v-linux-podrobnaja`

<details>
<summary>Screen</summary>

![2023-07-28_083629](https://github.com/easylist/ruadlist/assets/111344219/2979f891-7629-4e65-be0e-c78752393116)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/e1ac1f7e83fbd03e6d110c3c21ff8dbcee5d78d6

**Comment by dportvine** [comment]
Там еще источник добавляет при копировании.

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/de12bbe2ed06baceb83e86d93b0a8a5a2d149ebc
