### ISSUE TITLE
irtafax.com.ua

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#192]
`http://irtafax.com.ua/news/2023/07/2023-07-31-19.html`

<details>
<summary>Screen</summary>

![2023-07-31_220711](https://github.com/easylist/ruadlist/assets/111344219/381eec82-0fd2-494e-b680-37d60469882f)
![2023-07-31_220749](https://github.com/easylist/ruadlist/assets/111344219/92834898-4503-4c49-8203-c72826d536e0)
![2023-07-31_220813](https://github.com/easylist/ruadlist/assets/111344219/149d42de-1358-41d5-a0d4-a1465debab8d)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/ce6e6573f8429f79c54adde46a731c1644a70924
