### ISSUE TITLE
Ads container on `akkordam.ru`

### ISSUE THREAD

**Issue by eporubin** [easylist/ruadlist#193]
Hi could you please check this domain: `https://akkordam.ru/` there is a left over container from the ads, which can be hidden with this filter `akkordam.ru##.k-container` 

<details>
<summary>Screenshot(s)</summary>

<img width="1245" alt="image" src="https://github.com/easylist/ruadlist/assets/33602691/1d9dcf5b-5c0d-450e-962a-57e4cac06257">

</details>

Using ABP for Chrome: with ABP filters and RuAdList

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/4e53e2d188bfa12bd262e59122c55daa12dec099

https://github.com/abp-filters/abp-filters-anti-cv/issues/172#issuecomment-1667858758

**Comment by eporubin** [comment]
Cool @dimisa-RUAdList, thanks a lot :)
