### ISSUE TITLE
Radio-Archive.ru

### ISSUE THREAD

**Issue by JasonDeru** [easylist/ruadlist#194]
Adblock Browser, Honor, Android 9
При включении любой радиостанции палит адблок и полностью блокируется работа плеера.

**Comment by dimisa-RUAdList** [comment]
Фильтр RU AdList поддерживается [только для десктопных](https://forums.lanik.us/viewtopic.php?t=22512) браузеров. И я не уверен, что Adblock Browser вообще использует фильтр RU AdList, а не какой-то собственный.

Впрочем, и на десктопной версии сайте срабатывает детектор адблока. Но это не приводит к поломке плеера, просто перед стартом эфира появляется аудио-предупреждение на несколько секунд.

Fix: https://github.com/easylist/ruadlist/commit/324699fb26c74bce9667e200c0c2a16b796d78e9

Возможно, это поможет и Adblock Browser.
