### ISSUE TITLE
growhow.in.ua

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#197]
Рекламный бэкграунд.

```
https://www.growhow.in.ua/actros-vid-cheskoho-vyrobnyka-bednar-kombinovanyy-dysko-lapovyy-kultyvator-vypravdovuie-doviru-ukrainskykh-ahrariiv/
```

<details>
<summary>Screen</summary>

![2023-08-21_153308](https://github.com/easylist/ruadlist/assets/111344219/b56f6e98-6474-409f-8053-5c3459fb1d54)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/4de1de08ad660d72bcd2679ecd27745355dadcec

**Comment by dportvine** [comment]
При переходах и обновлении страницы.

<details>
<summary>Video</summary>

https://github.com/easylist/ruadlist/assets/111344219/851c9ff1-9980-4d5d-8871-1e1771ee7413
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/d5bc398886de6b5c3433ae8e62b493e8b2b0cf18

**Comment by dportvine** [comment]
`https://www.growhow.in.ua/svynyna-podeshevshala-mayzhe-na-4-hryvni/`

Кликабельный бекграунд.

<details>
<summary>Screen</summary>

![2024-10-19_162607](https://github.com/user-attachments/assets/6aa16aca-44a4-466e-822b-23424996d6b6)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/d2083abe4987b72bed1373e28285fcf26c8fa554
and https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/issues/165
