### ISSUE TITLE
chronicles.pro

### ISSUE THREAD

**Issue by P0Rtvine** [easylist/ruadlist#2]
### Перечислите веб-сайт(ы), с которым(и) у вас возникли проблемы:

`https://chronicles.pro/ru/crime/moshenniki-v-ukraine-predlagayut-dobrovol-no-ustanovit-v-telefon-virus`

### Что происходит?

Рекламные баннеры.

![2020-10-06_195148](https://user-images.githubusercontent.com/57287308/95234259-0f0ce600-080e-11eb-9c43-ecb4c23d7b5a.png)
![2020-10-06_195333](https://user-images.githubusercontent.com/57287308/95234309-1207d680-080e-11eb-9010-a8fa141bf0c5.png)
![2020-10-06_195403](https://user-images.githubusercontent.com/57287308/95234336-13d19a00-080e-11eb-9237-8ef17062308c.png)

### Список используемых вами подписок:
![2020-10-06_200541](https://user-images.githubusercontent.com/57287308/95236290-68c1e000-080f-11eb-858f-43e5d3dbeb6b.png)

### Ваши настройки

- ОС/версия: Win 8.1 x64
- Браузер/версия: Opera|Stable(85.0.4183.121)
- Расширение/Adblock|uBO: uBO 1.30.0

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/bff7ba3c20634d3b3151ddc95c0fa7125a0195a0
