### ISSUE TITLE
*.xyz domain is blocked when doing a request from *.github.io

### ISSUE THREAD

**Issue by ENT8R** [easylist/ruadlist#20]
https://github.com/easylist/ruadlist/blob/bad81acd021be625235fb2b1435d803c192ddbb6/advblock/first_level.txt#L16

This rule blocks all requests to a domain with the `*.xyz` TLD. While I don't necessarily see the reasoning behind it, I saw that it is already excluded for certain domains (i.e. `herokuapp.com` and `web.app`).
I would therefore like to request to add <b>`github.io`</b> to the list of excluded domains as this domain belongs to a service which allows its users to host their own content, similar to Heroku (`herokuapp.com`) or Google Firebase (`web.app`).

**Comment by dimisa-RUAdList** [comment]
Ok: https://github.com/easylist/ruadlist/commit/39e201b6d93aff821c1c9fe1d2613906a45b39fa

**Comment by ENT8R** [comment]
Wow, that was fast! Thank you very much 🎉

**Comment by T1MOXA** [comment]
Same with api.sdev.xyz
POST https://api.sdev.xyz/adamitebot/v1/quitChannel net::ERR_BLOCKED_BY_CLIENT

**Comment by dimisa-RUAdList** [comment]
How can this be repeated?

**Comment by T1MOXA** [comment]
> How can this be repeated?

https://adamite.xyz/panel/
![image](https://user-images.githubusercontent.com/19938629/122972749-263e3480-d399-11eb-9ad2-d2b952251390.png)

**Comment by dimisa-RUAdList** [comment]
Impossible to check without a test account. Please create a topic [here](https://forums.lanik.us/viewforum.php?f=102) ([rules](https://forums.lanik.us/viewtopic.php?f=102&t=24280)).
