### ISSUE TITLE
obukhiv.info

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#200]
#### Описание проблемы (Description of the problem):

Пустые места от рекламы.

`https://obukhiv.info/news/vazhlivi-roboti-v-sadu-pislya-zboru-vrozhaiu-obrobka-yablun/`

<details>
<summary>Screenshot(s)</summary>

![2023-08-24_104348](https://github.com/easylist/ruadlist/assets/111344219/a2f1e751-9008-4894-9c63-ffb15133bb86)
![2023-08-24_104412](https://github.com/easylist/ruadlist/assets/111344219/6438d70c-2996-43d8-a4cd-85ce33b885a4)
![2023-08-24_104427](https://github.com/easylist/ruadlist/assets/111344219/825d035a-6b56-41df-b0fc-ed77748df2a1)
</details>

#### Конфигурация (Configuration):

- OS/version: Windows 10 22H2 x64
- Browser/version: Google Chrome 116.0.5845.111
- Ad block extension/version: uBO 1.51.0

#### Используемые фильтры (Used filters):

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 114196
 cosmetic: 128344
 scriptlet: 25925
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 26441-18, now
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1640-25, now
  https://www.awwwwesome.org/url-blocklist/url-blocklist.txt: 783-0, now
  fanboy-cookiemonster: 48203-416, now
  ublock-annoyances: 5385-61, now
  ublock-cookies-easylist: 266-266, now
 default:
  user-filters: 0-0, never
  ublock-filters: 34359-42, 1m
  ublock-badware: 7765-0, 1m
  ublock-privacy: 535-7, 1m
  ublock-unbreak: 2116-7, 1m
  ublock-quick-fixes: 283-104, 1m
  easylist: 69640-283, 1m
  easyprivacy: 33308-401, now
  RUS-0: 39748-286, now
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 cacheStorageAPI: indexedDB
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 1374 ms
 maxAssetCacheWait: 739 ms
popupPanel:
 blocked: 4
 network:
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  sinoptik.ua: 1
 extended:
  ##ins.adsbygoogle
  ###SinoptikInformer
```
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/0b654256066212354fc6bd1607197ef972abbe9f
