### ISSUE TITLE
forklog.com

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#215]
#### Описание проблемы (Description of the problem):

Реклама + социалка.

`https://forklog.com/news/sec-obvinila-binance-us-v-nezhelanii-sotrudnichat`

<details>
<summary>Screenshot(s)</summary>

![2023-09-16_100327](https://github.com/easylist/ruadlist/assets/111344219/dcdfa2ab-b191-4f24-ab95-fd939af23480)
![2023-09-16_100247](https://github.com/easylist/ruadlist/assets/111344219/a38eea83-e696-4a87-b04b-6b9547ec99b2)
![2023-09-16_100315](https://github.com/easylist/ruadlist/assets/111344219/c93eb688-2b03-4abb-8f20-0cae5c2ca766)
![2023-09-16_100616](https://github.com/easylist/ruadlist/assets/111344219/bf306b09-f69b-48e9-ae32-7d0d0dc90292)
</details>

#### Конфигурация (Configuration):

- OS/version: Windows 10 22H2
- Browser/version: Google Chrome 117.0.5938.89
- Ad block extension/version: uBO 1.52.0

#### Используемые фильтры (Used filters):

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 117
filterset (summary):
 network: 115228
 cosmetic: 129020
 scriptlet: 26209
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
  urlhaus-1: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 26364-18, 51m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1648-26, 51m
  https://www.awwwwesome.org/url-blocklist/url-blocklist.txt: 788-0, 51m
  fanboy-cookiemonster: 48349-412, 51m
  ublock-annoyances: 5462-61, 51m
  ublock-cookies-easylist: 291-291, 51m
 default:
  user-filters: 0-0, never
  RUS-0: 39929-139, 51m
  easylist: 70894-54, 51m
  easyprivacy: 33255-465, 51m
  ublock-badware: 7984-145, 51m
  ublock-filters: 34635-180, 51m
  ublock-privacy: 558-14, 51m
  ublock-quick-fixes: 160-61, 51m
  ublock-unbreak: 2131-35, 51m
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 921 ms (selfie)
 maxAssetCacheWait: 534 ms
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  jsdelivr.net: 1
 extended:
  ##.footer_socials
  ##.gototop
  ##.share_blk
  ##.terms_popup
  ##div[class^="subscribe_blk"]
```
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/041c815ca97d90ced5fbfb8d749ba4cc6de837c8
