### ISSUE TITLE
actlz.github.io

### ISSUE THREAD

**Issue by actlz** [easylist/ruadlist#22]
Данный скрипт обеспечивает доступность фрейма: `actlz.github.io/actualize.js`

Не могли бы вы повторить https://github.com/easylist/ruadlist/commit/57df2e6da2dfc7b20705ece1d62eaeee1838c7d6 для всех доменов, где используются не актуальные или недоступные по иным причинам ссылки?

**Comment by dimisa-RUAdList** [comment]
Данный скрипт в течении недели ежедневно использовался для обхода блокировки рекламы космолот, показываемой пользователям с украинской геолокацией. Без его блокировки возникает необходимость резать постоянно создаваемые одноразовые адсервера, что не является эффективным. Если блокировка скрипта где-то приводит к проблемам, они будут решаться точечно, для каждого отдельно указанного случая.

**Comment by actlz** [comment]
Это неправда, скрипт уже 3 месяца не обновлялся и, более того, принципы работы не менялись более долгое время. Для обхода были использованы особенности работы, а не сам скрипт.
Предоставьте ссылку для обнаружения блока. Где будет обнаружен блок будет использован src с актуальным доменом (меняется довольно редко), а в таком фрейме действуют third-party ограничения.
Таким образом не будет сломан скрипт и вам не придётся резать одноразовые адсервера.

**Comment by dimisa-RUAdList** [comment]
В настоящий момент обход адблока с использованием особенностей вашего скрипта наблюдается в 100% случаев его размещения. Именно поэтому он и заблокирован глобально. Единственное достоверно ложное срабатывание было обнаружено на `kindkino.ru`, для которого и было добавлено исключение. Прочие исключения могут быть добавлены только точечно, для каждого отдельно указанного случая. Но не наоборот. Бегать и выявлять все онлайн-кинотеатры, использующие ваш скрипт и добавлять для каждого из них отдельное правило не планируется. Как я уже написал выше, обход адблока наблюдается в 100% случаев.

**Comment by actlz** [comment]
Ломать -- не строить. Откровенно говоря, плохо обнаруживаете ложные срабатывания.
Я предложил изменить скрипт, всё что нужно -- сылка, по которой можно понять, используется ли блок.
> Где будет обнаружен блок будет использован src с актуальным доменом (меняется довольно редко), а в таком фрейме действуют third-party ограничения.

Я могу использовать любую из вашего списка, но нужна постоянная

**Comment by dimisa-RUAdList** [comment]
Мы вообще ничего не обнаруживаем, это делают пользователи. Среди всех блокировщиков, использующих RU AdList, основным игроком является Adblock Plus. Его функционал предусматривает отправку сообщения об ошибках, из которых формируется дайджест репортов. Вот им-то мы и оперируем.

26 июля от украинских пользователей начали поступать жалобы на пропущенную в плеере venom рекламу космолот. За сутки их количество составило несколько сотен. В последующие дни блокируемые адсеревера каждые несколько часов менялись вслед за добавлением правил в фильтры, что продолжалось до 2 августа, когда был заблокирован ваш скрипт. За последние сутки ни одной жалобы на космолот не было. Единственное сообщение о ложном срабатывании, на `kindkino.ru` - пришло в 01:46 3 августа и было исправлено в 03:02 3 августа.

Таким образом, блокировка вашего скрипта видится абсолютно адекватным ответом на агрессивный и намеренный обход адблока. Фактически, код вашего скрипта является уязвимостью, позволяющей практиковать ротацию адсерверов, поскольку с ним реклама грузится не во фрейм балансера, которых немного, а во фрейм онлайн-кинотеатра, коих сотни.

Насколько я понимаю, вы предлагаете самостоятельно детектировать использование адблока и при его обнаружении ограничивать third-party. На фоне произошедших событий это не выглядит удачным решением. Наоборот, сохранять уязвимость, отдавая решение на откуп тех, кто в течении недели намеренно гадил пользователям блокировщиков, представляется совершенно абсурдным.

**Comment by actlz** [comment]
Нет, при обнаружении адблока скрипт будет писать в src фрейма конкретный домен балансера (сейчас это kinogram.best) и "уязвимость", о которой вы говорите, работать не будет. Потому что https://github.com/easylist/ruadlist/blob/master/advblock/specific_special.txt#L42

**Comment by actlz** [comment]
> Единственное сообщение о ложном срабатывании
В том то и дело, что вставка фреймов часто происходит с помощью скриптов, поэтому ни вы, ни пользователи блокировщиков даже не узнают, что что-то пошло не так.

**Comment by dimisa-RUAdList** [comment]
Честно говоря, я бы предпочёл, чтобы "уязвимости" вообще не было. Зачем мне разрешать загрузку скрипта, использование которого привело к "войне правок", длившейся целую неделю? Да ещё без диалога со всеми участниками, её инициировавшими... Те, кто это устроил, никаким экспириенсом в этом случае не обзаведутся. Я до последнего не трогал ваш скрипт, но упёртость в желании показать рекламу пользователям адблока не оставила мне выбора. Сейчас всё работает отлично, жалобы на пропуск рекламы или ложные срабатывания отсутствуют. Проходить ещё раз через подобное у меня желания нет. Причём разрешение скрипта прямо сейчас приведёт как раз к возможности снова практиковать загрузку рекламы с одноразовых адсерверов напрямую во фреймы онлайн-кинотеатров. Как автор скрипта, вы можете гарантировать, что такого не будет? Сомневаюсь. Если скрипт будет изменён таким образом, что этой возможности в принципе не будет, то через период, равный периоду прошедшей войны правок, его можно попробовать разрешить. Как-то так.

**Comment by actlz** [comment]
Я бы предпочёл, чтобы **адблок блокировал рекламу**, а не контент. Как будто других проблем с доступностью нет.

> Если скрипт будет изменён таким образом, что этой возможности в принципе не будет

Изменить _полностью_ принцип работы скрипта не могу, это не от хорошей жизни придумано. Предлагаю поправить ровно для адблока, чтобы вашу проблему _нормально_ решить, _не нарушая работоспособности_ -- так этого мало. Не могу понять, какую цель вы преследуете. Это уже за гранью просто.

**Comment by dimisa-RUAdList** [comment]
Всё очень просто. В основном реклама блокируется правилами из фильтров. Но также стабильность блокировки обеспечивается доброй волей ресурсов, отказавшихся от обхода адблока, либо договорённостями отказа от такого обхода, достигнутыми после "войны правок". В рассматриваемом случае цикл агрессивного обхода адблока состоялся, а договорённости, если вы не имели к нему отношения - пока не предполагается.

Вы уже оставили в тиките шесть сообщений, но ни одно из них не содержит конкретной информации о хотя бы одном ложном срабатывании. **Фактически, отсутствует предмет для обсуждения, поскольку проблема никак не заявлена**. То есть, вы просто хотите, чтобы я убрал блокировку скрипта, без аргументации, без гарантий отказа от обхода адблока, без достижения каких-либо договорённостей. Так это не работает.

Плееров сейчас достаточно. Если с каким-то возникают проблемы, ресурсы переключаются на другой. И чем дольше наблюдаются проблемы у плеера, тем большую долю забирают под себя его конкуренты. Если у вас есть возможность связаться с инициаторами обхода адблока - сделайте это пожалуйста. Если за ним стоите именно вы - напишите об этом прямо. Но односторонней разблокировки скрипта не будет. Более того, прямо сейчас это приведёт к пропуску рекламы, я об этом уже писал выше.

**Comment by bogachenko** [comment]
К слову о `kindkino.ru`, че это на Adguard не добавили исправление для этого скрипта `http://kindkino.ru/load/zov_predkov_2020_smotret_onlajn_hd_720p/12-1-0-662`

@Yuki2718 `@@||actlz.github.io/actualize.js$domain=kindkino.ru` add to adguard https://github.com/easylist/ruadlist/commit/57df2e6da2dfc7b20705ece1d62eaeee1838c7d6#diff-98bab096ae97882916b12cfa2b44d9e996b0a9f436790f2467064fce1673c013R44
@dimisa-RUAdList `http://kinovego.ru/load/krepkij_oreshek_4_0_2007_hd_smotret_onlajn/17-1-0-3207` еще одно ложное срабатывание от этого говно-скрипта

**Comment by Yuki2718** [comment]
@bogachenko Thx for letting me know but I'm not sure what the rule fixes, on my end video works fine. @zloyden

**Comment by zloyden** [comment]
@bogachenko по ссылке выше проблемы с плеером нет, но здесь `http://kindkino.ru/load/dom_strannykh_detej_miss_peregrin_smotret_onlajn_hd_720p/19-1-0-90` плеер не грузится. Добавил исключение в русский фильтр, но лучше об этом сообщать в наш репозиторий через [эту ссылку](https://agrd.io/report) или программу / расширение.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/132511337-fa4b3282-aa79-478b-978d-95e73cd66b9e.png)

</details><br/>
