### ISSUE TITLE
market.yandex.ru

### ISSUE THREAD

**Issue by CATIOR** [easylist/ruadlist#220]
#### Описание проблемы (Description of the problem):

`https://market.yandex.ru/`
Можно ли убрать мерзкий баннер и анимированную кнопку на скриншоте?

<details>
<summary>Screenshot(s)</summary>

![маркет](https://github.com/easylist/ruadlist/assets/37276986/9b887b02-f63b-4268-8923-08b28bfe4691)

</details>

#### Конфигурация (Configuration):

- OS/version: Windows 10
- Browser/version: Google Chrome 117.0.5938.132
- Ad block extension/version: uBlock 1.52.2

#### Используемые фильтры (Used filters):
<details>

<summary>Screenshot(s)</summary>

![image](https://github.com/easylist/ruadlist/assets/37276986/9c4abe1c-b7dd-4803-bbd1-b9b3066ef1bf)

</details>

#### Конфликты предотвращены.

**Comment by dimisa-RUAdList** [comment]
Указанный элемент сторонней рекламой не является. Подобные анонсы блокируются фильтром [RU AdList: BitBlock](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/bitblock.txt&title=RU%20AdList:%20BitBlock).

**Comment by CATIOR** [comment]
![image](https://github.com/easylist/ruadlist/assets/37276986/ef91f646-a2f4-4d75-bc3a-fe86a25da878)

Не даёт добавить, почему-то. Добавлял через "Импортировать..."

**Comment by dimisa-RUAdList** [comment]
Используйте левую кнопку мыши. А то, что вы добавили, удалите.

**Comment by CATIOR** [comment]
До этого левая кнопка мыши привела на страницу с ошибкой. Спасибо!
