### ISSUE TITLE
google.com

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#222]
#### Описание проблемы (Description of the problem):

Раздражитель. Как воспроизвести, видео под спойлером.

`https://www.google.com/search?q=open`

<details>
<summary>Screenshot(s)</summary>

![2023-10-11_091337](https://github.com/easylist/ruadlist/assets/111344219/781290c2-ace4-4a3a-adec-2fbfd4169012)

https://github.com/easylist/ruadlist/assets/111344219/c8b4a40e-8680-448c-a6eb-2a56a68754a9
</details>

#### Конфигурация (Configuration):

- OS/version: Windows 10 22H2
- Browser/version: Google Chrome Stable
- Ad block extension/version: uBO 1.52.2

#### Используемые фильтры (Used filters):

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 115083
 cosmetic: 129559
 scriptlet: 26621
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
  urlhaus-1: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 26449-17, 26m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1655-28, 26m
  https://www.awwwwesome.org/url-blocklist/url-blocklist.txt: 863-0, 26m
  fanboy-cookiemonster: 48513-416, 26m
  ublock-annoyances: 5568-61, 26m
  ublock-cookies-easylist: 324-324, 26m
 default:
  user-filters: 1-0, never
  RUS-0: 39995-139, 26m
  easylist: 71663-56, 26m
  easyprivacy: 33224-465, 26m
  ublock-badware: 7222-133, 26m
  ublock-filters: 34911-191, 26m
  ublock-privacy: 559-14, 26m
  ublock-quick-fixes: 197-58, 26m
  ublock-unbreak: 2140-34, 26m
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 969 ms (selfie)
 maxAssetCacheWait: 579 ms
popupPanel:
 blocked: 12
 network:
  google.com: 10
  doubleclick.net: 2
 extended:
  ###atvcap
  ##+js(remove-node-text, script, cookieUpdateConsentUrl)
  ##+js(remove-attr, jsaction, #islsp c-wiz a[href^="http"][data-v…
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
  ##.ytp-share-button
  ##.ytp-cards-teaser
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(trusted-replace-fetch-response, /(youtubei.*?)"adSlots.*?\…
  ##+js(trusted-replace-fetch-response, /(youtubei.*?)"adPlacement…
  ##+js(trusted-replace-fetch-response, /(youtubei.*?)"playerAds.*…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(set-constant, Object.prototype.eomEssentialCookieMsgItems,…
```
</details>

**Comment by dimisa-RUAdList** [comment]
И в Google Chrome 109 win7 и в Google Chrome 109 mac в контекстном меню у меня присутствует только строка "Найти хххх в Google", и поиск при этом выполняется в новой вкладке. Опция поиска в Google на исходном сайте включается где-то в настройках?

**Comment by dportvine** [comment]
>Опция поиска в Google на исходном сайте включается где-то в настройках?

Видимо, Google тестирует ее не у всех пользователей.

**Comment by dimisa-RUAdList** [comment]
А без этой фичи проблему можно воспроизвести другим способом?

**Comment by dportvine** [comment]
Нет, только с ней. Может если флаг `chrome://flags/#side-search` принудительно включить, оно появится.

**Comment by dimisa-RUAdList** [comment]
Включил, но не появилось. В выходные попробую на другом устройстве.

**Comment by dportvine** [comment]
А если принудительно включить `chrome://flags/#csc` ?

**Comment by dimisa-RUAdList** [comment]
Да, фича появилась. Но только не на моей железке, отладку я на ней не сделаю, ибо придётся чистить куки гугла и обрекать пользователя на переустановку сделанных настроек. Так что вернусь к этому на выходных.

**Comment by dportvine** [comment]
Ок.

**Comment by dportvine** [comment]
https://github.com/easylist/easylist/commit/49f294205f5dcaffd250867ee816b039003d16c0

<details>
<summary>Screenshot(s)</summary>

![2023-10-18_193140](https://github.com/easylist/ruadlist/assets/111344219/3b5174a1-ce07-4d11-b0a2-6a7cfce6c3aa)
</details>

**Comment by dimisa-RUAdList** [comment]
Добавили для всех? А я так не добрался...

Закинул в BitBlock для наших доменов.

**Comment by dportvine** [comment]
>Добавили для всех?

Да, для всех у кого подключен **EasyList – Notifications**.

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/100948335bebcf982f5142008ce58eddce57548e
