### ISSUE TITLE
tsn.ua

### ISSUE THREAD

**Issue by Spok1** [easylist/ruadlist#230]
#### Описание проблемы (Description of the problem):

<details>
<summary>Screenshot(s)</summary>

![XRecorderLite_24102023_044331](https://github.com/easylist/ruadlist/assets/34476664/eec4d026-e1a0-4e65-afce-0c19ca6c5c90)

</details>

`tsn.ua/ru/nauka_it/pochemu-kosmos-tak-temen-esli-vselennaya-napolnena-ogromnym-kolichestvom-zvezd-2434837.html`

#### Конфигурация (Configuration):

- OS/version: Android 7.0
- Browser/version: Brave 1.59.120, Chromium 118.0.5993.88
- Adblock extension/version: —

#### Используемые фильтры (Used filters):
Adblock Warning Removal List
Bitblock
Easylist
Easylist Cookie
Fanboy's Mobile Notifications
RU Adlist
RU Adlist: Counters

**Comment by dimisa-RUAdList** [comment]
Не используйте пожалуйста адрес страницы, на которой наблюдается проблема, в качестве заголовка issue.

https://github.com/easylist/ruadlist/commit/74e86ea30543efe3891218a5daf7b4bd382944d0
