### ISSUE TITLE
rezka.ag

### ISSUE THREAD

**Issue by Spok1** [easylist/ruadlist#232]
#### Описание проблемы (Description of the problem):

`https://rezka.ag/films/adventures/62855-molodoy-ayvengo-1995.html`

<details>
<summary>Screenshot(s)</summary>

![XRecorderLite_24102023_200107](https://github.com/easylist/ruadlist/assets/34476664/faa21947-7930-4003-ade2-bc79b2779eb6)

</details>

#### Конфигурация (Configuration):

- OS/version: Android 7.0; Build/NRD90M
- Browser/version: Brave 1.59.120, Chromium 118.0.5993.88
- Ad block extension/version: —

#### Используемые фильтры (Used filters):
Adblock Warning Removal List
Bitblock
Easylist
Easylist Cookie
Fanboy's Mobile Notifications
RU Adlist
RU Adlist: Counters

**Comment by dimisa-RUAdList** [comment]
Что за блокировщик вы используете?

**Comment by Spok1** [comment]
@dimisa-RUAdList встроенный в брэйв!

**Comment by dimisa-RUAdList** [comment]
Судя по вашему скрину, встроенный блокировщик Brave (в отличии от Adblock Plus, uBlock Origin и пр) не умеет работать с tld, по крайней мере в части встраивании стилей. То есть, чтобы встраивающее стиль правило сработало, оно должно содержать адрес сайта `rezka.ag`, а не только указание доменной зоны `ag`. В RU AdList все бесчисленные зеркала этого онлайн-кинотеатра не перечисляются, вместо этого используются общие правила скрытия и указание доменных зон для стилей.

Я не знаю, сломалось ли что-то именно в этой версии встроенного блокировщика, или же он не поддерживает работу с tld в принципе. Попробуйте обратиться с этим вопросом к разработчикам Brave.

**Comment by Mr-Maxsimus** [comment]
У меня за расширение uBlock Origin, тормозит видеоплеер на сайте HDrezka, не хочешь закачивать вовремя фильм или сериал! Но у меня эта проблема на PC с интернетом все ЗБС, то только на том сайте такое! я использую Хром!

**Comment by dimisa-RUAdList** [comment]
Ок, давайте разбираться, почему это происходит, и каковы особенности вашей конфигурации. Из технической информации, представленной и вашем исходном тикете, похоже что ваша геолокация - Украина. Укажите пожалуйста точный номер версии браузера, наличие аккунта на rezka.ag и до какого разрешения ограничивается качество.

**Comment by Mr-Maxsimus** [comment]
версия хрома 120.0.6099.217
аккаунт у меня есть на сайте!
качество по-разному, при попытке запустить видео, максимальное доступное качество становится 720, а затем после повторной прогрузки 480, это в основном вечером происходит, а днем все нормально 1080 тяжелое даже 4К!

**Comment by Mr-Maxsimus** [comment]
Добавляю видео с проблемой!

https://github.com/easylist/ruadlist/assets/156460167/52d75467-e683-4182-b3eb-822372d4efc5

**Comment by Mr-Maxsimus** [comment]
возможно это из-за сайта, потому что я уже выключил расширение, но проблема никуда не делась!

**Comment by dimisa-RUAdList** [comment]
В том-то и дело. Я никогда не фиксировал снижения качества на rezka.ag (и зеркалах) из-за блокировщика. Там предусмотрено всего два сценария снижения качества - из-за большой нагрузки на сервера, в часы пик, либо при доступе с российского ip.

Выполните следующие проверки ~>

1. Откройте любое зеркало, чтобы выяснить, повторяется ли эта проблема там. Например: `https://hdrezka.ag/series/drama/50102-uslysh-menya-2022.html`

2. Кликните по иконке uBlock Origin, в появившемся всплывающем окне нажмите на шестерёнки, для открытия панели управления, перейдите на вкладку "Мои фильтры" и добавьте: `||arial.trymeter.org/ajax/get_cdn_series/video.mp4$xmlhttprequest,removeparam=|`

Если ничего из этого не сработает, значит проблема на стороне вашего провайдера.

**Comment by Spok1** [comment]
@Mr-Maxsimus 
> *Перезагружаю страницу и качество 1080p уже доступно но при попытке запустить в этом качестве оно сбрасывает до 720p и скрывает более высокие значения качества!

Это не связано с плагинами! Связано это с региональной блокировкой стримингового сервера. В данном случае им выступает **voidboost.cc**,доступ на который запрещён на территории Украины. Там качество как и раньше. Для обхода блокированного домена в случае истечения тай-аута, запрос перенаправляется на резервный сервер **ukrtelcdn.net**, на котором и действуют ограничения вплоть до HD. Возможно на каком-то потоке до SD. Что могу сказать, хотите максимум качества—используйте прокси!

**Comment by Mr-Maxsimus** [comment]
я решил использовать ОПН, потому что зеркала тоже выдают эти ошибки! я решил использовать VPN, потому что зеркала тоже выдают эти ошибки!

**Comment by dimisa-RUAdList** [comment]
Ваше сообщение не содержит информации о проверках.

**Comment by Mr-Maxsimus** [comment]
я проверил, это проблема в региональной блокировке!

**Comment by Mr-Maxsimus** [comment]
все уже хорошо!

**Comment by Mr-Maxsimus** [comment]
нет

**Comment by Spok1** [comment]
@Mr-Maxsimus 
> ок я уже понял, это из-за региональной блокировки! я решил использовать VPN, потому что зеркала тоже выдают эти ошибки!

Естественно, адреса-то с одного ресурса берутся, и для основного домена и для зеркал будет одинаковый хост.

**Comment by dimisa-RUAdList** [comment]
@Mr-Maxsimus 
Единственный смысл текущего обсуждения заключается в проверке правила.

**Comment by Spok1** [comment]
@dimisa-RUAdList, можете закрывать соммит, так как это не связано с расширением в принципе! 😶‍🌫️

**Comment by dportvine** [comment]
@Mr-Maxsimus 

Просьба в качестве эксперимента, проделать следующее:

>Кликните по иконке uBlock Origin, в появившемся всплывающем окне нажмите на шестерёнки, для открытия панели управления, перейдите на вкладку "Мои фильтры" и добавьте: ||arial.trymeter.org/ajax/get_cdn_series/video.mp4$xmlhttprequest,removeparam=|

Почему это важно? Я тоже с Украины и у меня нет данной проблемы. Более того, я даже не вижу запросов к `trymeter.org`. Если можете, окажите помощь.

**Comment by Mr-Maxsimus** [comment]
Проблема не у uBlock   я вже перевырив !

**Comment by Mr-Maxsimus** [comment]
можна цю тему закрити

**Comment by dimisa-RUAdList** [comment]
Да, проблема не uBlock Origin, но возможно, её можно решить с его помощью. Чтобы проверить это, нужно попробовать добавить правило.

**Comment by Mr-Maxsimus** [comment]
не знаю. я переконався що той сайт нормально працює тільки з VPN

**Comment by dimisa-RUAdList** [comment]
Отключите пожалуйста VPN и попробуйте добавить правило. Эта проверка может помочь многим пользователям.

**Comment by Mr-Maxsimus** [comment]
гаразд а яке правило?

**Comment by dimisa-RUAdList** [comment]
Кликните по иконке uBlock Origin, в появившемся всплывающем окне нажмите на шестерёнки, для открытия панели управления, перейдите на вкладку "Мои фильтры" и добавьте: `||arial.trymeter.org/ajax/get_cdn_series/video.mp4$xmlhttprequest,removeparam=|`

**Comment by Mr-Maxsimus** [comment]
ОК дякую, я додав  це правило, буду тестувати! 😊

**Comment by Mr-Maxsimus** [comment]
пока ничего не изменилось, видео стоит на бесконечной загрузке!

**Comment by dimisa-RUAdList** [comment]
А если обновить страницу?

**Comment by Mr-Maxsimus** [comment]
тоже самое!

**Comment by dimisa-RUAdList** [comment]
Жаль.

**Comment by Mr-Maxsimus** [comment]
![Знімок екрана 2024-01-14 171235](https://github.com/easylist/ruadlist/assets/156460167/88db1b94-6da0-4d81-bddb-cc5b115c66b0)

**Comment by Mr-Maxsimus** [comment]
я удалил то правило потому что выдавало ошибку на сайте!
![Знімок екрана 2024-01-14 170903](https://github.com/easylist/ruadlist/assets/156460167/2ada3baa-1f33-424c-9650-22b98117e04e)
