### ISSUE TITLE
5692.com.ua

### ISSUE THREAD

**Issue by Spok1** [easylist/ruadlist#233]
#### Описание проблемы (Description of the problem):

[https://www.5692.com.ua/ru/amp/news/3678992/vy-vsu-zizn-gotovili-sosiski-nepravilno-sef-povar-rasskazal-o-samyh-rasprostranennyh-osibkah](https://www.5692.com.ua/ru/amp/news/3678992/vy-vsu-zizn-gotovili-sosiski-nepravilno-sef-povar-rasskazal-o-samyh-rasprostranennyh-osibkah)

<details>
<summary>Screenshot(s)</summary>

![XRecorderLite_24102023_211238](https://github.com/easylist/ruadlist/assets/34476664/83125cc8-f0af-4c83-bdc1-9f0628abfaf5)

</details>

#### Конфигурация (Configuration):

- OS/version: Android 7.0; Build/NRD90M
- Browser/version: Brave 1.59.120, Chromium 118.0.5993.88
- Ad block extension/version: Встроенный

#### Используемые фильтры (Used filters):
Adblock Warning Removal List
Bitblock
Easylist
Easylist Cookie
Fanboy's Mobile Notifications
RU Adlist
RU Adlist: Counters

**Comment by dimisa-RUAdList** [comment]
Фильтры RU AdList предназначены для десктопных расширений и версий сайтов. Работа с мобильными версиями выполняется "как есть" и этот принцип не планируется менять в будущем. Исключения составляют только те случаи, когда требуется устранить поломку.

**Comment by dportvine** [comment]
На мобильной версии без `amp`, такого нету.

**Comment by dimisa-RUAdList** [comment]
Ampproject - это реклама гугл. Если я не ошибаюсь, включается и отключается amp в настройках браузера. Любой новостной сайт может иметь специфический amp-макет, и чтобы заблокировать на таких сайтах рекламу гугла без оставшихся пустых мест, может потребоваться несколько тысяч правил, по сути - это нужен отдельный фильтр.
