### ISSUE TITLE
osu.ppy.sh

### ISSUE THREAD

**Issue by Cavitedev** [easylist/ruadlist#234]
#### Описание проблемы (Description of the problem):

Blocks API requests like `https://score.respektive.pw/u/6313643?mode=osu`

The issue is on this file: https://github.com/easylist/ruadlist/blob/master/advblock/first_level.txt

it blocks all domains with .pw at the very least. I believe that's not the expected behavior from that rule

<details>
<summary>Screenshot(s)</summary>

<img src="https://github.com/easylist/ruadlist/assets/52750778/6320f81d-ae56-4447-a950-3d94cf12b36e"/>

</details>

#### Конфигурация (Configuration):

- OS/version: Windows 11 22621.2428
- Browser/version: Firefox 119.0 (20231019122658)
- Ad block extension/version: uBlock Origin: 1.52.2

#### Используемые фильтры (Used filters):

- [ru]  ru [ua]  ua [uz]  uz [kz]  kz: RU AdList
That's the list with this issue

**Comment by dimisa-RUAdList** [comment]
You forgot to specify the URL where the problem occurs.

**Comment by Cavitedev** [comment]
Anything with a domain .pw
`https://score.respektive.pw/u/6313643?mode=osu` would be one example. But `x.pw` would get blocked too.

**Comment by Cavitedev** [comment]
I'm trying on this url https://osu.ppy.sh/users/6313643 but this gets blocked pretty much everywhere

Here some more examples

![image](https://github.com/easylist/ruadlist/assets/52750778/2c64b2a0-eb46-4b9a-a018-a924fed1b512)

**Comment by dimisa-RUAdList** [comment]
I don't see requests for the pw domain zone when I visit this page. Please indicate your geolocation and language settings of the site.

**Comment by Cavitedev** [comment]
I mean. This issue is not related with the website per se.
it is related to an userscript or to an extension that encompasses different features.
https://gist.github.com/respektive/7795fecf6dd559cd0570dd29516b4eab
https://github.com/Cavitedev/osu-subdivide-nations

I suggest you test it with the userscript as it's a lot simpler. I hope that's what you were looking for. You can use Tapermonkey or similar software to install it

**Comment by dimisa-RUAdList** [comment]
Is your script intended for only one site? I can add this site to the exceptions, but I cannot completely disable the rule. Many Russian sites use one-time ad servers in the .pw domain zone, and the current rule is the only reliable way to block them.

**Comment by Cavitedev** [comment]
There are different options.
1. I can forward this to the owner of the API and change the domain
2. It's only meant to work on osu website, that may include the old website from the userscript comments. Even though I'm not sure if I'd try using it for other related websites

**Comment by Cavitedev** [comment]
I'd discuss it for the time being. So far only 1 player used this blocklist, for the time being you could prevent if from working on the osu! website. Actually only osu.ppy.sh/ is enough, this doesn't work on old.ppy.sh at all
