### ISSUE TITLE
otzyvua.net

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#235]
#### Описание проблемы (Description of the problem):

Пустые блоки от рекламы.

`https://www.otzyvua.net/mobilnoe-prilojenie-gosudarstvennyh-tsifrovyh-uslug-diya`

<details>
<summary>Screenshot(s)</summary>

![2023-11-05_181016](https://github.com/easylist/ruadlist/assets/111344219/10548991-b16d-46e3-8a88-1d98692f3bb1)
![2023-11-05_181043](https://github.com/easylist/ruadlist/assets/111344219/2b03dd9c-1799-42d6-9529-45132d4f83cd)
</details>

#### Конфигурация (Configuration):

- OS/version: Windows 10 22H2
- Browser/version: Google Chrome Stable
- Ad block extension/version: uBO 1.53.1b4

#### Используемые фильтры (Used filters):

<details>

```yaml
uBlock Origin: 1.53.1b4
Chromium: 119
filterset (summary):
 network: 115854
 cosmetic: 111223
 scriptlet: 25219
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 26329-19, now
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1667-27, now
  https://www.awwwwesome.org/url-blocklist/url-blocklist.txt: 1191-1, now
  adguard-cookies: 27997-244, now
  ublock-annoyances: 5743-25, now
 default:
  user-filters: 3-0, never
  ublock-filters: 35131-47, now
  ublock-badware: 7425-5, now
  ublock-privacy: 651-9, now
  ublock-unbreak: 2134-8, now
  ublock-quick-fixes: 143-84, now
  easylist: 72479-284, now
  easyprivacy: 32835-404, now
  RUS-0: 40099-284, now
filterset (user): [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 cacheStorageAPI: indexedDB
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 939 ms (selfie)
 maxAssetCacheWait: 513 ms
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
  ###gdpr
```
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/a345a0a092fdd7ad6dcd17f7e65bb94dde3f3cbc
