### ISSUE TITLE
pikabu.ru

### ISSUE THREAD

**Issue by XAHTEP26** [easylist/ruadlist#236]
#### Описание проблемы (Description of the problem):

В Chrome на всем сайте не отображаются `placeholder` для `<input>` и `<textarea>`. Например в полях формы авторизации и регистрации (`https://pikabu.ru`), на страницах настроек профиля (`https://pikabu.ru/settings`) и сообщества или на странице добавления поста (`https://pikabu.ru/add`).

Думаю причина в [этой строке](https://github.com/easylist/ruadlist/commit/ba89cf34a150d3c057fcb661494dcc6357fb66ab#diff-98bab096ae97882916b12cfa2b44d9e996b0a9f436790f2467064fce1673c013R52).

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/easylist/ruadlist/assets/16738756/be7fee47-5556-4d71-b899-d91df69885c7)

</details>

#### Конфигурация (Configuration):

- OS/version: не имеет значения
- Browser/version: Chrome 118
- Ad block extension/version: 5.13.0

#### Используемые фильтры (Used filters):

- Russian & Ukrainian + EasyList

**Comment by dimisa-RUAdList** [comment]
Ок, исправлено: https://github.com/easylist/ruadlist/commit/01e8655766101d0f361af8e63dfa34eb573a9263
