### ISSUE TITLE
Hides embedded players from zippyshare.com 

### ISSUE THREAD

**Issue by MioVisman** [easylist/ruadlist#24]
uBlock Origin 1.37.2
Filter: RUS: RU AdList
```[Adblock Plus 2.0]
! Checksum: l9E46WRdScvjyT263PVVmA
! Version: 202108140800
! Title: RU AdList + CSS Fixes
! Last modified: 14 Aug 2021 08:00 UTC
! Expires: 2 days (фильтр обновляется автоматически каждые 2 дня)
! Homepage: https://forums.lanik.us/viewforum.php?f=102
```
The rule: 
`zippyshare.com##body > :not(.container)` 
https://github.com/easylist/ruadlist/blob/master/advblock/specific_hide.txt#L5909

This rule hides media players embedded via iframes on other sites (incorrect operation). 

RUS: RU AdList - on:
![rule-on](https://user-images.githubusercontent.com/5917956/129441124-0fa9375a-c4de-48f1-846c-44a5b0a486b2.png)

RUS: RU AdList - off:
![rule-off](https://user-images.githubusercontent.com/5917956/129441131-1f8ad9dc-612f-4479-b1ab-10cbfe0ba030.png)

**Comment by dimisa-RUAdList** [comment]
Ok: https://github.com/easylist/ruadlist/commit/8383909981a70288abf15f8cd21f74e2288300ce

**Comment by MioVisman** [comment]
Thanks, it works now. And on the site zippyshare.com the link "embed player" began to function.
