### ISSUE TITLE
pikabu.ru

### ISSUE THREAD

**Issue by alexmnv** [easylist/ruadlist#242]
#### Описание проблемы (Description of the problem):

pikabu.ru
подгрузка постов в ленте ломается правилом:
```
||pikabu.ru/ajax/?key=$xmlhttprequest,domain=pikabu.ru
```
т.е. сайт\лента фактически не работает

#### Конфигурация (Configuration):

- Browser/version: Chrome
- Ad block extension/version: AdblockPlus

#### Используемые фильтры (Used filters):

`RuAdList+EasyList`

**Comment by dimisa-RUAdList** [comment]
Дубликат: https://github.com/easylist/ruadlist/issues/241

**Comment by alexmnv** [comment]
это вовсе не дубликат, а совсем другая проблема.
повторюсь, сейчас лента постов на сайте не работает с блокировщиком
