### ISSUE TITLE
ya.ru

### ISSUE THREAD

**Issue by PhoenixIndigo** [easylist/ruadlist#243]
#### Описание проблемы (Description of the problem):

`https://ya.ru/search/?text=1&lr=213&search_source=yaru_desktop_common&search_domain=yaru`

[Нет полосы прокрутки](https://forum.mozilla-russia.org/viewtopic.php?id=78671) при первом запросе или чистке куков

#### Конфигурация (Configuration):

- OS/version: win11
- Browser/version: firefox 120
- Ad block extension/version: ABP 3.17.1

#### Используемые фильтры (Used filters):

<details>
<summary>Screenshot(s)</summary>

![](https://github.com/easylist/ruadlist/assets/107413021/f0218b3b-56db-42a1-852d-148044a878b7)

</details>

**Comment by dimisa-RUAdList** [comment]
Вы не выполнили [рекомендации](https://forum.ru-board.com/topic.cgi?forum=5&topic=51141&start=0&limit=1&m=2#1), на которые ссылаетесь. Установите оба пакета RU AdList Fixes.

**Comment by PhoenixIndigo** [comment]
Спасибо хотел помочь челу мне этот гемор с фиксами на uBlock Origin ни к чему
