### ISSUE TITLE
ya.ru

### ISSUE THREAD

**Issue by B0mak** [easylist/ruadlist#252]
Описание проблемы (Description of the problem):

Реклама в промежутках (?) между пачками картинок. 

`https://ya.ru/images/search?from=tabbar&text=red%20alert%203%20soviet%20background`

<details>
<summary>Скриншот</summary>

![3](https://github.com/easylist/ruadlist/assets/45781131/352c5cab-5ea9-4073-b996-5a4d24c1ea51)

</details>

#### Конфигурация (Configuration):

- OS/version: Win 10
- Browser/version: Yandex.Browser; ver. 23.11.1.731 (64-bit)
- Ad block extension/version: uBlock Origin 1.54.0

#### Используемые фильтры (Used filters):
<details>
<summary>Скриншот</summary>

![4](https://github.com/easylist/ruadlist/assets/45781131/7dff88ba-2451-4b69-95af-1a26fb787e8a)

</details>

**Comment by dimisa-RUAdList** [comment]
Оу, судя по представленной информации, вы используете рекламный браузер яндекса. Это чудо не только следит за пользователями, но и (в зависимости от сборки) добавляет свою рекламу на страницы посещаемых сайтов, в дополнение к той, что имеется там изначально.

Помимо этого, рекламный браузер яндекса запрещает запуск расширений, блокирующих рекламу, на своих и партнёрских сайтах. Именно поэтому, в разделе "Сведения" [исходного issue](https://github.com/uBlockOrigin/uAssets/issues/21323) - `blocked: 0` и не зафиксировано ни одного сработавшего правила. То есть, браузер попросту не позволил расширению запуститься.

Официально uBlock Origin не поддерживает этот браузер. И этого не планируется в будущем. Это просто бессмысленно. Если вы хотите и далее использовать браузер яндекса, то единственно потенциально рабочий способ блокировки в нём рекламы, это установка [dev-версии uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin-dev-build/cgbcahbpdhpcegmbfconppldiemgcoii) и загрузка [готового файла конфигурации](https://github.com/easylist/ruadlist/wiki/RU-Adlist-links). Впрочем, это не гарантия, и неизвестно, сколь долго данная недокументированная возможность будет сохранять функциональность.

P.S. Судя по данным [исходного issue](https://github.com/uBlockOrigin/uAssets/issues/21323), можно предположить, что вы пытались использовать скрипт RU AdList JS Fixes в Tampermonkey. Это бесполезно, и скорее всего, будет приводить к поломкам.

**Comment by B0mak** [comment]
Хм, действительно активированы "расширения от яндекса", только сейчас заметил. Прошу прощения.
Но что с ними, что без них -- итог один и тот же.

По поводу вашего варианта блокировки посмотрю что можно сделать, спасибо!

Насчёт Tampermonkey, то я его использую чтобы избавиться от рекламы в почте яндекса. Года два уже пользуюсь и не было "поломок".

**Comment by dimisa-RUAdList** [comment]
Мы никогда не проводили отладку RU AdList JS Fixes в браузере яндекса, тогда как сообщения о поломках периодически приходили. Поэтому я и предупредил о таком риске. Расширения от яндекса лишь добавляют рекламу, но не влияют на запуск блокировщиков, их браузер запрещает самостоятельно. Но насколько мне известно, dev-версии uBlock Origin в большинстве случаев пока ещё работает.
