### ISSUE TITLE
dostyp.com.ua

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#254]
#### Описание проблемы (Description of the problem):

Рекламный баннер + социалка.

`https://dostyp.com.ua/novini/vnochi-sili-ppo-znishili-14-shahediv/`

<details>
<summary>Screenshot(s)</summary>

![2023-12-15_092644](https://github.com/easylist/ruadlist/assets/111344219/47eb04e9-1d32-4882-8425-0ca72896ef50)
![2023-12-15_092542](https://github.com/easylist/ruadlist/assets/111344219/f6db42a1-63da-466a-a74f-89586fdd9a0f)
![2023-12-15_092728](https://github.com/easylist/ruadlist/assets/111344219/522e8597-9be2-43ea-b74d-c09da02166ed)
</details>

#### Конфигурация (Configuration):

- OS/version: Windows 10 22H2
- Browser/version: Google Chrome Stable
- Ad block extension/version: uBO 1.54.0

#### Используемые фильтры (Used filters):

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 116277
 cosmetic: 114945
 scriptlet: 26366
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 25943-19, now
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1682-27, now
  https://www.awwwwesome.org/url-blocklist/url-blocklist.txt: 1237-0, now
  adguard-cookies: 28250-249, now
  ublock-annoyances: 6222-28, now
 default:
  user-filters: 5-0, never
  ublock-filters: 36164-60, now
  ublock-badware: 7616-11, now
  ublock-privacy: 949-13, now
  ublock-unbreak: 2167-7, now
  ublock-quick-fixes: 109-33, now
  easylist: 75655-303, now
  easyprivacy: 33110-403, now
  RUS-0: 40002-283, now
filterset (user): [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 cacheStorageAPI: indexedDB
 filterAuthorMode: true
 popupPanelHeightMode: 1
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 564 ms (selfie)
 maxAssetCacheWait: 345 ms
popupPanel:
 blocked: 6
 network:
  dostyp.com.ua: 1
  gemius.pl: 2
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ##.footer-social
  ##.footer-social-links
```
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/72a87085c35855b496268c2630b893cb565496d7
