### ISSUE TITLE
anilibria.tv

### ISSUE THREAD

**Issue by PhoenixIndigo** [easylist/ruadlist#255]
#### Описание проблемы (Description of the problem):
`https://anilibria.tv/release/tate-no-yuusha-no-nariagari-season-3.html`
Для кого кнопка поделиться, она разве не лишняя? ![](https://github.com/easylist/ruadlist/assets/107413021/a79a6de9-8c8a-4041-863d-a5c2ee888a9a)

<details>
<summary>Screenshot(s)</summary>

![](https://github.com/easylist/ruadlist/assets/107413021/14b7a760-e6b7-4a3a-9400-d1f6358991d1)

</details>

#### Конфигурация (Configuration):
`https://pastebin.com/u/GodIndigo`

- OS/version: W11
- Browser/version: Firefox 121
- Ad block extension/version: uBlock Origin 1.54.0

#### Используемые фильтры (Used filters):
<details><summary>Details</summary>
<p>

![](https://github.com/easylist/ruadlist/assets/107413021/5ff7bf5a-54c8-4e8a-baab-a1618c9c1e56)

</p>
</details>

**Comment by PhoenixIndigo** [comment]
У вас в анонсах два иклюсения
```adblock-filter-list
@@||vk.com/widget_comments.php^$domain=anilib.moe|anilib.one|anilib.top|anilibria.iss.one|anilibria.tv|xn--80aacbuczbw9a6a.xn--p1ai
@@||vk.com/widget_comments.php^$domain=anilib.top|anilibria.iss.one|anilibria.tv|xn--80aacbuczbw9a6a.xn--p1ai
```

**Comment by dimisa-RUAdList** [comment]
Исключения там не случайно. Они добавлены по просьбе постоянных пользователей anilibria. 

Стрелочку убрал: https://github.com/easylist/ruadlist/commit/047f91fc7a0bd172ee9e28c557302ea9a76a50f8

**Comment by PhoenixIndigo** [comment]
Так одно из них вроде повторяет другое, Я не прав?

**Comment by dimisa-RUAdList** [comment]
Действительно. По каким-то причинам FOP не упорядочил эти правила автоматически.

Поправил: https://github.com/easylist/ruadlist/commit/c3d2ef97b22278e3904018ee5f9b75c3ebf5c963

**Comment by PhoenixIndigo** [comment]
`https://tv3.darklibria.it/release/tensei-shitara-slime-datta-ken-coleus-no-yume`
кнопка поделиться: ![](https://github.com/user-attachments/assets/0cb4ea39-78c3-42d0-8314-4ccd3211fef3)
<details><summary>Details</summary>
<p>

![](https://github.com/user-attachments/assets/97550b91-653c-40c2-9331-3508cff8b414)

</p>
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/1464d211ed5b2eef698386ed87332ca1a6acd825
