### ISSUE TITLE
forum.mozilla-russia.org

### ISSUE THREAD

**Issue by PhoenixIndigo** [easylist/ruadlist#256]
#### Описание проблемы (Description of the problem):
`https://forum.mozilla-russia.org/userlist.php?username=meshki&show_group=-1&sort_by=username&sort_dir=ASC&search=Отправить`

Одна дрянь спамит и регистрируется, сделайте с этим что то
```adblock-filter-list
forum.mozilla-russia.org##[href*="meshki-"]
forum.mozilla-russia.org##[href*="bahily-"]
``` 

<details>
<summary>Screenshot(s)</summary>

![](https://github.com/easylist/ruadlist/assets/107413021/d97bf918-08ef-4f7c-9096-46c090222c4d)

</details>

#### Конфигурация (Configuration):

- OS/version: W11
- Browser/version: Firefox 121
- Ad block extension/version: uBlock Origin 1.54.0

#### Используемые фильтры (Used filters):
`https://pastebin.com/u/GodIndigo`

**Comment by dimisa-RUAdList** [comment]
Это проблема модератора форума. Засорять фильтр правилами для подобного - плохая идея.
