### ISSUE TITLE
surl.li

### ISSUE THREAD

**Issue by Surlli** [easylist/ruadlist#258]
#### Описание проблемы (Description of the problem):

`https://surl.li/omolc`

<details>
<summary>Screenshot(s)</summary>

При включенном Adblock (отсутствует блок с контентом)
![as it is](https://github.com/easylist/ruadlist/assets/155148299/3db9fdfe-3930-4e33-8bc7-cdd5cf0df1d0)

Без Adblock блок присутствует (блок с контентом выделен)
![should be](https://github.com/easylist/ruadlist/assets/155148299/9335047f-894c-462a-8a28-45c849984aa8)

</details>

#### Конфигурация (Configuration):

- OS/version: Windows 11, version 22H2
- Browser/version: Chrome - 119.0.6045.160
- Ad block extension/version: Adblock Plus 3.21.1

#### Используемые фильтры (Used filters):
<details>
<summary>Filters</summary>
ABP filters, RU, UA, UZ, KZ+EasyList, Allow nonintrusive advertising

**Comment by dimisa-RUAdList** [comment]
Некоторое время назад этот элемент выводился из-под скрытия, однако исключение было удалено, поскольку выяснилось, что ваш сервис не имеет системы безопасности, что приводит к прямым переходам на сайты, продвигающим вредоносное ПО, типа [AppWizard](https://www.virustotal.com/gui/file/06f031b1c0d4a2aa87a27dd24bdaa1aed52c8b42caa9b6d33f54e1208a48523c).

Пример: `https://surl.li/nqlfx`

Пока замечено несколько подобных случаев. Если они будут множиться, речь будет идти о полной блокировке сервиса. Ресурсы, использующие эту особенность вашего сервиса, заблокированы уже сейчас. С примерами можно ознакомится [здесь](https://forums.lanik.us/viewtopic.php?t=40123).

**Comment by Surlli** [comment]
Система безопасности у сервиса имеется. 
При первом получении ссылки, и потом регулярно, система отправляет запрос в Google Safe Browsing и на основании этой информации линк или создается, или блокируется.
<details>
<summary>Скриншоты</summary>

![first](https://github.com/easylist/ruadlist/assets/155148299/6ec68328-12a6-468b-ae96-9ba495ad0658)

![second](https://github.com/easylist/ruadlist/assets/155148299/67517b0f-bdc5-456c-b084-ccb9e38f9edd)
</details>

Касательно приведенной выше ссылки, ее конечный линк - `https://lobar.site/`, у него в  `transparencyreport.google.com` только warning - "На этом сайте размещены редко скачиваемые файлы.", ссылки со статусом "warning" на данном этапе не блокируются.

К примеру, есть другая ссылка `http://surl.li/orhgj`, ее конечный линк `https://www.nextechqpg.com/ITBeans/?f=ZnNrJmFtcDtpPTE5MzM0Mg==` - и она в сервисе, как можно увидеть, заблокирована из-за соответствующего статуса в Safe Browsing - "Этот сайт небезопасен".

**Comment by dimisa-RUAdList** [comment]
Большинство сервисов сокращения ссылок бесплатны, и имеют минимальный функционал. У вас же присутствует платная составляющая, потому и ответственность выше. Убирая исключение для скрытия предпросмотра, я преследовал цель в первую очередь убрать отображающееся в нём описание AppWizard, в котором присутствовало утверждение, что это безопасный софт. Размещённое на страницах сервиса, оно вводило в заблуждение пользователей, и приводило в итоге к скачиванию вредоносного ПО.

Если вы видите какой-то путь к решению, предлагайте. Будем обсуждать.

**Comment by Surlli** [comment]
Хорошо, с нашей стороны мы видим несколько вариантов, как мы можем решить данную ситуацию с нашей стороны:
1)Если мы правильно вас поняли в этом моменте:
> в котором присутствовало утверждение, что это безопасный софт

Вы о тексте на странице превью "Автоматическая проверка не выявила проблем безопасности" - если это так, можем сделать данный текст более универсальным.

2)Как мы и проговаривали, сейчас у нас блокируются те ссылки, которые у GSB уже помечены как вредоносные (со статусом "warning" не блокируются). В таком случае можем дописать функционал, когда даже такие не критические ошибки google safe browsing со статусом "warning" будут автоматически вести на предупреждение.

**Comment by dimisa-RUAdList** [comment]
Наверное, второй вариант лучше. Когда вы сможете раскатать его реализацию? На момент отмены исключения скрытия превью ссылка `https://surl.li/nqlfx` вела на транзитную страницы вашего домена, сейчас же её использование приводит к прямому переходу на `lobar.site`. От чего это зависит?

**Comment by Surlli** [comment]
В течении 2-х недель реализуем обновленные статусы google safe browsing
Касательно /nqlfx, на данный момент ссылка в статусе "warning", мы тестировали автоматику.
Сейчас и в будущем независимо от внутренних статусов ссылки "warning" или "banned" будут выше в приоритете

**Comment by dimisa-RUAdList** [comment]
Хм, похоже что в случае с /nqlfx статус "warning" срабатывает только в Firefox. В Google Chrome открывается `https://lobar.site/r/31089/`.

**Comment by Surlli** [comment]
Возможно, у вас в Хроме сохранился кэш.
Проверили у себя в инкогнито, переход ведет на страницу warning:
<details>
<summary>Скриншоты</summary>

![new-screen](https://github.com/easylist/ruadlist/assets/155148299/652880a6-7c82-4ca0-a688-8c39ec89ebbe)

![new-screen1](https://github.com/easylist/ruadlist/assets/155148299/a3262b57-a1b2-4327-88bb-91cf00f785da)
</details>

Версия браузера - 120.0.6099.130

**Comment by dportvine** [comment]
> В Google Chrome открывается `https://lobar.site/r/31089/`

У меня так.

<details>
<summary>Screen</summary>

![2024-01-03_165201](https://github.com/easylist/ruadlist/assets/111344219/061c466b-9bea-4a06-8796-edacf5561284)
</details>

**Comment by dimisa-RUAdList** [comment]
Да, действительно. Но если пользователь уже посещал `surl.li` ранее, то он напрямую попадёт на страницу загрузки вредоносного ПО. И ещё появилась новая проблема с агрессивным оверлеем, содержащим предложение купить впн. Чтобы его заблокировать, учитывая что он отключает прокрутку, потребуется скрыть половину страницы, оставив только её верхнюю часть.

**Comment by Surlli** [comment]
Если мы Вас правильно поняли, переход на новый принцип работы с google safe browsing решит данный вопрос, поскольку у пользователя не будет первичного перехода на конечный URL он сразу попадет на страницу с предупреждением.
Касательно поп-апа, проводили А/В тестирования функционала, легко можем отключить, если это создает хоть какие-то неудобства пользователям. (Выполнили)

**Comment by dimisa-RUAdList** [comment]
Ок. Вернул исключение: https://github.com/easylist/ruadlist/commit/0044dbfdd648458b3bd244e7ad669f7f88cc68fe

Далее уже будем смотреть на то, как фактически будет использован ваш сервис вредоносными офферами в будущем. Тему закрываю, но писать в ней будет можно. Если что, сообщу в ней.
