### ISSUE TITLE
peers.tv

### ISSUE THREAD

**Issue by PhoenixIndigo** [easylist/ruadlist#259]
#### Описание проблемы (Description of the problem):
`https://peers.tv/aiva_tv/`
Блокируется доступ без подтверждённых номером кук

<details>
<summary>Screenshot(s)</summary>

![](https://github.com/easylist/ruadlist/assets/107413021/34c1b18a-54fa-4061-b7d2-d07c135cf0de)

</details>

#### Конфигурация (Configuration):

- OS/version: Win11
- Browser/version: Firefox 121
- Ad block extension/version: uBlock Origin 1.54.0

#### Используемые фильтры (Used filters):
<details><summary>Details</summary>
<p>

`https://pastebin.com/u/GodIndigo`

![](https://github.com/easylist/ruadlist/assets/107413021/e7fcc609-c4cb-4406-aafc-aec16e646b3a)

</p>
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/342727be0289fb706af5eebf308f05182896081d
