### ISSUE TITLE
kinovego.ru

### ISSUE THREAD

**Issue by Kocsten** [easylist/ruadlist#26]
Здравствуйте, пожалуйста разблокируйте плеер, которые на старых доменах раздачи. Так как при включение приложение резчика рекламы, то на старых доменах пропадает видео.

Сайт: http://kinovego.ru/

Разблокировать домены:

multikland.net
mir-dikogo-zapada.com
placehere.link

Спасибо!

**Comment by dimisa-RUAdList** [comment]
В вашем сообщении отсутствует ссылка на страницу, где наблюдается проблема.

**Comment by Kocsten** [comment]
Вот один плеер из примеров - http://kinovego.ru/load/prizrachnyj_patrul_2013_smotret_onlajn/18-1-0-131

Скрин, так выглядит при включенным  AdGuard - https://rataku.com/images/2021/09/03/561.jpg

И так на всех 3 доменов.

**Comment by dimisa-RUAdList** [comment]
На всех трёх доменах? Вы привели ссылку только на kinovego.ru.

**Comment by Kocsten** [comment]
На сайте kinovego.ru размещены плееры.

Пример плеера:
<iframe width="560" height="400" src="https://api1578915698.**embedstorage.net**/embed/movie/3766" frameborder="0" allowfullscreen=""></iframe>

Вот три домена, что при включенным AdGuard картинки нет, как здесь - https://rataku.com/images/2021/09/03/561.jpg

multikland.net
mir-dikogo-zapada.com
placehere.link

**Comment by dimisa-RUAdList** [comment]
То есть, проблема наблюдается не на нескольких доменах, а только на одном, но при этом под ложную блокировку попадают разные фреймы. Ок, добавил исправление для блокировщиков uBlock Origin, Adblock Plus, AdBlock, форков на их движке, встроенного блокировщика Оперы и Вивальди: https://github.com/easylist/ruadlist/commit/047d9cacccc1490d22bb01461a1790fefc20cb14

Изменения вступят в силу в течении 15 минут, после чего станут доступны при обновлении [вручную](https://forums.lanik.us/viewtopic.php?f=102&t=22786). В расширениях автоматом они раскатаются в течении 48 часов, во встроенных блокировщиках - в течении недели.

AdGuard использует собственные фильтры, сообщать о проблемах с ними нужно [на их баг-трекере](https://github.com/AdguardTeam/AdguardFilters/issues).

**Comment by Kocsten** [comment]
Мне посоветовали! 
"Для того чтобы устранить эту проблему быстрее, вы можете обратиться по ссылке https://github.com/easylist/ruadlist/issues/new с просьбой разблокировать плеер (старые домены раздачи), в течении дня они всё исправят конкретно для вашего сайта"

То приходится не первый день менять ссылку, так как дали новую.
Пример
<iframe width="560" height="400" src="https://api1630623309.tobaco.ws/embed/movie/49893" frameborder="0" allowfullscreen=""></iframe>

Где ссылка tobaco.ws показывает при включенном везчике рекламы. А это надо столько перелопатить, что изначально вручную менял, пока рука не заболела, вот посоветовали, и решил обратиться.

**Comment by dimisa-RUAdList** [comment]
AdGuard не использует фильтры RU AdList. Куда обращаться - я написал выше.

**Comment by Kocsten** [comment]
Спасибо!
