### ISSUE TITLE
motiv.fm

### ISSUE THREAD

**Issue by qkveri** [easylist/ruadlist#262]
#### Описание проблемы (Description of the problem):

Долго висят запросы в состоянии Queueing при включенном фильтре RU, UA, UZ, KZ+EasyList.

`https://motiv.fm/`

Шаги воспроизведения:
1. Открыть главную `https://motiv.fm/`
2. Переключаться между вкладками сайдбара: Главная, Топ-100, Статьи.

<details>
<summary>Screenshot(s)</summary>

![network](https://github.com/easylist/ruadlist/assets/26967934/2b807b58-cd3d-4039-9183-099064df5d36)

</details>

#### Конфигурация (Configuration):

- OS/version: Windows 11 Home
- Browser/version: Google Chrome/120.0.6099.217
- Ad block extension/version: 3.22

#### Используемые фильтры (Used filters):

<details>
<summary>Screenshot(s)</summary>

![filters](https://github.com/easylist/ruadlist/assets/26967934/32f0a3af-5eb0-46ee-ada0-0e1e59d63b10)

</details>

**Comment by dimisa-RUAdList** [comment]
Не уверен, что проблема в фильтре RU AdList. Там вообще нет ни одного срабатывания. Попробуйте отключить комбинированный фильтр и подключить вместо него чистый EasyList.

**Comment by qkveri** [comment]
@dimisa-RUAdList да, вы правы, вероятно, проблема в EasyList, спасибо!
