### ISSUE TITLE
dorama.land

### ISSUE THREAD

**Issue by CbumDino** [easylist/ruadlist#265]
#### Описание проблемы (Description of the problem):
Movies blocked at `https://dorama.land/i-dzhe-skoro-umryot-1-seriya-a`

<details>
<summary>Screenshot(s)</summary>

https://github.com/easylist/ruadlist/assets/65717387/83387b9d-4588-4e84-a02a-ae21ec469311

</details>

#### Используемые фильтры (Used filters):
Potential cause: 
`https://s3.jaswish.com/hls/stream/serials/s01/i_dzhe_skoro_umryot_s1e1_ozvuchka_softbox_358938/hls/index.m3u8`

**Comment by dimisa-RUAdList** [comment]
Solved: https://blog.adblockplus.org/releases/adblock-plus-323-for-chrome-firefox-microsoft-edge-and-opera
