### ISSUE TITLE
music.youtube.com

### ISSUE THREAD

**Issue by PhoenixIndigo** [easylist/ruadlist#266]
#### Описание проблемы (Description of the problem):
https://github.com/AdguardTeam/AdguardFilters/issues/171218
Конфликт к кому?

<details>
<summary>Screenshot(s)</summary>

</details>

#### Конфигурация (Configuration):

- OS/version: Win11(10)
- Browser/version: Firefox 121
- Ad block extension/version: uBlock Origin 1.55.0

#### Используемые фильтры (Used filters):
<details><summary>Details</summary>
<p>

![](https://github.com/easylist/ruadlist/assets/107413021/0859c15e-38fd-4cf2-932e-ac35b8e65205)

</p>
</details>

**Comment by dimisa-RUAdList** [comment]
Если вы сознательно используете заведомо конфликтную конфигурацию фильтров, то должны быть готовы к соответствующим последствиям.

**Comment by PhoenixIndigo** [comment]
У вас то всё норм?

**Comment by dimisa-RUAdList** [comment]
Даже не проверял. Это бессмысленно в подобной конфигурации. Баги и конфликты при её использовании гарантированны.

**Comment by PhoenixIndigo** [comment]
Конфликт не в конфигурации, а в одновременном включении конфликтующих правил:
```adblock-filter-list
||youtube.com/youtubei/v1/log_event?
/generate_204
```

**Comment by PhoenixIndigo** [comment]
Конфликт не в конфигурации, а в одновременном включении конфликтующих правил:
```adblock-filter-list
||youtube.com/youtubei/v1/log_event?
/generate_204
``` 
То есть какое ненужное?

**Comment by dimisa-RUAdList** [comment]
Когда в конфигурации задействованы никогда не тестируемые на предмет совместной работы фильтры, и правила из этих фильтров начинают конфликтовать, такая конфигурация определяется как конфликтная.

В случае с uBlock Origin дополнительные фильтры RU AdList проверяются на совместимость только с теми фильтрами, которые включены по умолчанию.

А в вашем конкретном случае вы ещё и AdGuard Russian filter подключили, который был намеренно удалён из списков uBO из-за конфликтов с RU AdList.

Вашу конфигурацию не имеет смысла проверять.

**Comment by PhoenixIndigo** [comment]
Просто не понятно какой фильтр лишний для исключения. Исключил пока оба.

**Comment by PhoenixIndigo** [comment]
Так хотя бы логгер страницы хотябы проверить стоило бы.

**Comment by dimisa-RUAdList** [comment]
Эти фильтры не предназначены для совместной работы.

**Comment by PhoenixIndigo** [comment]
Так это ясно, а какой будет ненужнее. Плюс ru countrs тоже исключён но он же тоже добавленный.

**Comment by dimisa-RUAdList** [comment]
Выбирая из двух аналогичных по назначению фильтров EasyPrivacy и AdGuard Tracking Protection, разработчик uBlock Origin сделал включенным по дефолту EasyPrivacy. Именно на предмет совместимости с ним и тестируется рекомендованный для рунета RU AdList: Counters.

**Comment by PhoenixIndigo** [comment]
Так совет насчёт ненужного из этих двух будет от вас как разбирающегося в запросах серверов, а то мне не известно какой хуже?

**Comment by dimisa-RUAdList** [comment]
Я никогда не тестировал AdGuard Tracking Protection и ничего не могу сказать о его работе. Но он аналогичен по назначению EasyPrivacy, поэтому для обеспечения корректной работы нужно использовать только один из них. Поскольку uBO в дефолте уже использует EasyPrivacy, и именно для совместной работы с ним проводится отладка всех остальных фильтров, логика подсказывает, что оставить нужно именно его. 

А AdGuard Tracking Protection полагаю, оптимален для работы в расширении и программе AdGuard, где уже EasyPrivacy и RU AdList: Counters будут лишними.

**Comment by PhoenixIndigo** [comment]
Так меня интерисуют не подписки, а исключение из двух
```adblock-filter-list
@@||music.youtube.com/youtubei/v1/log_event?
@@||music.youtube.com/generate_204
```

**Comment by PhoenixIndigo** [comment]
Дело ведь ещё в том что адгуард блокирует то что пропускают изи анонсы

**Comment by dimisa-RUAdList** [comment]
Правила работают не индивидуально, сами по себе, работает набор правил, который в итоге даёт кумулятивный эффект. Поэтому рассматривать два отдельных правила без контекста всего набора бессмысленно. В случае с корректной настройкой uBlock Origin, никакие исключения не требуются.

**Comment by dportvine** [comment]
`/log_event` видимо был удален из **EasyPrivacy**. Остались только исключения.

<details>
<summary>Screen</summary>

![2024-01-21_212750](https://github.com/easylist/ruadlist/assets/111344219/3f8eb271-7569-4ffe-8165-5f723eb1ef75)
</details>

**Comment by PhoenixIndigo** [comment]
Спасибо понял врое лишнее ||music.youtube.com/youtubei/v1/log_event? блокировка прибавляет ||music.youtube.com/generate_204$xhr

**Comment by dimisa-RUAdList** [comment]
Вы поняли неправильно. Не следует использовать конфликтную конфигурацию. Если же вы делаете это сознательно, решение конфликтов становится вашей личной проблемойю
