### ISSUE TITLE
terev.ru

### ISSUE THREAD

**Issue by CbumDino** [easylist/ruadlist#268]
`https://terev.ru/`
#### Описание проблемы (Description of the problem):
Broken functionality on the client side (images, videos and animations).
`$third-party,script,domain=` filter seems to be the cause

<details>
<summary>Screenshot(s)</summary>
<img width="1460" alt="Screenshot 2024-01-25 at 15 18 03" src="https://github.com/easylist/ruadlist/assets/65717387/5543fa21-31e5-4706-a6f7-3386db92ed1a">
<img width="1512" alt="Screenshot 2024-01-25 at 15 24 52" src="https://github.com/easylist/ruadlist/assets/65717387/ba027485-9eda-49a8-92ba-b0c4e56940ec">

</details>

#### Конфигурация (Configuration):

- OS/version: MacOS Monterey 12.4
- Browser/version: Chrome 120.0.6
- Ad block extension/version: ABP 3.23

#### Используемые фильтры (Used filters):
ruadlist+easylist.txt

**Comment by dimisa-RUAdList** [comment]
Это ваш домен?

**Comment by CbumDino** [comment]
> Это ваш домен?

No it's not my domain, although the owner reached out since clients are experiencing issues.

**Comment by dimisa-RUAdList** [comment]
As far as I understand, this domain was previously owned by other owners who used disposable servers.

Fix: https://github.com/easylist/ruadlist/commit/1d163637bad4600cd897edeeba237d972203f6ba
