### ISSUE TITLE
Блокировка рекламных и реферальных ссылок в поисковых подсказках яндекса

### ISSUE THREAD

**Issue by GOGEN** [easylist/ruadlist#27]
### List the website(s) where you encounter issues with ruadlist filters

* https://yandex.ru/search/?text=gmail&lr=213
* https://yandex.ru/

### Define the problem 

When I enable uBlock Origin with ABP filters enabled (from https://github.com/easylist/ruadlist/blob/master/ruadlist-fixes.user.css#L4888) the site is broken and navigation suggests is blocked. It came with this [commit](https://github.com/easylist/ruadlist/commit/5e40c6c8b8876c65785f98ae8fecc1b6c5215fcd)

### Screenshot(s) 
Without filters

<img width="1459" alt="Screenshot 2021-09-07 at 16 33 34" src="https://user-images.githubusercontent.com/5768578/132353893-c4f8cd91-35bc-4b70-9803-8b62a4824280.png">

With filters

<img width="1443" alt="Screenshot 2021-09-07 at 16 34 03" src="https://user-images.githubusercontent.com/5768578/132353937-508ada4b-4cf7-4dc3-b6f6-f20c0b9efd32.png">

**Comment by dimisa-RUAdList** [comment]
Вы уже писали по этой проблеме: https://github.com/easylist/ruadlist/issues/14

Вероятно, в данном случае имеет место какой-то баг. Целевое правило `##.mini-suggest__item > a[href^="http://"]` блокирует только небезопасные ссылки http, тогда как ссылка на почту гугл начинается на https и под блокировку не попадает.

**[Скрин](https://i.imgur.com/zVncOqt.png)**

**Comment by P0Rtvine** [comment]
Баг повторяется, если добавить в **uBO** `https://raw.githubusercontent.com/easylist/ruadlist/master/ruadlist-fixes.user.css`
Только зачем? 
Более того, происходит сохранение в куки и простым удалением **ruadlist-fixes.user.css** проблему не решить.
<details>
<summary>Скрин</summary>

![2021-09-08_092429](https://user-images.githubusercontent.com/57287308/132457417-fd3d24b2-56b3-42c1-9dbb-15e6aa743329.png)
</details>

**Comment by dimisa-RUAdList** [comment]
@GOGEN
Я правильно понимаю, что вы имеете непосредственное отношение к разработке этой функции?

**Comment by GOGEN** [comment]
Да, я делаю навигационные подсказки

**Comment by dimisa-RUAdList** [comment]
Ок, тогда вам должно быть хорошо известно, что яндекс использует детектор адблока и при обнаружении такового - обфусцирует макет. При этом нормальные прямые безопасные https-ссылки в поисковых подсказках подменяются реферальными небезопасными http-ссылками.

Разные блокировщики имеют разное назначение и позиционирование. В Adblock Plus и uBlock Origin используются разные версии фильтра RU AdList. Adblock Plus - мягкий блокировщик, в котором по-умолчанию разрешена допустимая реклама. uBlock Origin - более строгий, и в нём по-умолчанию делается акцент на приватности и безопасности. Поэтому в фильтр RU AdList для uBlock Origin было добавлено правило для скрытия http-ссылок в подсказках.

Сейчас я уже не уверен, что такая блокировка должна присутствовать только в RU AdList для uBlock Origin. Дело в том, что я обнаружил, что генерация ссылок в поисковых подсказках неадекватна, приоритет отдаётся рекламе, причём вопреки здравому смыслу.
<details>
<summary>Подробнее</summary>

![примеры](https://i.imgur.com/8LuLebX.jpg)

</details>

Прокомментируйте пожалуйста эти результаты.
