### ISSUE TITLE
localrent.pl

### ISSUE THREAD

**Issue by CbumDino** [easylist/ruadlist#270]
#### Описание проблемы (Description of the problem):
Blocked widget at the bottom of the page
Aware that the domain is Polish, although the user who is facing the issue is using only the RU list.

<details>
<summary>Screenshot(s)</summary>

<img width="1512" alt="Screenshot 2024-02-06 at 10 45 34" src="https://github.com/easylist/ruadlist/assets/65717387/43949b93-00af-4ac8-a271-fed9ef449c42">
<img width="1511" alt="Screenshot 2024-02-06 at 10 47 23" src="https://github.com/easylist/ruadlist/assets/65717387/666cae1a-e29e-4909-9b0c-c87e29c5c4fe">

</details>

**Comment by dimisa-RUAdList** [comment]
Please provide the exact link to the page where the problem is occurring and the configuration that is being used.

**Comment by CbumDino** [comment]
> Please provide the exact link to the page where the problem is occurring and the configuration that is being used.

https://localrent.pl/journal/turkey/articles/toll-roads/

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/7615ea9b874b2986dc7f8fe9c09ed061cdcb635e
