### ISSUE TITLE
ovk.to

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#273]
#### Описание проблемы (Description of the problem):

Социалка. Ранее https://github.com/uBlockOrigin/uAssets/issues/22717

`https://ovk.to/`

<details>
<summary>Screenshot(s)</summary>

![2024-03-01_172215](https://github.com/easylist/ruadlist/assets/111344219/1b4a72da-fd3a-4454-b212-f3cc91fcab96)
</details>

#### Конфигурация (Configuration):

- OS/version: Windows 10 22H2
- Browser/version: Firefox 123.0
- Ad block extension/version: ABP 3.23

#### Используемые фильтры (Used filters):

<details>
<summary>Screenshot(s)</summary>

![2024-03-01_172215](https://github.com/easylist/ruadlist/assets/111344219/b01d3ec1-a220-4b93-a796-9a5be67ba602)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/c5b4266c7ad910ee93ed2d440c6a56ef5759f633
