### ISSUE TITLE
in-facts.info

### ISSUE THREAD

**Issue by eporubin** [easylist/ruadlist#279]
#### Описание проблемы (Description of the problem):
Hi, can you please allowlist this domain `montenegro.in-facts.info` for the existing filter in the list  `||static.localrent.com/widget/$third-party,domain=~localrent.pl`  the page owner complained the organic integrated widget on this page `https://montenegro.in-facts.info/en/cost-of-living-in-montenegro/` is hidden away from the user although it's a functionality the domain offers. 

`https://montenegro.in-facts.info/en/cost-of-living-in-montenegro/` 

<details>
<summary>Screenshot(s)</summary>
<img width="353" alt="image" src="https://github.com/easylist/ruadlist/assets/33602691/e5741322-52d8-4a74-86ae-fc36f7688e5f">

</details>

#### Конфигурация (Configuration):

- OS/version: macOS Sonoma V.14.4
- Browser/version: Google Chrome Version 122.0.6261.128
- Ad block extension/version: ABP Version number 3.25

#### Используемые фильтры (Used filters):

ABP Filters, RuAdList

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/2493ae43ca098eb103053a723f9bd79c828dbc6a
