### ISSUE TITLE
zetflix.io, zetflix.pro

### ISSUE THREAD

**Issue by shibby237** [easylist/ruadlist#28]
Здравствуйте. Прошу разблокировать домены раздачи iframe-video. Так как при включение адблоков (adblock, adblock+, udblock) а так же встроенные в браузеры блокировщики рекламы, плеер с видео остановится недоступен.

Сайты на которых обнаружена проблема: zetflix.io, zetflix.pro

Примеры страниц:

https://zetflix.pro/films/the-power-of-the-dog
https://zetflix.io/films/the-dig-2021
https://zetflix.io/films/io-2019

Разблокировать домены раздачи iframe-video:

tobaco.ws
multikland.net
synchroncode.com
mir-dikogo-zapada.com
embedstorage.net
placehere.link

Спасибо!

**Comment by dimisa-RUAdList** [comment]
Ок, исправлено:
https://github.com/easylist/ruadlist/commit/80cd525a6c2e31020c7ca211d20d9490e81a16fa
https://github.com/easylist/ruadlist/commit/55d0eb2dafc9994ab6b3036bb4c152e2ab8f4e9e

Изменения вступят в силу в течении 15 минут, после чего станут доступны при обновлении [вручную](https://forums.lanik.us/viewtopic.php?f=102&t=22786). В расширениях автоматом они раскатаются в течении 48 часов, во встроенных блокировщиках - в течении недели.
