### ISSUE TITLE
dtf.ru

### ISSUE THREAD

**Issue by Aculeasis** [easylist/ruadlist#280]
#### Описание проблемы (Description of the problem):
На новом дизайне косметический фильтр `dtf.ru##div:has(> div > [class^="skeleton-"] ~ [class^="skeleton-"])` ломает подгрузку постов (бесконечную прокрутку). После добавления в настройки исключения `~dtf.ru##div:has(> div > [class^="skeleton-"] ~ [class^="skeleton-"])` все работает нормально.
<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/easylist/ruadlist/assets/42580940/d57e8002-73e1-4479-9fda-5da3afb7d89f)
</details>

#### Конфигурация (Configuration):

- OS/version: Windows 10 Pro 22H2
- Browser/version: Firefox Browser 123.0.1
- Ad block extension/version: uBlock Origin 1.56.0

#### Используемые фильтры (Used filters):
<details>
<summary>Json из конфига</summary>

```
{
  "userSettings": {
    "externalLists": "https://filters.adtidy.org/extension/ublock/filters/1.txt\nhttps://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt\nhttps://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt\nhttps://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt\nhttps://www.fanboy.co.nz/enhancedstats.txt",
    "importedLists": [
      "https://filters.adtidy.org/extension/ublock/filters/1.txt",
      "https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt",
      "https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt",
      "https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt",
      "https://www.fanboy.co.nz/enhancedstats.txt"
    ],
  },
  "selectedFilterLists": [
    "ublock-quick-fixes",
    "user-filters",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-unbreak",
    "adguard-generic",
    "adguard-mobile",
    "easylist",
    "adguard-spyware",
    "easyprivacy",
    "urlhaus-1",
    "fanboy-thirdparty_social",
    "fanboy-social",
    "plowe-0",
    "RUS-0"
  ],  
}
```
</details>

**Comment by dimisa-RUAdList** [comment]
Насколько я понимаю, старого дизайна там сейчас нет в принципе. Проверять как работает ваша конфигурация, нет смысла. Подключением конфликтующих и заброшенных фильтров вы благополучно поломали работу блокировщика.

Что касается самой проблемы, то она наблюдается уже давно и не зависит от срабатывания указанного вами правила. Решается откручиванием ленты вверх, после чего она снова начинает подгружаться при прокрутке вниз. Отключение любого правила скрытия, приводящее к сдвигу ленты, даёт аналогичный эффект. Но при этом проблема не решается кардинально. Также к её решению не приводит даже полное отключение блокировки рекламы.

**Comment by Aculeasis** [comment]
Ну лично у меня это исключение чинит прокрутку, а вот прокрутка ленты вверх нет.

Еще выяснил что прокрутка не ломается если ты разлогинен, после логина и обновления страницы снова ломается. Если просто зайти в настройки и выйти не обновляя страницу, то прокрутка тоже временно починится. И изменение размеров окна браузера ее чинит, временно :)

> Подключением конфликтующих и заброшенных фильтров вы благополучно поломали работу блокировщика.

Если вы о внешних фильтрах, то ни один из них не был включен. На днях попробую воспроизвести баг на другом пк, с тем же набором фильтров и на чистой лисе.

<details>
<summary>Скрин фильтров</summary>

![image](https://github.com/easylist/ruadlist/assets/42580940/d7753ff1-8ee2-4c13-a43b-d1ecf7a495e6)

</details>

**Comment by dimisa-RUAdList** [comment]
Ещё раз повторю - это известная проблема, она появилась с новым дизайном и не зависит от браузера, блокировщика, аккаунта и пр. Этот баг, наряду с поиском и прочими, должен исправляться веб-мастерами сайта.
