### ISSUE TITLE
vk.com

### ISSUE THREAD

**Issue by LeonserGT** [easylist/ruadlist#282]
#### Описание проблемы (Description of the problem):
`https://vk.com/feed`

Начиная с 22.04.2024 внезапно полезла вся реклама в ленте ВК, которая раньше всегда успешно скрывалась, будто рубильником выключили. Учитывая малое количество подписок, лента наполовину в рекламе и в таком виде неюзабельна.

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/easylist/ruadlist/assets/49585618/0bc1e41d-f4d0-4860-b349-5feed1561371)
![image](https://github.com/easylist/ruadlist/assets/49585618/b5e18f3c-c524-4321-aa9d-1ff0ce7a0372)

</details>

#### Конфигурация (Configuration):

- OS/version: Microsoft Windows 10 Pro Version	10.0.19045 Build 19045
- Browser/version: Google Chrome Version 124.0.6367.61 (Official Build) (64-bit)
- Ad block extension/version: uBlock Origin 1.57.0

<details>
<summary>Используемые фильтры</summary>

![image](https://github.com/easylist/ruadlist/assets/49585618/bdee537a-6698-47e3-8833-55bf68658f36)

</details>

Единственный блокировщик, другие расширения: 
Return YouTube Dislike 3.0.0.16
Runet Censorship Bypass 0.0.1.63
Search by Image 6.1.2

**Comment by LeonserGT** [comment]
Какой мод? Все расширения перечислены. Неужели это про язык, который официальный ВКшный "советский"?
И проверял с отключенными всеми расширениями еще при открытии предыдущего тикета у самого юблока - не влияет.
Сам блокиратор сейчас переустановлю.

Также отмечу, что проблема исключительно в ВК, во всех остальных местах все хорошо - мейл.ру всегда мутили что-то темное со скриптами полиморфами для обхода блокировок (одна из причин ухода с их почты), мое подозрение что они что-то придумали и прорвали "оборону".

**Comment by dimisa-RUAdList** [comment]
Последние несколько лет в почте mail.ru никакой рекламы с uBlock Origin нет. Что касается vk, то когда они что-то обновляют в части рекламы, то сообщения о ней исчисляются сотнями в день. Сейчас этого нет, так что скорее всего, либо проблема имеет локальный характер, либо имеет место бета-тестирование, касающееся лишь небольшого числа аккаунтов, и пока проблема не станет массовой, воспроизвести её затруднительно.

Сделайте пожалуйста скрин элемента в инструментах разработчика.

1. Разверните окно браузера во весь экран, если не сделали этого ранее.

2. Кликните по целевому элементу правой кнопкой мыши и выберите в появившемся контекстном меню пункт "Просмотр кода элемента". 

3. В открывшихся инструментах разработчика кликните по трём точкам в правом верхнем углу и выставьте позиционирование окна инструментов так, чтобы оно располагалось в нижней части окна браузера, горизонтально.

4. Найдите в инструментах целевой элемент (он будет подсвечиваться при наведении на строку) и прокрутите строку с ним, чтобы она оказалась в самом низу видимой зоны окна. Это необходимо для того, чтобы были видны родительские элементы и иерархия.

<details>
<summary>Должно получить как-то так, сделано при отключенной блокировке.</summary>

![vkads](https://github.com/easylist/ruadlist/assets/20126984/fce27376-3166-4208-a85f-21061af550f6)

</details>

**Comment by LeonserGT** [comment]
Правильно сделал? Или что-то не захватил в кадр?
<details>
<summary>Скрин</summary>
![image](https://github.com/easylist/ruadlist/assets/49585618/bf5b5d98-96ec-4051-8350-9b8c5c00ccc7)
</details>

**Comment by LeonserGT** [comment]
Так, хотел по-хорошему, спрятать под кат, но что-то пошло не так и не редактируется...
![image](https://github.com/easylist/ruadlist/assets/49585618/77ad267b-b6c2-4b55-bc28-8a43040fc51e)

**Comment by dimisa-RUAdList** [comment]
Ок, попробуйте добавить в "Мои фильтры": `vk.com##._ads_block_data_w`

**Comment by LeonserGT** [comment]
Боже, помогло! Какое облегчение, сразу лента в два раза короче стала!

**Comment by dimisa-RUAdList** [comment]
Ок, добавил в RU AdList: https://github.com/easylist/ruadlist/commit/4becb0ca94a2d74cfe6344b128183f077407103c

Минут через 15 изменения вступят в силу и станут доступны при [обновлении вручную](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=all). Либо можно подождать и в течении 5 часов раскатается автоматом.

**Comment by LeonserGT** [comment]
Добрый день! Прошло 4+ месяца и все повторилось. Снова лезет реклама, прямо как тогда. Добавление _ads_blocks_data_w в фильтры больше не действует.
![image](https://github.com/user-attachments/assets/755d213d-c44b-40b3-b9db-cca8ab9fdcdd)

**Comment by dimisa-RUAdList** [comment]
Поменяйте в настройках аккаунта vk язык с советского на русский и проверьте, пропадёт ли реклама.

**Comment by LeonserGT** [comment]
Не пропала (слава богу, могу дальше советским наслаждаться 😬)

**Comment by dimisa-RUAdList** [comment]
Оставаясь на русском языке, попробуйте добавить в "Мои фильтры": 

`vk.com#?##feed_rows > div[class^="feed_row"]:-abp-has(> [id^="post-"] > ._post_content .PostHeader > .PostHeaderInfo > .PostHeaderSubtitle > .PostHeaderSubtitle__item:-abp-contains(/Community ad|Реклама |Рэклама | жарнама/))`

**Comment by LeonserGT** [comment]
Увы, все также лезет (язык не менял)

**Comment by dimisa-RUAdList** [comment]
Какой у вас язык установлен сейчас?

**Comment by LeonserGT** [comment]
Русский

**Comment by dimisa-RUAdList** [comment]
Ок, зайдите в панель управления uBlock Origin и кликните на вкладке "Списки фильтров" по иконке часов в строке RU AdList, удерживая клавишу Shift.

**Comment by LeonserGT** [comment]
Ничего не изменилось, кроме контента самой рекламы
![image](https://github.com/user-attachments/assets/bab266de-ca0c-4e7b-b806-60454762b824)

**Comment by dimisa-RUAdList** [comment]
Сделайте пожалуйста такой же скриншот, раскрыв иерархию элементов до бейджа «реклама».

**Comment by LeonserGT** [comment]
![image](https://github.com/user-attachments/assets/fafe0309-8f0b-41cf-b739-f3184ccf5aff)
Типа так?

**Comment by dimisa-RUAdList** [comment]
Нет, выделено должно быть именно само слово.

**Comment by LeonserGT** [comment]
Упс, не так понял, правильно сейчас?
![image](https://github.com/user-attachments/assets/fe859185-b975-4285-9cfd-1666e62feaa7)

**Comment by dimisa-RUAdList** [comment]
Да, теперь правильно. Попробуйте добавить в "Мои фильтры":

`vk.com#?##feed_rows > div[class^="feed_row"]:-abp-has(> [id^="post-"] > ._post_content .PostHeader > .PostHeaderInfo > .PostHeaderSubtitle > .PostHeaderSubtitle__item > .PostHeaderSubtitle__item > span ~ span ~ span ~ span ~ span)`

**Comment by LeonserGT** [comment]
Ура! Помогло!

**Comment by dimisa-RUAdList** [comment]
Ок, добавил в RU AdList: https://github.com/easylist/ruadlist/commit/70aa8ce5e59f924c0814180c7e1517840d2e0fc4

Минут через 15 изменения вступят в силу и станут доступны при обновлении вручную. Автоматом же раскатается в течении 5 часов.

**Comment by LeonserGT** [comment]
Спасибо, пожалуй добавлю этот тикет в закладки, через полгода увидимся снова 😂

**Comment by LeonserGT** [comment]
Такс, в этот раз продержалось гораздо меньше, тревожная тенденция. Или нет?
Странная хрень происходит - реклама то снова вылазит в ленте, то после обновления страницы исчезает. Или нет. Обычно 3-4 раза перезагрузить надо чтобы исчезло. Сейчас вот опять вылезло и не уходит.
Сразу повторил все шаги с прошлого раза, обновил лист, переключил на русский: 
![image](https://github.com/user-attachments/assets/08cfbc3d-fc5a-47d9-bec8-af3f774d6365)

**Comment by dimisa-RUAdList** [comment]
Поправил: https://github.com/easylist/ruadlist/commit/6cdff0ccaac5cf4aae224397589603aa78e9bc3f

**Comment by LeonserGT** [comment]
Спасибо, оперативно!

Пользуясь случаем - хотел бы попросить совета какой клиент ВК на андроид лучше использовать вместо невыносимого официального, в первую очередь который бы зачистил всю рекламу? В принципе, как адлист в браузере сейчас справляется 👀
Кейт мобайл (если еще жив) выглядит сильно урезанным и интерфейс будто из начала нулевых

**Comment by dimisa-RUAdList** [comment]
По мобильным - не подскажу, я поддерживаю только расширения для десктопных браузеров. Да и на ВК я попадаю только по запросу, когда начинает просачиваться реклама.

**Comment by CATIOR** [comment]
> какой клиент ВК на андроид лучше использовать

@LeonserGT, SOVA, VK mp3 mod. Я лично использую VTosters.

**Comment by LeonserGT** [comment]
И снова полезла эта параша. Все те же симптомы, все те же шаги что раньше, снова застряло окончательно:
![image](https://github.com/user-attachments/assets/fb381eed-ec43-4064-be25-daa87fc3d5ba)

**Comment by LeonserGT** [comment]
В прошлый раз когда я пошел ловить код по инструкции оно само убралось и больше не вылезало.

Но не надолго, снова вылезла эта херня, теперь выцепил код:
`<div class="feed_row "><div class="feed_post_indicator mailru-visibility-check BmYTVxTLCcyxWV1urCqf _6fA0YW0meJA3HUt5G7dw LNDxBXcR1IzN3cTr7YWo" post_view_hash="67be2b6057f86d70fa" data-media-type="img" theme="light"><div class="_post_content"><div class="post page_block deep_active Post--redesign tr3qkM6DleKaXm9orJ5n"><div class="PostHeader PostHeader--compact PostHeader--inPost js-PostHeader"><div class="AvatarRichContainer PostHeader__avatar"><span class="AvatarRich AvatarRich--sz-40 AvatarRich--shadow l2Q63U68RkAXQkXEoJnJ"><img class="AvatarRich__img" src="https://r0.mradx.net/imgs/bb/cd/49a482eff4abc43d.jpg" style="aspect-ratio: 1 / 1;"></span></div><div class="PostHeaderInfo PostHeaderInfo--inHeader"><div class="PostHeaderTitle l2Q63U68RkAXQkXEoJnJ"><div class="PostHeaderTitle__authorBlock"><h5 class="PostHeaderTitle__author"><span class="PostHeaderTitle__authorLink"><span class="PostHeaderTitle__authorName">Объясняем.РФ</span></span></h5></div></div><div class="PostHeaderSubtitle PostHeaderSubtitle--layoutDefault"><span class="PostHeaderSubtitle__item"><div class="PostHeaderSubtitle PostHeaderSubtitle--layoutDefault tr3qkM6DleKaXm9orJ5n"><span class="sO36#fFH">Социальна<span class="TXOZJriPrly1h0EVbsM2">wbbv35</span>я реклама</span><div class="format_edit inline tr3qkM6DleKaXm9orJ5n" aria-level="4">18+</div></div></span></div></div><div class="PostContextMenuReact__root PostContextMenu Efxztiz1tCs6S5IDhTuN"><div class="vkui__root"><div class="PostContextMenu__wrapper--v4eitt vkuiFlex vkuiFlex--align-center vkuiFlex--justify-center vkuiRootComponent"><button class="vkuiIconButton vkuiIconButton--sizeY-compact vkuiTappable vkuiTappable--hasPointer-none vkuiClickable__resetButtonStyle vkuiClickable__host vkuiClickable__realClickable vkui-focus-visible vkuiRootComponent"><svg aria-hidden="true" display="block" class="vkuiIcon vkuiIcon--24 vkuiIcon--w-24 vkuiIcon--h-24 vkuiIcon--more_horizontal_24 vkitgetColorClass__colorIconTertiary--yV1-BE" viewBox="0 0 24 24" width="24" height="24" style="width: 24px; height: 24px;box-sizing:content-box;"><use xlink:href="#more_horizontal_24" style="fill: currentcolor;"></use> </svg></button></div></div></div></div><div class="wall_text media_on_top_mailru media_on_top"><div class="MM77MZuw9JUXVWmX_A_V"><div class="g03FJ4dTToqroympKAMc"><div class="inline_video_wrap" style="width: 550px; height: 309px;"><img class="videoplayer_media_provider l2Q63U68RkAXQkXEoJnJ" src="https://r0.mradx.net/imgs/d6/40/410658cf896b6ef0.jpg" style="width: 100%; height: 100%; aspect-ratio: 1.77924 / 1;"><div class="videoplayer_ui _feed no_gradient"><div class="videoplayer_controls" style="bottom: var(--controls-bOffset, 0px);"><div class="videoplayer_controls_item videoplayer_timecode"></div><div class="videoplayer_controls_item videoplayer_btn videoplayer_btn_mute" style="gap: 8px;"></div></div></div></div></div><span class="l2Q63U68RkAXQkXEoJnJ"><div class="r4jouGh_Hfn9c5AzpbJg" style="background-color: rgb(164, 124, 84); box-shadow: none; color: rgb(255, 255, 255);"><div class="R51FgbECkOS_oK5K7RT1"><div>Подробнее</div><span><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 0 20 20"> <path fill-rule="evenodd" d="M7.3 4.3a1 1 0 0 1 1.4 0l5 5a1 1 0 0 1 0 1.4l-5 5a1 1 0 0 1-1.4-1.4l4.29-4.3-4.3-4.3a1 1 0 0 1 0-1.4Z" clip-rule="evenodd"></path> </svg></span></div></div></span></div><div class="wall_post_text l2Q63U68RkAXQkXEoJnJ"><span>Новые препараты включены в перечень жизненно необходимых лекарств. Какие изменения произошли и как это повлияет на доступность лечения? Подробности</span><button class="PostTextMore"><span class="PostTextMore__gradient"></span><span class="PostTextMore__content">Показать ещё</span></button><span style="display:none"> читайте на нашем сайте.</span></div></div></div></div></div></div>`

![Image](https://github.com/user-attachments/assets/4b8ffb7a-2a32-4d45-a466-c5a7b71a6930)

**Comment by LeonserGT** [comment]
Сначала несколько таких постов было чисто социалка, я подумал может ввели отдельные шаблоны под соц. рекламу чтоб ее не блокировалось, в принципе идея здравая. Но разве здравые идеи это про ВК? через пару апдейтов меняется на спам какой-то, так что там не только социалка

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/f53b37d9367545f2949e33e34bf94077d3169dda

**Comment by LeonserGT** [comment]
И снова. 
`<div class="feed_row " ill316mnz=""><div class="BmYTVxTLCcyxWV1urCqf _6fA0YW0meJA3HUt5G7dw LNDxBXcR1IzN3cTr7YWo" id="post-536531178_4509" data-post-id="post-536531178_4509"><div class="_post_content"><div class="post deep_active Post--redesign tr3qkM6DleKaXm9orJ5n" style="margin: 0 0 8px 0;background: var(--vkui--color_background_content)"><div class="PostHeader PostHeader--compact PostHeader--inPost js-PostHeader"><div class="AvatarRichContainer PostHeader__avatar"><span class="AvatarRich AvatarRich--sz-40 AvatarRich--shadow l2Q63U68RkAXQkXEoJnJ"></span></div><div class="PostHeaderInfo PostHeaderInfo--inHeader"><div class="PostHeaderTitle l2Q63U68RkAXQkXEoJnJ"><div class="PostHeaderTitle__authorBlock"><h5 class="PostHeaderTitle__author"><span class="PostHeaderTitle__authorLink"><span class="PostHeaderTitle__authorName">Альфа-Банк</span></span></h5></div></div><div class="PostHeaderSubtitle"><div class="FallBackTitle"></div></div></div><div class="PostContextMenuReact__root PostContextMenu Efxztiz1tCs6S5IDhTuN"><div class="vkui__root"><div class="PostContextMenu__wrapper--v4eitt vkuiFlex vkuiFlex--align-center vkuiFlex--justify-center vkuiRootComponent"><button class="vkuiIconButton vkuiIconButton--sizeY-compact vkuiTappable vkuiTappable--hasPointer-none vkuiClickable__resetButtonStyle vkuiClickable__host vkuiClickable__realClickable vkui-focus-visible vkuiRootComponent"><svg aria-hidden="true" display="block" class="vkuiIcon vkuiIcon--24 vkuiIcon--w-24 vkuiIcon--h-24 vkuiIcon--more_horizontal_24 vkitgetColorClass__colorIconTertiary--yV1-BE" viewBox="0 0 24 24" width="24" height="24" style="width: 24px; height: 24px;box-sizing:content-box;"><use xlink:href="#more_horizontal_24" style="fill: currentcolor;"></use> </svg></button></div></div></div></div><div class="wall_text"><div class="MM77MZuw9JUXVWmX_A_V"><div class="g03FJ4dTToqroympKAMc"><div class="inline_video_wrap" style="width: 550px; height: 309px;"><div class="videoplayer_ui _feed no_gradient"><div class="videoplayer_controls" style="bottom: var(--controls-bOffset, 0px);"><div class="videoplayer_controls_item videoplayer_timecode"></div><div class="videoplayer_controls_item videoplayer_btn videoplayer_btn_mute" style="gap: 8px;"></div></div></div></div></div><span class="l2Q63U68RkAXQkXEoJnJ"><div class="r4jouGh_Hfn9c5AzpbJg" style="border-color: rgb(240, 40, 40); background-color: rgb(240, 40, 40); color: rgb(255, 255, 255);"><div class="R51FgbECkOS_oK5K7RT1"><div>Пе<span class="TXOZJriPrly1h0EVbsM2">d0cex7</span>рейти</div><span><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 0 20 20"> <path fill-rule="evenodd" d="M7.3 4.3a1 1 0 0 1 1.4 0l5 5a1 1 0 0 1 0 1.4l-5 5a1 1 0 0 1-1.4-1.4l4.29-4.3-4.3-4.3a1 1 0 0 1 0-1.4Z" clip-rule="evenodd"></path> </svg></span></div></div></span></div><div class="wall_post_text l2Q63U68RkAXQkXEoJnJ">Комплекс услуг для ВЭД за 0 ₽.</div></div></div></div></div></div>`

![Image](https://github.com/user-attachments/assets/ed7cb0de-c5dc-4025-94eb-8163098f9545)
