### ISSUE TITLE
uniondht.org

### ISSUE THREAD

**Issue by DogancanYr** [easylist/ruadlist#283]
<details>
<summary>Screenshot(s)</summary>

![resim](https://github.com/easylist/ruadlist/assets/90002969/236f3603-dfa3-45af-85dd-ed9bc5532165)

</details>

**Comment by dimisa-RUAdList** [comment]
You completely ignored the issue form. In this case, I can't help you.

**Comment by dimisa-RUAdList** [comment]
From the screenshot I see that the RU AdList filter is not updated, and as a result, outdated rules are triggered.

**Comment by DogancanYr** [comment]
I updated it 3 minutes ago, but when I updated it now, the problem was solved.
