### ISSUE TITLE
rutor.org

### ISSUE THREAD

**Issue by PhoenixIndigo** [easylist/ruadlist#289]
#### Описание проблемы (Description of the problem):
На сайте `https://rutor.org/torrent/980548` нет бесплатных ссылок на загрузку торрентов бесплатно, так что нужно разблокировать бесплатные зеркала:
`http://new-rutor.org/torrent/981805/kung-fu-panda-4_kung-fu-panda-4-2024-web-dlrip-1080p-ot-exkinoray-d-p/`
мешающие правила
```adblock-filter-list
123torrent.ru,37.1.201.32,37.1.202.140,37.1.203.156,37.1.204.182,37.1.204.76,37.1.205.159,37.1.205.47,37.1.206.118,37.1.206.121,37.1.206.231,37.1.206.95,37.1.207.130,37.1.207.65,37.1.216.106,37.1.216.119,37.1.217.105,37.1.217.113,5.45.65.153,5.45.66.118,5.45.70.162,5.45.86.39,5.45.87.85,berutor.site,blackrutor.site,extrutor.org,extrutor.site,fastrutor.site,hawk.live,herutor.org,listrutor.org,new-rutor.org,pipitor.org,pronpic.org,prutor.site,r-tor.ru,rutor-live.tk,rutor-search.info,rutor1.site,tracker-rutor.tk,xrutor.org##:not(obhod-adblocka)
$third-party,domain=123torrent.ru|37.1.201.32|37.1.202.140|37.1.203.156|37.1.204.182|37.1.204.76|37.1.205.159|37.1.205.47|37.1.206.118|37.1.206.121|37.1.206.231|37.1.206.95|37.1.207.130|37.1.207.65|37.1.216.106|37.1.216.119|37.1.217.105|37.1.217.113|5.45.65.153|5.45.66.118|5.45.70.162|5.45.86.39|5.45.87.85|berutor.site|blackrutor.site|extrutor.org|extrutor.site|fastrutor.site|herutor.org|listrutor.org|new-rutor.org|pipitor.org|pronpic.org|prutor.site|r-tor.ru|rutor-live.tk|rutor-search.info|rutor1.site|tracker-rutor.tk|xrutor.org|znaipticu.ru

``` 

<details>
<summary>Screenshot(s)</summary>

</details>

#### Конфигурация (Configuration):

- OS/version: Win1123H2
- Browser/version: Firefox:126
- Ad block extension/version: uBlock Origin: 1.57.2

#### Используемые фильтры (Used filters):
`https://pastebin.com/u/GodIndigo`

**Comment by dimisa-RUAdList** [comment]
Упоминание возможности бесплатного скачивания подразумевает наличие платного. Если же платного скачивания нет, обсуждать бесплатное попросту бессмысленно. 

По сути вопроса. Вы уже задавали это вопрос. Дубль: https://github.com/easylist/ruadlist/issues/117

Фейковые зеркала `rutor.info`, практикующие обход адблока с целью продвижения вредоносного ПО и прочей дряни, не будут разблокированы никогда. Единственное истинное зеркало - `rutor.is`.

**Comment by PhoenixIndigo** [comment]
На rutor.org скакчивание платное, почему разблокировано. В фильмах ПО нет. Лучше екламой вредоносного ПО займитесь. Про rutor.info не указано, спасибо.
На 
`http://new-rutor.org/torrent/922786/the-long-drive-v-2023.05.02-nonvr-multi-early-access-2019-pc-repack-ot-pioneer/`
как и на
`https://rutor.info/torrent/922786/the-long-drive-v-2023.05.02-nonvr-multi-early-access-2019-pc-repack-ot-pioneer`
 ничего лишнего никакого вредоносного ПО где оно?

**Comment by dimisa-RUAdList** [comment]
По фейкам рутора вопрос закрыт навсегда. Их все генерит один и тот же веб-мастер, и обход адблока с целью продвижения разных гадастей практикует годами. Если какие-то из фейков прямо сейчас загажены меньше обычного, это не значит, что так будет и далее. Скорее всего идёт просто поиск нового решения. Поэтому обсуждения разблокировки фейков не будет.

Что касается `rutor.org`, являющегося согласно заголовку пруфом для обсуждения, приведите пожалуйста пример страницы, на которой применяется платное скачивание, о котором вы говорите. По ссылке из стартового сообщения я вижу необходимость регистрации, а не оплаты.

**Comment by PhoenixIndigo** [comment]
`
https://bugmenot.com/view/rutor.org
`
<details><summary>Screenshot(s)</summary>
<p>

![](https://github.com/easylist/ruadlist/assets/107413021/bef84230-30e1-4128-9685-d37e5d809f56)

</p>
</details>

**Comment by dimisa-RUAdList** [comment]
А, так у них после регистрации ещё нужно оплатить подписку? В таком случае пользователи должны принимать решения самостоятельно, либо платить, либо использовать бесплатные альтернативы, типа `rutracker.org`, `rutor.info`, `nnmclub.to` и пр. Но к блокировке рекламы подобный выбор не относится.

**Comment by PhoenixIndigo** [comment]
Проверьте пожалуста
123torrent.ru,37.1.201.32,37.1.202.140,37.1.203.156,37.1.204.182,37.1.204.76,37.1.205.159,37.1.205.47,37.1.206.118,37.1.206.121,37.1.206.231,37.1.206.95,37.1.207.130,37.1.207.65,37.1.216.106,37.1.216.119,37.1.217.105,37.1.217.113,5.45.65.153,5.45.66.118,5.45.86.39,5.45.87.85,berutor.site,blackrutor.site,extrutor.org,extrutor.site,fastrutor.site,hawk.live,herutor.org,listrutor.org,pipitor.org,prutor.site,r-tor.ru,rutor-live.tk,rutor1.site,tracker-rutor.tk,xrutor.org
Некоторые неработают, некоторые пустые, некоторые переводят на фейк, например на sssrtor.ru
rutor-search.info теперь не фейк с рекламой

**Comment by dimisa-RUAdList** [comment]
Я уже не раз сталкивался с возобновлением функционирования не работавших на момент проверки доменов из этой группы, поэтому правила для них могут быть удалены, если только по этим адресам начнут работать реально другие сайты. `rutor-search.info` - это прокладка для транзита на помойку, какой она и была на момент блокировки. `sssrtor.ru` заблокировал: https://github.com/easylist/ruadlist/commit/4c254c21c0a27c13e243c8238c9a7ab6eafe5a1c
