### ISSUE TITLE
drp.su

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#292]
> uBlock Origin предотвратил загрузку следующей страницы:
```
http://driverpack.io
https://driverpack.io
http://drp.su
https://drp.su
```
но если нажать продолжить, то открывается просто пустая страница.

сайт полезен, хотелось бы чтобы работал нормально.

**Comment by dportvine** [comment]
Ознакомьтесь https://forums.lanik.us/viewtopic.php?f=102&t=44348-drp-su

**Comment by trup** [comment]
ну касперский же говорит что это Not-a-virus.
режим эксперта всё же есть, и с этим режимом проблем у юзера не будет.
любой программой надо уметь пользоваться, а то и диск форматнуть можно из контекстного меню в проводнике ;)

**Comment by dimisa-RUAdList** [comment]
На форуме RU AdList причины блокировки [указаны](https://forums.lanik.us/viewtopic.php?f=102&t=44348-drp-su) более чем подробно. Разработчики в курсе, знают что нужно исправить и куда писать. До тех пор, пока это не произойдёт, домены останутся заблокированы.

**Comment by trup** [comment]
> Ознакомьтесь https://forums.lanik.us/viewtopic.php?f=102&t=44348-drp-su
> 
> > сайт полезен, хотелось бы чтобы работал нормально.
> 
> Без вирусов и прочей ерунды `https://sdi-tool.org/?lang=ru`.

спасибо за ссылку, отличная прога!
