### ISSUE TITLE
avtodom.by

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#293]
`https://avtodom.by`

![avtodom](https://github.com/easylist/ruadlist/assets/3046716/6e02be03-00bf-4007-8fcf-942cb7b93e5d)

п.с. в названии листа указаны ru, ua, uz, kz. а почему не указан by? домены by в нём есть.

**Comment by dimisa-RUAdList** [comment]
Ok: https://github.com/easylist/ruadlist/commit/ae01f912155bb3f05666fcd9510438acb06f9b9b

Указание регионов, обслуживаемых фильтром, ограничено четырьмя самыми населёнными.
