### ISSUE TITLE
domclick.ru

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#294]
`https://domclick.ru`
<details>
<summary>Screenshot(s)</summary>

![Безымянный](https://github.com/easylist/ruadlist/assets/3046716/41c45ebb-1419-472e-97d9-0bfdbac17270)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/a14f41825fd7f5037513ed7ca97fbf08c87586c8
