### ISSUE TITLE
google.com

### ISSUE THREAD

**Issue by erhenjt** [easylist/ruadlist#295]
#### Описание проблемы (Description of the problem):
When BitBlock list is enabled, Google search would break.

Steps:
1. Go to https://www.google.com
2. Search any thing
3. Click `Tools` -> `Any time` -> `Custom range...`
4. Custom date range selector won't show up

#### Конфигурация (Configuration):

- OS/version: Windows 11
- Browser/version: Edge 125.0.2535.92 (Official build) (64-bit)
- Ad block extension/version: uBlock Origin 1.58.0

#### Используемые фильтры (Used filters): bitblock.txt (https://easylist-downloads.adblockplus.org/bitblock.txt)

All other extensions and filters are disabled.

**Comment by dportvine** [comment]
Блокируется скролл при запросе из адресной строки. `044 591 3909`. Куки нужно удалять.

```adblock
www.google.*##html[itemtype="http://schema.org/SearchResultsPage"][style^="top: "] #main > #cnt > #lb:has(update-location):style(display: none !important)
```

<details>
<summary>Screen</summary>

![2024-08-12_115916](https://github.com/user-attachments/assets/1853ccbb-db7f-4502-a97d-af6a77c32cbc)
![2024-08-12_121341](https://github.com/user-attachments/assets/64d26de3-9fca-430f-9d2f-d53da8ad6127)
</details>

**Comment by dportvine** [comment]
Пускай будет тогда, как есть.

**Comment by dimisa-RUAdList** [comment]
На самом деле, лучше уж пускай разово прокручивается полностью страница, нежели пользователи столкнутся с поломкой. До конца дня поменяю.

**Comment by dportvine** [comment]
Маркеры. 

`https://www.google.com/search?q=time`

<details>
<summary>Video</summary>

https://github.com/user-attachments/assets/30ae7523-3d45-4e3f-af38-873f43687dc8
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/85e57a576400cf1904305d7dba894a60500a48f9
