### ISSUE TITLE
mamba.ru

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#296]
`https://www.mamba.ru/ru`
<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/easylist/ruadlist/assets/3046716/ccc00a9c-7f39-4048-9c19-6114eb10714f)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/e8b2d25cdb66de9e5de82e607712ab92a72b1b40

**Comment by trup** [comment]
опять.

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/bc1a6342f3f140b3784d8ef65da7e676343012a7

**Comment by dimisa-RUAdList** [comment]
Актуализировал правила для домена: https://github.com/easylist/ruadlist/commit/f2d05fac79611ffd18fafe13ecdbdf8532f52005

**Comment by Twilightssuperb** [comment]
Обновил RU AdList, но баг остался при просмотре анкет по ссылкам mamba.ru/profile/*. Заодно обнаружил, что есть какой-то затык с аналитикой Яндекса. Возможно, она в свою очередь вызывает белый экран:
<details>

![Image](https://github.com/user-attachments/assets/36370622-a762-41a4-a77b-fcffafe99b27)
</details>

Или не она... Логгер пишет следующее:
<details>

![Image](https://github.com/user-attachments/assets/e0739ef3-19cf-4dea-97cc-c8215fb5e9b7)
</details>

**Comment by Twilightssuperb** [comment]
Переустановил uBO с бэкапом настроек, кажется, заработало.

Просто парадоксально, что в режиме инкогнито, (или) когда я не залогинен на Мамбе, проблем с включённым uBO нет.
