### ISSUE TITLE
zagonkov.gb.net

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#297]
`http://zagonka2.zagonkov.gb.net/30215-2_osoboe-mnenie-2001-onlayn.html`
домен у них частенько блокируется и меняется.
на скринах - пустые блоки после удаления рекламы.
<details>

<summary>Screenshot(s)</summary>

![изображение](https://github.com/easylist/ruadlist/assets/3046716/43fbdd5a-038b-41f2-93a6-4d808123efac)
![изображение](https://github.com/easylist/ruadlist/assets/3046716/693fe67e-b08e-45a4-856e-4781d994a7e9)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/d9d95ace0ac64bb8bfcfb7f94c47966ee92113bf
