### ISSUE TITLE
roscontrol.com

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#298]
`https://roscontrol.com/product/karp-perekrestok-givoy/`
баннера нет, а кнопка "закрыть" осталась.

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/easylist/ruadlist/assets/3046716/feb9b6de-ca9c-4ec3-a5a3-fec942a3ed08)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/56dc91890414587727b322ea8bcd0f84d7ee6408
