### ISSUE TITLE
magnit.ru

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#299]
`https://magnit.ru`
баннеры с акциями магнита блокируются, надо бы исключение.

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/easylist/ruadlist/assets/3046716/5aece1f0-981a-4b65-a388-6d5c0c1eaeaa)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/25b60453a0b496be61eb84f32faaba12f37d59cd
