### ISSUE TITLE
icons8.ru

### ISSUE THREAD

**Issue by P0Rtvine** [easylist/ruadlist#3]
### Перечислите веб-сайт(ы), с которым(и) у вас возникли проблемы:
`https://icons8.ru/icon/pack/cultures/doodle`

### Что происходит?
Рекламный баннер, кликабельный, ведет на другой сайт.
![2020-10-06_203838](https://user-images.githubusercontent.com/57287308/95239691-fdc6d800-0813-11eb-91cd-513a6a8c39cb.png)

### Список используемых вами подписок:
![2020-10-06_200541](https://user-images.githubusercontent.com/57287308/95236290-68c1e000-080f-11eb-858f-43e5d3dbeb6b.png)

### Ваши настройки

- ОС/версия: Win 8.1 x64
- Браузер/версия: Opera|Stable(85.0.4183.121)
- Расширение/Adblock|uBO: uBO 1.30.0

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/8a63ce6664a554b983f635d6fcaddce16092c375
