### ISSUE TITLE
lemanapro.ru

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#300]
`https://lemanapro.ru`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/easylist/ruadlist/assets/3046716/9e7429af-db3e-40d0-b50e-d0a563ab6c10)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/c259e03ceac5363123cb40d32f9a933d4ce1d836
