### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by Tsuchimikado** [easylist/ruadlist#305]
#### Описание проблемы (Description of the problem):

После добавления в uBlock Origin списка RU AdList: Counters на ютубе у некоторых видео перестала запоминаться позиция просмотра.
В [логгере](https://github.com/gorhill/uBlock/wiki/The-logger) видно что периодически блокируются запросы на страницу `youtube.com/generate_204` и совершенно нет запросов на `/api/stats/watchtime`. После закрытия вкладки идёт единственный запрос на `/api/stats/watchtime` и скорее всего именно он иногда не доходит или игнорируется.
После добавления в пользовательские фильтры исключения `@@||youtube.com/generate_204$xhr,domain=youtube.com` отсылка позиции просмотра видео начинает работать.

#### Конфигурация (Configuration):

- OS/version: Windows 10 19044.4529
- Browser/version: Firefox 127.0.1
- Ad block extension/version: uBlock Origin 1.58.0

#### Используемые фильтры (Used filters):

uBlock filters – Ads
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Quick fixes
uBlock filters – Unbreak
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Peter Lowe’s Ad and tracking server list
ru ua uz kz: RU AdList
RU AdList: Counters
в пользовательских фильтрах `youtube.com/live_chat_replay`

**Comment by dimisa-RUAdList** [comment]
Опишите пожалуйста, что это за функция, "запоминание позиции просмотра"? Она включается в настройках аккаунта, или она доступна без авторизации?

**Comment by Tsuchimikado** [comment]
Это встроенная включённая по умолчанию (и вроде бы даже неотключаемая) функция ютуба которая запоминает на какой временной позиции в видео пользователь прекратил просмотр видео и автоматически продолжает воспроизведение с этой точки при следующем открытии видео.
Например, пользователь смотрел видео и на позиции четыре часа восемь минут пятнадцать секунд в видео операционная система решает перезагрузиться для применения обновлений. После перезагрузки пользователь открывает то же самое видео и оно автоматически стартует с позиции на которой был прерван просмотр - четыре часа восемь минут пятнадцать секунд.
Без авторизации эта функция вроде бы не доступна и есть только индикация просмотренных видео в вертикальном столбике справа от плеера.

**Comment by dimisa-RUAdList** [comment]
Что-то не стартует, даже без блокировщика. Вероятно, должно быть выполнено одно или несколько условий, типа определённой версии браузера, ip страны, геопринадлежности аккаунта, и пр. Либо в настройках аккаунта YouTube или Google необходимо активировать определённые параметры персонализации. Опишите пожалуйста конфигурацию, при использовании которой у вас работает эта функция.

**Comment by Tsuchimikado** [comment]
> Опишите пожалуйста конфигурацию, при использовании которой у вас работает эта функция.

Любая без списка RU AdList: Counters.
Скорее всего у вас что-то дополнительно настроено блокировать доступ к странице `youtube.com/generate_204`.
Вот так выглядят скриншоты логгера с включённым и отключённым списком RU AdList: Counters.
[![FastPic.Ru](https://i123.fastpic.org/thumb/2024/0625/9f/_f5f9fc99488fddfcdbcbe68a8a3c4f9f.jpeg)](https://fastpic.org/view/123/2024/0625/_f5f9fc99488fddfcdbcbe68a8a3c4f9f.png.html)
С включённым списком есть только блокированные запросы на `youtube.com/generate_204`.
После выключения списка восстанавливается доступ к странице `youtube.com/generate_204` и сначала идёт одномоментная отправка всех накопившихся позиций просмотра на `/api/stats/watchtime`, а потом регулярная.
В системном браузере Edge основанном на Chromium такая же ситуация.

**Comment by dimisa-RUAdList** [comment]
Я проверяю с дефолтными настройками актуальных стабильных версий браузеров Google Chrome и Firefox для Win и Mac, без установки каких-либо расширений, аккаунт Google/YouTube русский, ip российский, и функция запоминания позиции просмотра при этом не работает.

Вероятно, должно быть выполнено одно или несколько условий, типа ip страны, геопринадлежности аккаунта, и пр. Либо в настройках аккаунта YouTube или Google необходимо активировать определённые параметры персонализации. Опишите пожалуйста конфигурацию, при использовании которой у вас работает эта функция.

**Comment by Tsuchimikado** [comment]
> выполнено одно или несколько условий

> активировать определённые параметры персонализации

Повторюсь, это встроенная функция включённая по умолчанию. Если у вас она не работает, то либо ютуб проводит какой-то эксперимент, либо вы сами изменили настройки вроде [очистки истории просмотра](https://support.google.com/youtube/answer/7174115?hl=en).

**Comment by dimisa-RUAdList** [comment]
Во всех онлайн-плеерах запоминание позиции просмотра работает приблизительно одинаково - при повторном открытии адреса видео воспроизведение стартует с момента остановки, либо появляется предложение это сделать.

В случае с YouTube ничего из этого не происходит, видео каждый раз начинает проигрываться с самого начала. Вход в аккаунт, у которого активна история просмотра и отключение средств блокировки, на ситуацию влияния не оказывают.

Однако, поскольку YouTube практикует геозависимые принципы предоставление функционала, запоминание позиции просмотра может быть попросту отключено, как это сделано для рекламы на Россию. Укажите пожалуйста геопринадлежность аккаунта Google/YouTube и ip, при использовании которых функция запоминания позиции просмотра работает должным образом.

**Comment by dimisa-RUAdList** [comment]
Закрыто в связи с отсутствием обратной связи
