### ISSUE TITLE
vprok.ru

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#307]
`https://www.vprok.ru`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/easylist/ruadlist/assets/3046716/48978846-742a-4d62-8903-d59975cffa40)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/63849d4c394e71cab9d6047e0e2d50e1646c35c9
