### ISSUE TITLE
stentex.ru

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#308]
`https://stentex.ru`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/easylist/ruadlist/assets/3046716/d66b0efe-ef9a-4d17-b617-42c46d72205d)

</details>

**Comment by dimisa-RUAdList** [comment]
Укажите пожалуйста конфигурацию так, как это предусмотрено стартовой формой issue.

**Comment by trup** [comment]
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 145187
 cosmetic: 136348
 scriptlet: 29380
 html: 2141
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 25233-22, 17h.37m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1722-20, 3h.37m
  fanboy-cookiemonster: 51244-385, 5d.4h.21m
  ublock-annoyances: 5872-68, 2h.37m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 38993-117, 2h.37m Δ
  ublock-badware: 8938-0, 2h.37m Δ
  ublock-privacy: 929-11, 2h.37m Δ
  ublock-unbreak: 2423-7, 2h.37m Δ
  ublock-quick-fixes: 109-5, 2h.37m Δ
  easylist: 87387-203, 2h.37m Δ
  easyprivacy: 51101-367, 2h.37m Δ
  RUS-0: 40663-261, 3h.37m Δ
filterset (user): [empty]
switchRuleset:
 removed:
  no-csp-reports: * true
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 311574 ms (selfie)
 maxAssetCacheWait: 746 ms
 cacheBackend: indexedDB

**Comment by dimisa-RUAdList** [comment]
Оу, я вижу у вас подключен fanboy-cookiemonster (EasyList/uBO – Cookie Notices). В таком случае лучше сообщить об этом случае в ветке [EasyList](https://github.com/easylist/easylist/issues), указав что подключен данный фильтр.

BitBlock подчищает там, где фильтры fanboy недорабатывают, но это касается только крупных и посещаемых ресурсов. Добавлять правила для маленьких или непопулярных сайтиков, превращая BitBlock в региональный филиал специализированных фильтров - цели никогда не стояло.

**Comment by trup** [comment]
вроде добавили https://github.com/easylist/easylist/issues/19424
но чего то результата я не вижу.

**Comment by dimisa-RUAdList** [comment]
Для принудительного обновления одного конкретного фильтра, нужно на вкладке "Списки фильтров" кликнуть по иконке часов в строке целевого фильтра, удерживая клавишу Shift.

**Comment by trup** [comment]
вот я и не вижу эффекта...
