### ISSUE TITLE
relax-fm.ru [big nasty ad placeholder at the bottom]

### ISSUE THREAD

**Issue by felix-22** [easylist/ruadlist#31]
![e](https://user-images.githubusercontent.com/75935068/140336431-619f40db-e708-424a-b1bc-a218f7ac8a58.png)

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/5b82d30343f49c1b1d5c27ac24d5c9700e70cc73#diff-4678692434e861bd0921111ae2d0afe0b9df10888aefd920427539f68d3da868R6353
