### ISSUE TITLE
zaycev.net

### ISSUE THREAD

**Issue by PhoenixIndigo** [easylist/ruadlist#310]
#### Описание проблемы (Description of the problem):
Блокируется воспроизведение из-за: RU AdList
```adblock-filter-list
||dl.zaycev.net/$badfilter
``` 

<details>
<summary>Screenshot(s)</summary>

</details>

#### Конфигурация (Configuration):

- OS/version: Win11 23H2
- Browser/version: Firefox 127.0.2
- Ad block extension/version: uBlock Origin 1.58.0

#### Используемые фильтры (Used filters):
`https://pastebin.com/u/GodIndigo`

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/fba92bc399227a710861b7acc61e35a5080476d7
