### ISSUE TITLE
e.mail.ru

### ISSUE THREAD

**Issue by SashaXser** [easylist/ruadlist#311]
#### Описание проблемы (Description of the problem):
Место, где ранее были скрыты баннеры, теперь стало видимым. Та же проблема возникает при использовании Firefox Nightly на моем телефоне.

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/easylist/ruadlist/assets/24498484/1e337a58-ce4d-41a7-9470-bd7c6e99380c)

</details>

#### Конфигурация (Configuration):

- Browser/version: Firefox Nightly
- Ad block extension/version: uBlock Origin 1.58.0

**Comment by dimisa-RUAdList** [comment]
Какие ещё средства фильтрации контента используются помимо uBlock Origin?

**Comment by SashaXser** [comment]
> Какие ещё средства фильтрации контента используются помимо uBlock Origin?

Возможная проблема связана с включенным бета-тестированием. Если его отключить, все работает корректно. Вероятно, причина кроется в сдвигах CSS или других стилистических элементах, которые применяются в бета-версии.

**Comment by dimisa-RUAdList** [comment]
В таком случае это не проблема фильтров. Их отладка в бета-версиях браузеров не производится и не планируется в будущем.

**Comment by SashaXser** [comment]
> В таком случае это не проблема фильтров. Их отладка в бета-версиях браузеров не производится и не планируется в будущем.

Ладно...
![image](https://github.com/easylist/ruadlist/assets/24498484/9a60f6ad-0e33-4997-8b38-84540cac9014)

**Comment by dimisa-RUAdList** [comment]
Главным условием для воспроизведения проблемы является её описание. Упоминание ночных сборок FF и бета-тестирования указывает в первую очередь на браузер. Если бы вы не разместили скриншот, я бы так и не узнал, что это касается самого сервиса почты.

Поправил для стабильных версий десктопных браузеров. В остальных конфигурациях правила работают "как есть".
