### ISSUE TITLE
planetazdorovo.ru

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#312]
`https://planetazdorovo.ru`
если только про куки нельзя убрать, то лучше ничего не убирать.

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/easylist/ruadlist/assets/3046716/77d887f7-f060-4db3-8868-fba8f5fe4e36)

</details>

**Comment by dimisa-RUAdList** [comment]
Поясните пожалуйста, что означает ваш комментарий?

**Comment by dimisa-RUAdList** [comment]
Что-то не вижу там ничего про куки. Да и на вашем скрине отображается строка о рекомендательных технологиях. Возможно, вы имеете ввиду её?

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/cc8cf5b39ec5730afd2a9f7e5402fe6900d92884

**Comment by trup** [comment]
на `https://planetazdorovo.ru/lk/signin/` опять вылезло.

**Comment by dimisa-RUAdList** [comment]
Непонятно о чём речь. Визуально проблема не повторяется, строка о рекомендательных технологиях отсутствует.

**Comment by trup** [comment]
по указанной ссылке опять было уведомление о рекомендательных технологиях. но сейчас уже нет. странно.

**Comment by trup** [comment]
понял.
есть уведомление про цены на сайте...
если его закрыть, появляется сообщение о рекомендательных технологиях.

**Comment by dimisa-RUAdList** [comment]
Оба этих уведомления не имеют никакой информационной ценности. 

Переделал, дабы скрывались оба: https://github.com/easylist/ruadlist/commit/d412c928388140b4a066a9b9783628536bc38940

**Comment by dimisa-RUAdList** [comment]
Я писал [совсем о другом](https://github.com/easylist/ruadlist/issues/308#issuecomment-2195602660). Случай, который применим только для uBlock Origin с подключенным фильтром EasyList/uBO – Cookie Notices и предупреждением о куки на малопосещаемых сайтиках, некорректно экстраполировать на другие блокировщики, где этого фильтра в принципе нет в опциях, а ресурс достаточно популярен.

**Comment by trup** [comment]
так куда лучше репортить на куки простому юзеру?

**Comment by dimisa-RUAdList** [comment]
О сайтах с массовым посещением - сюда. Если же речь идёт о сайтах компаний, на которые заходят только их собственные сотрудники и пара десятков клиентов, то засорять фильтры правилами для подобных случаев вообще нет никакого смысла, со следующего года у 2/3 пользователей блокировщиков начнут действовать лимиты MV3, в результате чего "раздутые" фильтры придётся отключать, чтобы сохранить работоспособность расширения. Но если есть неудержимое желание поучаствовать в раздутии фильтра, то лучше чтобы он был по крайней мере профильный по назначению, а решение о добавлении правила принимал его автор.
