### ISSUE TITLE
knmoloko.ru

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#313]
`https://knmoloko.ru`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/easylist/ruadlist/assets/3046716/ca884e02-4d9f-400a-86f7-8a6e7eed54b1)

</details>

**Comment by dimisa-RUAdList** [comment]
Не повторяется

**Comment by trup** [comment]
ошибся ссылкой.
`https://knmoloko.ru/produktsiya`

**Comment by dimisa-RUAdList** [comment]
Как я уже [писал ранее](https://github.com/easylist/ruadlist/issues/308#issuecomment-2195602660), добавлять правила для маленьких или непопулярных сайтиков, превращая BitBlock в региональный филиал специализированных фильтров - цели никогда не стояло. Поэтому если вы хотите зачистить от предупреждений куки десятки тысяч сайтов комбинатов, компаний, микро-магазинчиков и пр. - лучше сразу пишите [авторам профильных фильтров](https://github.com/easylist/easylist/issues), специально для этого предназначенных.

В данном случае, в **EasyList/uBO – Cookie Notices** требуется добавить общее правило:
`##div[data-storage-item^="t887cookiename_"]`. Кстати, `##div[data-storage-item^="t886cookiename_"]` там уже есть.
