### ISSUE TITLE
esputnik.com

### ISSUE THREAD

**Issue by Riddlegun** [easylist/ruadlist#314]
#### Описание проблемы (Description of the problem):
Не работает превью виджетов-диалогов на списке виджетов и редактор виджетов-диалогов. [Редактор виджетов](https://esputnik.com/forms-ui/#/form/13787/variant/13787/appearance). Причина в этом коммите https://github.com/easylist/ruadlist/commit/56afa30e79a6c602d7d08b9bf0a9d742ea5d4961

<details>
<summary>Screenshot(s)</summary>

![Screenshot_1](https://github.com/easylist/ruadlist/assets/18221577/447153f1-0130-4134-afb6-fcdfef1e05bf)

</details>

#### Конфигурация (Configuration):

- OS/version: Windows 10, 22H2
- Browser/version: Google Chrome 126.0.6478.127
- Ad block extension/version: uBlock Origin 1.58.0

#### Используемые фильтры (Used filters):

Все фильтры отключены, кроме RU AdList.
Title: RU AdList for uBO only
Expires: 4 days
Last modified: Thu, 11 Jul 2024 10:24:57 +0000
Diff-Path: ../patches/2024.7.11.624.patch#ruadlist
Diff-Expires: 5 hours
License: https://github.com/dimisa-RUAdList/RUAdListCDN/blob/main/LICENSE
*** ruadlist:RuAdList-uBO.txt ***
*** ./advblock/adservers.txt ***

**Comment by dimisa-RUAdList** [comment]
Без аккаунта отладка невозможна. Попробовал пока поправить так: https://github.com/easylist/ruadlist/commit/f057bb4e78790218035cfcf3b01545d36fd983ae

Минут через 15 изменения вступят в силу и будут доступны для вытягивания при обновлении. Для принудительного обновления одного конкретного фильтра, нужно на вкладке "Списки фильтров" кликнуть по иконке часов в строке целевого фильтра, удерживая клавишу Shift.

**Comment by ksufinski** [comment]
@dimisa-RUAdList still the same result

<details>
  <summary>expected</summary>
<img width="2060" alt="image" src="https://github.com/easylist/ruadlist/assets/11694954/b1e42991-12fe-4e80-b626-5f7ee52e700e">

</details>

<details >
  <summary>actual</summary>
<img width="2060" alt="image" src="https://github.com/easylist/ruadlist/assets/11694954/0e9bb146-8392-41cd-b92f-7b9657dfff90">


</details>

**Comment by Riddlegun** [comment]
после последней правки всё заработало, спасибо
