### ISSUE TITLE
yandex.ru

### ISSUE THREAD

**Issue by CATIOR** [easylist/ruadlist#315]
#### Описание проблемы (Description of the problem): 

`https://yandex.ru/images/touch/search?text=Додо+пицца`

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2024-07-12-21-59-07-06_893286cdd908a61bf33b4bc1d9b44b3c](https://github.com/user-attachments/assets/afcd46e8-a92e-4453-b2d5-aeb56d260ad8)

</details>

#### Конфигурация (Configuration):

- OS/version: Android
- Browser/version: Edge Canary 128.0.2617.0
- Ad block extension/version: uBlock Origin 1.57.2

#### Используемые фильтры (Used filters):

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2024-07-12-22-04-04-32_893286cdd908a61bf33b4bc1d9b44b3c](https://github.com/user-attachments/assets/3b229984-6823-4076-bef6-be72b4a09426)
![Screenshot_2024-07-12-22-04-13-63_893286cdd908a61bf33b4bc1d9b44b3c](https://github.com/user-attachments/assets/e54ef1ba-fa83-4efd-8f03-271ecc58c4c1)

</details>

**Comment by dimisa-RUAdList** [comment]
В десктопной версии - не повторяется. Для мобильных версий правила не проверяются, они там работают "как есть". Закинул пару пару правил, но не факт, что это поможет в вашем случае: https://github.com/easylist/ruadlist/commit/832e3941f64a2b3c6dc2e49e7dfc91dc684166b2

**Comment by CATIOR** [comment]
> Закинул пару пару правил

Благодарю. Реклама пропала! ❤️
Проблема решена ✅
