### ISSUE TITLE
howdyho.net

### ISSUE THREAD

**Issue by CbumDino** [easylist/ruadlist#316]
#### Описание проблемы (Description of the problem):
Blank domain.

<details>
<summary>Screenshot(s)</summary>
<img width="1345" alt="Screenshot 2024-07-16 at 15 55 07" src="https://github.com/user-attachments/assets/1d05ace0-c189-42f3-8fc4-ddfff3f9cbc0">

</details>

#### Конфигурация (Configuration):

- OS/version: MacOS 12.4
- Browser/version: Chrome 126
- Ad block extension/version: ABP 4.3

#### Используемые фильтры (Used filters):
<img width="1512" alt="Screenshot 2024-07-16 at 15 57 45" src="https://github.com/user-attachments/assets/cb30c57c-8150-4b03-b34b-58addd53851b">

**Comment by dimisa-RUAdList** [comment]
That's how it should be. This was done on purpose. The site owner makes sure that its functionality is incompatible with the blocker and deliberately changes the layout and paths of network requests so that nothing works for adblock users.

**Comment by Priler** [comment]
What about users from Ukraine?
Visitors from this country **does not have any ads**.
But website is still unaccessable for them.

Looks more like some kind of personal interest or even hate against Ukraine citizens.

**Comment by dimisa-RUAdList** [comment]
Решили поспекулировать на политике? Плохое начало.

**Comment by Priler** [comment]
I'm the owner of howdyho.net website.
And we did not receive any requests from the AdBlock team or EasyList team about compatibility issues.
Moreover, our website is not obliged to be "compatible" with third-party extensions or filter lists.

**Comment by dimisa-RUAdList** [comment]
До тех пор, пока у вас будет работать детектор, требующий отключить адблок, сайт останется заблокированным.

**Comment by Priler** [comment]
I understand inablity for you to make a working filter, but this is not our issues.
Please be advised that our website operates legally, complies with all applicable laws and regulations, and does not distribute any malicious software.
The indiscriminate blocking of our entire site by your extensions/filters adversely affecting our users’ experience.

And again, I repeat.
Users from Ukraine DOES NOT HAVE any ads or ad-detectors, yet you block them.

Failure to address this issue promptly will leave us no choice but to seek the removal of your list from all extensions that use it, or from the Chrome Web Store itself.
We trust that you understand the seriousness of this matter and will take the necessary steps to resolve it.

Thank you for your attention to this matter.

**Comment by dportvine** [comment]
> What about users from Ukraine?

I don't see the Ukrainian language on this site.
