### ISSUE TITLE
https://espanarusa.com/ru/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/ruadlist#32]
Hey ! I've found an ad at the following webpage: https://espanarusa.com/ru/

Proposed filter: espanarusa.com##[href*="https://yolka.eu"]

Screenshot:
<img width="615" alt="Screenshot 2021-11-08 at 14 48 01" src="https://user-images.githubusercontent.com/65717387/140753697-ad0539a4-6723-4848-928c-d57d4ac06708.png">

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/f61eade48ffab63f930876180e71137f8c75cc25#diff-4678692434e861bd0921111ae2d0afe0b9df10888aefd920427539f68d3da868R2525
