### ISSUE TITLE
playground.ru

### ISSUE THREAD

**Issue by Zhivag0** [easylist/ruadlist#320]
#### Описание проблемы (Description of the problem): заблокирована возможность авторизации на сайте через социальные сети. кнопки авторизации скрыли фильтром. 

<details>
<summary>Screenshot(s)</summary>

</details>

#### Конфигурация (Configuration):

- OS/version:ВСЕ
- Browser/version: ВСЕ
- Ad block extension/version:

**Comment by dimisa-RUAdList** [comment]
Кнопки социальной авторизации пришлось скрыть, поскольку они всё равно не работали. Админ ресурса использует агрессивный обход адблока, и пока будет длиться противостояние, второстепенные функции могут быть поломаны. Но это классическая картина для подобных случаев.

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/77f3f8973ec40979963d69c53f37a7ebd3a0313a
