### ISSUE TITLE
vc.ru

### ISSUE THREAD

**Issue by CATIOR** [easylist/ruadlist#321]
#### Описание проблемы (Description of the problem):

VC.ru
Остаточный блок от рекламы.
Понимаю, что в мобильных браузерах поддержки нет, но если есть возможность посмотреть, может быть можно что-то сделать? Пожалуйста 🙏

<details>
<summary>Screenshot(s)</summary>

[PasteBoard](https://pasteboard.co/61WO0j9YmzMw.jpg)

</details>

#### Конфигурация (Configuration):

- OS/version: Android 13
- Browser/version: Edge Canary 128.0.2704.0
- Ad block extension/version: uBlock Origin 1.57.2

#### Используемые фильтры (Used filters):

* RU AdList: Counters
* RU AdListRU 
* AdList: BitBlock + Fanboy's General
* uBlock filters – Annoyances
* EasyList/uBO – Cookie Notices
* uBlock filters
* EasyList

**Comment by dimisa-RUAdList** [comment]
Закинул: https://github.com/easylist/ruadlist/commit/289590f6ddebedab7d76be6fbff03636dc5aefa8

Но не уверен, что мобильный браузер отработает так же, как и десктоп в мобильной эмуляции.

**Comment by CATIOR** [comment]
Спасибо! Достаточно обновить фильтры?

**Comment by dimisa-RUAdList** [comment]
Я не знаю, достаточно или нет. На этот вопрос должны ответить вы, как обладатель целевого браузера.

**Comment by dimisa-RUAdList** [comment]
Если добавленные правила ничего не делают, то до конца дня будут удалены.

**Comment by CATIOR** [comment]
Добавленные правила помогли, но сломали комментарии к статьям, к сожалению.
![Screenshot_2024-08-06-12-22-56-73_893286cdd908a61bf33b4bc1d9b44b3c](https://github.com/user-attachments/assets/dd6a8b7a-6f02-44ef-88c8-22be7ad54b73)
![Screenshot_2024-08-06-12-23-11-44_893286cdd908a61bf33b4bc1d9b44b3c](https://github.com/user-attachments/assets/9600dc14-be04-4036-af5f-6d75b4df8789)

**Comment by dimisa-RUAdList** [comment]
Переделал: https://github.com/easylist/ruadlist/commit/8f881913d9ea3a02aa1e0108f4e47846120e5a83

Минут через 20 вступит в силу и будет доступно после обновления фильтров вручную для проверки.

**Comment by CATIOR** [comment]
Обновил фильтры вроде как, не исправилось. Думаю, нужно ещё подождать, в прошлый раз тоже после обновления фильтров не сразу изменения появились почему-то

**Comment by CATIOR** [comment]
Комментарии не показываются. Ещё раз обновил фильтры.

**Comment by dimisa-RUAdList** [comment]
В десктопной версии для принудительного обновления одного конкретного фильтра, нужно на вкладке "Списки фильтров" кликнуть по иконке часов в строке целевого фильтра, удерживая клавишу Shift. Но в мобильном варианте клавиши Shift по понятным причинам нет. Возможно, потому и обновление не вытягивается. Но можно попробовать тапнуть по иконке часов в строке целевого фильтра повторно.

**Comment by CATIOR** [comment]
Переустановил расширение на всякий случай.

Отлично! Всё работает, спасибо! ❤️❤️❤️
