### ISSUE TITLE
dtf.ru

### ISSUE THREAD

**Issue by CMTV** [easylist/ruadlist#322]
#### Описание проблемы

На сайте есть ряд фич, которые выполнены как видео с автовоспроизведением, а именно: видеобаннеры в профилях пользователей, видеоаватарки и анимированные постеры к некоторым новостям.

В данный момент никакой из указанных выше элементов не работает.
Все видео просто стоят на паузе.

<details>
<summary>Screenshot(s)</summary>

<img width="499" alt="Без имени" src="https://github.com/user-attachments/assets/49cb7f73-b057-472d-9c67-a00fde542037">

<img width="114" alt="Без имени" src="https://github.com/user-attachments/assets/422eda22-54d6-4e58-8d39-60f3aa7e54cc">
</details>
Рекламой эти элементы не являются и их остановка только мешает пользоваться и без того не самым удобным после редизайна сайтом и вводит пользователей в фрустрацию, регулярно становясь причиной постов о том, что на сайте есть баг, хотя это баг со стороны ruadlist.

Предполагаю, что проблема находится вот в этой строчке фильтра:

```
dtf.ru,vc.ru##+js(set-attr, video, controls, true)
```

Вот несколько ссылок, на которых демонстрируется проблема:

* [Баннер профиля](https://dtf.ru/u/136492-petr-radko)
* [Аватарка](https://dtf.ru/u/23790-jfyx)
* [Новость от редакции](https://dtf.ru/games/2347222-igra-goda-5-mesto-star-wars-jedi-survivor)
<details>
<summary>Используемые фильтры</summary>

<img width="447" alt="Без имени" src="https://github.com/user-attachments/assets/74528db0-8720-46c2-a671-f658407b2b61">
</details>

**Comment by dimisa-RUAdList** [comment]
Проблема обсуждалась неоднократно, наиболее подробно здесь: https://forums.lanik.us/viewtopic.php?p=167127-dtf-ru-vc-ru#p167127

Кстати, во многих браузерах отключение автовоспроизведения предусмотрено их функционалом, и юзеры активно этим пользуются. В этом случае в FF видео в новости от редакции превращается в картинку, а аватар - в чёрный прямоугольник.

**Comment by CMTV** [comment]
Я в курсе того обсуждения.

Проблема в том, что эти функции были добавлены еще до редизайна.
И все работало прекрасно.
И только после редизайна отвалились все эти функции.

Повторюсь, они не является рекламой, а потому я не вижу разумных причин вмешиваться в логику работы сайта.

Если юзеры хотят это отключить, у них есть возможность воспользоваться функционалом браузера.

**Comment by dimisa-RUAdList** [comment]
По вашим вопросам уже представлены ответы в обсуждении, ссылку на которое я дал выше.

И вероятно, вы невнимательно прочитали мой ответ. Отключение автовоспроизведения с помощью функционала браузера - ломает видео, либо превращая его в картинку, либо в чёрный прямоугольник. Правила для отключения автоплея в том или ином виде работают уже 4 года и ничего не ломают, позволяя запустить видео, если пользователь этого хочет. При этом нагрузка на аппаратную часть и аккумулятор возвращается в разумные границы, переставая убивать ноуты.

Претензии в отношении текущих правил имеют микроскопическое количество, в основном от тех, кто установил себе видео-аватарку, как в вашем случае.

**Comment by CMTV** [comment]
> Отключение автовоспроизведения с помощью функционала браузера - ломает видео, либо превращая его в картинку, либо в чёрный прямоугольник.

А какое отношение к uBlock имеют проблемы реализации DTF и его взаимодействия с функционалом отключения автовоспроизведения внутри браузеров? Насколько мне известно, uBlock вроде и не ставит своей целью фиксить не имеющие отношения к рекламы проблемы конкретных сайтов.

> Правила для отключения автоплея в том или ином виде работают уже 4 года и 

Не совсем понятна избирательность этих правил.
По вашей логики автовоспроизведение надо отлючать вообще на всех сайтах?
Потому что я могу привести целый ряд таких сайтов, на которых оно не отключено.
Включая DTF до редизайна.

Не должен ли сайт сам решать, какие видео воспроизводить, а какие нет, если эти видео не имеют рекламного характера?

> ничего не ломают, позволяя запустить видео, если пользователь этого хочет

Они уже ломают логику DTF, потому что ни баннер, ни видеоаватарку включить не выйдет. У баннера есть оверлей из-за чего включить там видео нельзя, аватарка имеет слишком маленький размер, отчего клик по ней не вызывает воспроизведения видео.

Выходит, пользователь хочет, но не может.

> При этом нагрузка на аппаратную часть и аккумулятор возвращается в разумные границы, переставая убивать ноуты.

Я конечно не в контексте ситуации, но не могу не спросить, а много ли к ruadlist было претензий по поводу "убийства аккумуляторов" из-за автовоспроизведения? И опять же, почему uBlock как инструмент для блокировки рекламы занимается оптимизацией расхода аппаратных ресурсов на сайтах?

> Претензии в отношении текущих правил имеют микроскопическое количество, в основном от тех, кто установил себе видео-аватарку, как в вашем случае.

В таком случае встречный вопрос -- много ли было жалоб конкретно на сайт DTF из-за проигрывающихся на нем видео?

---

У меня нет особого желания разводить какие-то невероятные баталии.

Но выглядит вся это ситуация как игра в пользу меньшинства -- под заботой об аккумуляторах происходит нарушение логики работы сайта, это нарушение неоднократно по вашим же словам было замечено обычными пользователями, но спорное правило не убирается.

Могу выдвинуть встречное предложение: попробовать убрать это правило и посмотреть, появятся ли жалобы на аккумулятор или что-то подобное.

**Comment by CMTV** [comment]
Кстати, забыл указать, что проблема касается не только баннеров и аватарок.

Многие скидывают короткие (1-2 секунды) mp4 в комменты, которые приходится запускать вручную.
Если они имеют достаточные размеры, запустить их можно вручную.
Если они маленькие, то возникает такая же проблема, что и с аватарками - запустить проблематично.

Опять получается прямой ущерб user experience от этого правила, не говоря уже о том, как убого смотрится непонятная полоска длины ролика вместо аватарок или гифок в комментах.

Так что еще раз озвучу свое предложение убрать конкретно это правило конкретно для DTF и посмотреть на реакцию.

**Comment by dimisa-RUAdList** [comment]
Оу, так конструктивного диалога не получится. Вы задаёте вопросы, ответы на которые уже даны ранее, плюс переиначиваете мои слова, превращая "микроскопическое количество" в "неоднократно". Принимать участие в таком обсуждении не имеет смысла.

Но если вы приведёте ссылку на страницу, где текущее правило ломает важный функционал, не относящийся к бессмысленному украшательству, я рассмотрю возможность адаптации.

**Comment by CMTV** [comment]
Ладно, тогда не буду распыляться и спрошу напрямую касательно энергоэффективности.

Не могли бы вы мне указать **конкретно** где речь идет о том, что в одну из целей расширения uBlock входит приостановка НЕ рекламных видео на сайтах?
Хотя бы одну ссылку.

Я посмотрел официальный сайт на русском и английском языках, я посмотрел их GitHub вики, посмотрел и [исследование](https://www.mdpi.com/2227-7080/8/2/18) "Energy Conservation with Open Source Ad Blockers".

Везде речь идет о том, что uBlock сам не жрет ресурсы. В исследовании речь идет о том, как именно исключение **рекламы** позволяет уменьшить энергопотребление и бла-бла прочее.

**Comment by dimisa-RUAdList** [comment]
Вы точно читаете мои сообщения?

RU AdList для uBlock Origin блокирует автовоспроизведение в рунете везде, кроме видео-сервисов. Это пять десятков сайтов Shkulev Media, 3dnews.ru, afisha.ru, autorambler.ru, championat.com, eda.ru, gazeta.ru, lenta.ru, letidor.ru, mail.ru, moslenta.ru, motor.ru, passion.ru, quto.ru, rambler.ru, wmj.ru, и так далее, в том числе и на pikabu.ru. Если на последнем у вас этого не происходит, значит что-то поломано в вашей конфигурации uBlock Origin, либо вы используете рекламный браузер вроде яндекса или амиго, где блокировщик в принципе не может работать должным образом.

Отключить автовоспроизведение на dtf.ru пользователи просили начиная с 2017г. Но отключено оно было лишь в 2020г, когда его реализация стала подвешивать на не самых продвинутых ПК ленту, а также страницы с комментариями, в которых пыталось стартануть сразу множество видео-аватаров.

Если вы хотите отключить блокировку автоплея на dtf.ru, откройте панель управления uBlock Origin, перейдите на вкладку "Мои фильтры" и добавьте туда: 
```
dtf.ru,vc.ru#@#video:remove-attr(autoplay)
dtf.ru,vc.ru#@#+js(set-attr, video, controls, true)
```

**Comment by CMTV** [comment]
Спасибо за пояснение, как добавить исключение.

Причина моих вопросов кроется в том, что я думал, что uBlock это блокировщик рекламы и трекеров аналитик.
Я и подумать не мог, что uBlock и в особенности устанавливающийся по умолчанию список буквально с названием ruADlist (название говорящее), будет "исправлять" косяки чужих сайтов.

Как по мне, для таких вещей было бы логичнее делать отдельный фильтр, чтобы не смешивать все в одну кучу.
В конце концов, одно дело это сокрытие рекламы и трекеров это одно и к этому вопросов никаких быть не может.
Другое дело, это внедрение в логику конкретных сайтов для того, чтобы внести "улучшения", что уже само по себе выглядит странно из-за того, насколько это субъективное поле.

> Отключить автовоспроизведение на dtf.ru пользователи просили начиная с 2017г.

Отдельный вопрос к ним, почему они в фильтре Ad List просят отключить автовоспроизведение.

**Comment by dimisa-RUAdList** [comment]
uBlock и uBlock Origin - это разные расширения. В [описании](https://ublockorigin.com/ru) последнего указано: "_uBlock Origin – это не просто «блокиратор рекламы», это блокировщик контента широкого спектра действия..._".

Действительно, в функционал фильтра RU AdList для uBlock Origin входит правка макета и прочие исправления косяков исходного кода, если об этом его создатели по тем или иным причинам позаботиться не в состоянии. А отключение автоплея вне видеосервисов практикуется практически всеми продвинутыми блокировщиками, причём уже довольно давно.

Тот же AdGuard будет блокировать автоплей базовым русским фильтром на [рамблере](https://news.rambler.ru/starlife/53199881-smi-sbylos-prorochestvo-zhirinovskogo-ob-ivane-urgante/) и прочих сайтах. Просто у них блокировка автоплея и исправление косяков сайтов реализована не столь всеобъемлюще, как в RU AdList, в котором я уделяю этому особое внимание.

**Comment by CMTV** [comment]
Безусловно, имеете на это право как автор фильтра, хотя я и категорически не согласен с вашими критериями "полезности" и "бесполезности".

В особенности это касается действительно красивых вещей по типу видео-аватар или гифок в комментах.
Они никому не мешают, а апелляция к энергоэффективности это вообще для меня за гранью.

**Comment by dimisa-RUAdList** [comment]
Проблема в том, что там нет гифок. Веб-мастер не придумал ничего лучше, как всё конвертировать в mp4-видео. И одновременный запуск нескольких таких видео тупо убивает сайт на слабых ПК. И то, что для вас "красивая вещь", для их обладателей превращается в невозможность пользования сайтом. А текущий макет не позволяет мне отделить мух от котлет, поэтому пока сайт не будет оптимизирован, всё останется как есть.

**Comment by CMTV** [comment]
> А текущий макет не позволяет мне отделить мух от котлет

Все аватарки на сайте имеют класс `.author__avatar`. Баннеры `.subsite-cover`.

**Comment by dimisa-RUAdList** [comment]
Спасибо, я умею пользоваться инструментами разработчика, и в состоянии посмотреть имена классов элементов. Но в данном случае это бесполезная информация, поскольку использование непрямого правила приводит к его нестабильной работе. Но небольшой шанс на адаптацию есть. Укажите ссылки на страницы, где используются видео, родительские элементы у которых имеют имена классов `.author__avatar` и `.subsite-avatar`.

**Comment by CMTV** [comment]
> это бесполезная информация, поскольку использование непрямого правила приводит к его нестабильной работе

Что понимается под "нестабильной работой"?

На всех страницах `.author__avatar` используется для обозначения аватар: в комментариях к постам, в верхней части любого поста. И то и другое можно вот [здесь](https://dtf.ru/games/2886484-shedouhart-celovali-chashe-vsego-statistika-baldurs-gate-3-za-god) найти. Еще этот же класс в лайв ленте используется (это то, что справа висит если активна подписка DTF+)

Класс `.subsite-avatar` используется для аватар пользователей на их страницах и страницах подсайтов (что суть одно и то же). Пример использования этого класса например [тут](https://dtf.ru/u/136492-petr-radko).

**Comment by dimisa-RUAdList** [comment]
Спасибо за ссылки. Нестабильная работа - это когда правило не успевает сделать то, что задумано. К сожалению, добавление исключений или использование пути к элементу вместо прямого указания элемента в некоторых случаях приводит именно к такому результату. Сейчас у меня под руками только мощный ПК, на котором это проверить затруднительно, но завтра в течении дня я попробую выполнить отладку на мобильном intel core i5 2.4Ghz, может быть удастся адаптировать текущие правила, чтобы они цепляли только медиа в постах и ленте и при этом успевали. Автор uBlock Origin дорабатывал свою библиотеку, возможно это сыграет свою роль.

**Comment by CMTV** [comment]
Понял. Мою проблему вы все равно уже решили, указав необходимые исключения.
Так что все это уже было не зря.

Если тесты дадут адекватные результаты, в чем я сомневаюсь, учитывая насколько все плохо на DTF после редизайна, то может удастся часть функций вернуть к жизни.

**Comment by dimisa-RUAdList** [comment]
Нашёлся добрый человек, который оттестил адаптацию. 

Исправлено: https://github.com/easylist/ruadlist/commit/ce78c1d7c0eea0ba468bcbb960fe96680501f96e

В течении 15 минут изменения вступят в силу и станут доступны при обновлении фильтра вручную. Для принудительного обновления нужно на вкладке "Списки фильтров" кликнуть по иконке часов в строке RU AdList, удерживая клавишу Shift. Автоматом изменения раскатаются в течении 5 часов.
