### ISSUE TITLE
netlab.ru

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#323]
`https://www.netlab.ru/katalog/raznoe-970178/salazki-dlya-noutbuka-hp-komplekt-ustanovki-zhestkogo-diska-821665-001/`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/user-attachments/assets/7cd63f55-3a1c-424a-980a-fd680cb04732)

</details>

**Comment by dimisa-RUAdList** [comment]
Малопопулярный сайт. Предупреждение пропадает само после первого показа. В EasyList Cookie.
