### ISSUE TITLE
hot.game

### ISSUE THREAD

**Issue by 10522** [easylist/ruadlist#324]
#### Описание проблемы (Description of the problem):
Невозможно перейти в магазин Fanatical и купить игру, т.к. ссылка на этот магазин удаляется, если навести на него курсор. Также не работает игра на этом сайте.

`https://hot.game/game/LEGO-Star-Wars-The-Skywalker-Saga`
`https://hot.game/game_js`

#### Конфигурация (Configuration):

- OS/version: Windows 10 Pro 22H2
- Browser/version: Google Chrome 127.0.6533.100
- Ad block extension/version: uBlock Origin 1.59.0

#### Используемые фильтры (Used filters):
<details>

![fhghdhfsdsf](https://github.com/easylist/ruadlist/assets/59209149/47924ee3-66ec-4eff-a058-0965d41ef850)

</details>

**Comment by dimisa-RUAdList** [comment]
В каком место страницы находится ссылка на магазин Fanatical?

**Comment by dportvine** [comment]
`https://hot.game/game/LEGO-Star-Wars-The-Skywalker-Saga`

<details>
<summary>Screen</summary>

![2024-08-12_113823](https://github.com/user-attachments/assets/5325cf3e-a8ae-43ca-bcc8-2615850161b3)
![2024-08-12_113838](https://github.com/user-attachments/assets/ccb41218-83b7-483d-87bf-2a7587be79d8)
![2024-08-12_113850](https://github.com/user-attachments/assets/991d0a7b-6aa7-4ab7-89bd-0ac381dbf55e)
</details>

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/7f46cf59b52459b805ba63cb386850a44efd9971

**Comment by dimisa-RUAdList** [comment]
@10522 
Вы имеете отношение к Fanatical или hot.game?

**Comment by dimisa-RUAdList** [comment]
Дело в том, что на hot.game в принципе нет ссылок на Fanatical. Вместо этого там используется рекламная ссылка-редиректор ad.admitad.com. При наведении скрипт меняет `data-href` на `href`, а такой селектор глобально блокируется всеми блокировщиками без исключения. Для исправления я добавил правило, которое конвертирует рекламную ссылку-редиректор в прямую, и тогда она перестаёт подпадать под блокировку. Работает это только в uBlock Origin, во всех остальных блокировщиках рекламная ссылка остаётся заблокированной. Но поскольку конвертация происходит только после замены `data-href` на `href`, на лету, как раз и наблюдается "моргание". Сделать с этим ничего нельзя.

Что касается поломки на onliner.by, то поясните пожалуйста, что вы имеете ввиду. Только не здесь, а в [целевом issue](https://github.com/easylist/ruadlist/issues/281).

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/392ed306a0a41b7bb5589e04a2c09da11515a1d3

**Comment by dimisa-RUAdList** [comment]
В этой теме обсуждается только `hot.game.` Если вы обнаружили, что правила из фильтров RU AdList где-то не отрабатывают или режут лишнее - создавайте отдельный issue для каждого домена.

**Comment by dimisa-RUAdList** [comment]
Эта проблема не может быть рассмотрена в рамках данного issue.
