### ISSUE TITLE
dobro.mail.ru

### ISSUE THREAD

**Issue by Pavel1711** [easylist/ruadlist#325]
#### Описание проблемы (Description of the problem): 
К сайту применяются общие правила mail.ru. В частности общее правило `~e.mail.ru,mail.ru,sportmail.ru##table > tbody > tr > td:first-child + td + td:last-child` блокирует данные таблицы. Сайт не содержит рекламу. Прошу добавить сайт `https://dobro.mail.ru/` в "белый лист"

<details>
<summary>Screenshot(s)</summary>

</details>

#### Конфигурация (Configuration):

- OS/version: macOS Sonoma 14.6.1
- Browser/version: 127.0.6533.119 (Официальная сборка), (arm64)
- Ad block extension/version: AdBlock 6.7.0

**Comment by dimisa-RUAdList** [comment]
Укажите пожалуйста ссылку на страницу, где срабатывает это правило.

**Comment by Pavel1711** [comment]
Страница, на которой ошибка воспроизводится - служебная.
Для примера можно добавить код на страницу
`<table class="styles_table__vQw52"><thead><tr><th><h4 class="vkuiTypography vkuiTypography--normalize vkuiTypography--weight-2 vkuiHeadline--sizeY-compact vkuiHeadline--level-1">Проект</h4></th><th><h4 class="vkuiTypography vkuiTypography--normalize vkuiTypography--weight-2 vkuiHeadline--sizeY-compact vkuiHeadline--level-1">Денег</h4></th><th><h4 class="vkuiTypography vkuiTypography--normalize vkuiTypography--weight-2 vkuiHeadline--sizeY-compact vkuiHeadline--level-1">Человек</h4></th></tr></thead><tbody><tr><td class="project-aid-stats_projectColumn__V7RoR"><span class="vkuiTypography vkuiTypography--normalize vkuiText vkuiText--sizeY-compact">test</span></td><td><span class="vkuiTypography vkuiTypography--normalize vkuiText vkuiText--sizeY-compact">1</span></td><td><span class="vkuiTypography vkuiTypography--normalize vkuiText vkuiText--sizeY-compact">10</span></td></tr></tbody></table>`

Либо на странице https://dobro.mail.ru/projects/obrazovatelnyie-zanyatiya-dlya-nasti-i-drugih-detej-iz-detskih-domov/?tab=reports удалить одну ячейку из строки. Когда в строке 3 ячейки, последняя не показывается 
<img width="872" alt="Снимок экрана 2024-08-15 в 18 57 43" src="https://github.com/user-attachments/assets/3804d06d-70fb-46f9-86ea-02a60117068e">
<img width="862" alt="Снимок экрана 2024-08-15 в 18 58 01" src="https://github.com/user-attachments/assets/3d2e9151-bdce-46da-9f04-5d58ab52f636">

**Comment by dimisa-RUAdList** [comment]
Хм, то есть обычные пользователи, не применяющие дополнительных манипуляций, со срабатыванием этого правила столкнуться не могут?

**Comment by Pavel1711** [comment]
Нашел еще пример без манипуляций. https://dobro.mail.ru/personal_events/den-rozhdeniya-so-smyislom-3. Не выводится сумма, хотя в разметке есть.
В основном страницы, в которых 3 ячейки в таблицах - служебные, поэтому скинул пример кода

**Comment by dimisa-RUAdList** [comment]
Ок, вижу такое. Подскажите пожалуйста, для собственных сотрудников с блокировщиком рекламы на главной странице mail.ru контент тоже скрывается, или это сделано только для обычных пользователей?
<details>
<summary>Screenshot(s)</summary>

![mailru](https://github.com/user-attachments/assets/431b7cb0-c8f4-4109-8206-c54def5d89bb)

</details>

**Comment by Pavel1711** [comment]
Контент тоже скрывается
<img width="1271" alt="Снимок экрана 2024-08-15 в 19 36 15" src="https://github.com/user-attachments/assets/32d20bd8-e3af-4ddd-89ad-f6d9737acdfe">

**Comment by dimisa-RUAdList** [comment]
Ясно, спасибо. Добро поправил: https://github.com/easylist/ruadlist/commit/4fa5e8361e4a402706adcf5f97ebe77f9a662890
