### ISSUE TITLE
pravda.com.ua

### ISSUE THREAD

**Issue by alxxjd** [easylist/ruadlist#326]
#### Описание проблемы (Description of the problem):

`https://www.pravda.com.ua/`

<details>
<summary>Screenshot(s)</summary>

https://github.com/easylist/ruadlist/blob/master/advblock/specific_block.txt
Коли цей файл filter.txt додано до uBO, з'являється попередження про те, що не слід блокувати html-load.com. Однак, переглянувши мережеву панель, видно, що запити до html-load.com блокуються. Через блокування цієї URL-адреси сторінка не працює.

<img width="1824" alt="image" src="https://github.com/user-attachments/assets/a84b925f-8e59-469f-947c-995271810011">

<img width="1191" alt="image" src="https://github.com/user-attachments/assets/f4ea5f72-2cae-4315-b80c-ec6d086e227e">

</details>

#### Конфигурация (Configuration):

- OS/version: Mac, 14.6.1
- Browser/version: Chrome/127.0.6533.120
- Ad block extension/version: uBlock Origin 1.59.0

#### Используемые фильтры (Used filters):

https://github.com/easylist/ruadlist/blob/master/advblock/specific_block.txt

**Comment by dimisa-RUAdList** [comment]
Удалите импортированный specific_block.txt и используйте фильтр RU AdList целиком, как это предусмотрено изначально. Активировать его можно в секции "Regions, languages".
