### ISSUE TITLE
xcom-shop.ru

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#328]
`https://www.xcom-shop.ru/crucial_ct204864bf160b_610964.html`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/user-attachments/assets/32bef809-9ff2-4842-8465-e9a393b8f659)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/a206e3ddfe5a15552ea644147efb68977c33c2bb
