### ISSUE TITLE
acapella.moscow

### ISSUE THREAD

**Issue by CATIOR** [easylist/ruadlist#329]
#### Описание проблемы

`https://acappella.moscow/participants/notemix-acappella`

Не работает авторизация через ВК после нажатия кнопки "Проголосовать". Нет кнопки "VK".

#### Конфигурация (Configuration):
OS/version: Android 13 (проблема повторяется с компьютера)
Browser/version: Edge Canary 128.0.2704.0
Ad block extension/version: uBlock Origin 1.59.0
#### Используемые фильтры (Used filters):
RU AdList: Counters
RU AdListRU
AdList: BitBlock + Fanboy's General
uBlock filters – Annoyances
EasyList/uBO – Cookie Notices
uBlock filters
EasyList

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/e31b0db227abed04c17760ff7b8640363162a7d0
