### ISSUE TITLE
synchroncode.com

### ISSUE THREAD

**Issue by bogachenko** [easylist/ruadlist#33]
`https://kinoferma.top/film/660-chelovek-pauk-smotret-online.html`
`https://kino-epta.top/load/fantastika/chelovek_pauk_2_2004/23-1-0-8422`

Твой регэксп `/^https?://(?![^\s]+\.rumer\.fun|[^\s]+\.streamvid\.club|[^\s]+\.takedwn\.ws|cdn\.jsdelivr\.net\/npm\/venom-player)/$third-party,domain=ameytools.club|buildplayer.com|delivembed.cc|embedstorage.net|kinogram.best|mir-dikogo-zapada.com|multikland.net|placehere.link|synchroncode.com|tobaco.ws` блокирует видео-фрейм.<br><br>Исправь его или добавь это правило `@@||cloudflare.net^$domain=synchroncode.com`

**Comment by dimisa-RUAdList** [comment]
Что-то не повторяется. Либо они уже сами внесли исправления, либо нужно выполнять проверку с использованием какой-то определённой геолокации.

**Comment by bogachenko** [comment]
Проверь так `https://api.synchroncode.com/embed/movie/1143?host=kinoferma.top`

Твой регэксп блокирует запрос CNAME `https://cdn.jsdelivr.net.cdn.cloudflare.net/`

**Comment by dimisa-RUAdList** [comment]
CNAME блокируется только в uBO и только в FF. Если вы используете подобную конфигурацию, желательно указывать это в стартовом сообщении. 

Исправлено: https://github.com/easylist/ruadlist/commit/e7822b87a2d7a5a50ba293d0047bb7f4f3143443
