### ISSUE TITLE
mi-shop.com

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#330]
`https://mi-shop.com`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/user-attachments/assets/c9093f85-1dea-4e2b-ba8d-76ed25a91f6f)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/f60af8448cc4a744f0436d1eb47955c318698438
