### ISSUE TITLE
yandex.by

### ISSUE THREAD

**Issue by suprunchuk** [easylist/ruadlist#332]
#### Описание проблемы (Description of the problem):
Привет. Когда я включил блокировщик рекламы ublock origin, у меня не работает кнопка "отправить маршрут на телефон". Если я отключил расширение, то все работает, а потом появляется модальное окно с QR-кодом для сканирования телефоном. Если снова включить блокировщик рекламы, кнопка снова не работает. 
https://github.com/uBlockOrigin/uAssets/issues/25163

Ссылка на карту с проблемой:
`https://yandex.by/maps/2/saint-petersburg/?ll=30.311987%2C59.924021&mode=routes&rtext=59.912398%2C30.297619~59.920776%2C30.298644~59.933131%2C30.314815~59.936019%2C30.322297&rtt=pd&ruri=~~~&z=14.4`

<details>
<summary>Screenshot(s)</summary>

![1](https://github.com/user-attachments/assets/31d264f3-704e-486c-a50c-78a963355e84)

![2](https://github.com/user-attachments/assets/664d2a9c-f7eb-4c7b-bd87-94feb1e0aa39)

</details>

#### Конфигурация (Configuration):

- OS/version: windows 11 pro
- Browser/version: Chrome 128.0.6613.114
- Ad block extension/version: **uBlock Origin 1.59.0**

**Comment by dimisa-RUAdList** [comment]
Судя по сработавшим правилам из исходного issue, вы вводите в заблуждение, когда указываете конфигурацию. Поэтому будет лучше, если вы сделаете слепок настроек. Для этого откройте панель управления uBO, перейдите на вкладку "Настройки" и кликните внизу страницы "Резервное копирование в файл".

**Comment by suprunchuk** [comment]
Не совсем понимаю о чем речь?

**Comment by suprunchuk** [comment]
[my-ublock-backup_2024-09-02_12.50.23.txt](https://github.com/user-attachments/files/16835763/my-ublock-backup_2024-09-02_12.50.23.txt)


> Судя по сработавшим правилам из исходного issue, вы вводите в заблуждение, когда указываете конфигурацию. Поэтому будет лучше, если вы сделаете слепок настроек. Для этого откройте панель управления uBO, перейдите на вкладку "Настройки" и кликните внизу страницы "Резервное копирование в файл".

**Comment by dimisa-RUAdList** [comment]
Всё понятно. Вы скопипастили часть правил из фильтра [RU AdList: Counters](https://github.com/easylist/ruadlist/wiki/RU-Adlist-links), причём его неактуальной версии. Удалите их, и подключите этот фильтр штатным способом.

**Comment by suprunchuk** [comment]
> подключите этот фильтр штатным способом.

Правильно понимаю, что достаточно просто нажать кнопку "подписаться" в правом верхнем углу?

**Comment by dimisa-RUAdList** [comment]
Правильно

**Comment by suprunchuk** [comment]
> Правильно

Спасибо. Все заработало!! Хорошего дня!
