### ISSUE TITLE
servermall.ru

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#333]
`https://servermall.ru`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/user-attachments/assets/a5d6fe09-3caa-4f55-a451-e5a09383831b)

</details>

**Comment by dimisa-RUAdList** [comment]
Как я [писал ранее](https://github.com/easylist/ruadlist/issues/308#issuecomment-2195602660), BitBlock подчищает только там, где фильтры fanboy недорабатывают, но это касается только крупных и посещаемых ресурсов. Данный ресурс узкоспециализированный и малопосещаемый обычными пользователями. Поэтому правила для него лучше добавить в EasyList/uBO – Cookie, сообщив об этой проблеме в ветке [EasyList](https://github.com/easylist/easylist/issues), указав что подключен данный фильтр.
