### ISSUE TITLE
chizhik.club

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#334]
`https://www.chizhik.club`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/user-attachments/assets/8d2b8134-c0ef-43f1-9687-7385b08201f4)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/43dcdc65cf3a3c895dfa152f3dffa11b4171a746
