### ISSUE TITLE
lk.megafon.ru

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#335]
`https://lk.megafon.ru`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/user-attachments/assets/de42d25d-e753-464e-b23b-eff281ba41e6)

</details>

**Comment by dimisa-RUAdList** [comment]
Без аккаунта это не проверить. Если он у вас есть, закройте сообщение о куки крестиком, зайдите в инструменты разработчика (Ctrl+Shift+i), перейдите на вкладку "Приложение" (для FF - "Хранилище"), выберите слева секцию куки и нажмите на строку домена, чтобы таблица справа заполнилась. Если данных в таблице слишком много, вытяните её вверх и сделайте скриншот. Затем повторите то же самое для секции "Локальное хранилище".

**Comment by trup** [comment]
после закрытия этого сообщения, оно больше не появляется. даже в приватном режиме. видимо хранят настройку в профиле юзера.
но в коде страницы оно есть.
![изображение](https://github.com/user-attachments/assets/98b7d4de-c9b3-434e-b61a-32c45f193a0a)

**Comment by dimisa-RUAdList** [comment]
Как видно из кода макета, уникального идентификатора у родительского элемента нет, а это значит что для его скрытия потребуется применять медленное has-правило, находящее нужный элемент по наличию дочернего с уникальным именем. В этом случае уведомление об использовании куки будет кратковременно отображаться перед скрытием при каждом открытии страницы, что раздражает как бы не больше, чем необходимость его закрытия крестиком. Попробуйте очистить куки и локальное хранилище, по идее уведомление должно появиться.

**Comment by trup** [comment]
ну так приватный режим в firefox не использует куки и кэш, что равноценно их удалению.

**Comment by dimisa-RUAdList** [comment]
Попробуйте открыть в другом браузере.

**Comment by trup** [comment]
нет, не помогло.
но раз они запоминают это на стороне сервера, тогда и смысла нет?

**Comment by dimisa-RUAdList** [comment]
Если так, то да, смысла в этом немного. Проще один раз отключить для аккаунта, нежели получить постоянно мелькающий элемент.
