### ISSUE TITLE
shop.okraina.ru

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#336]
`https://shop.okraina.ru`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/user-attachments/assets/e5275573-2710-4c01-b5ab-1fd6ab124c92)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/9534c8e0e215550f1d13e87e699b76bfbbfc1f49
