### ISSUE TITLE
winitpro.ru

### ISSUE THREAD

**Issue by ru1gha3** [easylist/ruadlist#337]
#### Описание проблемы (Description of the problem):

`https://winitpro.ru/`

<details>
<summary>Screenshot(s)</summary>

![winitpro.ru](https://github.com/user-attachments/assets/14f7a937-d6bd-4ce6-9680-0d139420651c)

</details>

#### Конфигурация (Configuration):

- OS/version: Windows 10
- Browser/version: Firefox 130
- Ad block extension/version: uBlock Origin 1.59.0

#### Используемые фильтры (Used filters):

listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1743-0, 16m
 default:
  user-filters: 0-0, never
  ublock-filters: 40200-138, 16m Δ
  ublock-badware: 11151-6, 16m Δ
  ublock-privacy: 1101-9, 16m Δ
  ublock-unbreak: 2528-5, 16m Δ
  ublock-quick-fixes: 111-4, 16m Δ
  easylist: 86073-190, 16m Δ
  easyprivacy: 53056-271, 16m Δ
  RUS-0: 40846-152, 16m Δ

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/1689e008fe8a4820bb989726959d8d293306b588
