### ISSUE TITLE
botanichka.ru

### ISSUE THREAD

**Issue by timur-davletshin** [easylist/ruadlist#341]
#### Описание проблемы (Description of the problem):

`https://www.botanichka.ru/article/vidovyie-pelargonii-komnatnyie-tsvetyi-v-stile-retro/`

Блоки с рекламой, почеменные class="td-all-devices", не удалены.

OS: Debian 12, Firefox 130.0.1 + Ublock Origin 1.59 (Easylist + EasyPrivacy + RU AdList filters enabled).

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/0494ebf0eca882b5877ae6243ec22a846da2d2a9
