### ISSUE TITLE
forums.rusmedserv.com

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#342]
`https://forums.rusmedserv.com/showthread.php?t=63936`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/user-attachments/assets/c342aac5-0280-43d6-8c34-fb20ff6156ba)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/4add902344cd3820d3f83a4cafc9ff997f3d1e8f
