### ISSUE TITLE
olx.ua

### ISSUE THREAD

**Issue by Inqurity** [easylist/ruadlist#344]
#### Описание проблемы (Description of the problem):

Каждые 10 объявлений появляются 3 "ТОП" объявлений, которые не имеют ничего общего с фильтрами поиска и лишь делают сам поиск неприятнее

`https://www.olx.ua/uk/list/q-raspberry-pi/?search%5Border%5D=filter_float_price:asc`

Для их удаления я создал своё правило: `olx.kz,olx.ua,olx.uz##[data-testid="l-card"]:has([data-testid="adCard-featured"])`

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/523f47a4-4df6-4559-806a-91ed70251c26)

</details>

#### Конфигурация (Configuration):

- Browser/version: Firefox 131.0
- Ad block extension/version: uBlock Origin 1.60.0

**Comment by dimisa-RUAdList** [comment]
@dportvine

**Comment by dportvine** [comment]
https://forums.lanik.us/viewtopic.php?p=167211-olx-ua, https://github.com/easylist/easylist/commit/698d0b884e0d5f1ee0c90b57658498034320a304

**Comment by dimisa-RUAdList** [comment]
@dportvine 
Точно. Спасибо. Мне как раз вспоминалось, что попытки оперировать этими селекторами приводили к ложным срабатывания.

**Comment by dportvine** [comment]
@Inqurity 

> которые не имеют ничего общего с фильтрами поиска

Фильтр поиска **raspberry pi**, вы получили выдачу, если ищети микросхему, сформулируйте запрос правильно.

**Comment by Inqurity** [comment]
"ТОП" объявления не уважают настройку сортировки по цене, из-за чего я их вважаю рекламой

**Comment by Inqurity** [comment]
Про ложные срабатывания не знал
