### ISSUE TITLE
eplaza.ru

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#346]
`https://eplaza.ru`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/user-attachments/assets/fd81f944-f327-4fc0-a48a-1d738893004b)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/903dadbcceb12ba70b0633732608a7d984e0660f
