### ISSUE TITLE
meduza.io

### ISSUE THREAD

**Issue by CATIOR** [easylist/ruadlist#347]
#### Описание проблемы (Description of the problem):
`https://meduza.io/` и её зеркала.

Огромный баннер сверху на полэкрана. Его можно исправить добавлением следующих строк в мои фильтры:
`##.Layout-module-banner`

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/a68e84a7-ff5b-4709-9472-e7810e988e0a)

</details>

#### Конфигурация (Configuration):

- OS/version: Windows 10
- Browser/version: MS Edge, версия 129.0.2792.89
- Ad block extension/version: uBlock Origin 1.60.0

#### Используемые фильтры (Used filters):

<details>
  <summary>Посмотреть</summary>

**Встроенные**
- uBlock filters 5/5

**Реклама**
- EasyList 1/3

**Уведомления о файлах куки**
- EasyList/uBO – Cookie Notices 1/2

**Раздражающие элементы**
- uBlock filters – Annoyances

**Регионы, языки 1/36**
- RU AdList

**Пользовательские 2/2**
- RU AdList: BitBlock + Fanboy's General
- RU AdList: Counters

</details>

Конфликты предотвращены.

**После возможного исправления данной ситуации прошу удалить данную issue.**

**Comment by dimisa-RUAdList** [comment]
Вероятно,  ваш экземпляр расширения поломан из-за сбоя или пользовательских настроек. Правило для скрытия этого элемента уже содержится в подключенном у вас BitBlock: https://github.com/easylist/ruadlist/blob/master/bitblock/annoyance_specific_hide.txt#L384

**Comment by dimisa-RUAdList** [comment]
Вы дали только один адрес. Если вам известны другие, укажите ссылки.

**Comment by CATIOR** [comment]
> Вы дали только один адрес. Если вам известны другие, укажите ссылки.

Так дело в том, что сайт постоянно меняет зеркала.

**Comment by dimisa-RUAdList** [comment]
Технически зеркало не может жить меньше нескольких часов. Укажите адрес текущего.

**Comment by CATIOR** [comment]
> Укажите адрес текущего

`https://bit.ly/meduzamirror`

**Comment by dimisa-RUAdList** [comment]
Правила для ресурсов, зеркалируемых посредством подобных сервисов, в фильтры никогда не добавлялись и не будут добавляться. Это бессмысленно, отзеркалить таким образом можно любой сайт.

**Comment by CATIOR** [comment]
понятно. удалите мой запрос или уберите адрес сайта в таком случае, пожалуйста.

**Comment by dimisa-RUAdList** [comment]
А смысл? Это не секретные ссылки, они публичные:
`https://meduza.io/feature/2024/05/03/bit-ly-meduzamirror`
`https://meduza.io/feature/2022/03/04/meduza-zablokirovana-v-rossii-my-byli-k-etomu-gotovy-i-prodolzhaem-rabotat`

**Comment by CATIOR** [comment]
> А смысл? Это не секретные ссылки, они публичные:

Нежелательная организация. По закону я не могу эти ссылки публиковать

**Comment by dimisa-RUAdList** [comment]
Действующий закон касается поисковой выдачи. Обсуждаемый - кликабельных ссылок в сми. Для физических лиц ничего пока даже не обсуждается.

**Comment by CATIOR** [comment]
> Действующий закон касается поисковой выдачи. Обсуждаемый - кликабельных ссылок в сми. Для физических лиц ничего пока даже не обсуждается.

![Screenshot_2024-10-17-22-02-31-04_893286cdd908a61bf33b4bc1d9b44b3c](https://github.com/user-attachments/assets/d0d10dad-fa6d-4edc-a45b-e9b3e9534249)
Вот уж не знаю про какой вы закон
