### ISSUE TITLE
journal.tinkoff.ru

### ISSUE THREAD

**Issue by CATIOR** [easylist/ruadlist#348]
#### Описание проблемы (Description of the problem):
`journal.tinkoff.ru`

Огромный баннер сверху на полэкрана.

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/3a72e2f9-26f6-4b69-9ade-22a0ca66700c)

</details>

#### Конфигурация (Configuration):

- OS/version: Windows 10
- Browser/version: MS Edge, версия 129.0.2792.89
- Ad block extension/version: uBlock Origin 1.60.0

#### Используемые фильтры (Used filters):

<details>
  <summary>Посмотреть</summary>

**Встроенные**
- uBlock filters 5/5

**Реклама**
- EasyList 1/3

**Уведомления о файлах куки**
- EasyList/uBO – Cookie Notices 1/2

**Раздражающие элементы**
- uBlock filters – Annoyances

**Регионы, языки 1/36**
- RU AdList

**Пользовательские 2/2**
- RU AdList: BitBlock + Fanboy's General
- RU AdList: Counters

</details>

Конфликты предотвращены.

**Comment by dimisa-RUAdList** [comment]
Что-то не вижу такого на главной странице. Проблема ещё актуальна?

**Comment by CATIOR** [comment]
> Что-то не вижу такого на главной странице. Проблема ещё актуальна?

`https://journal.tinkoff.ru/news/butter-cost-up/` попробуйте не на главной

**Comment by dimisa-RUAdList** [comment]
На других страницах может быть иной макет. Там этот анонс присутствует, но в таких случаях практикуется унифицирование правила в зависимости от макета, если это возможно. Форма issue предполагает указание точной ссылки именно на ту страницу, где наблюдается проблема. У вас указан адрес главной страницы. Также на вашем скрине я вижу, что выполнен вход в аккаунт. У меня его нет, поэтому проверку того, что происходит на главной, я выполнить не могу. Если вы видите из-под аккаунта этот анонс на главной, потребуется скрин кода элемента в таком варианте макета.

**Comment by dimisa-RUAdList** [comment]
Вы всё ещё можете воспроизвести проблему?

**Comment by CATIOR** [comment]
<details>
  <summary>Скриншот </summary>

   [image](https://github.com/user-attachments/assets/d4e6c164-0593-4dd3-ac76-6fa174d13191)

</details>

<details>
  <summary>Код </summary>

`<div class="banner---iimfrc"><div><div data-project-name="fortuna" data-app-name="top-banner" data-app-id="3vMkfMeJN-dBsql-Q2vbw" data-app-hydrated="true"><div class="_horizontalWideBannerLayoutFixWrapper_1cx04_64" style="--top-banner-bg-color:#62B0FF;--top-banner-on-bg-color:#ffffff;--top-banner-hovered-bg-color:#178BFF;--top-banner-hovered-on-bg-color:#ffffff;--top-banner-button-bg-color:#ffffff;--top-banner-button-on-bg-color:#000000;--top-banner-button-hovered-bg-color:#ffffff;--top-banner-button-hovered-on-bg-color:#000000" data-analytics="banner" data-analytics-info="entityType=fortuna.banner"><a id="fortuna-banner-spec-mobile-forbusiness-banner.fortuna" href="https://journal.tinkoff.ru/list/spec-mobile-forbusiness/?internal_source=tj_spec_mobile_spec-mobile-forbusiness_mobile-forbusiness-banner.fortuna.1" rel="noopener noreferrer" class="_horizontalWideBanner_1cx04_64"><div class="_contentContainer_1cx04_99"><div class="_contentDescription_1cx04_117"><span class="_label_1cx04_146">ПРОМО</span><div class="_heading_1cx04_2">Превратите свой телефон в&nbsp;бизнес-партнера</div><div class="_spacer_1cx04_51"></div><span class="_customButton_1cx04_94">Узнать&nbsp;как</span></div><div class="_spacer_1cx04_51"></div><div class="_contentImage_1cx04_155" style="background-image:url(https://opis-cdn.tinkoffjournal.ru/mercury/spec-mobile-forbusiness-banner-shapka.png)"></div></div></a></div></div><script type="application/json" data-app-id="3vMkfMeJN-dBsql-Q2vbw">{"id":"spec-mobile-forbusiness-banner.fortuna","link":"https://journal.tinkoff.ru/list/spec-mobile-forbusiness/?internal_source=tj_spec_mobile_spec-mobile-forbusiness_mobile-forbusiness-banner.fortuna.1","image":"https://opis-cdn.tinkoffjournal.ru/mercury/spec-mobile-forbusiness-banner-shapka.png","label":"ПРОМО","title":"Превратите свой телефон в&nbsp;бизнес-партнера","styles":{"banner":{"bg_color":"#62B0FF","on_bg_color":"#ffffff","hovered_bg_color":"#178BFF","on_hovered_bg_color":"#ffffff"},"button":{"bg_color":"#ffffff","on_bg_color":"#000000"}},"target":{"factor":100},"button_text":"Узнать&nbsp;как","flags":{"enable_image_preset":true}}</script></div></div>`


</details>

**Comment by dimisa-RUAdList** [comment]
Ранее я писал:
> Если вы видите из-под аккаунта этот анонс на главной, потребуется скрин кода элемента в таком варианте макета.

Однако судя по скриншоту, код скопирован не на главной, а в какой-то статье. Нужен код именно с главной страницы.

**Comment by CATIOR** [comment]
Да я вас не понимаю, проблему указал, код скопировал. Вы что-то выдумываете, на главной, не на главной — разница в чем? Баннер есть, занимает внушительную часть страницы. Не хотите исправлять — не исправляйте, пусть висит этот баннер.

**Comment by dimisa-RUAdList** [comment]
Ок, я поясню. Поскольку вы с авторизаций видите этот анонс на главной (как заявлено в стартовом сообщении), а я без авторизации его там не наблюдаю, это означает только одно - у залогиненных пользователей на главной странице формируется другой вариант макета. И добавив правило для скрытия анонса в статьях, я рискую поломать главную страницу у всех пользователей с авторизацией. Именно поэтому важно понять, какой всё-таки код у этого анонса на главной странице.

**Comment by dimisa-RUAdList** [comment]
Наконец, удалось выполнить проверку из-под аккаунта. Как выяснилось, анонс этого промо на главной отсутствует. Указывайте пожалуйста ссылку именно на ту страницу, где наблюдается проблема.

https://github.com/easylist/ruadlist/commit/2e03475dcf267692655f6e5f9e76e44cf09cd482
