### ISSUE TITLE
budport.com.ua

### ISSUE THREAD

**Issue by P0Rtvine** [easylist/ruadlist#4]
### Перечислите веб-сайт(ы), с которым(и) у вас возникли проблемы:
`http://budport.com.ua/`

### Что происходит?
Рецидив

### Скриншот(ы)
<details>
<summary>Вид сайта</summary>

![2020-10-06_220524](https://user-images.githubusercontent.com/57287308/95248708-5ef4a880-0820-11eb-9a29-bc3e9658b550.png)

![2020-10-06_220551](https://user-images.githubusercontent.com/57287308/95248712-6320c600-0820-11eb-9bc0-8575fd0468ca.png)
</details>

### Список используемых вами подписок:
<details>
<summary>Скрин фильтров</summary>

![2020-10-06_200541](https://user-images.githubusercontent.com/57287308/95236290-68c1e000-080f-11eb-858f-43e5d3dbeb6b.png)
</details>

### Ваши настройки

- ОС/версия: Win 8.1 x64
- Браузер/версия: Opera|Stable(85.0.4183.121)
- Расширение/Adblock|uBO: uBO 1.30.0

**Comment by dimisa-RUAdList** [comment]
Думаю, этот тикет можно не закрывать, поскольку это не первый с ним рецидив.
https://github.com/easylist/ruadlist/commit/1b5d324afbdd5f621b27e4f1fb3dde81835deecf

**Comment by P0Rtvine** [comment]
### Что происходит?
Обошли.

### Скриншот(ы)
<details>
<summary>Вид сайта</summary>

![2020-10-11_125905](https://user-images.githubusercontent.com/57287308/95675695-c2385f00-0bc1-11eb-90f1-cda0ecf37a38.png)
![2020-10-11_125941](https://user-images.githubusercontent.com/57287308/95675696-c49ab900-0bc1-11eb-95d6-081f79a88dc8.png)
</details>

### Список используемых вами подписок:
<details>
<summary>Скрин фильтров</summary>

![2020-10-06_200541](https://user-images.githubusercontent.com/57287308/95236290-68c1e000-080f-11eb-858f-43e5d3dbeb6b.png)
</details>

### Ваши настройки

- ОС/версия: Win 8.1 x64
- Браузер/версия: Opera|Stable(85.0.4183.121)
- Расширение/Adblock|uBO: uBO 1.30.0

**Comment by dimisa-RUAdList** [comment]
Поправил: https://github.com/easylist/ruadlist/commit/4254292fdd8c7bc119ea3805df33f91f12a0364b

Но hg.adblockplus.org сейчас "лежит", так что раньше понедельника фильтры не обновятся.

**Comment by P0Rtvine** [comment]
### Что происходит?
Снова обошли.

### Скриншот(ы)
<details>
<summary>Вид сайта</summary>

![2020-10-13_084729](https://user-images.githubusercontent.com/57287308/95820498-de0e4300-0d30-11eb-9492-97095887758b.png)
![2020-10-13_084825](https://user-images.githubusercontent.com/57287308/95820510-e0709d00-0d30-11eb-8c68-de821e6ebe25.png)
</details>

### Список используемых вами подписок:
<details>
<summary>Скрин фильтров</summary>

![2020-10-06_200541](https://user-images.githubusercontent.com/57287308/95236290-68c1e000-080f-11eb-858f-43e5d3dbeb6b.png)
</details>

### Ваши настройки

- ОС/версия: Win 8.1 x64
- Браузер/версия: Opera|Stable(85.0.4183.121)
- Расширение/Adblock|uBO: uBO 1.30.4

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/2696903262937a976e41e797b5d5fe7c21cea682

**Comment by P0Rtvine** [comment]
### Перечислите веб-сайт(ы), с которым(и) у вас возникли проблемы:

`http://budport.com.ua/`

### Что происходит?
Обошли
### Скриншот(ы)
<details>
<summary>Вид сайта</summary>

![2020-11-05_085653](https://user-images.githubusercontent.com/57287308/98207939-1cb8a700-1f45-11eb-8410-1461e3e76416.png)
</details>

### Список используемых вами подписок:
<details>
<summary>Скрин фильтров</summary>

![2020-10-06_200541](https://user-images.githubusercontent.com/57287308/95236290-68c1e000-080f-11eb-858f-43e5d3dbeb6b.png)
</details>

### Ваши настройки

- ОС/версия: Win 8.1 x64
- Браузер/версия: Opera|Stable(86.0.4240.111)
- Расширение/Adblock|uBO: uBO 1.30.8

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/7c3f8a291eea2d537f3eede343a06d976e156972

**Comment by P0Rtvine** [comment]
### Перечислите веб-сайт(ы), с которым(и) у вас возникли проблемы:

### Что происходит?
Детект адблока

### Скриншот(ы)
<details>
<summary>Вид сайта</summary>

![2020-11-11_114726](https://user-images.githubusercontent.com/57287308/98796830-812ba880-2414-11eb-9777-e93fe61a208b.png)
![2020-11-11_114627](https://user-images.githubusercontent.com/57287308/98796840-838e0280-2414-11eb-95de-f5fc5890e939.png)
</details>

### Список используемых вами подписок:
<details>
<summary>Скрин фильтров</summary>

![2020-10-06_200541](https://user-images.githubusercontent.com/57287308/95236290-68c1e000-080f-11eb-858f-43e5d3dbeb6b.png)
</details>

### Ваши настройки

- ОС/версия: Win 8.1 x64
- Браузер/версия:  Google Chrome(86.0.4240.193) x64
- Расширение/Adblock|uBO: uBO 1.30.6

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/884eee95318df74bd75ef80e016b6ef30f5a0589

**Comment by P0Rtvine** [comment]
### Перечислите веб-сайт(ы), с которым(и) у вас возникли проблемы:
`http://budport.com.ua/`

### Что происходит?
Обошли

### Скриншот(ы)
<details>
<summary>Вид сайта</summary>

![2020-11-15_210743](https://user-images.githubusercontent.com/57287308/99194213-b9b9e200-2786-11eb-857c-f9b48850b6be.png)
</details>

### Список используемых вами подписок:
<details>
<summary>Скрин фильтров</summary>

![2020-10-06_200541](https://user-images.githubusercontent.com/57287308/95236290-68c1e000-080f-11eb-858f-43e5d3dbeb6b.png)
</details>

### Ваши настройки

- ОС/версия: Win 8.1 x64
- Браузер/версия:  Google Chrome(86.0.4240.198) x64
- Расширение/Adblock|uBO: uBO 1.30.6

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/a6b309bafc5ef8aaf6cd905ca0da2f81553c377f

**Comment by dimisa-RUAdList** [comment]
Перенёс в AWRL: https://github.com/easylist/antiadblockfilters/commit/7910d9a293870277f9b00e709d4ba684cf22d03d

**Comment by P0Rtvine** [comment]
### Перечислите веб-сайт(ы), с которым(и) у вас возникли проблемы:
`http://budport.com.ua/news/19291-zakonoproekt-schodo-generalnoj-shemi-ukrajni-pidtrimano-komitetom-vr`

### Что происходит?
При клике по изображению - Детект адблока

### Скриншот(ы)
<details>
<summary>Вид сайта</summary>

![2020-11-16_092305](https://user-images.githubusercontent.com/57287308/99223556-6464eb80-27ed-11eb-9cc5-db3183683a90.png)
</details>

### Список используемых вами подписок:
<details>
<summary>Скрин фильтров</summary>

![2020-11-16_092305](https://user-images.githubusercontent.com/57287308/99223825-ece38c00-27ed-11eb-9e99-59fe79c37523.png)
</details>

### Ваши настройки

- ОС/версия: Win 8.1 x64
- Браузер/версия:  Google Chrome(86.0.4240.198) x64
- Расширение/Adblock|uBO: uBO 1.30.6

**Comment by dimisa-RUAdList** [comment]
Поправил: https://github.com/easylist/antiadblockfilters/commit/76ad57bdc9306a18bcabe7cba59fe926ef253549#diff-da9d223914be1a575e513b22c59aafc77500dff80be69018e3682a9c5bc3c490
