### ISSUE TITLE
http://mobtop.ru/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/ruadlist#40]
Side banners and adserver at http://mobtop.ru/

**Tested as mobile**

||fijfigaahebebdigd.ru
||mobtop.ru/static/imgs/

Screnshots: 
<img width="1198" alt="Screenshot 2022-01-14 at 12 03 43" src="https://user-images.githubusercontent.com/65717387/149505519-a3bfc6b6-cfb8-4fbd-9d30-72de5796eec3.png">
<img width="1188" alt="Screenshot 2022-01-14 at 11 59 16" src="https://user-images.githubusercontent.com/65717387/149505532-74a6ba11-b248-4d49-9ef0-c40d533bc0a8.png">

**Comment by dimisa-RUAdList** [comment]
Ok: https://github.com/easylist/ruadlist/commit/706a4b3ae31c417dbede9a89293994593268df0c
