### ISSUE TITLE
habr.com

### ISSUE THREAD

**Issue by jtraub** [easylist/ruadlist#41]
https://github.com/easylist/ruadlist/commit/edbcf224158475cbb61a1ec870dfa10fbc1a5661 broke profile display on habr.com

Open https://habr.com/ru/users/DmitryKazakov8/ for example with RU AdList: BitBlock + Fanboy's General enabled

You will see this
![image](https://user-images.githubusercontent.com/153191/151304360-1e43b668-7d72-42d0-aac9-d1eef1cfc3e6.png)

Here a quite useful block with general info about user and their comments and articles is missing

If the list is disabled everything seems to work just fine
![image](https://user-images.githubusercontent.com/153191/151304789-9dd71ba6-3435-4aa1-b0f6-4c2f2936e81d.png)

**Comment by dimisa-RUAdList** [comment]
Ок, исправлено: https://github.com/easylist/ruadlist/commit/45db42e2268e40f103a57b5229681fa5d0a473e4
