### ISSUE TITLE
регулярка ||de/|$third-party,xmlhttprequest  блокирует валидный сайт

### ISSUE THREAD

**Issue by Mybeard** [easylist/ruadlist#42]
использую UblockOrigin, при переходе из гугла или других сайтов, на главную страницу блокируется сайт https://makeupstore.de/

![image](https://user-images.githubusercontent.com/17643825/151551503-8cc54ab2-37e6-4381-b7f1-460a397f6bbc.png)

**Comment by dimisa-RUAdList** [comment]
Опишите пожалуйста проблему так, как указано [здесь](https://forums.lanik.us/viewtopic.php?t=24280) в пункте 4.
