### ISSUE TITLE
torrent-wind.net

### ISSUE THREAD

**Issue by gurulo1985** [easylist/ruadlist#43]
Здравствуйте, уважаемая техподдержка. Мой сайт не работает для пользователей из России и Украины из-за фильтра EasyList. Вместо сайта открывается пустая белая страница. Если наш сайт нарушил какое-нибудь правило, мы готовы исправить проблему. Скажите пожалуйста, как можно решить данную ситуацию? больше обход блокировки не будем делать

**Comment by gurulo1985** [comment]
torrent-wind.net

**Comment by dimisa-RUAdList** [comment]
Сайты, обходящие блокировку продвижения вредоносного ПО, блокируются намеренно. Через форму обратной связи на сайте вам направлялось [соответствующее предупреждение](https://forums.lanik.us/viewtopic.php?p=162378#p162378), но вы его [проигнорировали](https://forums.lanik.us/viewtopic.php?p=162998#p162998).

**Comment by gurulo1985** [comment]
мы не получили никакой письмо возможно попал в спам, если бы знали что такое строгое наказание никогда не сделали бы,  это наш первое предупреждение, мы больше не собираемся делать обход и кстати медигет эта белое реклама, оно у меня стоит уже 10 лет  оно на тысячи сайтах

**Comment by gurulo1985** [comment]
у вас был прецедент похожи тематикой,  https://forums.lanik.us/viewtopic.php?p=162271&hilit=soft+torrent+soft.net#p162271  очень просим разблокировать на site, мы берем ответственность  болше такое никогда не будет на site, я имею ввиду обход adblock

**Comment by gurulo1985** [comment]
Последний вопрос, с какова email адреса вы отправляете письма? через обратная связь?

**Comment by gurulo1985** [comment]
мы не получили никакой письмо возможно попал в спам, если бы знали что такое строгое наказание никогда не сделали бы, это наш первое предупреждение, мы больше не собираемся делать обход и кстати медигет эта белое реклама, оно у меня стоит уже 10 лет оно на тысячи сайтах, у вас был прецедент похожи тематикой, https://forums.lanik.us/viewtopic.php?p=162271&hilit=soft+torrent+soft.net#p162271 очень просим разблокировать наш site, мы берем ответственность болше такое никогда не будет на site, я имею ввиду обход adblock Отправлено из приложения "Почта" для Windows От: dimisaОтправлено: 31 января 2022 г. в 23:27Кому: easylist/ruadlistКопия: gurulo1985; AuthorТема: Re: [easylist/ruadlist] torrent-wind.net (Issue #43) Сайты, обходящие блокировку продвижения вредоносного ПО, блокируются намеренно. Через форму обратной связи на сайте вам направлялось соответствующее предупреждение, но вы его проигнорировали.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***> 



	
		
			
				
			
		
		
			
				Это сообщение проверено на вирусы антивирусом Avast.
				www.avast.com

**Comment by dimisa-RUAdList** [comment]
Вот отчёт по медиагет: `https://www.virustotal.com/gui/file/8e5fb0cb6d3e8a9a3d5977f6f41e378bbf8df07217d8726047eec8e60a2bab94`

Но главное даже не сам отчёт, а фактическое поведение софта.

В обратной форме сайта `torrent-wind.net` указано несколько получателей, которым можно отправить сообщение: torrent-games, kiril, mediagetkiril, uploader. Укажите того получателя, которому можно отправить адрес почты для продолжения диалога.

**Comment by gurulo1985** [comment]
шокирующий результат, у нас переходи на сите 99% из яндекс, не могу поверить что яндекс пропускает такие сайты в топ, честно от души говорю почти 10 лет у меня стоит на всех сайтах они, от пользователей тоже не было плохих отзывов. я поправлю обратный связь там проблема, поводу мои проблемы, буду от души благодарны если поможете исправить, не хочется на новый домен перейти, один шанс все заслуживают )))

**Comment by dimisa-RUAdList** [comment]
Я правильно понимаю, что речь идёт только о `torrent-wind.net` и к другим доменам вы отношения не имеете?

**Comment by gurulo1985** [comment]
> Я правильно понимаю, что речь идёт только о `torrent-wind.net` и к другим доменам вы отношения не имеете?

другие какие? софт тематика умения толька эта oдин  torrent-wind.net зеркало torrent-windows.org

**Comment by dimisa-RUAdList** [comment]
То есть, `allgames.zone` и прочие - это не ваши?

**Comment by gurulo1985** [comment]
allgame мои там тоже ничего не получали и предупреждение, умения на всех сайтах одинаковые дизайны, просто тематики другие, фильмы, игры, софт.

**Comment by dimisa-RUAdList** [comment]
Перечислите пожалуйста адреса ваших сайтов.

**Comment by gurulo1985** [comment]
26.11.21 Уведомлены, что в случае обхода скрытия кнопки, будут заблокированы:
download-windows.org
torrent-games.su
torrent-wind.net

------------------------------
download-windows.org я не знаю чей это

tfile.vip
torrentino.in
bestgamer.net
allgames.zone
torrent-wind.net

**Comment by gurulo1985** [comment]
consol-games.com

**Comment by gurulo1985** [comment]
толька эти два сайти allgames и windows  большие остальные 100- 200 человек в сутки заходит

**Comment by gurulo1985** [comment]
https://my.allgames.zone/news/repacks-xatab/91619-horizon-zero-dawn-complete-edition.html за последние 5 месяц на эту страницу около 500 комментарии, скачали эту игру несколько сотни тысячи человек, если вы увидите хоть одну комментарии по поводу вируса я удалю сити сегодня, этому сайту 11 лет

**Comment by dimisa-RUAdList** [comment]
Причём здесь игра? Речь во всех случаях идёт об офферах типа медиагета, янд.браузера и пр.

**Comment by gurulo1985** [comment]
я думаю никто не заставляет людей установить браузеры, я лично не допущу такое на моем сайте я читаю каждый отзыв, там же на выбор ставишь галочку и все, у вас ваша политика, спорить нет смысла,  я должен найти как вебмастер залатой вариант, чтобы не нарушать правила и не упал трафик, если честно я удивлен по поводу медиа гет, я могу вам перечислить здесь тысячи сайтов конкурентов где стоит mediaget, они обходят adblock, но я не вижу что они заблокированы как мои site, я не собираюсь стучат никаво вы если захотите увидите в топ яндекс

**Comment by gurulo1985** [comment]
> у вас был прецедент похожи тематикой, https://forums.lanik.us/viewtopic.php?p=162271&hilit=soft+torrent+soft.net#p162271 очень просим разблокировать наш site, мы берем ответственность болше такое никогда не будет на site, я имею ввиду обход adblock

torrent-soft.net 2 месяц назад вы простили его там все равно стоит, такие магу сотни тысячи показать

**Comment by dimisa-RUAdList** [comment]
Нет, уже заблокирован: https://hg.adblockplus.org/ruadlist/rev/b701408ffa8c но теперь уже навсегда.

**Comment by gurulo1985** [comment]
я вам дал и даю мои слова, на моих сайтах обход никогда не будет, от души прошу дать один шанс

**Comment by dimisa-RUAdList** [comment]
Хорошо. Пока пытаюсь разобраться.

`consol-games.net` - ваш?

Также наблюдаю редиректы:
`torrent-games.su > allgames.zone`
`bestgamer.net > bestgamer.su`

Сделайте пожалуйста чистовой список, чтобы он был размещён в одном сообщении, а не разбросан по нескольким.

**Comment by gurulo1985** [comment]
и так роскомнадзор блокирует такие сайты как наш, не хочется имя сменить опять.. буду благодарен если пойдете на один шанс.

consol-games.net
torrent-games.su > allgames.zone
bestgamer.net > bestgamer.su

да мои сайты

**Comment by gurulo1985** [comment]
добрый день, какое решение вы приняли?

**Comment by dimisa-RUAdList** [comment]
Домен разблокирован. Чтобы вытянуть изменения прямо сейчас, обновитесь [вручную](https://forums.lanik.us/viewtopic.php?f=102&t=22786). В блокировщиках Adblock Plus, AdBlock, uBlock Origin, и т.д. - изменения раскатаются автоматом в течении 48 часов, во встроенных блокировщиках Brave, Opera, Vivaldi, и т.д. - в течении 5-7 дней.

Воздержитесь пожалуйста от обхода блокировки на ваших сайтах, во избежании повторения подобного.

**Comment by gurulo1985** [comment]
я дал вам мои слова, удачи и спасибо, тема закрыта

**Comment by gurulo1985** [comment]
consol-games.net
consol-games.com

разные сайты.

чт, 3 февр. 2022 г., 21:12 dimisa ***@***.***>:

**Comment by gurulo1985** [comment]
этот 2  не отдал, потому что там посещаемость 50чел всутки

чт, 3 февр. 2022 г., 21:37 Giga Chxaidze ***@***.***>:

**Comment by dimisa-RUAdList** [comment]
То есть, `consol-games.com` - не ваш сайт и можно его убивать?

**Comment by gurulo1985** [comment]
consol-games.com
consol-games.net
оба мои, после того как вы заблокируйте, обход мы не будем делать, в
прошлый раз, когда вы сделали блокировку, мы не обходили его, просто этот 2
другой сайт.

чт, 3 февр. 2022 г., 21:41 dimisa ***@***.***>:

**Comment by dimisa-RUAdList** [comment]
Ок, поменял правила. Но далее подобное будет считаться обходом.

**Comment by gurulo1985** [comment]
это разные сайты, и в поисковой системе тоже по-разному индексируется. это
не обход100% обход - это когда вы заблокируете. и мы будем обходить. 🤷‍♂️
у нас сетка сайтов из сотни сайтов. если жалоба поступит на какой-нибудь, и
сделайте блокировку, и мы будем сделать обход, вы сможете пожизненно
заблокировать наш сайт. мы уже ведём переговоры с новым рекламодателем. так
что с ним проблем не будет.

чт, 3 февр. 2022 г., 22:03 dimisa ***@***.***>:

**Comment by dimisa-RUAdList** [comment]
Без разницы, как индексируется. Если я вижу, что заблокированные ранее кнопки загрузки вредоносного ПО снова активны - это обход.

**Comment by dimisa-RUAdList** [comment]
Наблюдаю обход за счёт создания зеркал `utorrent.games, allgames.vip` и пр. Тут есть варианты. Либо вы сами следите, чтобы кнопки офферов не отображались у пользователей блокировщиков, либо все ваши домены будут блокироваться автоматом.

**Comment by dimisa-RUAdList** [comment]
То есть, вариант самостоятельного отслеживания отсутствия кнопки офферов у пользователей блокировщиков вас не устраивает?

**Comment by gurulo1985** [comment]
как мне понять, для кого отключить? кому нравится и кому не нравится
реклама? то есть, как я понял, если я поменяю из-за блокировки имя сайта?
реклама опять видно людям? если это так подскажите как сделать так чтобы
реклама не показывался для пользователей adblock, тогда ещё вариант : после
каждой смены имя я напишу вам здесь, и вы  руками опять в чёрный список
его, поверьте меня сменить сайта из обхода реклама нет никакого смысла при
каждой смене имя сайта теряем очень много трафика. allgames.vip это
единственное новое имя, которое подключили сегодня. тогда внести его
поправку руками пожалуйста, потому что я не знаю, как с сайта управлять это.

пт, 11 февр. 2022 г., 20:17 dimisa ***@***.***>:

**Comment by gurulo1985** [comment]
https://reestr.rublacklist.net/search/?q=utorrent.games

**Comment by dimisa-RUAdList** [comment]
Понятно. На самом деле, вариант самостоятельного отслеживания отсутствия кнопки офферов у пользователей блокировщиков является уже устоявшейся практикой среди ресурсов, которые монетизируются за счёт продвижения вредоносного ПО и кочующих с одного домена на другой. Как правило, для этого используются общие (не привязанные к конкретным доменам) правила из фильтров.

Можно "подставить" под блокировку путь картинки, которая в итоге будет подпадать под блокирующую маску типа `/baner/`. Или же использовать имя элемента, которое будет подпадать под общее правило скрытия, например `###adv`.

Посмотреть общие правила блокировок и скрытия можно здесь:
https://github.com/easylist/ruadlist/blob/master/advblock/general_block.txt
https://github.com/easylist/ruadlist/blob/master/advblock/general_hide.txt

Подумайте, это действительно может оказаться удобнее, нежели постоянно помнить о необходимости уведомлений при каждом переезде. Можно и забыть.

**Comment by dimisa-RUAdList** [comment]
Пока заблокировал баннеры обычным способом.

**Comment by gurulo1985** [comment]
хорошо спасибо, я сообщу. если удастся мне что-то придумать, если нет,
обязательно напишу, даю слово. типа если сменю имя сайта какого нибудь. эта
ссылка у меня сохранено в закладках.

пт, 11 февр. 2022 г., 21:32 dimisa ***@***.***>:

**Comment by gurulo1985** [comment]
привет на сайте, allgames.vip, блокируется задний фон сайта, там нету реклама и никогда не было

**Comment by gurulo1985** [comment]
[https://a.radikal.ru/a31/2202/52/fcabeb8ad4a6.png](url)

**Comment by gurulo1985** [comment]
![Снимок экрана 2022-02-14 235253](https://user-images.githubusercontent.com/98765046/153936388-e214c5f3-9323-4a68-bea8-895ff23262ee.png)

**Comment by gurulo1985** [comment]
привет, давно меня есть этот домен никогда не использовал, пару месяц назад купил, сейчас хотел установить сите но главное страница заблочено ADblock [Белый экран]

**Comment by gurulo1985** [comment]
rutor.su

**Comment by dimisa-RUAdList** [comment]
Делайте. Как будет готов, я отредактирую текущие правила.

**Comment by dportvine** [comment]
`https://allgames.vip/`, `https://utorrent.games/` - не работают.

Редирект:
`https://bestgamer.net` ~> `https://my.bestgamer.su/`
`https://torrent-games.su` ~> `https://allgames.zone/`
`https://torrent-windows.org` ~> `https://torrent-wind.net/`

**Comment by gurulo1985** [comment]
> `https://allgames.vip/`, `https://utorrent.games/` - не работают.
> 
> Редирект: `https://bestgamer.net` ~> `https://my.bestgamer.su/` `https://torrent-games.su` ~> `https://allgames.zone/` `https://torrent-windows.org` ~> `https://torrent-wind.net/`

На всех сайтах блокируется реклама, и не срабатывает при включённом AdBlock

**Comment by dportvine** [comment]
>На всех сайтах блокируется реклама, и не срабатывает при включённом AdBlock

Вы робот? 
Первые два, **не работают**. Три остальные, редирект на другие адреса. О какой рекламе идет речь?

**Comment by gurulo1985** [comment]
> рекламе

Вас не учили общаться с людьми? Кого вы оскорбляете называя роботом? Ну и что редирект? Здесь что обсуждается в этот чат? Редиректы или блокировка рекламы? Какой ваши дела какой редиректами поставим на сайте? Мы следим активно чтобы не появился реклама при включённом AdBlock, и конкретно это обсуждается в этот чат. Или вы придумали собственные правила чтобы контролировать редирект, скорее всего я не понял что-то. Задание который мне дали активно следую, не должно появляться реклама, ещё что-то новое????????

**Comment by dimisa-RUAdList** [comment]
Непонятно, о чём спор, но думаю, не стоит его продолжать. Правила для неработающих доменов удалил.
