### ISSUE TITLE
https://tel.rukoed.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/ruadlist#45]
Popunders at https://tel.rukoed.com/

Screenshots: 
<img width="913" alt="Screenshot 2022-03-22 at 09 59 59" src="https://user-images.githubusercontent.com/65717387/159444390-b72aa1f9-1719-4315-bbae-aa892817705e.png">

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/dda8fc9e53bc6a9e919db98f404e5596add25134
