### ISSUE TITLE
https://you-stories.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/ruadlist#48]
Adserver at https://you-stories.com/

Screenshot:
<img width="1272" alt="Screenshot 2022-03-28 at 06 47 46" src="https://user-images.githubusercontent.com/65717387/160328387-bae1433c-e2db-4439-b62c-045a1fd70dc3.png">
<img width="1104" alt="Screenshot 2022-03-28 at 06 49 09" src="https://user-images.githubusercontent.com/65717387/160328441-a4e46e6e-3805-46cc-a682-4b490e467144.png">

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/7cba7141710de4cf94a1010275cb1e0fa6c7e49d
