### ISSUE TITLE
A: https://solenka.info/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/ruadlist#49]
Screenshot: 
<img width="1259" alt="Screenshot 2022-03-28 at 09 46 47" src="https://user-images.githubusercontent.com/65717387/160350991-d2abe00f-b603-40f9-90c8-4974e7eee216.png">

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/25dd828fb9f5eda9dd6c310b960263e7fe4ced18
