### ISSUE TITLE
tsn.ua

### ISSUE THREAD

**Issue by P0Rtvine** [easylist/ruadlist#5]
### Перечислите веб-сайт(ы), с которым(и) у вас возникли проблемы:
`https://tsn.ua/ru/ukrayina/konoplyanaya-moda-kak-ukraincy-mogut-zarabatyvat-na-etom-rastenii-i-pokorit-mir-1638877.html`

### Что происходит?
Детект адблока

### Скриншот(ы)
<details>
<summary>Вид сайта</summary>

![2020-10-07_102848](https://user-images.githubusercontent.com/57287308/95300675-25f01e80-0888-11eb-85cd-61b75f029714.png)

![2020-10-07_102908](https://user-images.githubusercontent.com/57287308/95300681-28527880-0888-11eb-8e55-15778489a940.png)

![2020-10-07_102931](https://user-images.githubusercontent.com/57287308/95300689-2be5ff80-0888-11eb-81a4-599843d9f0a4.png)
</details>

### Список используемых вами подписок:
<details>
<summary>Скрин фильтров</summary>

![2020-10-06_200541](https://user-images.githubusercontent.com/57287308/95236290-68c1e000-080f-11eb-858f-43e5d3dbeb6b.png)
</details>

### Ваши настройки

- ОС/версия: Win 8.1 x64
- Браузер/версия: Opera|Stable(85.0.4183.121)
- Расширение/Adblock|uBO: uBO 1.30.0

**Comment by dimisa-RUAdList** [comment]
Отредактировал тикет, добавив сворачивание скриншотов, использовав код:

```
<details>
<summary>Вид сайта</summary>

![2020-10-07_102848](https://user-images.githubusercontent.com/57287308/95300675-25f01e80-0888-11eb-85cd-61b75f029714.png)

![2020-10-07_102908](https://user-images.githubusercontent.com/57287308/95300681-28527880-0888-11eb-8e55-15778489a940.png)
```
Детектор пофиксил: https://github.com/easylist/ruadlist/commit/aa2f6705f3feaf178d4b9f7aff96b94a9d9289cc

**Comment by P0Rtvine** [comment]
@dimisa-RUAdList 
Я при создании, сделал случайно дубль, удалить его здесь нельзя.
Поэтому закрыл и убрал содержимое.

**Comment by P0Rtvine** [comment]
### Перечислите веб-сайт(ы), с которым(и) у вас возникли проблемы:
`https://tsn.ua/ru/ukrayina/mezhdunarodnye-posylki-po-novomu-rada-podderzhala-zakonoproekt-o-povyshenii-do-150-evro-besposhlinnogo-limita-1714645.html`

### Что происходит?
Огрызки соц.сетей

### Скриншот(ы)
<details>
<summary>Вид сайта</summary>

![2021-01-29_075035](https://user-images.githubusercontent.com/57287308/106237909-7bba4f00-6208-11eb-91da-8d9ecdf58b8d.png)
</details>

### Список используемых вами подписок:
<details>
<summary>Скрин фильтров</summary>

![2021-01-22_100714](https://user-images.githubusercontent.com/57287308/105464158-c3395c00-5c99-11eb-965b-81215d8f7bec.png)
</details>

### Ваши настройки

- ОС/версия: Win 8.1 x64
- Браузер/версия: Google Chrome
- Расширение/Adblock|uBO: uBO 1.32.4

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/34730a63b950c617618bc19fc39896cf4faa2f86

**Comment by dportvine** [comment]
Чисто спортивный интерес, можно убрать вот это из консоли?


<details>
<summary>Screen</summary>

![2023-05-30_144100](https://github.com/easylist/ruadlist/assets/111344219/0067d619-865a-473f-a893-bb5b2538d9bc)
</details>

```
https://tsn.ua/tsikavinki/turistka-pokazala-ogolenu-vaginu-prosto-posered-vulici-ta-rozlyutila-merezhu-video-2339665.html
```

**Comment by dimisa-RUAdList** [comment]
Не только можно, но и нужно, ведь AWRL, скрывающий предупреждение об отключении адблока, подключен не у всех пользователей блокировщиков.

В случае с uBlock Origin можно было бы использовать: `tsn.ua##+js(addEventListener-defuser, adblockDetected)`

Или: `tsn.ua##+js(abort-on-property-read, tsn.advertizer.isAdblock)`

Но пользователям ABP/AB это ничем не поможет, поэтому лучше обновить исключение для детектора адблока и заодно перенести скрытие его элементов в основной фильтр, поскольку если этого не сделать, получится масса пустых мест.

Fix: https://github.com/easylist/ruadlist/commit/a08931b59a8934bc94469d678310cac383a45a48

**Comment by dportvine** [comment]
У меня этот скриплет  `tsn.ua##+js(addEventListener-defuser, adblockDetected)` не работает, я проверял.

**Comment by dimisa-RUAdList** [comment]
С `addEventListener-defuser` происходит что-то непонятное, и его работоспособность сейчас зависит от версии uBO и попутного ветра. 

https://github.com/gorhill/uBlock/wiki/Resources-Library#addeventlistener-defuserjs-

Логгирование `##+js(aeld, { "type": "/.^/", "log": 2 })`, бывший `addEventListener-logger` вообще похоже перестал работать в dev-версиях, но при этом нормально функционирует в 1.49.2.

Надо писать Раймонду, постараюсь в течении дня это сделать.

**Comment by dimisa-RUAdList** [comment]
Сообщил: https://github.com/uBlockOrigin/uBlock-issues/issues/2679
