### ISSUE TITLE
http://animego.life/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/ruadlist#50]
Inside banner at http://animego.life/

**Tested as mobile**

Screenshot: 
<img width="1156" alt="Screenshot 2022-03-29 at 11 43 44" src="https://user-images.githubusercontent.com/65717387/160583606-6e44e0ba-4e09-44a0-9b10-942f13d4c7f2.png">

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/a7b08ebea1712b3f84b2da0f4dbcf1ed404f2456
