### ISSUE TITLE
https://www.adme.ru/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/ruadlist#51]
Placeholders at https://www.adme.ru/

**Mobile as well**

Screenshot: 
<img width="853" alt="Screenshot 2022-03-31 at 10 16 05" src="https://user-images.githubusercontent.com/65717387/161009735-a25e71bf-0d7b-4421-928e-72e4bb9a1920.png">

**Comment by dimisa-RUAdList** [comment]
What blocker are you trying to imitate when you use the mobile version of the site?
