### ISSUE TITLE
https://adult.mat6tube.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/ruadlist#53]
Not sure if it should be here or in EL. 

But here we go: 
<img width="1424" alt="Screenshot 2022-04-11 at 12 32 09" src="https://user-images.githubusercontent.com/65717387/162722556-ab3fc561-abe4-4fca-9ade-251c8a7ff585.png">
`cdn-e02.cdnbmb.com`

**Comment by dimisa-RUAdList** [comment]
You don't link to the page with the problem, but I think that the rules for this domain should be contained in EasyList, yet this site is not Russian.
