### ISSUE TITLE
4pda.to

### ISSUE THREAD

**Issue by CbumDino** [easylist/ruadlist#56]
Banners at `https://4pda.to/`

<details>
<summary>Screenshot(s)</summary>

<img width="1296" alt="Screenshot 2022-04-20 at 17 52 01" src="https://user-images.githubusercontent.com/65717387/164271898-b70a74f8-a12f-403c-a0fc-6d2633cc245a.png">

</details>

**Comment by dimisa-RUAdList** [comment]
This site belongs to the problematic category.
Solution here: https://greasyfork.org/en/scripts/19993-ru-adlist-js-fixes

**Comment by dportvine** [comment]
`https://4pda.to/2023/12/20/422165/obzor_infinix_smart_8_dostupnyj_smartfon_s_premialnymi_notkami/`


<details>
<summary>Screenshot(s)</summary>

![2023-12-20_151253](https://github.com/easylist/ruadlist/assets/111344219/2507d3d4-fa70-4444-90fc-4f768e697575)
</details>

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 116708
 cosmetic: 115118
 scriptlet: 26561
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
  urlhaus-1: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 25966-19, 8m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1682-27, 8m
  https://www.awwwwesome.org/url-blocklist/url-blocklist.txt: 1243-0, 8m
  adguard-cookies: 28231-254, 8m
  ublock-annoyances: 6360-24, 8m
 default:
  user-filters: 5-0, never
  RUS-0: 40021-138, 8m
  easylist: 76103-62, 8m
  easyprivacy: 33123-464, 8m
  ublock-badware: 7643-138, 8m
  ublock-filters: 36436-380, 8m
  ublock-privacy: 951-21, 8m
  ublock-quick-fixes: 100-5, 8m
  ublock-unbreak: 2176-34, 8m
filterset (user): [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 filterAuthorMode: true
 popupPanelHeightMode: 1
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 494 ms (selfie)
 maxAssetCacheWait: 307 ms
popupPanel:
 blocked: 3
 network:
  google.com: 3
 extended:
  ##.huawei-social
  ##.social
  ##html[style] > body [class]:not([id]):not(div):not([style]) :no…
  ##html[style] > body :not(div) ~ :not(div)[class][id][style]:sty…
  ##html[style] > body div.holder-no-hidden:style(margin-bottom: 1…
  ##+js(adjust-setTimeout, zat_tick)
  ##+js(no-xhr-if, /m2?_)
  ##+js(abort-current-script, document.querySelectorAll, outerHeig…
  ##+js(no-setTimeout-if, removeAttr, setTimeout)
  ##+js(abort-on-property-read, document.referrer)
```
</details>

**Comment by dimisa-RUAdList** [comment]
Ok: https://github.com/easylist/ruadlist/commit/87b96853ec7ffb5978930676c740404601b7bf8e

**Comment by dportvine** [comment]
А бекграунд?

**Comment by dimisa-RUAdList** [comment]
Рискованно. Маловато признаков уникальности, чтобы сделать это безопасно и стабильно.

**Comment by dimisa-RUAdList** [comment]
Вроде так нормально: https://github.com/easylist/ruadlist/commit/4c220ff218555c7177143873ac5b0a97df417f27

**Comment by dimisa-RUAdList** [comment]
Путь оказался всё-таки рандомный. Переделал на стили: https://github.com/easylist/ruadlist/commit/f002d899673c3a6ec486654adb5820fb9e86f7db

**Comment by dportvine** [comment]
Убрали `style`.

<details>
<summary>Screenshot(s)</summary>

![2023-12-21_122946](https://github.com/easylist/ruadlist/assets/111344219/8c7172e2-afc3-46db-abaa-a697d3dd53e1)
</details>

**Comment by dimisa-RUAdList** [comment]
Ок, посмотрим сколько проживёт такой вариант макета: https://github.com/easylist/ruadlist/commit/57c19f2eb2615f32d63dcd69bfc34ea7e7af1bac

**Comment by dportvine** [comment]
Походу обиделись.

**Comment by dportvine** [comment]
`https://4pda.to/page/1/`

<details>
<summary>Screenshot(s)</summary>

![2023-12-21_145547](https://github.com/easylist/ruadlist/assets/111344219/c8e517d2-dfa2-4c31-9d9a-428b6e09d257)
</details>

**Comment by dimisa-RUAdList** [comment]
Переделал: https://github.com/easylist/ruadlist/commit/9694ae610a607fe6491d2630b899447b109c177d

Вероятно, кто-то из веб-мастеров использует uBO с фильтром Counters. Судя по поломанным исходным макетом кнопкам назад-вперёд над комментариями в брендированных материалах, это ещё не финиш.

**Comment by dportvine** [comment]
Все очень плохо.

<details>
<summary>Screenshot(s)</summary>

![2023-12-21_174601](https://github.com/easylist/ruadlist/assets/111344219/cbd2b71f-06ae-41b0-b8dd-93f14a9e1d49)
![2023-12-21_174611](https://github.com/easylist/ruadlist/assets/111344219/6b36cd9f-89e2-4bee-9acd-b5b30f91516d)
</details>

**Comment by dimisa-RUAdList** [comment]
А если обновиться вручную (часы +шифт)?

**Comment by dportvine** [comment]
Да, да. Я понял. Все работает.

**Comment by dportvine** [comment]
Целенаправленно обходят правила.

**Comment by dimisa-RUAdList** [comment]
Они слишком долго находились в зоне комфорта и правила для блокировки отсутствовали в основных фильтрах. Полагаю, нужно вернуть их туда, с ежедневным контролем, и содержать до тех пор, пока не прекратится обход экзотических решений, коим является любой опциональный фильтр, в том числе и Counters для uBlock Origin.

https://github.com/easylist/ruadlist/commit/16ddb08379f6dd3f5d2c46795f0e1b6d8f3158f8

**Comment by dportvine** [comment]
Все ссылки и баннеры, ведущие на сторонние сайты, являются рекламными и должны быть заблокированы в **RU AdList**.
В противном случае, терятся смысл самой блокировки рекламы.

**Comment by dimisa-RUAdList** [comment]
Возможно, они ещё просто не поняли, что препятствуя малому, рускуют потерять большее. Написал им письмо, чтобы убедиться, что это не недоразумение.

**Comment by dimisa-RUAdList** [comment]
Закрывая, в связи с решением проблемы обхода.
