### ISSUE TITLE
[NSFW] https://sslkn.art/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/ruadlist#57]
Popunders at https://sslkn.art/

Screenshot: 
<img width="1026" alt="Screenshot 2022-04-22 at 12 25 51" src="https://user-images.githubusercontent.com/65717387/164692548-c96ceb65-f999-4f94-8cc1-e0a9cc87ae2b.png">

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/856d0d3c7528daedd2328f88fd230fc9f414d395
