### ISSUE TITLE
o2.pl

### ISSUE THREAD

**Issue by P-o-R-t-v-i-n-e** [easylist/ruadlist#58]
`https://www.o2.pl/`

Правило ломает сайт
`/^https?:\/\/[^/]+\/[a-z0-9]{15,}(\?hope=.*)?$/$script,domain=~coco.fr|~greenmangaming.com|~ign.com|~justjared.com|~live-tennis.eu|~myorderbox.com|~namemc.com|~novinky.cz|~onet.pl|~realtor.ca|~regway.com|~roblox.com|~sap.com|~spongemc.org|~spongepowered.org|~studio-svet.ru|~stumbleupon.com|~trueachievements.com|~tv.yandex.by|~tv.yandex.kz|~tv.yandex.ru|~wetteronline.de|~wp.pl`

<details>
<summary>скрин</summary>

![2022-04-23_183737](https://user-images.githubusercontent.com/104250631/164913026-8142d519-ceb0-45e2-9416-0169299b09c2.png)
![2022-04-23_182503](https://user-images.githubusercontent.com/104250631/164913031-22c593a3-e57d-4223-aa05-d42d2769f0e6.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/85e261bca05fed8371b607f9beab3ad7ae237198
