### ISSUE TITLE
https://sandra-nika.livejournal.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/ruadlist#59]
Top banner at https://sandra-nika.livejournal.com/
<img width="1275" alt="Screenshot 2022-05-06 at 10 45 06" src="https://user-images.githubusercontent.com/65717387/167098597-dccdf4e1-6f88-4cf4-8818-5790ba2795ee.png">

**Comment by dimisa-RUAdList** [comment]
This site belongs to the problematic category.
Solution here: https://greasyfork.org/en/scripts/19993-ru-adlist-js-fixes
