### ISSUE TITLE
Некорректная блокировка ссылок на StopGame.ru

### ISSUE THREAD

**Issue by dotterian** [easylist/ruadlist#61]
Привет.
Я — разработчик stopgame.ru
Вижу в фильтрах строчку `stopgame.ru##a[href^="/to?http"]`.
Это URL страницы с уведомлением о переходе с сайта по внешней ссылке. Автоматически подставляется ко **всем внешним ссылкам** на сайте (за исключением небольшого разрешённого списка). Сама страница выглядит так:
![Screenshot from 2022-06-16 14-06-41](https://user-images.githubusercontent.com/6250486/174058254-1b249f1d-41c2-48b8-8dee-e9e7c2e3f063.png)

Рекламы на этой странице нет, но она, в теории, может вести на рекламные и фишинговые сайты и нужна как раз для того, чтобы предотвратить бездумный переход на подобные ресурсы.

Фильтр в итоге удаляет абсолютно безобидные ссылки из текста новостей и статей на сайте, ломая пользовательский опыт, логику и мозг читающего.

Пример:
![Screenshot from 2022-06-16 14-15-18](https://user-images.githubusercontent.com/6250486/174060463-ca18d7bc-1d6d-46b8-8f6c-2f064725a27f.png)

**Comment by dimisa-RUAdList** [comment]
Вы не указываете ссылку на страницу, где наблюдается проблема, поэтому проверку провести затруднительно. Судя по всему, вы не делаете разницы между внешними ссылками, будь то рекламные или информационные. Жалоба на рекламные ссылки (тинькофф и пр) была заявлена [вчера](https://forums.lanik.us/viewtopic.php?p=164376-stopgame-ru#p164376).

В правило [внесены изменения](https://github.com/easylist/ruadlist/commit/8aa36b2ba1ef846c92ec1bef6df9363f94f23e6e), с целью изоляции.

**Comment by dotterian** [comment]
> Вы не указываете ссылку на страницу, где наблюдается проблема

Как и написал в первом сообщении: проблема проявляется во **всех** материалах на сайте, содержащих внешние ссылки.
Примеры:
https://stopgame.ru/newsdata/53770
https://stopgame.ru/game/witcher_3_wild_hunt (смотреть в графы «Разработчик» и «Издатель» в шапке с информацией об игре)

> Судя по всему, вы не делаете разницы между внешними ссылками, будь то рекламные или информационные.

Не делаем. Текст на сайт пишет огромное количество человек через WYSIWYG-редактор. Как-то автоматически разделять рекламу и обычную ссылку с точки зрения кода — нереально. Также нереально заставить всех, публикующих на сайте, проставлять какую-то особенную ссылку, вместо обычной, в случае рекламы.
К тому же, есть блоги пользователей, где пользователи могут запостить рекламную ссылку и мы вообще никак не сможем это проконтроллировать.

> Жалоба на рекламные ссылки (тинькофф и пр) была заявлена [вчера](https://forums.lanik.us/viewtopic.php?p=164376-stopgame-ru#p164376).

Видел. Не очень понимаю, почему мешает **одна ссылка** в тексте материала и зачем её удалять.

Блокировка рекламы была придумана, чтобы удалять назойливые баннеры. И тут я полностью согласен: это имеет смысл. Они большие, они мешают, они, в конце-концов, не релевантны абсолютно и не имеют никакого отношения к материалу. Но тут уже, кажется, случай, когда вырезание рекламы превращается в религию. Описание под роликом полностью дублирует описание к ролику в YouTube, из которого, абсолютно уверен, никакие ссылки не режутся. Так почему к StopGame подход отличный от YouTube?

> В правило [внесены изменения](https://github.com/easylist/ruadlist/commit/8aa36b2ba1ef846c92ec1bef6df9363f94f23e6e), с целью изоляции.

Да, и это я тоже видел. Все остальные строчки, кроме указанной мной в первом репорте, меня не беспокоят и работают корректно.

**Comment by dimisa-RUAdList** [comment]
Ссылка на страницу с проблемой должна быть всегда, даже если проблема наблюдается на всех страницах. Это явным образом прописано в [правилах оф.форума RU AdList](https://forums.lanik.us/viewtopic.php?t=24280), в [теме поддержки RU AdList на руборде](https://forum.ru-board.com/topic.cgi?forum=5&topic=50761&start=0&limit=1&m=6#1), на [баг-трекере uBO](https://github.com/uBlockOrigin/uAssets/issues/new?assignees=&labels=&template=bug_report.yml) и т.д. На гитхабе у RU AdList фидбек микроскопический, поэтому я не стал добавлять это требование. Однако в будущем указывайте пожалуйста ссылки, к тому же в вашем случае, внешние ссылки имеются далеко не везде. 

Блокировка рекламы осуществляется не только для того, чтобы удалять назойливые баннеры. Подлежащее блокировке описано в [EasyList policy](https://easylist.to/pages/policy.html), на что в основном и ориентируются авторы фильтров. И нет никакой разницы, идет ли речь о баннере, снабжённом рекламной ссылкой, или рекламной ссылкой как таковой, в т.ч. в виде текста.

**Comment by dotterian** [comment]
Так же в той же policy описано:

> Consistently problematic filters should be removed from the subscription.

Этот фильтр очевидно "consistently problematic" и менее проблематичным в будущем не станет, даже если я на стороне сайта предприму какие-то меры по разграничению рекламных ссылок и обычных. Блокировать ссылки внутри контентного блока, заполняемого пользователями — плохая идея, как ни крути.

**Comment by triviumx** [comment]
> и менее проблематичным в будущем не станет

Ну и в чем проблематичность-то?  В том, что главный редактор себе не купит еще одну квартиру на Арбате? Как всякий скам рекламить и на стримах цензурить кадры из Сталкера где показывают войну в Украине под смех, так проблем нет, а как рекламу убрали ой памагите это же проблема, так нечестно.

**Comment by dotterian** [comment]
> а как рекламу убрали ой памагите это же проблема, так нечестно.

Рекомендую перечитать всю ветку внимательно ещё раз: убрали не только рекламу, но и все внешние ссылки во всех статьях, новостях, блогах и даже на страницах игр на всём сайте.
(Уже исправлено, но не до конца — теперь удаляются все внешние ссылки внутри жирного текста).

Всё остальное описанное вами не имеет отношения ни ко мне, ни к этому репорту, направляйте свои жалобы главреду, если вас не устраивает его работа и заработок (о котором вы ничего не знаете, равно как и о количестве работ, на которых он работает).

**Comment by dotterian** [comment]
Дополню: против хорошо работающих фильтров, уюирающих **только** рекламу я не имею ничего: право каждого, видеть интернет без рекламы.

Но когда фильтр буквально ломает сайт, это не корректно и такой фильтр должен быть либо исправлен, если это возможно, либо удалён.

**Comment by electrifying** [comment]
> о котором вы ничего не знаете, равно как и о количестве работ, на которых он работает

Ну ошибся, чел он же не знал что твой начальник такие деньги со скам рекламы отмывает, что смог переехать аж в Южную Корею. Очень бедный,чел очень. Мы поняли, добавь ещё 70 рекламных ссылок на сайт, а то чел последний хлеб доедает, на квартиру около белого дома не хватает(((

**Comment by dotterian** [comment]
Не считаю issue блоклиста подходящим местом для подобных дискуссий. Данный тикет был создан потому, что конкретный фильтр ломает сайт и блокирует то, что не должен блокировать. (И продолжает это делать, на что я указал в комментарии к «исправляющему» коммиту).

Холивары на тему «насколько уместно размещать рекламу и кто на ней сколько заработал», предлагаю перенести в любое другое место.

**Comment by dimisa-RUAdList** [comment]
@dotterian 
Единственные ссылки, которые вы указали, это:

`https://stopgame.ru/newsdata/53770`
`https://stopgame.ru/game/witcher_3_wild_hunt`

Никаких фактов, что блокировщик продолжает что-то ломать, вы не привели.

**Comment by dotterian** [comment]
Претензия снимается.
Коммит https://github.com/easylist/ruadlist/commit/f883570c0dd73dd68e80d8a1d3065aa2cd655a97 всё исправил (но я увидел его только сейчас).

**Comment by dimisa-RUAdList** [comment]
@dotterian 
https://github.com/easylist/ruadlist/issues/100
> Привет, это снова разработчик StopGame.ru и снова недоволен тем, как работает блокировщик:
> 
> Вот этот фильтр убирает в том числе и абсолютно корректные списки, не содержащие рекламных ссылок:
> 
> ```
> stopgame.ru#?#section > div[class^="_content-wrapper_"]:-abp-has(> div > a[href^="/watch"]) ~ div[class^="_content"] [class^="_list_"]
> ```
> 
> Убедиться можно на этих страницах: https://stopgame.ru/show/131336/cistemki_the_callisto_protocol_paket_yarovoy_dlya_igr_uhod_ea_iz_rossii_kitaycy_perestali_igrat https://stopgame.ru/show/131355/ischem_horoshie_igry
> 
> Я бы, как минимум, добавил к нему проверку на то, что `href` начинается с `/to?` (эта часть автоматически подставляется ко всем внешним ссылкам в тексте) и резал не весь список, а конкретные `li`, содержащие эти ссылки. Не очень знаком с синтаксисом селекторов блоклиста, но, судя по всему, такая техническая возможность есть.
> 
> _(Во избежание оффтопика в комментариях: я не бунтую против блокировки рекламы на сайте, я не доволен тем, что фильтр режет не только рекламу. Пожалуйста, оставьте обсуждение того, кто, чем и сколько зарабатывает за пределами комментариев этого ишью)_

Переделал: https://github.com/easylist/ruadlist/commit/d66a74afa5354599282db423e0924ca534cd38aa

**Comment by dotterian** [comment]
В `cntblock.txt` есть правило, блокирующее все изображения с `counter` в названии.
В итоге, например, на странице https://stopgame.ru/game/counter_strike_source блокируются обложка игры и изображение в шапке.

Без блокировки счётчиков:
![Screenshot from 2022-12-21 05-32-46](https://user-images.githubusercontent.com/6250486/208806905-90574c6b-c089-46fb-b687-2c23d2240091.png)

С блокировкой счётчиков:
![Screenshot from 2022-12-21 05-33-07](https://user-images.githubusercontent.com/6250486/208806969-099da382-1aae-4b8f-9f81-017e29f268fc.png)

Во встроенном блокировщике Opera блокировка счётчиков включена в стандартную поставку RuAdlist, что создаёт проблемы для пользователей.

**Comment by dimisa-RUAdList** [comment]
Ок, исправлено: https://github.com/easylist/ruadlist/commit/20e6df1230ceef0612afda1fe3567ceabc691ba2

**Comment by dotterian** [comment]
Ложное срабатывание на странице https://stopgame.ru/newsdata/55143/v_metal_hellsinger_dlya_pk_teper_mozhno_postavit_svoyu_muzyku

Из текста удаляется список.

**Comment by dimisa-RUAdList** [comment]
Поправил: https://github.com/easylist/ruadlist/commit/355ea5dd1af3047b4965c9bd2a27623b0554cbca

**Comment by dotterian** [comment]
Продублирую:
https://stopgame.ru/newsdata/58024/tizer_trailer_seriala_po_twisted_metal

При попытке открыть страницу с включенным RuAdList в списке блоклистов страница **не загружается**.
(Выводит «StopGame не работает без интернета!» если пользователя заходил на сайт ранее и закэшировал ServiceWorker)
Если отключить RuAdList в списке блоклистов — страница открывается.

Страница блокироваться не должна, ничего криминального на ней нет.

**Comment by dimisa-RUAdList** [comment]
В этой конфигурации при проверке всё работает нормально. Может, нужно выполнить какие-то дополнительные условия? Опишите пожалуйста шаги, приводящие к проблеме.

**Comment by dimisa-RUAdList** [comment]
Поймал, поправил. Оказалось, проблема в блокировке аякса по популярной маске `/tizer_`.
