### ISSUE TITLE
yandex.ru/yandsearch (все проблемы яндекс-поиска обсуждаются здесь)

### ISSUE THREAD

**Issue by fromanywhere** [easylist/ruadlist#62]
Добрый день.
Firefox 102 + uBlock Origin 1.43.0 + RU AdList: Counters вырезает нерекламный сниппет на выдаче

Запрос:
`https://www.yandex.ru/yandsearch?text=%D1%81%D0%B1%D0%B5%D1%80%D0%B1%D0%B0%D0%BD%D0%BA&lr=213`

Правило:
yandex.*#?#.serp-list > .serp-item:-abp-has(> .bno)

<details>
<summary>Screenshot(s)</summary>

![s](https://user-images.githubusercontent.com/1042969/178561238-d674be64-f591-4636-8af2-174aec287478.png)

</details>

**Comment by dimisa-RUAdList** [comment]
Это нормально. Фильтр Counters блокирует не только рекламный контент. Это опциональный фильтр, в котором много экспериментального. И далеко не всё, что он режет, относится к рекламе.

Тем не менее, скрытие данного блока не входило в идею этого правила. Поправил, спасибо за ваше сообщение.

**Comment by ilyhryh** [comment]
зачем вырезать все галереи в топе выдачи? (например, [фильмы](https://yandex.ru/search/?text=%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D1%8B&lr=213), [книги](https://yandex.ru/search/?text=%D0%BA%D0%BD%D0%B8%D0%B3%D0%B8&lr=213), [список чудес света](https://yandex.ru/search/?text=%D1%81%D0%BF%D0%B8%D1%81%D0%BE%D0%BA+%D1%87%D1%83%D0%B4%D0%B5%D1%81+%D1%81%D0%B2%D0%B5%D1%82%D0%B0&lr=213), [пингвин из DC](https://yandex.ru/search/?text=%D0%9F%D0%B8%D0%BD%D0%B3%D0%B2%D0%B8%D0%BD+(DC+Comics)&lr=213&noreask=1&ento=0oCgpydXcxOTc4ODA2EhJydXcyODEwMTU6Y3VzdG9tOjAYAnoo0KHQv9C40YHQvtC6INCy0YDQsNCz0L7QsiDQkdGN0YLQvNC10L3QsDe8YLA))

https://hg.adblockplus.org/ruadlist/rev/0f7cad5c44e0

```
+yandex.by,yandex.kz,yandex.ru,yandex.uz##.serp.main__carousel
```

понятно, что `annoyance_specific_hide.txt`, но субъективно же, а не объективно

к вырезанию рекламной галереи в топе ([купить окна](https://yandex.ru/search/?text=%D0%BA%D1%83%D0%BF%D0%B8%D1%82%D1%8C+%D0%BE%D0%BA%D0%BD%D0%B0&lr=213)) вопросов нет ;)
