### ISSUE TITLE
shop.purina.ru, shop.tikkurila.ru

### ISSUE THREAD

**Issue by tanairran** [easylist/ruadlist#63]
Доброго времени суток!

Обнаружили, что uBlock с RuAdlist блокирует загрузку скриптов на некоторых наших проектах (например: shop.purina.ru, shop.tikkurila.ru)
Связано это с правилом загрузки сторонних скриптов из доменной зоны .pw 
`||pw^$third-party,script,xmlhttprequest,domain`

В DNS записях наших доменов часто используется тип записи CNAME, который указывает на один из наших серверов разработки в доменной зоне *.aristos.pw

Прошу добавить в исключения сам домен aristos.pw и маску для его поддоменов *.aristos.pw

Заранее спасибо!

**Comment by dimisa-RUAdList** [comment]
Это происходит только в браузере Firefox.

Исправлено: https://github.com/easylist/ruadlist/commit/abef8246ca35c094d2146879e1be3a582f97fe8b
