### ISSUE TITLE
avito.ru

### ISSUE THREAD

**Issue by darkalor** [easylist/ruadlist#65]
Firefox 103.0. uBlock Origin 1.43.0. 
<details>
<summary>Скриншоты</summary>

![image](https://user-images.githubusercontent.com/2834813/181879322-ed7da5a2-4e9a-4744-a12b-29a4932fa0d9.png)

![image](https://user-images.githubusercontent.com/2834813/181879535-28e7465b-ee78-496f-8b8a-3b643812c539.png)

![image](https://user-images.githubusercontent.com/2834813/181879284-5f1e7841-52c1-405b-8974-b39623ddf3f5.png)
</details>

https://www.avito.ru/krasnodar/doma_dachi_kottedzhi/dom_100_m_na_uchastke_6_sot._2510213506

**Comment by dimisa-RUAdList** [comment]
Проблема повторяется только в Firefox и только при использовании uBlock Origin.

Исправлено: https://github.com/easylist/ruadlist/commit/edf0a70324c4f944f46b07492b37094a53fe3e27

Изменения вступили в силу доступны при [обновлении фильтров вручную](https://forums.lanik.us/viewtopic.php?f=102&t=22786). Автоматом они раскатаются в течении 48 часов.
