### ISSUE TITLE
games-pc.top

### ISSUE THREAD

**Issue by PhoenixIndigo** [easylist/ruadlist#66]
1. <comment> [RUS: RU AdList](moz-extension://7d4c3759-8669-45bb-b7f8-250eb5401a14/asset-viewer.html?url=RUS-0) блокирует открытие скрытых спойлеров на всём [форуме](https://rustorka17221108.games-pc.top/forum/viewtopic.php?t=279007) правилом **$script,3p,domain=games-pc.top** без исключения **@@||naylo.top^$script,domain=rustorka17221108.games-pc.top** : `https://rustorka17221108.games-pc.top/forum/viewtopic.php?t=279007`

2. А на [главной](https://rustorka17221108.games-pc.top/forum/index.php) [RUS: RU AdList](moz-extension://7d4c3759-8669-45bb-b7f8-250eb5401a14/asset-viewer.html?url=RUS-0)  блокирует мини-чат правилом ***$xmlhttprequest,3p,domain=games-pc.top** без исключения **@@||naylo.top^$xhr,domain=rustorka17221108.games-pc.top** : `https://rustorka17221108.games-pc.top/forum/index.php`

3. Screenshots

<details><summary>Screenshot 1:</summary>

![изображение](https://user-images.githubusercontent.com/107413021/184241999-99d4763e-3331-446b-ba33-2a5d03d4c609.png)

</details>

<details><summary>Screenshot 2:</summary>

![изображение](https://user-images.githubusercontent.com/107413021/184243663-8499db92-3c37-4d04-8fcb-03ddd105cd98.png)

</details>

4. Info:

<details><summary>Info:</summary>

```
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 156013
  cosmetic: 247924
  scriptlet: 39647
  html: 749
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 31211-66, 16m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1502-0, never
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 30373-238, 14m
    https://secure.fanboy.co.nz/enhancedstats.txt: 2996-11, 15m
    https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 89591-32836, 15m
    https://shorturl.at/cfqKV: 12-0, 15m
    adguard-generic: 66803-5633, 16m
    adguard-mobile: 8085-153, 16m
    adguard-spyware: 26774-1294, 16m
    adguard-annoyance: 55878-4895, 16m
    ublock-annoyances: 4530-8, 16m
  default: 
    user-filters: 1-0, never
    ublock-filters: 33099-116, 16m
    ublock-badware: 4211-0, 16m
    ublock-privacy: 247-0, 16m
    ublock-abuse: 76-0, 16m
    ublock-unbreak: 1868-9, 16m
    ublock-quick-fixes: 378-1, 16m
    easylist: 69331-958, 16m
    easyprivacy: 27324-10014, 16m
    urlhaus-1: 4761-0, 16m
    plowe-0: 3634-10, 16m
    RUS-0: 42011-3883, 14m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1334 ms (selfie)
  maxAssetCacheWait: 2015 ms
```
</details>

**Comment by dimisa-RUAdList** [comment]
Указанные правила тут не причём. Проблема повторяется только в сочетании uBlock Origin + Firefox, из-за специфической для этой конфигурации блокировки cname.

Исправлено: https://github.com/easylist/ruadlist/commit/38d51c3647f26030768bb5d11f8c6bb3ef23c69f
