### ISSUE TITLE
limehd.tv

### ISSUE THREAD

**Issue by PhoenixIndigo** [easylist/ruadlist#69]
1. <comment> `https://limehd.tv/channel/super` Требует отключить блокировщик и не работает онлайн трансляция

2. Screenshots
<details><summary>Screenshot 1:</summary>

![изображение](https://user-images.githubusercontent.com/107413021/184676651-c04a1862-3a94-43b4-8e24-c81da3a85303.png)

</details>

<details><summary>Configs:</summary>

`https://pastebin.com/u/GodIndigo`

</details>

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/2f00ca72a63aafd4a20a3903836bdd05337b3b32
