### ISSUE TITLE
trialeset.net trialnod.net trialnod.club

### ISSUE THREAD

**Issue by bogachenko** [easylist/ruadlist#7]
`trialeset.net,trialnod.*##.remodal-is-opened.remodal-wrapper, .remodal-is-opened.remodal-overlay`
`trialeset.net,trialnod.*##html:style(overflow-y: scroll !important;)`

Модальное окно после копирования ключа.

**Comment by dimisa-RUAdList** [comment]
Честно говоря, не уверен, что данное модельное окно следует фиксить. Даже в раздражителях. Фидбек позволяет раздающим ключи (бесплатно!) сервисам оперативно реагировать и актуализироваться. Пока добавил, понаблюдаю.

https://github.com/easylist/ruadlist/commit/efe5b5859f7a23b77c80d9d85dd5ac6084a4fd7d
https://github.com/easylist/ruadlist/commit/5115c6fac35be8dea4fef9bcd5838dbb0922bb58

`trialnod.net` - не работает

**Comment by bogachenko** [comment]
https://8fornod.net/

**Comment by bogachenko** [comment]
`https://8fornod.net/`

**Comment by dimisa-RUAdList** [comment]
Ок: https://github.com/easylist/ruadlist/commit/2d4bb89b721d56d42f81b6180f9976ce04e302ab

`http://w98008mo.beget.tech/` - трогать не стал, ибо не выглядит долговременным, да и рекламы там нет. В общем, засорять фильтры столь сомнительными правилами для потенциально одноразовых доменов - не хотелось бы.

**Comment by bogachenko** [comment]
`trialnod.net` мертв.
`trialeset.net` мертв.

>http://w98008mo.beget.tech/ - трогать не стал, ибо не выглядит долговременным, да и рекламы там нет. В общем, засорять фильтры столь сомнительными правилами для потенциально одноразовых доменов - не хотелось бы.

живее всех живых.

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/441eec5aee313702c0f7ce6f884001d5ed91aba6
https://github.com/easylist/ruadlist/commit/9b42c24f80c05109a24441fc5ec1f14f33c377f9

**Comment by bogachenko** [comment]
`https://noddb.ru` тут тоже

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/e3c57fce35708b32cc133b71cf85a49c31bc47e4
