### ISSUE TITLE
yandex.ru/search: .main__carousel

### ISSUE THREAD

**Issue by ilyhryh** [easylist/ruadlist#70]
добрый день

правки https://hg.adblockplus.org/ruadlist/rev/75c17e89b36f, а именно правило:

```yandex.by,yandex.kz,yandex.ru,yandex.uz##.serp.main__carousel```

режут нерекламные галереи ([фильмы](https://yandex.ru/search/?text=%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D1%8B&lr=213), [книги](https://yandex.ru/search/?text=%D0%BA%D0%BD%D0%B8%D0%B3%D0%B8&lr=213), [достопримечательности](https://yandex.ru/search/?text=%D0%B4%D0%BE%D1%81%D1%82%D0%BE%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%87%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D0%B8+%D0%BC%D0%BE%D1%81%D0%BA%D0%B2%D1%8B&lr=213), [личности](https://yandex.ru/search/?text=%D0%BF%D1%80%D0%B5%D0%B7%D0%B8%D0%B4%D0%B5%D0%BD%D1%82%D1%8B+%D1%81%D1%88%D0%B0&lr=213))

уберите, пожалуйста.

**Comment by dimisa-RUAdList** [comment]
Данное правило добавлено в фильтр BitBlock, который нацелен на блокировку не рекламы, а анонсов и разных раздражителей. Поэтому такое правило для этого фильтра - норма. Однако те примеры, которые вы привели, указывают на то, что правило работает не так, как задумано. Исправлено.
