### ISSUE TITLE
github.com

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [easylist/ruadlist#71]
https://github.com/joeyballentine/chaiNNer
https://raw.githubusercontent.com/joeyballentine/chaiNNer/main/src/public/banner.png
`/banner.png$third-party`
https://github.com/joeyballentine/chaiNNer/issues/792

Сделайте хотя бы исключение для гитхаба для всех таких глобальных фильтров.

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/60efd616a549b4988a70ca745d6ecc87204b48d9

**Comment by 0x4E69676874466F78** [comment]
Спасибо!
