### ISSUE TITLE
sportmaster.ru

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#711]
`https://www.sportmaster.ru`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/user-attachments/assets/0d300fd5-70f9-4141-80f8-c150fb850ae6)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/9dbd5f2a7d4ea19987edf1b55f92ebd14a413734
