### ISSUE TITLE
asna.ru

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#712]
`https://asna.ru`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/user-attachments/assets/ec986dc5-a2f2-49e9-8133-ca54e793f94b)

</details>

<details>

> uBlock Origin: 1.60.0
> Firefox: 132
> filterset (summary):
>  network: 25017
>  cosmetic: 89416
>  scriptlet: 10043
>  html: 300
> listset (total-discarded, last-updated):
>  removed:
>   ublock-filters: null
>   ublock-badware: null
>   ublock-privacy: null
>   ublock-unbreak: null
>   ublock-quick-fixes: null
>   easylist: null
>   easyprivacy: null
>   urlhaus-1: null
>   plowe-0: null
>  added:
>   https://easylist-downloads.adblockplus.org/bitblock.txt: 24244-22, 3h.11m
>   https://easylist-downloads.adblockplus.org/cntblock.txt: 1756-21, 2h.11m
>   fanboy-cookiemonster: 69087-17038, 4d.1h.54m
>   ublock-annoyances: 5928-58, 3h.11m Δ
>  default:
>   user-filters: 0-0, never
>   RUS-0: 41043-135, 11m Δ
> filterset (user): [empty]
> trustedset:
>  removed:
>   chrome-extension-scheme
> switchRuleset:
>  removed:
>   no-csp-reports: * true
> userSettings:
>  advancedUserEnabled: true
>  contextMenuEnabled: false
>  showIconBadge: false
> hiddenSettings:
>  userResourcesLocation: [redacted]
> supportStats:
>  allReadyAfter: 5806 ms (selfie)
>  maxAssetCacheWait: 1984 ms
>  cacheBackend: indexedDB

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/483281669e7b27299511e874fe311f8f37c2c8ec
