### ISSUE TITLE
4pda.to

### ISSUE THREAD

**Issue by Fluboxer** [easylist/ruadlist#713]
#### Описание проблемы (Description of the problem):

`4pda.to`
Реклама не гасится, более того, вырубить её встроенным пикером невозможно. Фильтры последней версии

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/user-attachments/assets/74dd3b64-1585-4f86-af75-d791c0df005e)

</details>

#### Конфигурация (Configuration):

- OS/version: Windows 10 22H2
- Browser/version: Waterfox G6.0.14
- Ad block extension/version: uBlock Origin 1.60.0

#### Используемые фильтры (Used filters):
<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/user-attachments/assets/6be2d2f9-70ff-4d67-83d6-90eb4ba878f3)
![изображение](https://github.com/user-attachments/assets/de883777-69f1-4512-9fcf-86c6ac626cfc)

</details>

**Comment by dimisa-RUAdList** [comment]
Судя по скрину, вы подключили ВСЕ фильтры одновременно. С вероятностью 99,9999% работа блокировщика будет поломана из-за многочисленных конфликтов фильтров, которые никогда не тестировались на предмет совместной работы и такое тестирование не планируется в будущем. Так делать нельзя.

Откройте  в панели управления uBlock Origin вкладку "Настройки" и кликните по кнопке "Восстановить настройки по умолчанию". После этого подключите фильтр RU AdList: Counters:  https://github.com/easylist/ruadlist/wiki/RU-Adlist-links

Либо же используйте готовый файл конфигурации (рекомендуемый для рунета) из последнего абзаца RU Adlist links.

**Comment by Fluboxer** [comment]
Отключение фильтров путём сброса настроек не помогло, однако установка Counters всё решила. Спасибо!
