### ISSUE TITLE
lkk.mosoblgaz.ru

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#714]
`https://lkk.mosoblgaz.ru`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/user-attachments/assets/c7c31df6-f945-4e49-aa0c-f61ffa5a4087)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/fdd610751911158d71b51898473d4f3d07d17e69
