### ISSUE TITLE
joyreactor.cc

### ISSUE THREAD

**Issue by k0ka** [easylist/ruadlist#715]
Чем вам помешал autoplay в видеогифках? Все видогифки без звука. Кому надо - могут зарегистрироваться и включить галку "гифки по клику'. 
А сейчас - половина работает, половина - не работает. 

https://github.com/easylist/ruadlist/commit/a127944db7edf5d644c9b45343b0e399a2766cba

`https://joyreactor.cc/post/5959487`

**Comment by k0ka** [comment]
Ну так же надо убрать 
`joyreactor.cc,reactor.cc##+js(set-attr, video, controls, true)`

все "видео" на реакторе - это переконверченные гифки. При этом система сама может решить - имеет ли смысл конвертить их или нет. Поэтому для пользователей они должны выглядеть как гиф-анимация. 

Ты можешь открыть https://joyreactor.cc/tag/%D0%BF%D0%BE%D1%85%D1%83%D0%B9%20%D0%BF%D0%BB%D1%8F%D1%88%D0%B5%D0%BC комментарии к какому-нибудь посту и увидеть по сути одинаковые мелкие анимации, часть их которых отоброжена как гиф-анимация, а часть - как mp4/webm-видео.

**Comment by dimisa-RUAdList** [comment]
Нет, это правило убрано не будет. Без него исчезает возможность перематывать и ставить на паузу длинные видео, вроде таких: `https://joyreactor.cc/post/5960269`

**Comment by k0ka** [comment]
Если сильно нужно, то это можно сделать нажав правой кнопкой мышки на видео и нажав "show controls". Гифки не предполагают что их можно останавливать и проматывать. 

Но я понимаю, что ты лучше разбираешься что пользователям надо. Если не против, то всем жалующимся я буду давать ссылку на этот тикет.

**Comment by dimisa-RUAdList** [comment]
Сомневаюсь, что появляющиеся при наведении курсора элементы управления могут стать причиной хоть какого-то недовольства. А на длинных роликах скрытие управления это априори антипользовательское решение.

Тем не менее я допускаю, что в определённых случаях могут возникнуть какие-то баги, так что конечно же вы можете давать ссылку на этот issue.

Каждое сообщение, содержащее информацию о проблеме и способе её воспроизведения будет обработано. Сообщения оскорбительного характера будут удалены. 

На этом issue закрывается, с возможностью продолжения комментирования.
