### ISSUE TITLE
Gesturefy

### ISSUE THREAD

**Issue by Trixlight** [easylist/ruadlist#716]
#### Описание проблемы (Description of the problem):
Line 22965 in the RU AdList filter breaks the functionality of the Gesturefy extension.
See https://github.com/Robbendebiene/Gesturefy/issues/731#issue-2648764490

`https://dzen.ru/`

<details>
<summary>Screenshot(s)</summary>

![385057437-66d18f54-2059-4ec8-8187-e8e690b96859](https://github.com/user-attachments/assets/26ea5a20-f6e9-436d-8549-89bbe5fd8405)

</details>

#### Конфигурация (Configuration):

- OS/version: Windows 11 23H2 (22631.4169)
- Browser/version: Firefox 128.3.1esr
- Ad block extension/version: uBlock Origin 1.60.0

#### Используемые фильтры (Used filters):

RU AdList

**Comment by dimisa-RUAdList** [comment]
Вы не пишите прямо, но подразумеваете, что проблема должны быть решена на стороне RU AdList. Ок, давайте разберём данный случай.

Фильтр RU AdList используется по-умолчанию во встроенных блокировщиках Brave, Opera, Vivaldi, расширениях для блокировки Adblock Plus, AdBlock, uBlock Origin, и т.д, на круг это несколько десятков миллионов пользователей. Для домена дзен, появившегося в 22г, правила в фильтре менялись уже более [240 раз](https://github.com/search?q=repo%3Aeasylist%2Fruadlist+%3A%2F%2Fdzen.ru%2F&type=commits), то есть их приходится постоянно адаптировать, а также содержать те из них, которые превентивно предотвращают некоторые виды встраивания рекламы. Правило, которое вы приводите, как раз из таких. Оно применялось и применяется для разных доменов уже более 8 лет и обладает доказанной эффективностью.

Gesturefy имеет менее 100.000 пользователей и находится в тепличных условиях. Никто не противодействует его функциям, позволяя развиваться и совершенствоваться без помех.

Stylus, как и все аналогичные менеджеры, можно не брать в расчёт, поскольку внедряя стиль для целевого элемента, они не создают у него атрибута `style`, соответственно под действие правила блокировки попасть не могут. 

С учётом этого контекста предложение решить проблему на стороне RU AdList выглядит несколько неоднозначно.

**Comment by dimisa-RUAdList** [comment]
Закрываю, в связи закрытием issue на стороне Gesturefy.
