### ISSUE TITLE
pikabu.ru

### ISSUE THREAD

**Issue by 4815162342lost** [easylist/ruadlist#717]
#### Описание проблемы (Description of the problem):

Нужно открыть несколько любых тем из "лучшего": `https://pikabu.ru/best`
Иногда (не всегда) комментарии к теме перестают отображаться, не всегда, ошибка плавающая. Откройте несколько тем и начните читать комментарии, пролистывая вниз. На некоторых страницах они перестают грузиться. Если отключить блокировщик рекламы, то всё нормально. Проблема возникает только в мобильном браузере. На ПК такой проблемы нет.

<details>
<summary>Screenshot(s)</summary>

![photo_2024-11-16_20-13-55](https://github.com/user-attachments/assets/437f3379-2e8f-4e7e-82c9-3e0b71c49b7d)

</details>

#### Конфигурация (Configuration):

- OS/version: Android 12
- Browser/version: Firefox  mobile 132.0.2
- Ad block extension/version: Ublock Orign 1.61.0

#### Используемые фильтры (Used filters):
<details>
<summary>Screenshot(s)</summary>

![photo_2024-11-17_00-21-48](https://github.com/user-attachments/assets/d68909a7-af77-413e-9abc-c82717d41145)
![photo_2024-11-17_00-21-51](https://github.com/user-attachments/assets/220c7ec0-a687-4b20-9f7f-14b60370f2f7)

</details>

У меня только одно расширение в браузере -- Ublock Orign

**Comment by dimisa-RUAdList** [comment]
Для определения фильтра, содержащего правило, вызывающее проблему, попробуйте отключать их по одному, до выявления виновного.

**Comment by 4815162342lost** [comment]
> Для определения фильтра, содержащего правило, вызывающее проблему, попробуйте отключать их по одному, до выявления виновного.

EasyPrivacy.

**Comment by dimisa-RUAdList** [comment]
Хорошо, с фильтром понятно. Включите EasyPrivacy и добавляйте на вкладке My filters одно за другим отключающие правила, до выявления виновного.

**Comment by dimisa-RUAdList** [comment]
Проблема ещё актуальна?

**Comment by 4815162342lost** [comment]
В данный момент всё работает.
