### ISSUE TITLE
usmall.ru

### ISSUE THREAD

**Issue by trup** [easylist/ruadlist#718]
`https://usmall.ru`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/user-attachments/assets/7bbf3fe0-a8d7-4099-8313-d3872daf34d1)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/87655a6ab7bafaca97477f74dab38865f4bdb260
