### ISSUE TITLE
zoneofgames.ru

### ISSUE THREAD

**Issue by 10522** [easylist/ruadlist#720]
#### Описание проблемы (Description of the problem):

Скриншоты игр открываются по центру экрана и отображаются полностью только при отключенном RU AdList.

`https://www.zoneofgames.ru/games/lego_star_wars_the_skywalker_saga/screens/`

</details>

#### Конфигурация (Configuration):

- OS/version: Windows 10 Pro 22H2
- Browser/version: Google Chrome 131.0.6778.109
- Ad block extension/version: uBlock Origin 1.61.2

#### Используемые фильтры (Used filters):
<details>

![fhghdhfsdsf](https://github.com/easylist/ruadlist/assets/59209149/47924ee3-66ec-4eff-a058-0965d41ef850)

</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/3a8cec39144690108bed9b2939c645c33ca8e496

**Comment by dimisa-RUAdList** [comment]
Это другой домен. Создайте пожалуйста новый issue.

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/52ffe05a1873a9bba633d959dcd677d74c34ab6c

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/0a7561c129190124aa6401a28bb06aef78712110

**Comment by 10522** [comment]
@dimisa-RUAdList

Обнаружил пустое пространство (в самом верху и в самом низу страницы), которое осталось после удаления рекламы:

`https://www.zoneofgames.ru/games/eng/1/`

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/f46b2e97ff0084c231e38865749dfcd1ae6f02d5
