### ISSUE TITLE
habr.com

### ISSUE THREAD

**Issue by suprunchuk** [easylist/ruadlist#724]
#### Описание проблемы (Description of the problem):
Счетчики лайков записей не отображаются, как и блок историй в ленте. Прочие внешние блоки также не загружаются.
https://habr.com/ru/news/

<details>
<summary>Screenshot(s)</summary>

![img-2024-12-30-10-12-12](https://github.com/user-attachments/assets/524a479f-4930-4dea-934e-baffea2db41c)

https://github.com/user-attachments/assets/36232d16-edb4-4afb-8524-3bf6a0f0726f

</details>

#### Конфигурация (Configuration):

- OS/version: windows 11 pro
- Browser/version: firefox 133.0.3
- Ad block extension/version: 
```yml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 161881
 cosmetic: 71137
 scriptlet: 23295
 html: 2282
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1761-0, 1h.45m
 default:
  user-filters: 1-0, never
  ublock-filters: 41206-122, 1h.39m
  ublock-badware: 12397-1, 1h.39m
  ublock-privacy: 1822-35, 1h.39m
  ublock-unbreak: 2605-5, 1h.39m
  ublock-quick-fixes: 182-3, 39m Δ
  easylist: 78748-229, 1h.39m
  easyprivacy: 53377-281, 1h.39m
  urlhaus-1: 23810-0, 1h.45m
  plowe-0: 3546-995, 1h.39m
  RUS-0: 41120-159, 1h.45m Δ
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 303 ms (selfie)
 maxAssetCacheWait: 129 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  habr.com: 12
  google.com: 1
  googletagmanager.com: 1
  vk.com: 1
  yandex.ru: 3
```

**Comment by dimisa-RUAdList** [comment]
В указанной конфигурации проблема не повторяется. Попробуйте открыть панель управления uBlock Origin на вкладке "Списки фильтров" и отключать их до выявления виновного.

**Comment by dimisa-RUAdList** [comment]
И что в итоге было причиной заявленного поведения?

**Comment by suprunchuk** [comment]
вот здесь было пару каких-то непонятных фильтров. я их удалил и все ок стало. не знаю откуда они там появились)
![изображение](https://github.com/user-attachments/assets/cb772269-9a00-430a-a984-e63da89b480c)
