### ISSUE TITLE
nv.ua

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#75]
`https://radio.nv.ua/online-radio-nv`

Скрывает лишнее `nv.ua##style:first-child + div[class]:not([class*=" "]):not([class*="-"]):not(.container)`

<details>
<summary>Скрин</summary>

![2022-09-08_080223](https://user-images.githubusercontent.com/111344219/189038411-128e353a-224f-4dcd-9a0b-1dccc927718f.png)
</details>

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 98557
  cosmetic: 128386
  scriptlet: 23742
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 31407-27, 32m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1489-24, 32m
    fanboy-cookiemonster: 40880-285, 32m
    ublock-annoyances: 4569-52, 32m
  default: 
    user-filters: 10-0, never
    RUS-0: 42148-145, 32m
    easylist: 64873-85, 32m
    easyprivacy: 27492-533, 32m
    ublock-abuse: 76-1, 32m
    ublock-badware: 4222-99, 32m
    ublock-filters: 32562-167, 32m
    ublock-privacy: 251-8, 32m
    ublock-quick-fixes: 421-2, 32m
    ublock-unbreak: 1850-44, 32m
filterset (user): [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: 
  filterAuthorMode: true
  popupFontSize: 13px
  popupPanelHeightMode: 1
supportStats: 
  allReadyAfter: 753 ms (selfie)
  maxAssetCacheWait: 690 ms
```
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/ab79020f7d206bd6e2f84f3ec768de52599937a5

**Comment by dportvine** [comment]
`https://techno.nv.ua/ukr/it-industry.html`

<details>
<summary>Скрин</summary>

![2023-10-07_202814](https://github.com/easylist/ruadlist/assets/111344219/58a31153-3a70-4a9e-90aa-3f75f64547b0)
</details>

`https://techno.nv.ua/ukr/it-industry/duckduckgo-i-standartniy-poshukovik-dlya-safari-50358542.html`

<details>
<summary>Скрин</summary>

![2023-10-07_202814](https://github.com/easylist/ruadlist/assets/111344219/490efde3-b0c0-4b61-9a05-f6a5e4856233)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/6c93ba3c4ec9181058249aaed4ac4cf1cb8ecda7
