### ISSUE TITLE
Блокировка нерекламной органики на выдаче yandex.ru/search

### ISSUE THREAD

**Issue by fromanywhere** [easylist/ruadlist#76]
Добрый день.
Firefox 1024+ uBlock Origin 1.44.0 + [[advblock](https://github.com/easylist/ruadlist/tree/7e2416b4e849983ead74a77bda84d3aee64e3d0a/advblock)/specific_special.txt]

Запрос:
https://yandex.ru/search/?text=KRAFTWELL+KRWFJ5&lr=213

Правило:
yandex.by,yandex.kz,yandex.ru,yandex.uz#?##search-result > .serp-item:-abp-has([role="text"] span:not([class*=" "]) > span)
[? yandex.ru###search-result > .serp-item:has([role="text"] span:not([class*=" "]) > span)]

Пользователи жалуются, что вырезается нерекламная выдача.
<img width="1645" alt="Снимок экрана 2022-09-09 в 16 52 41" src="https://user-images.githubusercontent.com/1042969/189369298-95a61340-7403-4bbd-a070-24e381fcc0c9.png">

**Comment by dimisa-RUAdList** [comment]
Тема для яндекс-поиска уже есть: https://github.com/easylist/ruadlist/issues/62
