### ISSUE TITLE
cursorinfo.co.il

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#78]
`https://cursorinfo.co.il/world-news/rossijskie-smi-soobshhayut-chto-ih-armiya-pokinula-liman-pod-davleniem-vsu/`

<details>
<summary>Скрин</summary>

![2022-09-10_164105](https://user-images.githubusercontent.com/111344219/189486416-f15f73f2-9feb-4103-b1c1-f1f71a08c98d.png)
![2022-09-10_164755](https://user-images.githubusercontent.com/111344219/189486424-7f2523d6-1ffa-4e13-8fa6-07a2d904ddeb.png)
</details>

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 98557
  cosmetic: 128386
  scriptlet: 23742
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 31407-27, 32m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1489-24, 32m
    fanboy-cookiemonster: 40880-285, 32m
    ublock-annoyances: 4569-52, 32m
  default: 
    user-filters: 10-0, never
    RUS-0: 42148-145, 32m
    easylist: 64873-85, 32m
    easyprivacy: 27492-533, 32m
    ublock-abuse: 76-1, 32m
    ublock-badware: 4222-99, 32m
    ublock-filters: 32562-167, 32m
    ublock-privacy: 251-8, 32m
    ublock-quick-fixes: 421-2, 32m
    ublock-unbreak: 1850-44, 32m
filterset (user): [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: 
  filterAuthorMode: true
  popupFontSize: 13px
  popupPanelHeightMode: 1
supportStats: 
  allReadyAfter: 753 ms (selfie)
  maxAssetCacheWait: 690 ms
```
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/b21bc24037577fb99857d23be53b22c7aa952135

**Comment by dportvine** [comment]
`https://cursorinfo.co.il/israel-news/bezviz-s-ssha-v-amerikanskom-posolstve-sdelali-vazhnoe-zayavlenie/`

<details>
<summary>Скрин</summary>

![2023-09-26_095519](https://github.com/easylist/ruadlist/assets/111344219/eb81b7ce-bad9-405f-9019-60f3a998e845)
![2023-09-26_100131](https://github.com/easylist/ruadlist/assets/111344219/3b010c32-d065-4a20-bb1f-85f478ceb1a7)
</details>
