### ISSUE TITLE
radiorecord.ru

### ISSUE THREAD

**Issue by bogachenko** [easylist/ruadlist#8]
`https://www.radiorecord.ru/`

Соц сети (внизу страницы, справа и на боковой панели, слева)

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/df7644b939437a643352ffb7e7635ab6fc182083

**Comment by bogachenko** [comment]
@Yuki2718 https://www.radiorecord.ru/track/110518

The rule https://github.com/AdguardTeam/AdguardFilters/blob/b4ed1f4c2b39b3bedffbaf08c4a47590bf1df0c3/SocialFilter/sections/social_trackers.txt#L144 is blocking the display of the page.

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/c96509d90b2b224b0190a878c8d387b7eca1b069

**Comment by Yuki2718** [comment]
@bogachenko Thanks, confirmed. I'll exclude the domain from the Social media filter.

**Comment by dportvine** [comment]
`https://www.radiorecord.ru/`
<details>
<summary>Screen</summary>

![2023-04-25_091532](https://user-images.githubusercontent.com/111344219/234190181-490dbbcd-9a5f-4442-b233-2c3a3f5c683b.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/5dd4eeb22a0fabaed9df770f242c3169d471ca9f
