### ISSUE TITLE
outdoor.adspace.pro

### ISSUE THREAD

**Issue by Miklesp** [easylist/ruadlist#80]
Добрый день! Блокировщики рекламы, использующие easylist блокируют добросовестный сайт агентства наружной рекламы на субдомене [outdoor.adspace.pro](https://outdoor.adspace.pro/)
Блокируют по имени домена как основной фильтр easylist, так и региональный ruadlist(russian-ukrainian easylist).
Ранее сталкивались с такой проблемой для основного сайта adspace.pro, теперь вот для поддомена.
Прошу внести сайт в белый список.

**Comment by dimisa-RUAdList** [comment]
Блокирующая маска `.adspace.` содержится в фильтре EasyList: https://easylist-downloads.adblockplus.org/easylist.txt

Вносить правки в фильтры могут только их авторы. Вам лучше продолжить дискуссию здесь: https://github.com/easylist/easylist/issues/13330
