### ISSUE TITLE
dzen.ru

### ISSUE THREAD

**Issue by felippesantos46** [easylist/ruadlist#83]
Sponsored content at https://dzen.ru/

Screenshot:

<img width="726" alt="Screenshot 2022-09-20 at 15 10 13" src="https://user-images.githubusercontent.com/65717387/191266466-cccd3ff3-b907-4e15-899b-c1430d0a8ae8.png">

##div[data-name="zen2-carousel"]

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/3f663e1669d04aba28ca36929ccb10dc8bf567ae

I do not think that the added rules will work for more than a few days. Most likely, the only effect achieved will be more sophisticated obfuscation of the layout.

To block ads on problem sites, Eyeo developers need to do a lot of work. They know about it, and promised to take care of it after the release of the MV3 version.

**Comment by felippesantos46** [comment]
> Fix: [3f663e1](https://github.com/easylist/ruadlist/commit/3f663e1669d04aba28ca36929ccb10dc8bf567ae)
> 
> I do not think that the added rules will work for more than a few days. Most likely, the only effect achieved will be more sophisticated obfuscation of the layout.
> 
> To block ads on problem sites, Eyeo developers need to do a lot of work. They know about it, and promised to take care of it after the release of the MV3 version.

Hey @dimisa-RUAdList, completely agree, for instance we need to work with what we have.
