### ISSUE TITLE
yandex.ru/search: нерекламные галереи

### ISSUE THREAD

**Issue by ilyhryh** [easylist/ruadlist#85]
добрый день

правки  https://hg.adblockplus.org/ruadlist/rev/7e134d4b2167, а именно правило:
```
+yandex.by,yandex.kz,yandex.ru,yandex.uz##.serp.main__carousel:not([data-bem*="lst."])
```
режут нерекламные галереи (например, [кафе москвы](https://yandex.ru/search/?text=%D0%BA%D0%B0%D1%84%D0%B5+%D0%BC%D0%BE%D1%81%D0%BA%D0%B2%D1%8B&lr=213), [королева виктория](https://yandex.ru/search/?text=%D0%9A%D0%BE%D1%80%D0%BE%D0%BB%D0%B5%D0%B2%D0%B0+%D0%92%D0%B8%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D1%8F&lr=213&noreask=1&ento=0oCghydXc0NzkwMxIRcnV3MjEyNTI6Y3VzdG9tOjAYAnoQ0JLQuNC90LTQt9C-0YDRiygYuyM), [ковид](https://yandex.ru/search/?text=%D0%BA%D0%BE%D0%B2%D0%B8%D0%B4&lr=213), [лига чемпионов](https://yandex.ru/search/?text=%D0%BB%D0%B8%D0%B3%D0%B0+%D1%87%D0%B5%D0%BC%D0%BF%D0%B8%D0%BE%D0%BD%D0%BE%D0%B2&lr=213))

поправьте, пожалуйста.

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/issues/62

**Comment by ilyhryh** [comment]
связь Isuues, ввиду `"(все проблемы яндекс-поиска обсуждаются здесь)"` => переехать в то Issue или просто won't fix?
