### ISSUE TITLE
spcs.social

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#88]
`https://spcs.social/sz/video/`

<details>
<summary>Screen</summary>

![2022-10-07_165658](https://user-images.githubusercontent.com/111344219/194572354-0c5ab1ae-8784-4d47-83d5-a0917049f475.png)
</details>

`https://spac1.info/sz/video/xrotika/`

<details>
<summary>Screen</summary>

![2022-10-07_165744](https://user-images.githubusercontent.com/111344219/194572694-a1b4ceaa-780b-4e6d-9730-41c88f6478d2.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/67e0ba0bde308c1a4d5361ddeb64ce57a23c3653

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/abc2f865f9ed35634f70256d7133c76fb68e907a
