### ISSUE TITLE
vk.ru

### ISSUE THREAD

**Issue by danyadev** [easylist/ruadlist#89]
На vk.ru не отображаются некоторые уведомления. Это связано с тем, что для vk.com сделали исключения, а для vk.ru - нет.

`advblock/general_hide.txt`

<details>
<summary>Screenshot(s)</summary>

![](https://user-images.githubusercontent.com/35631027/194595646-7ed1653c-9410-4cdc-a54e-32bdf8540881.png)

</details>

Как проверить:
1) авторизоваться на [vk.ru](https://vk.ru)
2) написать [боту](https://vk.ru/im?sel=-195966353) сообщение `/нг`
3) нажать на любую кнопку
<details>
<summary>Screenshot(s)</summary>

![](https://user-images.githubusercontent.com/35631027/194596210-9152e4d1-2bde-4ee4-9873-02938335d833.png)

</details>

4) должно появиться уведомление, но его нет

<details>
<summary>Screenshot(s)</summary>

![](https://user-images.githubusercontent.com/35631027/194596303-8d77b588-ef29-471d-83f7-72ba852ddc0e.png)

</details>

Проверено на adblock plus и ublock origin

**Comment by dimisa-RUAdList** [comment]
Непонятно, что это за домен. Для проверки требуется регистрация, для регистрации - номер телефона. Авторизацию аккаунта vk.com это зеркало не видит. Расскажите пожалуйста подробнее о проекте и предоставьте тестовый аккаунт.

**Comment by danyadev** [comment]
Это второй домен для сайта vk.com, поэтому аккаунт оттуда должен работать и на vk.com

новости про то, что вк выкупил этот домен:
[https://vc.ru/social/420697-vkontakte-vykupila-domen-vk-ru](https://vc.ru/social/420697-vkontakte-vykupila-domen-vk-ru)
[https://tass.ru/ekonomika/14617207](https://tass.ru/ekonomika/14617207)

**Comment by dimisa-RUAdList** [comment]
Ок, добавил исключения: https://github.com/easylist/ruadlist/commit/55e7d012b1fe0ddffd6ca1f2ae5543555a53fa13
