### ISSUE TITLE
Заблокирован посторонний домен

### ISSUE THREAD

**Issue by QAlin1** [easylist/ruadlist#9]
Здравствуйте, не отношусь к представителям партнерской сети, но являюсь вебмастером и в период праздников приходится реагировать оперативнее. 
Adblock - полезная вещь, но очень неприятно, когда из-за нее возникают проблемы в работе.

В коммите https://github.com/easylist/ruadlist/commit/25b273072617c584020ec492a308c801b75e1cd7 из-за сайта с рыболовными приманками в блеклист попал основной домен партнерской сети epn: **cooldeal.by** при открытии ссылки в новом окне.

Многие вебмастера монетизировали через него свой трафик на AliExpress, теперь же ссылки просто режутся блокировщиками рекламы, хотя пользователи осознанно хотят по ним перейти. Вот пример: https://vk.com/alikdarom?w=wall-146937630_2021726

Прошу убрать из списка этот домен, чтобы не мешать вебмастерам. Давайте жить дружно)

**Comment by dimisa-RUAdList** [comment]
Монетизация - это и есть реклама. То есть, блокировщик в данном случае делает именно то, для чего и предназначен.

**Comment by QAlin1** [comment]
Позиция, конечно, интересная. 
То есть вы считаете, что блокировщик должен решать за пользователя, можно ли ему переходить на определенный сайт или нет? 

Если пользователь выражает свое осознанное желание перейти на сайт (как в случае с ссылками в посте ВК выше), но у него сразу же закрывается вкладка, это нормальное поведение блокировщика рекламы? 

Всякая реклама - это монетизация, но не всякая монетизация осуществляется с помощью рекламы. 
Зачем в данном случае запрещать людям те действия, которые они целенаправленно совершили?

**Comment by dimisa-RUAdList** [comment]
Рекламные домены-редиректоры блокируются всегда, это очевидная функция блокировщика. Если кто-то размещает на своих страничках конкурсы, акции, и прочие подобные вещи, или организует сервис заработка за просмотр рекламы, он должен быть готов к тому, что под адблоком всё это работать не будет.

**Comment by QAlin1** [comment]
Видимо, на сайте с рыболовными приманками (вместе с коммитом которого был заблокирован и домен epn'a) вам попался переход с таймером обратного отсчёта. Таких ссылок по собственному пользовательскому опыту меньшинство. 

Если по вашему мнению полностью отказаться от блокировки этого домена нельзя, то можно хотя бы скорректировать правило таким образом, чтобы отсекались только ссылки с таймером, а ссылки с редиректом напрямую работали, так как не приносят пользователям никакого неудобства.

Сравните, пожалуйста, трейсинг по ссылкам ниже, напомню, что в RUAdList попал домен cooldeal.by, а ali.pub - это просто сокращалка, типа goo.gl, vk.cc и т.д.:
- https://wheregoes.com/trace/2021680582/ - часть url /cashback/view/ отвечает за переход к показу промежуточного экрана.
- https://wheregoes.com/trace/2021680610/ - часть url /redirect/cpa - безусловный переход на страницу AliExpress, пользователи при этом не видят никаких посторонних баннеров или лишней информации.

Не являюсь специалистом в составлении правил для блокировщиков, но насколько мне известно, существует возможность проверять на соответствие определенные фрагменты url, а не только домен целиком.
