### ISSUE TITLE
inkorr.com

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#91]
`https://inkorr.com/naskolko-prodolzat-rasti-ceny-108448`

<details>
<summary>Screen</summary>

![2022-10-11_143921](https://user-images.githubusercontent.com/111344219/195080716-bfa662a0-97e1-46f0-94ff-4e496f7d2455.png)
![2022-10-11_144022](https://user-images.githubusercontent.com/111344219/195080736-0707e2e8-d596-40fa-8b05-ed34fba05110.png)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/176f2a8d65950cbba966cfb518dd0eb63d7d1ea1

**Comment by dportvine** [comment]
`https://inkorr.com/`

<details>
<summary>Screen</summary>

![2023-12-18_113507](https://github.com/easylist/ruadlist/assets/111344219/99b76162-8fdf-455b-addf-66f53933e66f)
</details>

`https://inkorr.com/kiberataka-na-kiivstar-u-kompanii-rozpovili-pro-neviriseni-problemi-209533`

<details>
<summary>Screen</summary>

![2023-12-18_113538](https://github.com/easylist/ruadlist/assets/111344219/e344af42-1c52-40a8-aa03-e1aa6d143520)
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/255e312f25494127b818fc1eeda40c277dd375bf
