### ISSUE TITLE
facebook.com

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#92]
`https://www.facebook.com/harddancecoalition/`

<details>
<summary>Screen</summary>

![2022-10-11_161508](https://user-images.githubusercontent.com/111344219/195109672-2d351ccd-9aec-42ba-a554-751f3aa24dca.png)
</details>

```adb 
facebook.com##.asf1osic ~> больше не актуально.
```  

[Фейсбук предложения регистрации](http://forum.ru-board.com/topic.cgi?forum=5&topic=50761&start=1800#:~:text=%D0%9C%D0%BE%D0%B6%D0%BD%D0%BE%20%D1%81%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%BD%D0%B0-,%D0%A4%D0%B5%D0%B9%D1%81%D0%B1%D1%83%D0%BA,-%D0%BF%D1%80%D0%B5%D0%B4%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F%20%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%B8%3F%0A%C2%A0)

**Comment by dimisa-RUAdList** [comment]
Поменял на `facebook.com##.x1u8a7rm`: https://github.com/easylist/ruadlist/commit/8a7ebb2edf71cbb638f797f7c0a0ba810a4090c5

Посмотрим, динамическое имя класса, или нет.

**Comment by dimisa-RUAdList** [comment]
Похоже, постоянное.
