### ISSUE TITLE
olx.pl

### ISSUE THREAD

**Issue by dportvine** [easylist/ruadlist#94]
`https://www.olx.pl/`

Нужно подключить **EasyPrivacy**.
Весь каламбур в том, что правила работают по отдельности.
[Gif](https://imgur.com/9t9B5wb)

Заблокировано в Counters ~> разрешить.
```adb
@@||ninja.data.olxcdn.com/ninja-cee.js$script,domain=www.olx.pl
```
Разрешено в EasyPrivacy ~> заблокировать/исключить.
```adb
@@||olx.pl^*/js/tracking/ninja.js$domain=olx.pl,badfilter 
```
Перекрывает данное правило.
<details>
<summary>Screen</summary>

![2022-10-26_092503](https://user-images.githubusercontent.com/111344219/197950736-4703f71e-22c4-4b6e-a27b-823e54996a3d.png)
</details>

Кто должен это исправить?

**Comment by dimisa-RUAdList** [comment]
Занятная ситуация. Сама проблема возникла в связи с тем, что из EasyList была удалена маска `/advertising.`.

Если в uBO подключить региональный польский фильтр "POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda", то с ним проблема уже возникать не будет, ибо он содержит правила для этой маски, даже при одновременном использовании Counters и EasyPrivacy. 

Но поскольку Counters не нацелен непосредственно на польские сайты, думаю, не случится ничего страшного, если я исключу `olx.pl` из правила.

Fix: https://github.com/easylist/ruadlist/commit/b08342ebd688ccf32933be12c27f4788108b4803
