### ISSUE TITLE
hitfm.ru + rusradio.ru

### ISSUE THREAD

**Issue by PhoenixIndigo** [easylist/ruadlist#96]
1. <comment> `hitfm.ru,rusradio.ru##.ad-blocked-messagee-mobile`

2. Screenshots
<details><summary>Screenshot 1:</summary>

![изображение](https://user-images.githubusercontent.com/107413021/200099849-51f10113-fce0-4eef-a4b3-4eafcf75bee0.png)

</details>

И плеер на компе в Firefox и Chrome не работает.

**Comment by dimisa-RUAdList** [comment]
Скрытие предупреждения об отключении блокировщика - [унифицировал](https://github.com/easylist/ruadlist/commit/591146f1c764fb1bdf9601a3befa68731c85c5ab) с десктопной версий. Поломка плеера не повторяется. Опишите пожалуйста конфигурацию в соответствии с [вот этими правилами](https://forums.lanik.us/viewtopic.php?t=24280).

**Comment by dportvine** [comment]
@PhoenixIndigo 
`https://hitfm.hostingradio.ru/hitfm96.aacp` при прямом переходе по адресу, радио работает? В Украине только через VPN.

**Comment by PhoenixIndigo** [comment]
@dportvine
Спасибо хоть как то работает))

@dimisa-RUAdList
Проблема остаётся даже с отключённым uBlock Origin, даже выскакивает ещё реклама. На Chrome правда с VPN немного поработало. Благодарю.

<details><summary>А конфигурация на максимуме.</summary>

[backup](https://pastebin.com/u/GodIndigo)

```
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 177696
  cosmetic: 264749
  scriptlet: 39231
  html: 836
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 31544-67, 8m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1548-0, 8m
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 29222-232, 8m
    https://secure.fanboy.co.nz/enhancedstats.txt: 2989-11, 8m
    https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 95274-34880, never
    https://shorturl.at/cfqKV: 9-0, 8m
    adguard-generic: 79332-5457, 8m
    adguard-mobile: 8226-150, 8m
    adguard-spyware: 36590-15995, 8m
    adguard-annoyance: 60735-6082, 8m
    adguard-social: 18861-1022, 8m
    ublock-annoyances: 4789-8, 8m
  default: 
    user-filters: 10-0, never
    ublock-filters: 31907-150, 9m
    ublock-badware: 3957-0, 9m
    ublock-privacy: 285-0, 9m
    ublock-abuse: 76-0, 9m
    ublock-unbreak: 1908-8, 9m
    ublock-quick-fixes: 482-0, 9m
    easylist: 62871-974, 8m
    easyprivacy: 30779-2056, 8m
    urlhaus-1: 8916-0, 8m
    plowe-0: 3667-11, 8m
    RUS-0: 39698-3831, 8m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1195 ms (selfie)
  maxAssetCacheWait: 1268 ms
```

</details>

**Comment by dimisa-RUAdList** [comment]
Если плеер ломается даже с отключённым uBlock Origin, значит проблема не в нём.

Что касается вашей конфигурации, то она представляет собой винегрет из заведомо конфликтных и несовместимых фильтров, нормально она не будет работать никогда. Я бы посоветовал зайти в панель управления uBlock Origin, перейти на вкладку "Настройки" и использовать кнопку (в самом низу) "Восстановить настройки по умолчанию". И уже после этого привести фильтры в соответствие образцу ~ >
<details>
<summary>Образец</summary>

![TKSwoDi](https://user-images.githubusercontent.com/20126984/200137628-1b60013c-09f9-47cc-8a8d-848b8d101209.jpeg)

</details>

Фильтры, отсутствующие среди дефолтных, можно взять в [RU-Adlist-links](https://github.com/easylist/ruadlist/wiki/RU-Adlist-links).

**Comment by PhoenixIndigo** [comment]
Ну к примеру для Samsung browser for Android кроме AdGuard Content Blocker нет альтернативнного uBlock Origin. Плюс там ещё и дополнительная блокировка (в адгард).

**Comment by dimisa-RUAdList** [comment]
В заявленной [выше](https://github.com/easylist/ruadlist/issues/96#issuecomment-1304616088) конфигурации заявлен Firefox: 106, соответственно рекомендация дана именно для него. Поддержки Samsung browser for Android в настоящее время нет и пока даже не планируется.

**Comment by PhoenixIndigo** [comment]
Это всё, проблема закрыта. А с расширенным винегретом может и посоветуюсь ещё. Спасибо огромное.

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/issues/97 >
> Оказалось что плеер не воспроизводился с отключённым uBlock Origin из-за расширения ClearURLs, видимо оно уж слишком экстремальное, раз даже не позволяло авторизировать приложение Google Drive. А с включённым uBO рекомендуемо настроенным то же не работает! Можете повторить и помочь?

Работу ClearURLs выполняет фильтр RU AdList: Counters, использовать два несогласованных средства для решения одной и той же задачи нет смысла. И да, это далеко не первый случай, когда ClearURLs ломает функционал ресурсов.

Откройте в Firefox `about:preferences#privacy` и установите стандартную настройку. Отключите все расширения в браузере. Отключите все системные средства фильтрации сетевых запросов, вроде антивирусов и приведите системный hosts-файл в исходное состояние, если вы вносили в него правки ранее. Если плеер заработает, попробуйте включить uBlock Origin. Убедившись, что именно он является виновником поломки плеера, откройте его панель инструментов, перейдите на вкладку "Настройки" и сделайте "Резервное копирование в файл", я проверю.

**Comment by PhoenixIndigo** [comment]
Спасибо за всё. Как оказалось проблема в [Audio Equalizer](https://addons.mozilla.org/ru/firefox/addon/audio-equalizer-wext/), даже винегрет не виноват. А в чём его несовместимость с uBO то, вот [лог](https://pastebin.com/YCdNt11Z), если там чё будет понятно.

**Comment by PhoenixIndigo** [comment]
Спасибо за всё. Как оказалось проблема в [Audio Equalizer](https://addons.mozilla.org/ru/firefox/addon/audio-equalizer-wext/) (Firefox/Edge/Chrome), даже винегрет не виноват. А в чём его несовместимость с uBO то, вот [лог](https://pastebin.com/YCdNt11Z), если там чё будет понятно.

**Comment by PhoenixIndigo** [comment]
Ну да болт с ним, отписался и поменял на Audio Equalizer and Amplifier.
