### ISSUE TITLE
hitfm.ru

### ISSUE THREAD

**Issue by PhoenixIndigo** [easylist/ruadlist#97]
Оказалось что плеер не воспроизводился с отключённым uBlock Origin изза расширения ClearURLs, видимо оно уж слишком экстремальное, раз даже не позволяло авторизировать приложение Google Drive. А с включённым uBO рекомендуемо настроенным то же не работает! Можете повторить и помочь?

**Comment by dimisa-RUAdList** [comment]
Дубль: https://github.com/easylist/ruadlist/issues/96
